force-app/main/default/objects/Account_Reassignment__c/Account_Reassignment__c.object-meta.xml
<CustomObject>
    <description>Account Reassignments are determined by a set of criteria run by the data analytics team and then loaded quarterly.  Evaluation Criteria and ShipTo Assignments are loaded as child objects.</description>
    <label>Account Reassignment</label>
    <nameField>
        <label>Account Reassignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Reassignments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Reassignment__c/fields/No_Reassignment_Needed_Explanation__c.field-meta.xml
<CustomField>
    <fullName>No_Reassignment_Needed_Explanation__c</fullName>
    <description>Required text field if Account Reassignment Status field reflects &quot;No Reassignment Needed&quot;</description>
    <label>No Reassignment Needed Explanation</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Reassignment__c/fields/Proposed_New_Owner_Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Proposed_New_Owner_Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If New Rep - enter the new Sales Rep&apos;s name
If House - enter the SM name (you)
If Inside Sales - qualify account with Inside Sales manager, enter the Inside Sales Rep&apos;s name</inlineHelpText>
    <label>Proposed New Owner</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Account Reassignments Incoming</relationshipLabel>
    <relationshipName>Account_Reassignments_New_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Reassignment__c/fields/Reassignment_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reassignment_Notes__c</fullName>
    <inlineHelpText>Enter any notes</inlineHelpText>
    <label>Reassignment Notes</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Reassignment__c/fields/Reassignment_Stage__c.field-meta.xml
<CustomField>
    <fullName>Reassignment_Stage__c</fullName>
    <inlineHelpText>Where the account is in the reassignment process</inlineHelpText>
    <label>Reassignment Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flagged for Reassignment</fullName>
            </value>
            <value>
                <fullName>Current Rep - 90 Day Observation</fullName>
            </value>
            <value>
                <fullName>Reassignment Pending</fullName>
            </value>
            <value>
                <fullName>New Rep - In 180-Day Review</fullName>
            </value>
            <value>
                <fullName>Reassigned - House</fullName>
            </value>
            <value>
                <fullName>Reassigned - Inside Sales</fullName>
            </value>
            <value>
                <fullName>No Reassignment Needed</fullName>
            </value>
            <value>
                <fullName>Observation Complete - Stay with Rep</fullName>
            </value>
            <value>
                <fullName>Reassigned - House / Inside Sales</fullName>
                <isActive>false</isActive>
                <label>Reassigned - House / Inside Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/massUpdateAccountReassignmentCls.cls
public with sharing class massUpdateAccountReassignmentCls {
    
    private ApexPages.StandardSetController standardController;
    public list<Account_Reassignment__c> aRListing {get;set;}
    public string NoReassignmentNeededExplanation{get;set;}
    public string ReassignmentNotes{get;set;}
    public List<Account_Reassignment__c> updtList;
    public string selectedStage{get;set;}
    //public id lookUpId{get;set;}
    public Account_Reassignment__c aRe{get;set;}
    
    public massUpdateAccountReassignmentCls(ApexPages.StandardSetController standardController) {
        this.standardController = standardController;
    }
    
    public PageReference massUpdateRecords(){
        List<Account_Reassignment__c> SelectedRecords = (List<Account_Reassignment__c>) standardController.getSelected();
        System.debug('selected records are'+SelectedRecords);
        loadAccountReassignment(SelectedRecords);
        return null;
    }
    
    private void loadAccountReassignment(List<Account_Reassignment__C> aRIds) {
        this.aRListing = [Select Id,Proposed_New_Owner_Primary_Sales_Rep__c,Reassignment_Stage__c,Reassignment_Notes__c,No_Reassignment_Needed_Explanation__c FROM Account_Reassignment__c where    
                          Id in : aRIds];  
        
    }
    public Account_Reassignment__c getproposedLookup()
    {
        aRe = [select Proposed_New_Owner_Primary_Sales_Rep__c from Account_Reassignment__c limit 1];
        //lookUpId = aRe.Proposed_New_Owner_Primary_Sales_Rep__c;
        return aRe;
    }
    
    public List<SelectOption> reassignmentStages
    {
        get
        {
            List<SelectOption> options = new List<SelectOption>();
            Schema.DescribeFieldResult fieldResult = Account_Reassignment__c.Reassignment_Stage__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
            for( Schema.PicklistEntry f : ple)
                options.add(new SelectOption(f.getLabel(), f.getValue()));
            return options;
        }
    }
    
    
    public PageReference updateSelected(){
        system.debug('inside update');
        updtList = new List<Account_Reassignment__c>();
        for(Account_Reassignment__c updtaR: aRListing){
            updtaR.Proposed_New_Owner_Primary_Sales_Rep__c = aRe.Proposed_New_Owner_Primary_Sales_Rep__c;
            updtaR.Reassignment_Notes__c = ReassignmentNotes;
            updtaR.No_Reassignment_Needed_Explanation__c = NoReassignmentNeededExplanation;
            updtaR.Reassignment_Stage__c = selectedStage;
            updtList.add(updtaR);
            
        }
        
        try{
            update updtList; 
       
            Schema.DescribeSObjectResult result = Account_Reassignment__c.SObjectType.getDescribe(); 
            PageReference pageRef = new PageReference('/' + result.getKeyPrefix()); 
            pageRef.setRedirect(true); 
            if(test.isRunningTest() == true){
                decimal x = 1/0;
            }
            return pageRef;
           
        }
        catch(Exception ex){
            
            ApexPages.addMessages(ex);
            
        }
        return null; 
    }
      
}