force-app/main/default/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <description>2/13/18 - Only used on VLS and eBusiness Cases</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complimentary items</fullName>
            </value>
            <value>
                <fullName>Follow up on strategic quote</fullName>
            </value>
            <value>
                <fullName>New product intro</fullName>
            </value>
            <value>
                <fullName>Revenue Tracker</fullName>
            </value>
            <value>
                <fullName>Special Offer</fullName>
            </value>
            <value>
                <fullName>Lost Business</fullName>
            </value>
            <value>
                <fullName>Migrating Business</fullName>
            </value>
            <value>
                <fullName>POD</fullName>
            </value>
            <value>
                <fullName>Pricing Discrepancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Substitution</fullName>
            </value>
            <value>
                <fullName>Zilliant Pricing</fullName>
            </value>
            <value>
                <fullName>Warehouse item not found</fullName>
            </value>
            <value>
                <fullName>Shuttle item not received</fullName>
            </value>
            <value>
                <fullName>Wrong item filled</fullName>
            </value>
            <value>
                <fullName>Item left off</fullName>
            </value>
            <value>
                <fullName>APD</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
            <value>
                <fullName>FSC</fullName>
            </value>
            <value>
                <fullName>NOA</fullName>
            </value>
            <value>
                <fullName>Demand Issue</fullName>
            </value>
            <value>
                <fullName>ERS Issue</fullName>
            </value>
            <value>
                <fullName>NIR</fullName>
            </value>
            <value>
                <fullName>Non-Stock</fullName>
            </value>
            <value>
                <fullName>Out of Stock</fullName>
            </value>
            <value>
                <fullName>Damaged Product</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
            <value>
                <fullName>Order Short</fullName>
            </value>
            <value>
                <fullName>Order Over</fullName>
            </value>
            <value>
                <fullName>Wrong Quantity Pulled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Email_Origin__c.field-meta.xml
<CustomField>
    <fullName>Email_Origin__c</fullName>
    <description>This field contains all of the email addresses related to the email that created the Case.</description>
    <label>Email Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <description>Determines whether the person that should pick up the case is the primary or the internal backup</description>
    <label>zzIs Primary</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCaseNotification.cls
@isTest
private class TestCaseNotification
{
    static RecordType inboundCaseRT;
    static Account account;
    static Contact contact;
    static User newOwner;
    
    private static void setup()
    {
        //inboundCaseRT  = [SELECT Id FROM RecordType WHERE SObjectType = 'Case' AND Name = 'Inbound Case'];
        
        inboundCaseRT  = CaseModel.getInboundCaseRT();
        
        account = new Account(Name='test');
        insert account;
        
        contact = TestDataGeneration.generateTestContact( 'Jones', account.Id, 'jones@domain.com', true, '', true );
        
        User adminUser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
        
        System.runAs(adminUser)
        {           
            newOwner  = TestDataGeneration.getTestUser('new' + DateTime.now().getTime(), 'CSP with Create Order');
            
            insert newOwner; 
        }
    }
    
    static testMethod void testSendOwnerChangedEmail()
    {
        setup();
        
        // create a Case
        Case aCase = new Case( Subject = 'Test Subject',
                               Status = 'New',
                               Priority = 'Medium',
                               ContactId = contact.Id,
                               Case_Type__c = 'POD',
                               OwnerId = newOwner.Id,
                               RecordTypeId = inboundCaseRT.Id );

        insert aCase;       
        
        Test.startTest();
        
            Boolean sendSuccess = CaseNotification.sendOwnerChangedEmail( new List<Case>{ aCase } );
        
        Test.stopTest();
        
       // System.assert( sendSuccess );
    }
    
    static testMethod void testSendOwnerChangedEmailBulk()
    {
        setup();
        
        List<Case> cases = new List<Case>();
        for(Integer i = 0; i < 3; i++)
        {
            // create a Case
            Case aCase = new Case( Subject = 'Test Subject',
                                   Status = 'New',
                                   Priority = 'Medium',
                            //     ContactId = contact.Id,
                                   Case_Type__c = 'POD',
                                   Is_Primary__c = 'TRUE',
                                   OwnerId = newOwner.Id,
                                   Email_Origin__c = contact.Email,
                                   RecordTypeId = inboundCaseRT.Id );
            cases.add(aCase);
        }

        insert cases;
                
        Test.startTest();
        
            System.debug(System.loggingLevel.ERROR, 'STARTING TEST');
            
            Boolean sendSuccess = CaseNotification.sendOwnerChangedEmail( cases );
        
        Test.stopTest();
        
      //System.assert( sendSuccess );
    }

    static testMethod void testGenerateTempContacts()
    {
        setup();
        
        // create a Case
        Case aCase = new Case( Subject = 'Test Subject',
                               Status = 'New',
                               Priority = 'Medium',
                               ContactId = contact.Id,
                               Case_Type__c = 'POD',
                               OwnerId = newOwner.Id,
                               RecordTypeId = inboundCaseRT.Id );

        insert aCase;       
        
        Test.startTest();
        
            Map<Id, Contact> caseId2Contact = CaseNotification.generateTempContacts( new List<Case>{ aCase } );
        
        Test.stopTest();
        
        if(caseId2Contact.keyset().contains(aCase.Id)){
            System.assert(caseId2Contact.containsKey(aCase.Id));
        }
        
        
        System.assertEquals(newOwner.Email, caseId2Contact.get(aCase.Id).Email);
        
    }
}