force-app/main/default/objects/Case/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used for Cost Mainenance - they have to select a division</description>
    <label>Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Cases (Division)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>2/16/18 - No longer used on any Active page layouts</description>
    <label>Item #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/Contract_Line_Item_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object to track the progress of a line item approval. The custom object route met the business requirements most aptly, specifically the ability to auto-escalate on a time-based schedule.</description>
    <label>Contract Line Item Approval</label>
    <nameField>
        <displayFormat>#{00000}</displayFormat>
        <label>Contract Line Item Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Item Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Agreement_Score__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Score__c</fullName>
    <description>Score, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Agreement Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Approval_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Approval_Sequence__c</fullName>
    <description>Essentially maps to whether this was for an SM or for a GM. This value will be populated from process builder. 1= the first approval record created and the one designed for the SM. 2= the second approval record created and the one for the GM/pricing team. This field is created so that the time-based workflow rule knows when to cancel the second record rather than create an additional CLI. The second record never needs to expire.</description>
    <label>Approval Sequence</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Brand, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Brand</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Campaign_Recommended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Recommended_Cost__c</fullName>
    <description>Campaign Recommended Cost, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>New Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Campaign_Recommended_Price__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Recommended_Price__c</fullName>
    <description>Campaign Recommended Price, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Campaign Recommended Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Class, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Created by BW to tracking the comments associated with Contract line item approval records</description>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by BW to reference the contract line item on the Contract Line Item Approval records</description>
    <inlineHelpText>Please select the corresponding contract line item associated with the Contract Line Item Approval record.</inlineHelpText>
    <label>Contract Line Item</label>
    <referenceTo>zpl__ContractLineItem__c</referenceTo>
    <relationshipLabel>Contract Line Item Approvals</relationshipLabel>
    <relationshipName>Contract_Line_Item_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Created_From_Quote__c.field-meta.xml
<CustomField>
    <fullName>Created_From_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Stamped from the contract line item at creation by process builder to show a CLIA approver key details needed at time of decision. Will be TRUE if the source of the CLI is Q</description>
    <label>Created From Quote?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Division, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Division</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Floor_Price__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price__c</fullName>
    <description>Stamped value of the CLI at the time of creation. Process builder will stamp the value from the CLI on creation of the first one; if the first CLIA expires then process builder will stamp the value from the first CLIA onto the second.</description>
    <inlineHelpText>The Floor_Price__c at the time of submission</inlineHelpText>
    <label>Floor Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <description>Item Description, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>Item Number, stamped from the contract line item&apos;s product at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Item Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Item_Score__c.field-meta.xml
<CustomField>
    <fullName>Item_Score__c</fullName>
    <description>Item Score, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Item Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Previous_Comments__c.field-meta.xml
<CustomField>
    <fullName>Previous_Comments__c</fullName>
    <label>Previous Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Sales_Requested_Price__c.field-meta.xml
<CustomField>
    <fullName>Sales_Requested_Price__c</fullName>
    <description>Sales Requested Price, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Sales Requested Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Set__c.field-meta.xml
<CustomField>
    <fullName>Set__c</fullName>
    <description>Set, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Set</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created by BW to track the status of Contract Line Item Approval Records</description>
    <inlineHelpText>Please select the status of the Contract Line Item Approval Record</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Subset__c.field-meta.xml
<CustomField>
    <fullName>Subset__c</fullName>
    <description>Subset, stamped from the contract line item at creation by process builder, to show a CLIA approver key details needed at time of decision.</description>
    <label>Subset</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <description>Stamped value of the CLI at the time of creation. Process builder will stamp the value from the CLI on creation of the first one; if the first CLIA expires then process builder will stamp the value from the first CLIA onto the second.</description>
    <inlineHelpText>The Target_Price__c at the time of submission</inlineHelpText>
    <label>Target Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Timeframe_days__c.field-meta.xml
<CustomField>
    <fullName>Timeframe_days__c</fullName>
    <description>Created by BW to track number of days the assigned approver has to action the record. Populated on creation via a custom setting. This field will be referenced in the due date formula to remove weekends from the assigned timeframe.</description>
    <label>Timeframe days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/recordTypes/CLIA_Open.recordType-meta.xml
<RecordType>
    <fullName>CLIA_Open</fullName>
    <active>true</active>
    <description>Created by BW to create Open CLIA records</description>
    <label>CLIA Open</label>
</RecordType>

force-app/main/default/objects/User/fields/Contract_Line_Approver_Override__c.field-meta.xml
<CustomField>
    <fullName>Contract_Line_Approver_Override__c</fullName>
    <description>Permanent override for routing of Contract Line Item Approval records</description>
    <inlineHelpText>Permanent override for routing of Contract Line Item Approval records</inlineHelpText>
    <label>Contract Line Approver Override</label>
    <relationshipName>CLIAs</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/Delegation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Delegation_End_Date__c</fullName>
    <description>End Date for temporary override for routing of Contract Line Item Approval records</description>
    <inlineHelpText>End Date for temporary override for routing of Contract Line Item Approval records</inlineHelpText>
    <label>Delegation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Delegation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Delegation_Start_Date__c</fullName>
    <description>Start Date for temporary override for routing of Contract Line Item Approval records</description>
    <inlineHelpText>Start Date for temporary override for routing of Contract Line Item Approval records</inlineHelpText>
    <label>Delegation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Pricing_Delegated_Approver__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Delegated_Approver__c</fullName>
    <description>Temporary override for routing of Contract Line Item Approval records based on Delegation Start and End Date</description>
    <inlineHelpText>Temporary override for routing of Contract Line Item Approval records based on Delegation Start and End Date</inlineHelpText>
    <label>Pricing Delegated Approver</label>
    <relationshipName>PricingDelegatedApprover</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/Zilliant_Approval_Variables__c/Zilliant_Approval_Variables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Zilliant Approval Variables</label>
</CustomObject>

force-app/main/default/objects/Zilliant_Approval_Variables__c/fields/SM_Timeframe_2__c.field-meta.xml
<CustomField>
    <fullName>SM_Timeframe_2__c</fullName>
    <defaultValue>2</defaultValue>
    <description>Created by BW to track the SM timeframe for approvals</description>
    <label>SM Timeframe</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContractLineItemApprovalService.cls
global class ContractLineItemApprovalService {

    private static final String CLI_PREFIX = zpl__ContractLineItem__c.SObjectType.getDescribe().getKeyPrefix(); // 'a5He' in sandbox
    public static Map<Id, Contract_Line_Item_Approval__c> mNewCLIA = new Map<Id, Contract_Line_Item_Approval__c>();
    @TestVisible
    private static Date current_date = Date.today();
	
    @future
    public static void deleteContractLineItemApprovalsFuture(Set<Id> inactiveLineIds) {
        deleteContractLineItemApprovals(inactiveLineIds);
    }
    
    public static void deleteContractLineItemApprovals(Set<Id> inactiveLineIds) {
        List<Contract_Line_Item_Approval__c> deleteApprovals = [
            SELECT Id
            FROM Contract_Line_Item_Approval__c
            WHERE Contract_Line_Item__r.Id IN :inactiveLineIds];
        
        system.debug('##deleteApprovals: ' + deleteApprovals);
        system.debug('##deleteApprovals: ' + deleteApprovals.size());
        
        if (!deleteApprovals.isEmpty()) {delete deleteApprovals;}
    }

    @InvocableMethod(Label='CreateContractLineItemApprovals')
    public static void createContractLineItemApprovals(List<Id> ids) {

        system.debug('##HERE!');
        Map<Id, User> mapIdToUser;
        Map<String, String> mapLevelToField;
        Set<String> approvalsEmails = new Set<String>();
        Map<Contract_Line_Item_Approval__c, String> mapCliaToEmail = new Map<Contract_Line_Item_Approval__c, String>();
        List<Id> completedApprovals = new List<Id>();
        List<Contract_Line_Item_Approval__c> newClias = new List<Contract_Line_Item_Approval__c>();
        Id CLIAOpenRecordTypeId = Schema.SObjectType.Contract_Line_Item_Approval__c.getRecordTypeInfosByDeveloperName().get('CLIA_Open').getRecordTypeId();

        mapLevelToField = customSettingsFieldNames();

        if (mapLevelToField.isEmpty()) {
            return;
        }

        String idType = String.valueOf(ids[0]);

        Boolean isCli  = idType.startsWithIgnoreCase(CLI_PREFIX);

        Decimal timeFrameDays = SOQL_timeFrame();

        system.debug('##timeFrameDays: ' + timeFrameDays);

        List<Wrapper> wrappers = SOQL_Build(isCli, ids); // a wrapper of cli or clia

        mapIdToUser = SOQL_Users(
                String.join(mapLevelToField.values(), ','),
                buildOwnerIds(wrappers)
        );

        system.debug('##mapIdToUser: ' + mapIdToUser);
        system.debug('##mapIdToUser: ' + mapIdToUser.size());

        Integer numLevels = mapLevelToField.size();

        system.debug('##numLevels: ' + numLevels);

        Map<String, User> mapEmailToUser = new Map<String, User>();

        System.debug('##wrappers: ' + wrappers);
        System.debug('##wrappers: ' + wrappers.size());

        for (Wrapper wrapper : wrappers) {

            if (wrapper.isComplete(numLevels)) {
                System.debug('##Complete');
                completedApprovals.add(wrapper.getClia().Contract_Line_Item__c);

            } else {
                System.debug('##Not Complete');
                Contract_Line_Item_Approval__c newClia = wrapper.initClia(timeFrameDays);
                newClia.RecordTypeId = CLIAOpenRecordTypeId;

                // [cli, clia] --> source cli --> ownerId --> owner   -->|
                //                                                       |--> email
                // newClia --> approval sequence --> email field name -->|
        
                //String seq = V(newClia.Approval_Sequence__c);
                //String field = mapLevelToField.get(seq);
                //system.debug('@@' + field);
                zpl__ContractLineItem__c sourceCli = wrapper.SourceCli();
                Id ownerId = (Id) Validate(ownerId(sourceCli), 'No owner found for cli:' + wrapper);
                
                User owner = mapIdToUser.get(ownerId);                
                
                Id delegateId = DelegateId(owner, newClia.Approval_Sequence__c);                
                
                if (delegateId != null){
                    newClia.ownerId = delegateId;
                    system.debug('##delegated: ' + delegateId);
                }
                else{
                    // If the PSR have the field Contract_Line_Approver_Override__c filled on your user, use this manager
                    system.debug('##newClia.Approval_Sequence__c: ' + newClia.Approval_Sequence__c);
                    if (newClia.Approval_Sequence__c == 1 ){
                        
                        if(owner.Manager.Contract_Line_Approver_Override__c != null){
                            newClia.ownerId = owner.Manager.Contract_Line_Approver_Override__c;
                        }
                        else{
                            newClia.ownerId = owner.ManagerId;
                        }
                    }
                    //[START 02/03/2021] Simplus Case 26214 (Deal Manager - 1 step approval) - Commented out 
                    // for the second level use manager of manager from field Contract_Line_Approver_Override__r.Contract_Line_Approver_Override__c of PSR user
                    /*if (newClia.Approval_Sequence__c == 2 ){
                        system.debug('##newClia.Approval_Sequence__c: ' + newClia.Approval_Sequence__c);
                        if(owner.Manager.Manager.Contract_Line_Approver_Override__c != null){
                            newClia.ownerId = owner.Manager.Manager.Contract_Line_Approver_Override__c;
                        }
                        else{
                            newClia.ownerId = owner.Manager.ManagerId;
                        }
                    }*///[END 02/03/2021] Simplus Case 26214 (Deal Manager - 1 step approval) - Commented out 
                    
                }
                system.debug('RODNEY DEBUG @@@@'+newClia);
                system.debug('RODNEY DEBUG newClia ownerid, @@@@'+newClia.ownerid);
                system.debug('RODNEY DEBUG newClia ownername@@@@'+newClia.owner.name);
                system.debug('RODNEY DEBUG newClia owner email@@@@'+newClia.owner.email);
                newClias.add(newClia);

                //String email = V(owner.get(field));
                //mapCliaToEmail.put(newClia, email);

                //Validate(email, 'Email is missing for the cli: ' + wrapper + ' by looking into the field ' + field + ' of the user:' + ownerId + '-' + owner.Name);

                //pprovalsEmails.add(makeExampleEmail(email));
                //approvalsEmails.add(email);
            }
        }

        //for (User user : SOQL_UsersByEmails(approvalsEmails)) {
        //    mapEmailToUser.put(
        //            fixExampleEmail(user.Email),
        //            user
        //    );
        //}
        

        //List<Contract_Line_Item_Approval__c> newClias = new List<Contract_Line_Item_Approval__c>(mapCliaToEmail.keySet());

        //Map<Id, Id> userToDelegateMap = new Map<Id, Id>{};

        //for (Contract_Line_Item_Approval__c clia : newClias) {

            // clia --> email --> owner --> delegate --> id
          // String email = (String) Validate(mapCliaToEmail.get(clia),  'Email missing for the clia: ' + clia.Name);
          //  User owner   = (User)   Validate(mapEmailToUser.get(email), 'No user corresponding to the email: ' + email);

           // Id delegateId = DelegateId(owner);
           // if (delegateId != null){
           //     clia.OwnerId = delegateId;
           // }
            // If the PSR don't have the field Contract_Line_Approver_Override__c filled on your user, use owner by email
            //else if(clia.OwnerId == null){
            //    clia.OwnerId = owner.Id;                
            //}

            /*
            clia.OwnerId =
                  delegateId != null
                ? delegateId
                : owner.Id;
      */
       // }

        system.debug('##newClias: ' + newClias);
        system.debug('##newClias: ' + newClias.size());
        insert newClias;
        
        system.debug('##completedApprovals: ' + completedApprovals);
        system.debug('##completedApprovals: ' + completedApprovals.size());
        if (completedApprovals.size()>0) {
            // IMPORTANT
            AIQAgrLineApproval.approveAgrLine(completedApprovals);
        }

    }

    private static Id DelegateId(User owner, Decimal seq) {

        if (owner == null) return null;

        // system.debug('@@@ owner: ' + owner);
        // system.debug('@@@ Dates: ' + owner.Delegation_Start_Date__c + ' - ' + owner.Delegation_End_Date__c);
        //  system.debug('@@@ Delegated Appr: ' + owner.Pricing_Delegated_Approver__c);

        if (seq == 1 && owner.Manager.Delegation_Start_Date__c <= current_date &&
                                              current_date <= owner.Manager.Delegation_End_Date__c)
        {
            return owner.Manager.Pricing_Delegated_Approver__c; 
        }

        if (seq == 2 && owner.Manager.Manager.Delegation_Start_Date__c <= current_date &&
                                                current_date <= owner.Manager.Manager.Delegation_End_Date__c)
        {
            return owner.Manager.Manager.Pricing_Delegated_Approver__c; 
        }

        return null;

    }

    private static Object Validate(Object obj, String errorMessage) {
        if (obj == null) {
            throw new ContractLineItemApprovalServiceException(errorMessage);
        }
        return obj;
    }

    // private static String V(Object obj) {
    //     return String.valueOf(obj);
    // }

    // private static String makeExampleEmail(String email) {
    //     return ('' + email).replace('@', '=') + '@example.com';
    // }
    // private static String fixExampleEmail(String email) {
    //     return ('' + email).replace('=', '@').replace('@example.com','');
    // }

    private static Decimal SOQL_timeFrame(){
        List<Zilliant_Approval_Variables__c> variables = [SELECT SM_Timeframe_2__c FROM Zilliant_Approval_Variables__c];
        if (variables.size()==0) {
            throw new ContractLineItemApprovalServiceException('Veritiv Internal Error: Zilliant_Approval_Variables__c table is empty.');
        }
        return variables[0].SM_Timeframe_2__c;
    }

    public class ContractLineItemApprovalServiceException extends Exception {

    }

    private static Contract_Line_Item_Approval__c initCLIA(zpl__ContractLineItem__c cli, Decimal timeFrameDays) {
        Contract_Line_Item_Approval__c newClia = new Contract_Line_Item_Approval__c(
                Agreement_Score__c = cli.zpl__Contract__r.Score__c,
                Approval_Sequence__c = 1,
                Brand__c = cli.Brand__c,
                Campaign_Recommended_Cost__c = cli.FuturePricingCost__c,
                Campaign_Recommended_Price__c = cli.CampaignProposedValue__c,
                Class__c = cli.Class__c,
                Contract_Line_Item__c = cli.Id,
                Created_From_Quote__c = cli.LineSource__c == 'Q' ? true : false,
                Division__c = cli.Division_Code__c,
                Floor_Price__c = cli.Floor_Price__c,
                Item_Description__c = cli.Description__c,
                Item_Number__c = cli.zpl__Product__r.ProductCode,
                Item_Score__c = cli.CurrentScore__c,
                Sales_Requested_Price__c = cli.zpl__PolicyValue__c,
                Set__c = cli.Set__c,
                Status__c = 'Pending',
                Subset__c = cli.Subset__c,
                Target_Price__c = cli.Target_Price__c
        );

        newClia.Timeframe_days__c = timeFrameDays;

        return newClia;
    }


    private static Contract_Line_Item_Approval__c initCLIA(Contract_Line_Item_Approval__c clia) {
        return new Contract_Line_Item_Approval__c(
                Agreement_Score__c = clia.Agreement_Score__c,
                Approval_Sequence__c = clia.Approval_Sequence__c + 1,
                Brand__c = clia.Brand__c,
                Campaign_Recommended_Cost__c = clia.Campaign_Recommended_Cost__c,
                Campaign_Recommended_Price__c = clia.Campaign_Recommended_Price__c,
                Class__c = clia.Class__c,
                Contract_Line_Item__c = clia.Contract_Line_Item__c,
                Created_From_Quote__c = clia.Created_From_Quote__c,
                Division__c = clia.Division__c,
                Floor_Price__c = clia.Floor_Price__c,
                Item_Description__c = clia.Item_Description__c,
                Item_Number__c = clia.Item_Number__c,
                Item_Score__c = clia.Item_Score__c,
                Previous_Comments__c = mNewCLIA.containsKey(clia.Id) ? mNewCLIA.get(clia.Id).Comments__c : clia.Comments__c,
                Previous_Approval__c = clia.Id,
                Sales_Requested_Price__c = clia.Sales_Requested_Price__c,
                Set__c = clia.Set__c,
                Status__c = 'Pending',
                Subset__c = clia.Subset__c,
                Target_Price__c = clia.Target_Price__c
        );
    }

    private static List<Contract_Line_Item_Approval__c> SOQL_CLIA(List<Id> ids) {
        return [SELECT ID, Name, Contract_Line_Item__r.Name, Agreement_Score__c, Approval_Sequence__c, Brand__c, Campaign_Recommended_Cost__c, Campaign_Recommended_Price__c,
                Class__c, Contract_Line_Item__c, Created_From_Quote__c, Division__c, Floor_Price__c, Item_Description__c,
                Item_Number__c, Item_Score__c, Sales_Requested_Price__c, Comments__c, Set__c, Status__c, Subset__c, Target_Price__c, OwnerId,
                Contract_Line_Item__r.zpl__Contract__r.Account.Primary_Sales_Rep_Name__r.SF_userid__r.Id,
                Contract_Line_Item__r.Published_By__c, Contract_Line_Item__r.Published_By__r.Id
        FROM Contract_Line_Item_Approval__c
        WHERE Id IN :ids];
    }

    private static List<zpl__ContractLineItem__c> SOQL_CLI(List<Id> ids) {
        return [SELECT zpl__Contract__r.Score__c, Name, zpl__Product__r.ProductCode, zpl__Contract__r.Account.Primary_Sales_Rep_Name__r.SF_userid__r.Id, Brand__c,
                FuturePricingCost__c, CampaignProposedValue__c, Class__c, LineSource__c, Division_Code__c,
                Floor_Price__c, Description__c, CurrentScore__c, zpl__PolicyValue__c, Set__c, Subset__c,
                Target_Price__c, Published_By__c, Published_By__r.Id
        FROM zpl__ContractLineItem__c
        WHERE Id IN :ids];
    }

    public static Map<String, String> customSettingsFieldNames() {

        Map<String, String> mp = new Map<String, String>();

        for (CLIA_Levels__mdt s : [SELECT Level__c, Field_Name__c FROM CLIA_Levels__mdt]) {
            mp.put('' + Integer.valueOf(s.Level__c), s.Field_Name__c);
        }

        return mp;

    }

    private static Map<Id, User> SOQL_Users(String field, List<Id> contractAccountOwnerIds) {

        List<User> users = Database.query('SELECT ' + field + ', Name, ' +
        'Manager.Delegation_Start_Date__c, Manager.Delegation_End_Date__c, Manager.Pricing_Delegated_Approver__c , ' +
        'Manager.Manager.Delegation_Start_Date__c, Manager.Manager.Delegation_End_Date__c, Manager.Manager.Pricing_Delegated_Approver__c , ' +
        'Manager.Contract_Line_Approver_Override__c, Manager.Manager.Contract_Line_Approver_Override__c, Contract_Line_Approver_Override__r.Contract_Line_Approver_Override__c FROM User WHERE Id IN :contractAccountOwnerIds');

        return new Map<Id, User>(users);
    }

    // private static List<User> SOQL_UsersByEmails(Set<String> approvalsEmails) {
    //     return [
    //             SELECT Name, Email, Delegation_Start_Date__c, Delegation_End_Date__c, Pricing_Delegated_Approver__c
    //             FROM User
    //             WHERE Email IN :approvalsEmails
    //     ];
    // }
    

    private static List<Id> buildOwnerIds(List<Wrapper> cs) {
        List<Id> ownerIds = new List<Id>();
        for (Wrapper c : cs) {
            ownerIds.add(c.OwnerId());
        }
        return ownerIds;
    }

    private static Id ownerId(zpl__ContractLineItem__c cli) {
        //return cli.zpl__Contract__r.Account.Primary_Sales_Rep_Name__r.SF_userid__r.Id;
        return cli.Published_By__r.Id;
    }

    public static List<Wrapper> SOQL_Build(Boolean isCli, List<Id> ids) {
        List<Wrapper> cs = new List<Wrapper>();

        if (isCli) {
            system.debug('##CLI');
            for (zpl__ContractLineItem__c cli :        SOQL_CLI(ids))  cs.add(new CliWrapper(cli));
        } else {
            system.debug('##CLIA');
            for (Contract_Line_Item_Approval__c clia : SOQL_CLIA(ids)) cs.add(new CliaWrapper(clia));
        }
        system.debug('##cs: ' + cs);
        system.debug('##cs: ' + cs.size());
        return cs;
    }


    public abstract class Wrapper {
        public abstract Id OwnerId();
        public abstract Contract_Line_Item_Approval__c initClia(Decimal timeDelay);
        public abstract String Seq();
        public abstract zpl__ContractLineItem__c SourceCli();
        public abstract Boolean isComplete(Integer mapLevelToFieldSize);
        public abstract Contract_Line_Item_Approval__c getClia();

    }

    public class CliWrapper extends Wrapper {
        private zpl__ContractLineItem__c cli;
        public CliWrapper(zpl__ContractLineItem__c cli) {
            this.cli = cli;
        }
        public override  Id OwnerId() {
            //return cli.zpl__Contract__r.Account.Primary_Sales_Rep_Name__r.SF_userid__r.Id;
            return cli.Published_By__r.Id;
        }
        public override Contract_Line_Item_Approval__c initClia(Decimal timeDelay) {
            return ContractLineItemApprovalService.initCLIA(cli, timeDelay);
        }
        public override String Seq() {
            return '1';
        }
        public override zpl__ContractLineItem__c SourceCli() {
            return cli;
        }
        public override Boolean isComplete(Integer mapLevelToFieldSize) {
            return false;
        }
        public override Contract_Line_Item_Approval__c getClia() {
            return null; // not possible
        }
        public override String ToString() {
            return '(CLA - ' + cli.Id + ' ' + cli.Name + ')';
        }
    }

    public class CliaWrapper extends Wrapper {
        private Contract_Line_Item_Approval__c clia;
        public CliaWrapper(Contract_Line_Item_Approval__c clia) {
            this.clia = clia;
        }
        public override Id OwnerId() {
            //return clia.Contract_Line_Item__r.zpl__Contract__r.Account.Primary_Sales_Rep_Name__r.SF_userid__r.Id;
            return clia.Contract_Line_Item__r.Published_By__r.Id;
        }
        public override Contract_Line_Item_Approval__c initClia(Decimal timeDelay) {
            return ContractLineItemApprovalService.initCLIA(clia);
        }
        public override String Seq() {
            return String.valueOf(clia.Approval_Sequence__c);
        }
        public override zpl__ContractLineItem__c SourceCli() {
            return clia.Contract_Line_Item__r;
        }
        public override Boolean isComplete(Integer totalNumOfSettings) {
            return clia.Approval_Sequence__c + 1 > totalNumOfSettings; // totalNumOfSettings is currently 2
        }
        public override Contract_Line_Item_Approval__c getClia() {
            return clia;
        }
        public override String ToString() {
            return '(CLA - ' + clia.Id + ' ' + clia.Name + ')';
        }

    }


}