force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zzShip To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ShipToAccount__c.field-meta.xml
<CustomField>
    <fullName>ShipToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <label>Address Line2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShipToLookupController.cls
public class ShipToLookupController {

	public Target target {get; set;}
	public List<SelectOption> shipTos {get; set;}
	public Id shipToId {get; set;}

	public Boolean showShipTos {get {return (shipTos.isEmpty()) ? false : true;} set;}

	public ShipToLookupController() {

		Map<String,String> params = ApexPages.currentPage().getParameters();
		Id recordId = params.get('id');
		Id accountId = (params.containsKey('accountId') && params.get('accountId') != '') ? params.get('accountId') : null;
		String objectType = params.get('type');
		String name = params.get('name');
		String accountName = params.get('accountName');
		target = new Target(recordId, accountId, objectType, name, accountName);
		shipTos = target.queryShipTos();
	}

	public PageReference saveShipTo()
	{
		if(shipToId == null)
		{
			if(target.objectType == 'Case' || target.objectType == 'Contact')
			{
				target.saveShipTo( shipToId );
				return new PageReference('/' + target.recordId);
			}

			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You need to select a Ship To in order to save.'));
			return null;
		}
		else
		{
			target.saveShipTo(shipToId);
			return new PageReference('/' + target.recordId);
		}
	}

	public PageReference cancel()
	{
		return new PageReference('/' + target.recordId);
	}

	public class Target {
		public Id recordId {get; set;}
		public Id accountId {get; set;}
		public String objectType {get; set;}
		public String name {get; set;}
		public String accountName {get; set;}

		public Target(Id recordId, Id accountId, String objectType, String name, String accountName) {
			this.recordId = recordId;
			this.accountId = accountId;
			this.objectType = objectType;
			this.name = name;
			this.accountName = accountName;
		}

		public List<SelectOption> queryShipTos()
		{
	        List<SelectOption> shipTos = new List<SelectOption>();
	        for(Ship_To__c shipToAccount : [select State__c, Ship_To_Code__c, Postal_Code__c, Name, Id, City__c, Address_Line2__c, Address_Line1__c
	                                        from Ship_To__c
	                                        where Bill_To_Account__c = :this.accountId
	                                        and Active__c = 'Yes'
	                                        order by Ship_To_Code__c
	                                        limit 999])
	        {
	            String curShipToAddress = '';
	            if(shipToAccount.Ship_To_Code__c != null && shipToAccount.Ship_To_Code__c.length() >= 12 )
	            	curShipToAddress = shipToAccount.Ship_To_Code__c.length() == 12 ? shipToAccount.Ship_To_Code__c.substring(6) + ' - ' : shipToAccount.Ship_To_Code__c.substring(10) + ' - ';

	            curShipToAddress += shipToAccount.Name != null? shipToAccount.Name: '';
	            curShipToAddress += shipToAccount.Address_Line1__c != null? '\n' + shipToAccount.Address_Line1__c: '';
	            curShipToAddress += shipToAccount.Address_Line2__c != null? '\n' + shipToAccount.Address_Line2__c: '';
	            curShipToAddress += shipToAccount.City__c != null? '\n' + shipToAccount.City__c: '';
	            curShipToAddress += shipToAccount.State__c != null? ', ' + shipToAccount.State__c: '';
	            curShipToAddress += shipToAccount.Postal_Code__c != null? ', ' + shipToAccount.Postal_Code__c: '';
	            shipTos.add(new SelectOption(shipToAccount.Id, curShipToAddress));
	        }

	        if(!shipTos.isEmpty())
	        	shipTos.add( 0, new SelectOption( '', 'None' ) );
	        else
	        	shipTos.add( new SelectOption( '', 'None' ) );

	        return shipTos;
		}

		public void saveShipTo(Id shipToId)
		{
			if(objectType == 'Contact')
			{
				Contact c = new Contact(Id = recordId, Ship_To__c = shipToId);
				update c;
			}
			else if(objectType == 'Case')
			{
				Case c = new Case(Id = recordId, ShipToAccount__c = shipToId);
				update c;
			}
			else if(objectType == 'Quote')
			{
				Quote__c q = new Quote__c(Id = recordId, Ship_To__c = shipToId);
				update q;
			}
		}
	}
}