force-app/main/default/objects/PDF_Name_Setting__mdt/PDF_Name_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata will allow admins to manage and update any file and attachment names to be referenced in code.</description>
    <label>PDF Name Setting</label>
    <pluralLabel>PDF Name Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PDF_Name_Setting__mdt/fields/Email_Type__c.field-meta.xml
<CustomField>
    <fullName>Email_Type__c</fullName>
    <label>Email Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Customer</fullName>
                <default>true</default>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDF_Name_Setting__mdt/fields/PDF_Department_Name__c.field-meta.xml
<CustomField>
    <fullName>PDF_Department_Name__c</fullName>
    <inlineHelpText>If the user belongs to this department, the corresponding pdf file name will be sent.</inlineHelpText>
    <label>Department Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDF_Name_Setting__mdt/fields/PDF_File_Name__c.field-meta.xml
<CustomField>
    <fullName>PDF_File_Name__c</fullName>
    <inlineHelpText>The actual name of the pdf to be sent</inlineHelpText>
    <label>PDF File Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDF_Name_Setting__mdt/fields/PDF_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>PDF_Template_Name__c</fullName>
    <inlineHelpText>Please enter the name of the template that needs to be sent.</inlineHelpText>
    <label>Template Unique Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PDFEmailServices.cls
public with sharing class PDFEmailServices {
    
    public static List<PDF_Name_Setting__mdt> PDFMetaTypes{
    	get{
    		if( PDFMetaTypes == null )
    		{
    			PDFMetaTypes = [Select PDF_Department_Name__c, Email_Type__c, PDF_File_Name__c, PDF_Template_Name__c from PDF_Name_Setting__mdt ];
    		}
    		return PDFMetaTypes;
    	}
    	set;
    } 
    
    private static String userDepartment
    {
        get
        {
            if(userDepartment == null)
            {
                userDepartment = [Select Department From User Where Id = :UserInfo.getUserId() Limit 1].Department;
            }
            return userDepartment;
        }
        set;
    }
    
    public static PDF_Name_Setting__mdt getTemplateSetting( String emailType )
    {
        PDF_Name_Setting__mdt selectedTemplate;
       
        Map<String, List<PDF_Name_Setting__mdt>> pdfTemplatesByDepartment = GroupBy.strings('PDF_Department_Name__c',PDFMetaTypes);
        Map<String, List<PDF_Name_Setting__mdt>> departmentPdfTemplatesByEmailType;

        for( String deptKey : pdfTemplatesByDepartment.keySet())
        {
        	if(String.isBlank(userDepartment))
            {   
                break;
            }
            else if(userDepartment.containsIgnoreCase( deptKey ) )
        	{
        		departmentPdfTemplatesByEmailType = GroupBy.strings('Email_Type__c',pdfTemplatesByDepartment.get(deptKey));
        		break;
        	}
        }
        
        if( departmentPdfTemplatesByEmailType == null )
        {
            departmentPdfTemplatesByEmailType = GroupBy.strings('Email_Type__c',pdfTemplatesByDepartment.get('Default'));            
        }
        
        selectedTemplate = departmentPdfTemplatesByEmailType.get(emailType)[0];
    	
        return selectedTemplate;
    }
    
}