force-app/main/default/objects/AIQZilliantConfiguration__c/AIQZilliantConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AIQZilliantConfiguration</label>
</CustomObject>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/BatchJobSize__c.field-meta.xml
<CustomField>
    <fullName>BatchJobSize__c</fullName>
    <label>Batch Job Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/AIQZilliantPermissionsConfig__c.object-meta.xml
<CustomObject>
    <label>AIQ Permissions Config</label>
    <nameField>
        <displayFormat>SEC-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIQ Permissions Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/AssignmentGroupName__c.field-meta.xml
<CustomField>
    <fullName>AssignmentGroupName__c</fullName>
    <externalId>true</externalId>
    <label>Assignment Group Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/AssignmentGroupType__c.field-meta.xml
<CustomField>
    <fullName>AssignmentGroupType__c</fullName>
    <defaultValue>&quot;Profile&quot;</defaultValue>
    <label>Assignment Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>UserRole</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/IsActivated__c.field-meta.xml
<CustomField>
    <fullName>IsActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Activated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/PermissionSetsToAssign__c.field-meta.xml
<CustomField>
    <fullName>PermissionSetsToAssign__c</fullName>
    <description>line separated list of permission sets that have to be assigned to the group of users</description>
    <inlineHelpText>line separated list of permission sets that have to be assigned to the group of users</inlineHelpText>
    <label>Permission Sets To Assign</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/PermissionSetsToUnassign__c.field-meta.xml
<CustomField>
    <fullName>PermissionSetsToUnassign__c</fullName>
    <description>line separated list of permission sets that have to be unassigned for the group of users</description>
    <inlineHelpText>line separated list of permission sets that have to be unassigned for the group of users</inlineHelpText>
    <label>Permission Sets To Unassign</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AIQsec_TestSetup.cls
@IsTest
public with sharing class AIQsec_TestSetup {

    @testSetup
    public static void setConfig(){
        
        AIQZilliantConfiguration__c customConfig = new  AIQZilliantConfiguration__c (BatchJobSize__c = 200);
        upsert customConfig;

        Profile sup = [SELECT Id FROM Profile WHERE Name='Standard User'];
        Profile sap = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        User usr = new User(
            Username = 'ztest@zilliant.com',
            LastName = 'ZTest', 
            email='ztest@zilliant.com', 
            Country='USA', 
            Alias='ztest', 
            Network_Id__c = 'ztest', 
            TimeZoneSidKey = 'America/Los_Angeles', 
            localeSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            ProfileId = sup.id, 
            LanguageLocaleKey = 'en_US');
        
        User usr2 = new User(
            Username = 'ztest2@zilliant.com',
            LastName = 'ZTest2', 
            email='ztest2@zilliant.com', 
            Country='USA', 
            Alias='ztest2', 
            Network_Id__c = 'ztest2', 
            TimeZoneSidKey = 'America/Los_Angeles', 
            localeSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            ProfileId = sap.id, 
            LanguageLocaleKey = 'en_US');
        
        List<User> usrs = new List<User>{usr, usr2};
        insert usrs;

        List<AIQZilliantPermissionsConfig__c> secConfigList = new List<AIQZilliantPermissionsConfig__c>();

        secConfigList.add( 
            new AIQZilliantPermissionsConfig__c(
                AssignmentGroupName__c = 'Standard User'
                , AssignmentGroupType__c = 'Profile'
                , PermissionSetsToAssign__c = 'Zilliant AIQ Security Manager \r\n Zilliant Platform User'
                , PermissionSetsToUnassign__c = 'Zilliant Platform Administrator \r\n Zilliant Price Lookup Administrator'
                , IsActivated__c = true
            )
        );
        secConfigList.add( 
            new AIQZilliantPermissionsConfig__c(
                AssignmentGroupName__c = 'System Administrator'
                , AssignmentGroupType__c = 'Profile'
                , PermissionSetsToAssign__c = 'Zilliant AIQ Security Manager \r\n Zilliant Platform User'
                , PermissionSetsToUnassign__c = 'Zilliant Platform Administrator \r\n Zilliant Price Lookup Administrator'
                , IsActivated__c = true
            )
        );
        secConfigList.add( 
            new AIQZilliantPermissionsConfig__c(
                AssignmentGroupName__c = 'ZilliantTestRole'
                , AssignmentGroupType__c = 'UserRole'
                , PermissionSetsToAssign__c = 'Zilliant AIQ Security Manager \r\n Zilliant Platform User'
                , PermissionSetsToUnassign__c = 'Zilliant Platform Administrator \r\n Zilliant Price Lookup Administrator '
                , IsActivated__c = true
            )
        );
        insert secConfigList;

    }
}