force-app/main/default/objects/AIQZilliantConfiguration__c/AIQZilliantConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AIQZilliantConfiguration</label>
</CustomObject>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/NotificationGroup__c.field-meta.xml
<CustomField>
    <fullName>NotificationGroup__c</fullName>
    <description>list email addresses separated by new line &quot;\r\n&quot;</description>
    <inlineHelpText>list email addresses separated by new line &quot;\r\n&quot;</inlineHelpText>
    <label>Notification Group</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/AIQZilliantPermissionsConfig__c.object-meta.xml
<CustomObject>
    <label>AIQ Permissions Config</label>
    <nameField>
        <displayFormat>SEC-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AIQ Permissions Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/AssignmentGroupName__c.field-meta.xml
<CustomField>
    <fullName>AssignmentGroupName__c</fullName>
    <externalId>true</externalId>
    <label>Assignment Group Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/AssignmentGroupType__c.field-meta.xml
<CustomField>
    <fullName>AssignmentGroupType__c</fullName>
    <defaultValue>&quot;Profile&quot;</defaultValue>
    <label>Assignment Group Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>UserRole</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/IsActivated__c.field-meta.xml
<CustomField>
    <fullName>IsActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Activated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/PermissionSetsToAssign__c.field-meta.xml
<CustomField>
    <fullName>PermissionSetsToAssign__c</fullName>
    <description>line separated list of permission sets that have to be assigned to the group of users</description>
    <inlineHelpText>line separated list of permission sets that have to be assigned to the group of users</inlineHelpText>
    <label>Permission Sets To Assign</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AIQZilliantPermissionsConfig__c/fields/PermissionSetsToUnassign__c.field-meta.xml
<CustomField>
    <fullName>PermissionSetsToUnassign__c</fullName>
    <description>line separated list of permission sets that have to be unassigned for the group of users</description>
    <inlineHelpText>line separated list of permission sets that have to be unassigned for the group of users</inlineHelpText>
    <label>Permission Sets To Unassign</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AIQsec_PermissionSetBatchProcessor.cls
global with sharing class AIQsec_PermissionSetBatchProcessor implements Database.Batchable<sObject>, Database.Stateful{
    public class AIQPermissionSetBatchProcessorException extends Exception{}
    private List<User> users;
    private List<String> errorStack;

    public AIQsec_PermissionSetBatchProcessor() {
        this.users = new List<User>();
        this.errorStack = new List<String>();
        
    }

    public AIQsec_PermissionSetBatchProcessor(List<User> theUsers) {
        this.users = new List<User>(theUsers);
        this.errorStack = new List<String>();
    }  

    public void getUsersForUpdateAll(){
        
        List<AIQZilliantPermissionsConfig__c> secConfigRecords = new List<AIQZilliantPermissionsConfig__c>(); 
        try{
            List<String> listOfColumns = new List<String>{
                'AssignmentGroupName__c'
                , 'AssignmentGroupType__c'
                , 'PermissionSetsToAssign__c'
                , 'PermissionSetsToUnassign__c'
            };
            
            String selectColumns = String.join(listOfColumns, ',');
            zal.SoqlBuilder soqlBuilder = new zal.SoqlBuilder()
                .selectx(selectColumns)
                .fromx('AIQZilliantPermissionsConfig__c')
                .wherex(new zal.FieldCondition('IsActivated__c', zal.Operator.EQUALS, true));
            
            secConfigRecords = Database.query(soqlBuilder.toSoql());
        } catch(Exception e){
            throw new DmlException(e.getMessage()+ ', '+ e.getStackTraceString());
        }

        Set<String> profileNames = new Set<String>();
        Set<String> roleNames = new Set<String>();

        for(AIQZilliantPermissionsConfig__c configRecord : secConfigRecords){

            if(configRecord.AssignmentGroupType__c=='Profile'){
                profileNames.add(configRecord.AssignmentGroupName__c);
            } else if (configRecord.AssignmentGroupType__c=='UserRole'){
                roleNames.add(configRecord.AssignmentGroupName__c);
            }
        }
        
        try{
            
            this.users = [SELECT Id, Name, Username, UserRoleId, ProfileId, IsActive 
                          FROM User 
                          WHERE IsActive = True AND (Profile.Name IN : profileNames OR UserRole.Name IN :  roleNames )];
        }catch(Exception e){

            this.errorStack.add(e.getMessage() + ', '+ e.getStackTraceString());
        }

    }

    global Iterable<sObject> start(Database.BatchableContext BC){
        return this.users;
    }


    global void execute(Database.BatchableContext BC, List<User> scope)
    {
        try{
            AIQsec_PermissionSetManager manager = new AIQsec_PermissionSetManager();
            manager.unassignPermissions(scope);
            manager.assignPermissions(scope);
        }catch(Exception e){
            this.errorStack.add(e.getMessage().trim() + (String.isBlank(e.getStackTraceString().trim()) ? '' : ', '+e.getStackTraceString().trim()));
        } 
    }
    
    
    global void finish(Database.BatchableContext BC){
        System.debug('### Finish Method Invoked....');
        AIQZilliantConfiguration__c configFields = AIQZilliantConfiguration__c.getInstance();
        String notifGroupString = (String) configFields.get('NotificationGroup__c');
        String emailsString = '';
        if (!String.isBlank(notifGroupString)){
            emailsString = notifGroupString.replaceAll('(\\r|\\n)+', ',');
        }
        String[] notificationGroup = emailsString.trim().split(',');
        //we need to send email here to Zilliant Support Portal
        if(!errorStack.isEmpty()){
            new AIQco_Messenger('Veritiv DM: AIQsec_PermissionSetBatchProcessor class errors', this.errorStack, notificationGroup).send();
        }        
    }

}