force-app/main/default/objects/NationalAccountsPricing__c/NationalAccountsPricing__c.object-meta.xml
<CustomObject>
    <description>Pricing for national accounts</description>
    <label>National Accounts Pricing</label>
    <nameField>
        <label>Short Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Accounts Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NationalAccountsPricing__c/fields/NationalAccountGroupID__c.field-meta.xml
<CustomField>
    <fullName>NationalAccountGroupID__c</fullName>
    <externalId>true</externalId>
    <label>National Account Group ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/NationalAccountPricingId__c.field-meta.xml
<CustomField>
    <fullName>NationalAccountPricingId__c</fullName>
    <externalId>true</externalId>
    <label>NationalAccountPricingId</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/NationalAccountsPricingKey__c.field-meta.xml
<CustomField>
    <fullName>NationalAccountsPricingKey__c</fullName>
    <externalId>true</externalId>
    <label>NationalAccountsPricingKey</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AIQ_NAPTriggerTest.cls
@IsTest
public class AIQ_NAPTriggerTest {

    @TestSetup
    static void creteTestData(){
        List<NationalAccountsPricing__c> newNaps = new List<NationalAccountsPricing__c>();
        for(Integer i=0; i<201; i++){
            NationalAccountsPricing__c na = new NationalAccountsPricing__c (NationalAccountGroupID__c = 'NA'+i, NationalAccountPricingId__c = 'NA'+i, NationalAccountsPricingKey__c = 'NA'+i);
            newNaps.add(na);
        }
        insert newNaps;
    }

    @IsTest
    static void testHandleDelete() {
        system.assertEquals(201,  new List<NationalAccountsPricing__c>([SELECT Id, Name FROM NationalAccountsPricing__c]).size());
        List<NationalAccountsPricing__c> newNaps = new List<NationalAccountsPricing__c>();
        for(NationalAccountsPricing__c nap : [SELECT Id, Name FROM NationalAccountsPricing__c LIMIT 201]){
            NationalAccountsPricing__c newNap = new NationalAccountsPricing__c(id = nap.Id, Action__c = 'D');
            newNaps.add(newNap);
        }

        update newNaps;
        system.assertEquals(0,  new List<NationalAccountsPricing__c>([SELECT Id, Name FROM NationalAccountsPricing__c]).size());


    }
}