force-app/main/default/objects/Pipeline_Review__c/Pipeline_Review__c.object-meta.xml
<CustomObject>
    <description>Tracking tool to enable managers to tell when they reviewed their team&apos;s pipeline.</description>
    <label>Pipeline Review</label>
    <nameField>
        <label>Business Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pipeline_Review__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipName>Pipeline_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BusinessReviewTriggerTest.cls
@isTest
public class BusinessReviewTriggerTest {

    @isTest
    public static void testMethod1(){
        
        
       Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        
     	User usr1 = new User(LastName = 'twert1234',
                           FirstName='teswr43t',
                           Alias = 'tu32bk',
                           Email = 'jasowen.liwrveston@asdf.com',
                           Username = 'jason.liveston@uyf4s.com',
                           ProfileId = profileId.id,
                           TimeZoneSidKey = 'GMT',
                           LanguageLocaleKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LocaleSidKey = 'en_US',
                            Network_Id__c = 'tu32bk',
                            country = 'USA'
                           );
        
        insert usr1;
        
     	User usr = new User(LastName = 'tet1234',
                           FirstName='tes543t',
                           Alias = 'tiubk',
                           Email = 'jason.liveston@asdf.com',
                           Username = 'jason.liviuyutgcteston@uyf4s.com',
                           ProfileId = profileId.id,
                           TimeZoneSidKey = 'GMT',
                           LanguageLocaleKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LocaleSidKey = 'en_US',
                            Network_Id__c = 'tiubk',
                            country = 'USA',
                            managerId = usr1.id
                           );
         insert usr;
        
        Primary_Sales_Rep__c newPSR = new Primary_Sales_Rep__c();
        newPSR.Name = 'Joe Test ';
        newPSR.Network_Id__c = 'tiubk';
        newPSR.Email__c = 'user@domain.com';
        newPSR.SF_userid__c = usr.id;
        insert newPSR ;
        
        
       
        
        
        Pipeline_Review__c pR = new Pipeline_Review__c();
        pR.Name = 'test';
         pR.Primary_Sales_Rep__c = newPSR.id;
        insert pR;
        
    }
    
}