force-app/main/default/objects/Industry_to_Vertical_Custom_Setting__c/Industry_to_Vertical_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of mapping for Industry to Vertical trigger</description>
    <label>Industry to Vertical Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Industry_to_Vertical_Custom_Setting__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Limit vertical to 30 characters only

Any additions/deletions here should also be done on Account Vertical on Account object</description>
    <inlineHelpText>The potential customer&apos;s vertical, not the vertical that Veritiv is selling. The Account Vertical is required in order to provide relevant marketing content.</inlineHelpText>
    <label>Lead Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ent and Hosp - Food</fullName>
            </value>
            <value>
                <fullName>Ent and Hosp - High Traffic</fullName>
            </value>
            <value>
                <fullName>Ent and Hosp - Lodging</fullName>
            </value>
            <value>
                <fullName>Food - Bakery &amp; Snack</fullName>
            </value>
            <value>
                <fullName>Food - Beverage</fullName>
            </value>
            <value>
                <fullName>Food - Candy</fullName>
            </value>
            <value>
                <fullName>Food - Cannabis</fullName>
            </value>
            <value>
                <fullName>Food - Cereal &amp; Grain</fullName>
            </value>
            <value>
                <fullName>Food - Dairy</fullName>
            </value>
            <value>
                <fullName>Food - Farming</fullName>
            </value>
            <value>
                <fullName>Food - Meat</fullName>
            </value>
            <value>
                <fullName>Food - Other</fullName>
            </value>
            <value>
                <fullName>Food - Perishable Prepared</fullName>
            </value>
            <value>
                <fullName>Fulfillment - Logistics</fullName>
            </value>
            <value>
                <fullName>Fulfillment - Online Retail</fullName>
            </value>
            <value>
                <fullName>Fulfillment - Other</fullName>
            </value>
            <value>
                <fullName>Fulfillment - Retail</fullName>
            </value>
            <value>
                <fullName>Fulfillment - Wholesale</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Government - Higher Ed</fullName>
            </value>
            <value>
                <fullName>Government - K - 12</fullName>
            </value>
            <value>
                <fullName>Graphic Design/Advertising</fullName>
            </value>
            <value>
                <fullName>Mfg - Aerospace</fullName>
            </value>
            <value>
                <fullName>Mfg - Apparel</fullName>
            </value>
            <value>
                <fullName>Mfg - Appliances</fullName>
            </value>
            <value>
                <fullName>Mfg - Automotive &amp; Heavy Eqt</fullName>
            </value>
            <value>
                <fullName>Mfg - Building Materials</fullName>
            </value>
            <value>
                <fullName>Mfg - Computers &amp; Electronics</fullName>
            </value>
            <value>
                <fullName>Mfg - Fabricated Metals</fullName>
            </value>
            <value>
                <fullName>Mfg - Furniture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLeadVerticalUpdate.cls
/**

 */
@isTest
private class TestLeadVerticalUpdate {
	// In a static block Create custom settings from scratch
    // CHecking for existing custom settings if they exist we delete them and create our own
static {
	system.runAs(testingUtils.admin_User){
        
        /*
        // Not Needed after API version 23
        Map<String,Industry_to_Vertical_Custom_Setting__c> settingsToDelete = Industry_to_Vertical_Custom_Setting__c.getAll();
        if (!settingsToDelete.isEmpty()){
        	delete settingsToDelete.values();
        	
        	}
        */
        	Industry_to_Vertical_Custom_Setting__c testIndustryToVertical1 = new Industry_to_Vertical_Custom_Setting__c (Name = 'Healthcare', Vertical__c = 'Healthcare');
        	Industry_to_Vertical_Custom_Setting__c testIndustryToVertical2 = new Industry_to_Vertical_Custom_Setting__c (Name = 'Government', Vertical__c = 'Government');
        	insert new List<Industry_to_Vertical_Custom_Setting__c> {testIndustryToVertical1, testIndustryToVertical2};
        	
        }
}
    static testMethod void testLeadCreation() {
        // TO DO: implement unit test
        
        // Create a Lead with reported industry set to a value
        // ensure value copies over to vertical field
        
        Lead testLead = testingUtils.createLeads(1, 'TestName', false).get(0);
        testLead.Industry = 'Healthcare';
                
        test.startTest();
        	insert testLead;
        test.stopTest();
        
        testLead = [SELECT Id, Vertical__c FROM Lead WHERE Id = :testLead.Id LIMIT 1];
        
       // system.assertEquals ('Healthcare', testLead.Vertical__c);
        
    }
    
     static testMethod void testLeadModify() {
        
        // Create a Lead with reported industry set to a value
        // ensure value copies over to vertical field
        // Modify existing Lead
        // ensure value copies over to vertical field
        
        Lead testLead = testingUtils.createLeads(1, 'TestName', false).get(0);
        testLead.Industry = 'Healthcare';
        insert testLead;       
        testLead.Industry = 'Government';
        
        test.startTest();
        	update testLead;
        test.stopTest();
        
        testLead = [SELECT Id, Vertical__c FROM Lead WHERE Id = :testLead.Id LIMIT 1];
        
       // system.assertEquals('Government', testLead.Vertical__c);
        
    }
    
        
        
        
        
    }