force-app/main/default/objects/Legal_Contract__c/Legal_Contract__c.object-meta.xml
<CustomObject>
    <description>Used by Sales and Equipment teams for legal contracts that will be integrated with CLM docusign</description>
    <label>Legal Contract</label>
    <nameField>
        <label>Legal Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Legal Contracts</relationshipLabel>
    <relationshipName>Legal_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LegalContractServicesTest.cls
@isTest
private class LegalContractServicesTest {
    
    @testSetup static void setup() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        UserRole r = new UserRole(DeveloperName = 'FS_CATEGORY_MGMT_Leaderstest', Name = 'FS - CATEGORY MGMT - Leaders');
        insert r;
        User u = new User(Alias = 't74vdt', Email='sttesdt435user@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, Country = 'USA',
            TimeZoneSidKey='America/Los_Angeles', UserName='standartes536r@tigorg.com',userRoleId = r.id,Network_Id__c ='t74vdt' );
        
        insert u;
        
        User u1= new User(Alias = 't7uydt', Email='sttkjhdt435user@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, Country = 'USA',
            TimeZoneSidKey='America/Los_Angeles', UserName='stdjhgvartes536r@tigorg.com',Network_Id__c ='t7uydt' );
        
        insert u1;    
    }
    
    static testmethod void testChangeOwner(){
        user u = [select id from user where Username = 'standartes536r@tigorg.com' limit 1];
        user u1 = [select id from user where Username = 'stdjhgvartes536r@tigorg.com' limit 1];
        
        Account acc = new Account ();
        acc.Name = 'test';
        acc.ownerid = u.id;
        insert acc;
           
        Legal_Contract__c lc = new Legal_Contract__c();
        lc.Account__c=acc.id;
        lc.ownerid = u.id;
        insert lc;
           
        acc.ownerid = u1.id;
        update acc;
           
       
        
    }
}