force-app/main/default/objects/Contract_Line_Item_Approval__c/Contract_Line_Item_Approval__c.object-meta.xml
<CustomObject>
    <description>Custom object to track the progress of a line item approval. The custom object route met the business requirements most aptly, specifically the ability to auto-escalate on a time-based schedule.</description>
    <label>Contract Line Item Approval</label>
    <nameField>
        <displayFormat>#{00000}</displayFormat>
        <label>Contract Line Item Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Item Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Actioned_By__c.field-meta.xml
<CustomField>
    <fullName>Actioned_By__c</fullName>
    <description>Created by BW to update whenever the status changes from Pending</description>
    <label>Actioned By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Actioned_Date__c.field-meta.xml
<CustomField>
    <fullName>Actioned_Date__c</fullName>
    <description>Created by BW to identify the date the status changes from Pending</description>
    <label>Actioned Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by BW to reference the contract line item on the Contract Line Item Approval records</description>
    <inlineHelpText>Please select the corresponding contract line item associated with the Contract Line Item Approval record.</inlineHelpText>
    <label>Contract Line Item</label>
    <referenceTo>zpl__ContractLineItem__c</referenceTo>
    <relationshipLabel>Contract Line Item Approvals</relationshipLabel>
    <relationshipName>Contract_Line_Item_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item_Approval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created by BW to track the status of Contract Line Item Approval Records</description>
    <inlineHelpText>Please select the status of the Contract Line Item Approval Record</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CLIApprovalTriggerHandler.cls
public class CLIApprovalTriggerHandler {
    public static Boolean contracLineItemApprovalTriggerFlag = false; // for preventing recursion

    public static void beforeUpdate(list<Contract_Line_Item_Approval__c> listCLIA, map<Id, Contract_Line_Item_Approval__c> oldMap, map<Id, Contract_Line_Item_Approval__c> newMap) {

        contracLineItemApprovalTriggerFlag = true;
        System.debug('contracLineItemApprovalTriggerFlag' + contracLineItemApprovalTriggerFlag);
        
        list<Id> listCLIAApproved = new list<Id>();
        list<Id> listCLIARejected = new list<Id>();
        list<Id> listCLIACanceled = new list<Id>();

        list<Id> listCLIAId = new list<Id>();
        list<Id> listCLIId = new list<id>();
        for(Contract_Line_Item_Approval__c clia : listCLIA){
            if(oldMap.get(clia.Id).Status__c != newMap.get(clia.Id).Status__c){
                system.debug('##clia: ' + clia);
                system.debug('##clia.Status__c: ' + clia.Status__c);
    
                if(clia.Status__c == 'Approved'){
                    clia.Actioned_Date__c = datetime.now();
                    clia.RecordTypeId = System.label.CLIA_Closed_Record_Type_ID;
                    listCLIAId.add(clia.Id);
                    listCLIAApproved.add(clia.Id);
                }else if(clia.Status__c == 'Rejected'){
                    clia.RecordTypeId = System.label.CLIA_Closed_Record_Type_ID;
                    listCLIARejected.add(clia.Id);
                    listCLIId.add(clia.Contract_Line_Item__c);
                }else if (clia.Status__c == 'Cancelled'){
                    clia.Actioned_By__c = 'Expiration';
                    clia.Actioned_Date__c = datetime.now();
                    clia.RecordTypeId = System.label.CLIA_Closed_Record_Type_ID;
                }
            }
        }

        //Approved
        system.debug('##listCLIAApproved: ' + listCLIAApproved);
        system.debug('##listCLIAApproved: ' + listCLIAApproved.size());
        if(listCLIAApproved.size() > 0){
            ContractLineItemApprovalService.mNewCLIA = newMap;
            ContractLineItemApprovalService.createContractLineItemApprovals(listCLIAApproved);
        }

        //Rejected 
        system.debug('##Rejected listCLIId: ' + listCLIId);
        system.debug('##Rejected listCLIId: ' + listCLIId.size());
        if(listCLIId.size() > 0){
            AIQAgrLineRejection.rejectAgrLine(listCLIId);
            SendRejectedEmail(listCLIId);
        }        
    }

    public static void SendRejectedEmail (List<Id> listCLIARejected) {

        list<Messaging.SingleEmailMessage> listmail = new list<Messaging.SingleEmailMessage>();
        
        EmailTemplate et = [Select id from EmailTemplate where DeveloperName = 'Deal_Manager_Contract_Line_Item_Rejection_Notification'];

        for(zpl__ContractLineItem__c cli : [Select Id, CreatedById , Published_By__c From zpl__ContractLineItem__c Where Id IN :listCLIARejected]){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String createdBy = cli.CreatedById ;
            mail.setTargetObjectId( createdBy );
            mail.setWhatId(cli.Id);            
            mail.setTemplateId(et.Id);

            mail.setUseSignature(false);
            mail.setBccSender(false);
            //mail.setSaveAsActivity(true);

            //listmail.add(mail);
        }
        
        System.debug('Sending the email ');     
        //Messaging.sendEmail(listmail);
        Messaging.SendEmailResult [] r = Messaging.sendEmail(listmail);
        System.debug ('##Email - ' + r );

    }

}