force-app/main/default/objects/ANI_Routing_Record__c/ANI_Routing_Record__c.object-meta.xml
<CustomObject>
    <description>The ANI routing logic for the Cisco application.</description>
    <label>Routing Record</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Routing Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ANI_Routing_Record__c/fields/Inactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Date__c</fullName>
    <description>Tracks when Inactive__c is checked.</description>
    <label>Inactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RoutingRecordCleanupBatch.cls
//Batch for deleting Routing Records that have been inactive for more than 60 days
public class RoutingRecordCleanupBatch implements Database.Batchable<SObject>, Schedulable, Database.Stateful {

    public void execute(SchedulableContext context) {
        Database.executeBatch(this, 200);
    }

    public List<ANI_Routing_Record__c> start(Database.BatchableContext bc) {
        return
            [SELECT Inactive_Date__c
            FROM ANI_Routing_Record__c
            WHERE Inactive_Date__c != TODAY AND Inactive_Date__c != null];
    }

    public void execute(Database.BatchableContext bc, List<ANI_Routing_Record__c> oldInactiveRoutingRecords) {
        delete oldInactiveRoutingRecords;
    }

    public void finish(Database.BatchableContext bc) {}
}