force-app/main/default/objects/ANI_Routing_Record__c/ANI_Routing_Record__c.object-meta.xml
<CustomObject>
    <description>The ANI routing logic for the Cisco application.</description>
    <label>Routing Record</label>
    <nameField>
        <displayFormat>RR-{000000000}</displayFormat>
        <label>Routing Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ANI_Routing_Record__c/fields/ANI_Contact__c.field-meta.xml
<CustomField>
    <fullName>ANI_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A contact can either be an individual at an external account or a Veritiv primary sales rep. This field is a lookup to a contact record.</description>
    <inlineHelpText>Who is the inbound caller whose calls need to be routed?</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ANI Routing Records</relationshipLabel>
    <relationshipName>Routing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ANI_Routing_Record__c/fields/ANI_Toll_Free_Map_Number__c.field-meta.xml
<CustomField>
    <fullName>ANI_Toll_Free_Map_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A lookup to the TFN_Mapping object. Records of that object have a name (the TFN) and a DID Number. This field exists to feed the DID Number to the Routing Record.</description>
    <inlineHelpText>Select a Toll-Free Number. If a contact dials this phone number, the call should be managed by the corresponding CSP.</inlineHelpText>
    <label>Toll-Free-Number</label>
    <referenceTo>ANI_TFN_Mapping__c</referenceTo>
    <relationshipLabel>Routing Records</relationshipLabel>
    <relationshipName>Routing_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ANI_Routing_Record__c/fields/Inactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Date__c</fullName>
    <description>Tracks when Inactive__c is checked.</description>
    <label>Inactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ANI_TFN_Mapping__c/ANI_TFN_Mapping__c.object-meta.xml
<CustomObject>
    <description>This custom object exists to improve the user experience for the system administrators that will be adding/modifying records for the custom object Routing Record. 

A record of this object should have a field for toll-free number and DID number.</description>
    <label>TFN Mapping</label>
    <nameField>
        <label>Toll-Free Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TFN Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the contact is no longer active.  This will enable the Inactive Reason field for you to give further detail.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive_Date__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Date__c</fullName>
    <description>Date the status changes from active to inactive on contacts</description>
    <label>Inactive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RoutingRecordCleanupBatchTest.cls
@IsTest
private class RoutingRecordCleanupBatchTest {
    @IsTest
    static void testInactiveDateStamp() {
        Contact testContact = (Contact) new SObjectBuilder(Contact.SObjectType)
                .create().getRecord();
        ANI_TFN_Mapping__c testMapping = (ANI_TFN_Mapping__c) new SObjectBuilder(ANI_TFN_Mapping__c.SObjectType)
            	.put(ANI_TFN_Mapping__c.name, '123-456-7890')
                .create().getRecord();
        ANI_Routing_Record__c testRecord = (ANI_Routing_Record__c) new SObjectBuilder(ANI_Routing_Record__c.SObjectType)
                .put(ANI_Routing_Record__c.ANI_Contact__c, testContact.Id)
                .put(ANI_Routing_Record__c.ANI_Toll_Free_Map_Number__c, testMapping.Id)
                .create().getRecord();

        testRecord.put(ANI_Routing_Record__c.Inactive__c, true);

        Test.startTest();
            update testRecord;
        Test.stopTest();

        Date today = Date.today();
        Date dateInSystem = [SELECT Inactive_Date__c FROM ANI_Routing_Record__c].Inactive_Date__c;
        System.assertEquals(today, dateInSystem, 'We expect the Inactive date to be stamped with the current date.');
    }
    @isTest
    static void testDelete60DayOldRecord() {
        Contact testContact = (Contact) new SObjectBuilder(Contact.SObjectType)
                .create().getRecord();
        ANI_TFN_Mapping__c testMapping = (ANI_TFN_Mapping__c) new SObjectBuilder(ANI_TFN_Mapping__c.SObjectType)
            	.put(ANI_TFN_Mapping__c.name, '123-456-7890')
                .create().getRecord();
        ANI_Routing_Record__c testRecord = (ANI_Routing_Record__c) new SObjectBuilder(ANI_Routing_Record__c.SObjectType)
                .put(ANI_Routing_Record__c.ANI_Contact__c, testContact.Id)
                .put(ANI_Routing_Record__c.ANI_Toll_Free_Map_Number__c, testMapping.Id)
                .put(ANI_Routing_Record__c.Inactive__c, true)
                .create().getRecord();

        testRecord.put(ANI_Routing_Record__c.Inactive_Date__c, Date.today().addDays(-61));
        update testRecord;

        RoutingRecordCleanupBatch cleanupBatch = new RoutingRecordCleanupBatch();

        Test.startTest();
            Database.executeBatch(cleanupBatch);
        Test.stopTest();

        ANI_Routing_Record__c deletedRecord = [SELECT IsDeleted FROM ANI_Routing_Record__c ALL ROWS];
        System.assertEquals(true, deletedRecord.IsDeleted,
                'We expect a routing record that has been Inactive for 60 days or more to be deleted.');
    }
    @isTest
    static void testDontDeleteUnder60DayOldRecord() {
        Contact testContact = (Contact) new SObjectBuilder(Contact.SObjectType)
                .create().getRecord();
        ANI_TFN_Mapping__c testMapping = (ANI_TFN_Mapping__c) new SObjectBuilder(ANI_TFN_Mapping__c.SObjectType)
            	.put(ANI_TFN_Mapping__c.name, '123-456-7890')
                .create().getRecord();
        ANI_Routing_Record__c testRecord = (ANI_Routing_Record__c) new SObjectBuilder(ANI_Routing_Record__c.SObjectType)
                .put(ANI_Routing_Record__c.ANI_Contact__c, testContact.Id)
                .put(ANI_Routing_Record__c.ANI_Toll_Free_Map_Number__c, testMapping.Id)
                .put(ANI_Routing_Record__c.Inactive__c, true)
                .create().getRecord();

        RoutingRecordCleanupBatch cleanupBatch = new RoutingRecordCleanupBatch();

        Test.startTest();
            Database.executeBatch(cleanupBatch);
        Test.stopTest();

        ANI_Routing_Record__c notDeletedRecord = [SELECT IsDeleted FROM ANI_Routing_Record__c];
        System.assertEquals(false, notDeletedRecord.IsDeleted,
                'We expect a routing record that has been Inactive for less than 60 days to not be deleted.');
    }
}