force-app/main/default/objects/Account/fields/Account_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Account_Vertical__c</fullName>
    <description>Limit verticals to 30 characters only

Any changes/additions here should also be made on Lead object, field Vertical, Vertical object and Brainshark
Must also add a Vertical record (to the Vertical object)

****If the values:  PRINTER - WEB or PRINTER - DIGITAL/WIDE FORMAT are ever changed, contact Heather Sagan immediately!!!  Any changes will impact call routing in the LA CSC!!!****</description>
    <inlineHelpText>Select the vertical that best suits this account.</inlineHelpText>
    <label>Sub Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Grouping__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Assisted Living</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Bakery &amp; Snack</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
            <value>
                <fullName>Big Box</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>Building Materials</fullName>
            </value>
            <value>
                <fullName>Candy</fullName>
            </value>
            <value>
                <fullName>Cereal &amp; Grain</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Computer &amp; Electronics</fullName>
            </value>
            <value>
                <fullName>Correctional</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>C-Stores</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Eating &amp; Drinking</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Electronic Shopping</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Grocery Stores</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Higher Ed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prospect_Segment__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Segment__c</fullName>
    <description>Require this field on the Prospect account.  Then use a workflow to convert this selection to the proper code for the Segment (F, P, M, L).  This is the code that comes in from DW on Customer Accounts.  Not required on 3PL prospects, as there is no matching Segment for them. 

Any changes to the picklist values should be coordinated with Brainshark administration and should also be made on the following objects - Vendor Detail, Opportunity, Contact, Lead, Work Orders.

1/29/18 - AL - Made this an unrestriced picklist because it was causing validation errors when converting to existing accounts</description>
    <label>Prospect Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facility Solutions</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Work_Order_Durations__c/Work_Order_Durations__c.object-meta.xml
<CustomObject>
    <description>Testing work order status calculations</description>
    <label>Work Order Durations</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Work Order Durations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Durations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Durations__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Input Work Order number.</description>
    <label>Parent</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Work Order Durations</relationshipLabel>
    <relationshipName>Work_Order_Durations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order_Durations__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/WorkOrderDurationsTest.cls
@isTest
private class WorkOrderDurationsTest {
    
    @isTest
    static void testTriggerInsertAndUpdate() {
        Primary_Sales_Rep__c rep = new Primary_Sales_Rep__c(Name='Test Name', Network_ID__c='TestTest', Email__c='test@test.com');
        insert rep;
        
        Account testAccount = new Account(Name='Test', Primary_Sales_Rep_Name__c=rep.Id, Account_Vertical__c='Education',Prospect_Segment__c='Print');
        insert testAccount;
        
        WorkOrder testWorkOrder = new WorkOrder(AccountId=testAccount.Id, Request__c='Test Work Order');
        insert testWorkOrder;
        
    	Work_Order_Durations__c wod = new Work_Order_Durations__c(Parent__c=testWorkOrder.Id, Status__c='Insert');        

        try {
            insert wod;
        } catch (Exception e) {
            System.assert(false, 'Before insert trigger should successfully run, but failed with this error: ' + e.getMessage());
        }
        
        wod.Status__c = 'Update';
        
        try {
            update wod;
        } catch (Exception e) {
            System.assert(false, 'Before update trigger should successfully run, but failed with this error: ' + e.getMessage());
        }
    }
}