force-app/main/default/objects/Account/fields/Account_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Account_Vertical__c</fullName>
    <description>Limit verticals to 30 characters only

Any changes/additions here should also be made on Lead object, field Vertical, Vertical object and Brainshark
Must also add a Vertical record (to the Vertical object)

****If the values:  PRINTER - WEB or PRINTER - DIGITAL/WIDE FORMAT are ever changed, contact Heather Sagan immediately!!!  Any changes will impact call routing in the LA CSC!!!****</description>
    <inlineHelpText>Select the vertical that best suits this account.</inlineHelpText>
    <label>Sub Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Grouping__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Assisted Living</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Bakery &amp; Snack</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
            <value>
                <fullName>Big Box</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>Building Materials</fullName>
            </value>
            <value>
                <fullName>Candy</fullName>
            </value>
            <value>
                <fullName>Cereal &amp; Grain</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Computer &amp; Electronics</fullName>
            </value>
            <value>
                <fullName>Correctional</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>C-Stores</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Eating &amp; Drinking</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Electronic Shopping</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Grocery Stores</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Higher Ed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Segment_2__c.field-meta.xml
<CustomField>
    <fullName>Segment_2__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>F = Fine Paper
M = Facilities Supplies
P = Packaging
L = Publishing</inlineHelpText>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>FS</fullName>
            </value>
            <value>
                <fullName>PK</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LightningSearchComponentController.cls
public without sharing class LightningSearchComponentController {

    @TestVisible private static final List<SObjectType> OBJECTS = new List<SObjectType>{ Account.SObjectType, Lead.SObjectType };
    @TestVisible private static final Map<String, String> segmentMap = new Map<String, String>{
        'F' => 'Print','M' => 'Facility Solutions','P' => 'Packaging','L' => 'Publishing'
    };

    @TestVisible private static final String headerSetFormat = '_LS_Display_Fields';
    @TestVisible private static final String subHeaderSetFormat = '_LS_Sub_Fields';
    @TestVisible private static final String detailSetFormat = '_LS_Detail_Fields';
    @TestVisible private static final String searchFieldSetFormat = '_LS_Search_Fields';

    public class MetadataWrapper {
        @AuraEnabled public Map<String, FormatWrapper> displayFormats;
        @AuraEnabled public List<FieldWrapper> statePicklistValues;
        @AuraEnabled public List<FieldWrapper> segmentPicklistValues;
        @AuraEnabled public List<FieldWrapper> verticalPicklistValues;
    }

    public class FormatWrapper {
        @AuraEnabled public FieldWrapper objectName;
        @AuraEnabled public List<FieldWrapper> headerFields;
        @AuraEnabled public List<FieldWrapper> subHeaderFields;
        @AuraEnabled public List<FieldWrapper> detailFields;
        @AuraEnabled public List<FieldWrapper> searchFields;
    }

    public class FieldWrapper {
        @AuraEnabled public String name;
        @AuraEnabled public String label;

        public FieldWrapper(FieldSetMember member) {
            this.name = member.getFieldPath();
            this.label = member.getLabel();
        }

        public FieldWrapper(String name, String label) {
            this.name = name;
            this.label = label;
        }
    }

    @AuraEnabled
    public static MetadataWrapper getObjectMetadata() {
        MetadataWrapper objectMetadata = new MetadataWrapper();
        objectMetadata.displayFormats = new Map<String, FormatWrapper>();

        for(SObjectType objectType : OBJECTS) {
            String objectName = objectType.getDescribe().getName();
            Map<String, Schema.FieldSet> objectFieldSets = objectType.getDescribe().fieldsets.getMap();

            Schema.FieldSet headerFieldSet = objectFieldSets.get(objectName + headerSetFormat);
            Schema.FieldSet subHeaderFieldSet = objectFieldSets.get(objectName + subHeaderSetFormat);
            Schema.FieldSet detailFieldSet = objectFieldSets.get(objectName + detailSetFormat);
            Schema.FieldSet searchFieldSet = objectFieldSets.get(objectName + searchFieldSetFormat);

            FormatWrapper metadata = new FormatWrapper();
            metadata.objectName = new FieldWrapper(objectName, objectType.getDescribe().getLabel());

            metadata.headerFields = fieldsetToFields(headerFieldSet);
            metadata.subHeaderFields = fieldsetToFields(subHeaderFieldSet);
            metadata.detailFields = fieldsetToFields(detailFieldSet);
            metadata.searchFields = fieldsetToFields(searchFieldSet);

            objectMetadata.displayFormats.put(objectName, metadata);
        }

        objectMetadata.statePicklistValues = new List<FieldWrapper>();
        List<Schema.PicklistEntry> stateEntries = Lead.State__c.getDescribe().getPicklistValues();
        for(Schema.PicklistEntry entry : stateEntries) {
            objectMetadata.statePicklistValues.add(new FieldWrapper(entry.getValue(), entry.getLabel()));
        }

        objectMetadata.segmentPicklistValues = new List<FieldWrapper>();
        List<Schema.PicklistEntry> segmentEntries = Account.Segment_2__c.getDescribe().getPicklistValues();
        for(Schema.PicklistEntry entry : segmentEntries) {
            String segmentValue = entry.getValue();
            String segmentLabel = entry.getLabel();
            if(segmentMap.containsKey(segmentValue)) {
                segmentLabel = segmentMap.get(segmentValue);
            }
            
            objectMetadata.segmentPicklistValues.add(new FieldWrapper(segmentValue, segmentLabel));
        }

        objectMetadata.verticalPicklistValues = new List<FieldWrapper>();
        List<Schema.PicklistEntry> verticalEntries = Account.Account_Vertical__c.getDescribe().getPicklistValues();
        for(Schema.PicklistEntry entry : verticalEntries) {
            objectMetadata.verticalPicklistValues.add(new FieldWrapper(entry.getValue(), entry.getLabel()));
        }

        return objectMetadata;
    }

    @AuraEnabled
    public static Map<String, List<SObject>> searchObjects(String searchString, String formatsString, String filtersString,  String filterOperatorsString) {
        Map<String, FormatWrapper> displayFormats = (Map<String, FormatWrapper>) JSON.deserialize(formatsString, Map<String, FormatWrapper>.class);

        Map<String, Map<String, List<String>>> objectNameToFilters = 
            (Map<String, Map<String, List<String>>>) JSON.deserialize(filtersString, Map<String, Map<String, List<String>>>.class);
        Map<String, Map<String, String>> objectNameToFilterOperators = 
            (Map<String, Map<String, String>>) JSON.deserialize(filterOperatorsString, Map<String, Map<String, String>>.class);
		
        System.debug('###objectNameToFilters: '+ objectNameToFilters);
        List<String> returnValues = new List<String>();

        List<String> objectNames = new List<String>(displayFormats.keySet());
        for(String objectName : objectNames) {
            FormatWrapper displayFormat = displayFormats.get(objectName);

            List<FieldWrapper> fields = displayFormat.headerFields;
            fields.addAll(displayFormat.subHeaderFields);
            fields.addAll(displayFormat.detailFields);

            List<String> fieldStrings = new List<String>();
            for(FieldWrapper field : fields) {
                fieldStrings.add(field.name);
            }
              System.debug('fieldStrings'+fieldStrings);
            List<String> whereClauses = new List<String>();

            for(FieldWrapper searchField : displayFormat.searchFields) {
                whereClauses.add(searchField.name + ' LIKE \'%' + searchString + '%\'');
            }
              System.debug('whereClauses'+whereClauses);
            Map<String, List<String>> filters = objectNameToFilters.get(objectName);
            System.debug('filters'+filters);
            Map<String, String> filterOperators = objectNameToFilterOperators.get(objectName);
            System.debug('filterOperators'+filterOperators);
            if(filters != NULL) {
                Set<String> validLeadStatus = new Set<String>{'Converted', '0_Dead'};
                List<String> fieldNames = new List<String>(filters.keySet());

                for(String fieldName : fieldNames) {
 
                    // Skip filtering for Lead.Status if it's in the excluded statuses
                   
                    List<String> orClauses = new List<String>();
                    for(String filterValue : filters.get(fieldName)) {
                        String filterOperatorValue = filterOperators.get(fieldName);
                        System.debug('filterValue filterValue ' + filterValue);
                        if(filterValue == '%%'){
                            continue;
                        }
                        else if(String.isBlank(filterValue)) {
                            orClauses.add(fieldName + ' ' + filterOperatorValue + ' NULL');
                            System.debug('orClauses'+orClauses);
                        }
                        else {
                            orClauses.add(fieldName + ' ' + filterOperatorValue + ' \'' + filterValue + '\'');
                            System.debug('orClauses'+orClauses);
                        }
                    }
                    if( fieldName == 'Status' ){
                        whereClauses.add( '( ' + fieldName + ' NOT IN ( \'0_Dead\', \'Converted\' ) ' + ')' );
                    }
                     
                    if(!orClauses.isEmpty()) {
                        whereClauses.add( '(' + String.join(orClauses, ' OR ') + ')' );
                        System.debug('orClauses'+orClauses);
                    }
                }


            }
            System.debug('whereClauses'+whereClauses);
            String whereString = '';
            if(!whereClauses.isEmpty()) {
                whereString = ' WHERE ' + String.join(whereClauses, ' AND ');
                System.debug('whereString'+whereString);
            }

            returnValues.add(objectName + '(' + String.join(fieldStrings, ',') + 
                whereString +')');
            System.debug('whereString'+whereString);
        }
          
        String queryString = 'FIND :searchString ';
        queryString += 'IN ALL FIELDS RETURNING ' + String.join(returnValues, ',');
        System.debug(queryString);
        System.debug(returnValues);
        List<List<SObject>> results = Search.query(queryString);

        Map<String, List<SObject>> objectNameToResults = new Map<String, List<SObject>>();
        for(Integer i = 0; i < objectNames.size(); i++) {
            objectNameToResults.put(objectNames[i], results[i]);
        }
        return objectNameToResults;
    }

    @TestVisible
    private static List<FieldWrapper> fieldsetToFields(Schema.FieldSet fieldSet) {
        List<FieldWrapper> fields = new List<FieldWrapper>();

        for(Schema.FieldSetMember field : fieldSet.getFields()) {
            fields.add(new FieldWrapper(field));
        }

        return fields;
    }
    

}