force-app/main/default/objects/Account/fields/Account_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Account_Vertical__c</fullName>
    <description>Limit verticals to 30 characters only

Any changes/additions here should also be made on Lead object, field Vertical, Vertical object and Brainshark
Must also add a Vertical record (to the Vertical object)

****If the values:  PRINTER - WEB or PRINTER - DIGITAL/WIDE FORMAT are ever changed, contact Heather Sagan immediately!!!  Any changes will impact call routing in the LA CSC!!!****</description>
    <inlineHelpText>Select the vertical that best suits this account.</inlineHelpText>
    <label>Sub Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Grouping__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Assisted Living</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Bakery &amp; Snack</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
            <value>
                <fullName>Big Box</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>Building Materials</fullName>
            </value>
            <value>
                <fullName>Candy</fullName>
            </value>
            <value>
                <fullName>Cereal &amp; Grain</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Computer &amp; Electronics</fullName>
            </value>
            <value>
                <fullName>Correctional</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>C-Stores</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Eating &amp; Drinking</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Electronic Shopping</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Grocery Stores</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Higher Ed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Case/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.deactivated_user__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Engineering/Lean Engineer</fullName>
            </value>
            <value>
                <fullName>Environmental Services (Custodial/EVS/Housekeeping)</fullName>
            </value>
            <value>
                <fullName>Estimating</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Infection Control</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Maintenance/Facility Manager</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations/Logistics/Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Owner/President</fullName>
            </value>
            <value>
                <fullName>Procurement/Purchasing</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Production/Manufacturing</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sustainability</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Eloqua_Lead_Rating__c.field-meta.xml
<CustomField>
    <fullName>Eloqua_Lead_Rating__c</fullName>
    <inlineHelpText>Automatically populated from the Eloqua system.</inlineHelpText>
    <label>Mktg Automation Lead Rating</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>The department that the lead represents.</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Engineering/Lean Engineer</fullName>
            </value>
            <value>
                <fullName>Environmental Services (Custodial/EVS/Housekeeping)</fullName>
            </value>
            <value>
                <fullName>Estimating</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Infection Control</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Maintenance/Facility Manager</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations/Logistics/Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Owner/President</fullName>
            </value>
            <value>
                <fullName>Procurement/Purchasing</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Production/Manufacturing</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sustainability</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Eloqua_Lead_Rating__c.field-meta.xml
<CustomField>
    <fullName>Eloqua_Lead_Rating__c</fullName>
    <label>Eloqua Lead Rating</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <description>BW-2012
Related to the Genesis project for mobile sales reps</description>
    <label>Network ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The rep who will be working the lead. Sometimes different from the Lead Owner.</inlineHelpText>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Account_Vertical__c</fullName>
    <formula>TEXT(Account.Account_Vertical__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Vertical</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Selling_Margin_Rate__c.field-meta.xml
<CustomField>
    <fullName>Customer_Selling_Margin_Rate__c</fullName>
    <inlineHelpText>Choose your target margin percentage for this opportunity</inlineHelpText>
    <label>Customer Selling Margin Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Primary Sales Rep
When a new Quote is created from an Account or Opportunity Record, the Primary Sales Rep field is pre-populated (but editable) with the Primary Sales Rep tied to the related Account
When a new Quote is created from an Opportunity, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Opportunity’s related Account, regardless of the Primary Sales Rep listed on the Opportunity. 
When a new Quote is created from a Contact, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Contact’s related Account record, regardless of the Primary Sales Rep listed on the Contact. 
When a Quote is cloned, the new Quote’s Primary Sales Rep field on the new cloned Quote is pre-populated with the Primary Sales Rep from the Quote it was cloned from</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataGeneration.cls
public class TestDataGeneration {

    public static final String LEAD_SOURCE = 'Web';
    public static final String LEAD_DEPT = 'Marketing';
    public static final String LEAD_STATUS = '1-Identify';

    public static final String SINGLE_EMAIL = 'bobaa@smsith.com';

    public static final Id TEST_ACCOUNT_ID = createAccount('Test Account', true).Id;

    private static Integer PSRNetworkIdOffSet = 1;

    public static void generateTestLeadBatch( Integer numOfLeads, String testEmail, Boolean initialEmailOpt, List<Lead> testLeads ) {

        generateTestLeadBatch( numOfLeads, testEmail, initialEmailOpt, testLeads, true );

    }

    public static void generateTestLeadBatch( Integer numOfLeads, String testEmail, Boolean initialEmailOpt, List<Lead> testLeads, Boolean willInsert ) {

        for( Integer i = 0; i < numOfLeads; i++ )
            testLeads.add( TestDataGeneration.generateTestLead( testEmail, initialEmailOpt ) );

        if ( willInsert )
            insert testLeads;

    }

    public static void generateTestContactBatch( Integer numOfContacts, String testEmail, Boolean initialEmailOpt, List<Contact> testContacts ) {

        generateTestContactBatch( numOfContacts, testEmail, initialEmailOpt, testContacts, true );
    }

    public static void generateTestContactBatch( Integer numOfContacts, String testEmail, Boolean initialEmailOpt, List<Contact> testContacts, Boolean willInsert ) {

        for( Integer i = 0; i < numOfContacts; i++ )
            testContacts.add( TestDataGeneration.generateTestContact( testEmail, initialEmailOpt ) );

        if ( willInsert )
            insert testContacts;

    }

    public static Lead generateTestLead( String email, String eloquaRating ) {

        return generateTestLead( 'Bob', 'Smith', email, false, eloquaRating, 'Some Company', false );
    }

    public static Lead generateTestLead( String email, Boolean emailOptOut ) {

        return generateTestLead( 'Bob', 'Smith', email, emailOptOut, '', 'Some Company', false );
    }

    public static Lead generateTestLead( String firstName, String lastName, String email, Boolean emailOptOut, String eloquaRating, String companyName, Boolean willInsert ) {

        Lead testLead = new Lead();

        testLead.FirstName = firstName;
        testLead.LastName = lastName;
        testLead.Company = companyName;
        testLead.Department__c = LEAD_DEPT;
        testLead.Status = LEAD_STATUS;
        testLead.LeadSource = LEAD_SOURCE;
        testLead.Email = email;
        testLead.HasOptedOutOfEmail = emailOptOut;
        testLead.Eloqua_Lead_Rating__c = eloquaRating;

        if ( willInsert )
            insert testLead;

        return testLead;

    }

    public static Contact generateTestContact( String email, String eloquaRating ) {

        return generateTestContact( 'Doe', TEST_ACCOUNT_ID, email, false, eloquaRating, false );
    }

    public static Contact generateTestContact( String email, Boolean emailOptOut ) {

        return generateTestContact( 'Doe', TEST_ACCOUNT_ID, email, emailOptOut, '', false );
    }

    public static Contact generateTestContact( String lastName, Id accountId, String email, Boolean emailOptOut, String eloquaRating, Boolean willInsert ) {

        Contact testContact = new Contact();

        testContact.LastName = lastName;
        testContact.Email = email;
        testContact.AccountId = accountId;
        testContact.HasOptedOutOfEmail = emailOptOut;
        testContact.Eloqua_Lead_Rating__c = eloquaRating;

        if ( willInsert )
            insert testContact;

        return testContact;

    }

    public static User getTestUser(String userName, String profileName)
    {
        String profileId;
        try
        {
            profileId = [SELECT Id FROM Profile WHERE Name = :profileName].Id;
        }
        catch(Exception ex)
        {
            System.debug(ex);
            System.assert(false, 'No profile exists with name'+ profileName);
        }
        User testUser = new User();
        testUser.LastName = 'test ' + UserName;
        
        Integer aliasLength = Schema.SObjectType.User.fields.Alias.getLength(); 
        testUser.Alias = (String) new SObjectFieldProviders.UniqueFixedLengthStringProvider(aliasLength).getValue();
                                                   
        testUser.Network_Id__c = testUser.Alias;
        testUser.Email = UserName+'@unisourcelink.com';
        testUser.Username = UserName+UserName+'@test.com';
        testUser.CommunityNickname = 'a'+UserName;
        testUser.TimeZoneSidKey = 'America/New_York';
        testUser.LocaleSidKey = 'en_US';
        testUser.EmailEncodingKey = 'ISO-8859-1';
        testUser.ProfileId = profileId;
        testUser.LanguageLocaleKey = 'en_US';
        testUser.Country = 'USA';
        testUser.IsActive = true;

        return testUser;
    }

    public static User ADMIN_USER = createUser('TestAd', 'System Administrator', false);

    public static User createUser(String userName, String profileName, Boolean insertUser)
    {
           return createUsers(userName, profileName, 1, insertUser)[0];
    }

    public static List<User> createUsers(String userName, String profileName, Integer size, Boolean insertUsers)
    {

           List<User>allUsers = new List<User>();

           String profileId;
            try
            {
                profileId = [SELECT Id FROM Profile WHERE Name = :profileName].Id;
            }
            catch(Exception ex)
            {
                System.debug(ex);
                System.assert(false, 'No profile exists with name'+ profileName);
            }

            for(Integer i = 0; i < size; i++)
            {
                User testUser = getTestUserWithProfileId(userName + i, profileId);

                allUsers.add(testUser);
            }

            if(insertUsers)
            {
               // System.RunAs(ADMIN_USER)
              //  {
                    insert allUsers;
              //  }
            }

            return allUsers;

    }

    private static User getTestUserWithProfileId(String userName, String profileId)
    {
        User testUser = new User();
        testUser.LastName = 'test ' + UserName;
        
        Integer aliasLength = Schema.SObjectType.User.fields.Alias.getLength(); 
        testUser.Alias = (String) new SObjectFieldProviders.UniqueFixedLengthStringProvider(aliasLength).getValue();
                                                   
        testUser.Network_Id__c = testUser.Alias;
        testUser.Email = UserName+'@unisourcelink.com';
        testUser.Username = UserName+UserName+'@test.com';
        testUser.CommunityNickname = 'a'+UserName;
        testUser.TimeZoneSidKey = 'America/New_York';
        testUser.LocaleSidKey = 'en_US';
        testUser.EmailEncodingKey = 'ISO-8859-1';
        testUser.ProfileId = profileId;
        testUser.LanguageLocaleKey = 'en_US';
        testUser.Country = 'USA';
        testUser.IsActive = true;

        return testUser;
    }

    public static Account createAccount(String acctName)
    {
        return createAccounts(acctName, 1)[0];
    }

    public static Account createAccount(String acctName, Boolean doInsert)
    {
        Account account = createAccounts(acctName, 1)[0];
        if(doInsert)
            insert account;

        return account;
    }

    public static List<Account> createAccounts(String acctName, Integer size)
    {
        List<Account>allAccounts = new List<Account>();

        for(Integer i = 0; i < size; i++)
        {
            allAccounts.add(new Account(Name = acctName+i,Account_Vertical__c='Test'));
        }

        return allAccounts;
    }

    public static Case createCase(Id rTypeId)
    {
        return createCases(rTypeId, 1)[0];
    }

    public static List<Case> createCases(Id rTypeId, Integer size)
    {

        Account testAcct = new Account( Name = 'test' );
        insert testAcct;

        Contact testContact = new Contact( LastName = 'someName', AccountId = testAcct.Id );
        insert testContact;

        List<Case>allCases = new List<Case>();

        for(Integer i = 0; i < size; i++)
        {
            allCases.add(new Case(RecordTypeId = rTypeId, contactId = testContact.Id, accountId = testAcct.Id));
        }

        return allCases;
    }

    public static EmailMessage createEmailMessage(Id parentId)
    {
        return createEmailMessages(parentId, 1)[0];
    }

    public static List<EmailMessage> createEmailMessages(Id parentId, Integer size)
    {
        List<EmailMessage>allEmailMessages = new List<EmailMessage>();

        for(Integer i = 0; i < size; i++)
        {
            allEmailMessages.add(new EmailMessage(ParentId = parentId));
        }

        return allEmailMessages;
    }

    public static Attachment createAttachment(Id parentId)
    {
        return createAttachments(parentId, 1)[0];
    }

    public static List<Attachment> createAttachments(Id parentId, Integer size)
    {
        List<Attachment>allEmailAttachments = new List<Attachment>();

        for(Integer i = 0; i < size; i++)
        {
            Attachment attachment = new Attachment();
            attachment.body = Blob.valueOf( 'this is an attachment test ' + i);
            attachment.name = 'fake attachment ' + i;

            attachment.parentId = parentId;

            allEmailAttachments.add(attachment);
        }

        return allEmailAttachments;
    }

    public static List<Primary_Sales_Rep__c> createPSRs( Integer numToCreate, Boolean doInsert )
    {
        List<Primary_Sales_Rep__c> psrsToInsert = new List<Primary_Sales_Rep__c>();

        for( Integer index = 0; index < numToCreate; index++ )
        {
            Primary_Sales_Rep__c newPSR = new Primary_Sales_Rep__c();
            newPSR.Name = 'Joe Test ' + index;
            newPSR.Network_Id__c = '1234' + PSRNetworkIdOffSet++;
            newPSR.Email__c = 'user' + index + '@domain.com';
            psrsToInsert.add( newPSR );
        }

        if( doInsert )
            insert psrsToInsert;



        return psrsToInsert;
    }

    public static List<Opportunity> createOpportunities( Integer numToCreate, Id accountId, Boolean doInsert )
    {
        List<Opportunity> opptysToInsert = new List<Opportunity>();

        for( Integer index = 0; index < numToCreate; index++ )
        {
            Opportunity newOppty = new Opportunity();
            newOppty.AccountId = accountId;
            newOppty.Name = 'test opp' + index;
            newOppty.StageName = '1- Prospect';
            newOppty.CloseDate = Date.today().addDays(365);
            newOppty.Customer_Selling_Margin_Rate__c = 50;
            newOppty.Prod_Category__c = 'ICE MELTER';
            opptysToInsert.add( newOppty );
        }

        if( doInsert )
            insert opptysToInsert;

        return opptysToInsert;
    }

    public static AccountShare createAccountShare( Id userId, Id accountId, String accountLevel, String opptyLevel )
    {
        AccountShare acctShare = new AccountShare();
        acctShare.UserOrGroupId = userId;
        acctShare.AccountId = accountId;
        acctShare.AccountAccessLevel = accountLevel;
        acctShare.OpportunityAccessLevel = opptyLevel;

        return acctShare;
    }

    public static List<Ship_To__c> createShipTos( Integer numShipTos, String baseName, Id accountId, Boolean doInsert )
    {
        List<Ship_To__c> shipTos = new List<Ship_To__c>();

        for( Integer index = 0; index < numShipTos; index++ )
        {
            Ship_To__c newShipTo = new Ship_To__c();
            newShipTo.Name = baseName + index;
            newShipTo.Bill_To_Account__c = accountId;
            shipTos.add( newShipTo );
        }

        if( doInsert )
        {
            insert shipTos;
        }

        return shipTos;
    }

    public static List<Quote__c> createQuotes( Integer numQuotes, String baseName, Id accountId, Boolean doInsert )
    {
        List<Quote__c> quotes = new List<Quote__c>();

        for( Integer index = 0; index < numQuotes; index++ )
        {
            Quote__c newQuote = new Quote__c();
            newQuote.Account__c = accountId;
            newQuote.Subject__c = baseName + index;
            quotes.add( newQuote );
        }

        if( doInsert )
        {
            insert quotes;
        }

        return quotes;
    }

    public static List<Product2> createProducts( Integer numProducts, String baseName, Boolean doInsert )
    {
        List<Product2> products = new List<Product2>();

        for( Integer index = 0; index < numProducts; index++ )
        {
            Product2 newProduct = new Product2();
            newProduct.Name = baseName + index;
            products.add( newProduct );
        }

        if( doInsert )
        {
            insert products;
        }

        return products;
    }
    
    public static List<Servicing_Division__c> createServicingDivisions( Integer numDivisions, Boolean doInsert )
    {
        List<Servicing_Division__c> servicingDivisions = new List<Servicing_Division__c>();

        for( Integer index = 0; index < numDivisions; index++ )
        {
            Servicing_Division__c sdivision = new Servicing_Division__c();
            servicingDivisions.add( sdivision );
        }

        if( doInsert )
        {
            insert servicingDivisions;
        }

        return servicingDivisions;
    }
    
    
}