force-app/main/default/objects/Account/fields/Account_DW_Key__c.field-meta.xml
<CustomField>
    <fullName>Account_DW_Key__c</fullName>
    <description>Key use by DW to load and update Customer Accounts</description>
    <externalId>true</externalId>
    <label>Account DW Key</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Account_Vertical__c</fullName>
    <description>Limit verticals to 30 characters only

Any changes/additions here should also be made on Lead object, field Vertical, Vertical object and Brainshark
Must also add a Vertical record (to the Vertical object)

****If the values:  PRINTER - WEB or PRINTER - DIGITAL/WIDE FORMAT are ever changed, contact Heather Sagan immediately!!!  Any changes will impact call routing in the LA CSC!!!****</description>
    <inlineHelpText>Select the vertical that best suits this account.</inlineHelpText>
    <label>Sub Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical_Grouping__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Assisted Living</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Bakery &amp; Snack</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
            <value>
                <fullName>Big Box</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>Building Materials</fullName>
            </value>
            <value>
                <fullName>Candy</fullName>
            </value>
            <value>
                <fullName>Cereal &amp; Grain</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Computer &amp; Electronics</fullName>
            </value>
            <value>
                <fullName>Correctional</fullName>
            </value>
            <value>
                <fullName>Cruise Lines</fullName>
            </value>
            <value>
                <fullName>C-Stores</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Eating &amp; Drinking</fullName>
            </value>
            <value>
                <fullName>Ecommerce</fullName>
            </value>
            <value>
                <fullName>Electronic Shopping</fullName>
            </value>
            <value>
                <fullName>Energy &amp; Mining</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Glass</fullName>
            </value>
            <value>
                <fullName>Grocery Stores</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Higher Ed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prospect_Segment__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Segment__c</fullName>
    <description>Require this field on the Prospect account.  Then use a workflow to convert this selection to the proper code for the Segment (F, P, M, L).  This is the code that comes in from DW on Customer Accounts.  Not required on 3PL prospects, as there is no matching Segment for them. 

Any changes to the picklist values should be coordinated with Brainshark administration and should also be made on the following objects - Vendor Detail, Opportunity, Contact, Lead, Work Orders.

1/29/18 - AL - Made this an unrestriced picklist because it was causing validation errors when converting to existing accounts</description>
    <label>Prospect Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facility Solutions</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Product_Analysis__c/Product_Analysis__c.object-meta.xml
<CustomObject>
    <label>Product Analysis</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Product Analysis Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Analyses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Analysis__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Analyses</relationshipLabel>
    <relationshipName>Product_Analyses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Bottom_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Current_Bottom_Load_Force__c</fullName>
    <label>Current Bottom Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Estimated_Annual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Current_Estimated_Annual_Cost__c</fullName>
    <label>Current Estimated Annual Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Film_Thickness_ga__c.field-meta.xml
<CustomField>
    <fullName>Current_Film_Thickness_ga__c</fullName>
    <label>Current Film Thickness (ga)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Film_Width_in__c.field-meta.xml
<CustomField>
    <fullName>Current_Film_Width_in__c</fullName>
    <label>Current Film Width (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Item__c.field-meta.xml
<CustomField>
    <fullName>Current_Item__c</fullName>
    <label>Current Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Current_Manufacturer__c</fullName>
    <label>Current Manufacturer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Middle_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Current_Middle_Load_Force__c</fullName>
    <label>Current Middle Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Roll_Length_ft__c.field-meta.xml
<CustomField>
    <fullName>Current_Roll_Length_ft__c</fullName>
    <label>Current Roll Length (ft)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Roll_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Roll_Price__c</fullName>
    <label>Current Roll Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Rotations__c.field-meta.xml
<CustomField>
    <fullName>Current_Rotations__c</fullName>
    <label>Current Rotations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Top_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Current_Top_Load_Force__c</fullName>
    <label>Current Top Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Total_Stretch__c.field-meta.xml
<CustomField>
    <fullName>Current_Total_Stretch__c</fullName>
    <label>Current Total Stretch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Weight_oz__c.field-meta.xml
<CustomField>
    <fullName>Current_Weight_oz__c</fullName>
    <label>Current Weight (oz)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/externalID__c.field-meta.xml
<CustomField>
    <fullName>externalID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>externalID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Manufacturer_Model__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Model__c</fullName>
    <label>Manufacturer/Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Height_in__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Height_in__c</fullName>
    <label>Pallet Height (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Length_in__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Length_in__c</fullName>
    <label>Pallet Length (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Type__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Type__c</fullName>
    <label>Pallet Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Weight_lbs__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Weight_lbs__c</fullName>
    <label>Pallet Weight (lbs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Width_in__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Width_in__c</fullName>
    <label>Pallet Width (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallets_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>Pallets_Per_Year__c</fullName>
    <label>Pallets Per Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Annual_Savings__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Annual_Savings__c</fullName>
    <label>Proposed Annual Savings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Bottom_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Bottom_Load_Force__c</fullName>
    <label>Proposed Bottom Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Estimated_Annual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Estimated_Annual_Cost__c</fullName>
    <label>Proposed Estimated Annual Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <description>Used as external key to User record for Evo integration</description>
    <externalId>true</externalId>
    <label>Employee ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SWRestResource.cls
@RestResource(urlMapping='/swRest')
global with sharing class SWRestResource {
    
   
  
    @HttpGet
    global static list<sObject> doGet() {
        RestRequest req = RestContext.request;
       
        String uniqueId = req.params.get('accDWKey');
        String accName = req.params.get('accName');
        String accType = req.params.get('accType');
        String employeeId = req.params.get('employeeId');
        String returnVal = req.params.get('returnVal');
        
        //get user via employee id
        user userRec = [select id, email, Employee_ID__c  from user where Employee_ID__c = :employeeId and IsActive = true and UserType ='Standard' limit 1];
        
        //return user detail if only needed for user checking
        if(returnVal == 'user'){
            list<user> uList = new list<user>();
            uList.add(userRec);
            return uList;    
        }else{

            Map <id,Account> accList;
            //check if customer or Prospect
            if (accType == 'Customer'){
                accList = new Map<id,account>([SELECT Id, Name, Primary_Sales_Rep_Name__r.Name, BillingAddress, Prospect_Segment__c, Account_Vertical__c FROM Account WHERE Account_DW_Key__c = :uniqueId AND  RecordType.Name = 'Customer']);
            }else{
            //prospect
                accList = new Map<id,account>([SELECT Id, Name, Primary_Sales_Rep_Name__r.Name, BillingAddress, Prospect_Segment__c, Account_Vertical__c FROM Account WHERE Name = :accName AND  RecordType.Name = 'Prospect']);
            }
            
            //check if user has access   
            list <UserRecordAccess> userAccessList = new list <UserRecordAccess>([select RecordId FROM UserRecordAccess WHERE UserId =:userRec.id AND Recordid IN :accList.keyset() AND HasReadAccess = true ]);
            list <account> readAccList = new list<Account>();
            for (UserRecordAccess uAcc : userAccessList ){
                if(accList.containsKey(uAcc.RecordId)){
                    //add readable account to the list to be returned
                    readAccList.add(accList.get(uAcc.RecordId)); 
                }
            }
            
            return readAccList ;
        }
    }
  
  @HttpPost
    global static Product_Analysis__c  doPost(SWRestResource.pAWrapper pAWrap ) {
    
        if(pAWrap != null){
                                
            Product_Analysis__c pA = new Product_Analysis__c();
            pA.account__c = pAWrap.accId;
            pA.Current_Bottom_Load_Force__c = pAWrap.currentBottomLoadForce;
            pA.Current_Estimated_Annual_Cost__c = pAWrap.currentEstimatedAnnualCost;
            pA.Current_Film_Thickness_ga__c  = pAWrap.currentFilmThicknessGA;
            pA.Current_Film_Width_in__c = pAWrap.currentFilmWidthIN; 
            pA.Current_Item__c = pAWrap.currentItem;
            pA.Current_Manufacturer__c = pAWrap.currentManufacturer;
            pA.Current_Middle_Load_Force__c = pAWrap.currentMiddleLoadForce;
            pA.Current_Roll_Length_ft__c = pAWrap.currentRollLengthFT;
            pA.Current_Roll_Price__c = pAWrap.currentRollPrice;
            pA.Current_Rotations__c = pAWrap.currentRotations;
            pA.Current_Top_Load_Force__c = pAWrap.currentTopLoadForce;
            pA.Current_Total_Stretch__c = pAWrap.currentTotalStretch;
            pA.Current_Weight_oz__c = pAWrap.currentWeightOz;
            pA.Equipment_Type__c = pAWrap.equipmentType;
            pA.externalID__c = pAWrap.externalID;
            pA.Manufacturer_Model__c = pAWrap.manufacturerModel;
            pA.Pallet_Height_in__c = pAWrap.palletHeightInC;
            pA.Pallet_Length_in__c = pAWrap.palletLengthtInC;
            pA.Pallets_Per_Year__c = pAWrap.palletsPerYear;
            pA.Pallet_Type__c = pAWrap.palletType;
            pA.Pallet_Weight_lbs__c = pAWrap.palletWeightLbs;
            pA.Pallet_Width_in__c = pAWrap.palletWidthIn;
            pA.Proposed_Annual_Savings__c = pAWrap.proposedAnnualSavings; 
            pA.Proposed_Bottom_Load_Force__c = pAWrap.proposedBottomLoadForce; 
            pA.Proposed_Estimated_Annual_Cost__c = pAWrap.proposedEstimatedAnnualCost;
            pA.Proposed_Film_Thickness_ga__c = pAWrap.proposedFilmThicknessGa; 
            pA.Proposed_Film_Width_in__c = pAWrap.proposedFilmWidthIn;
            pA.Proposed_Item__c = pAWrap.proposedItem;
            pA.Proposed_Middle_Load_Force__c = pAWrap.proposedMiddleLoadForce;
            pA.Proposed_Percent_Savings__c = pAWrap.proposedPercentSavings;
            pA.Proposed_Roll_Length_ft__c = pAWrap.proposedRollLengthFt;
            pA.Proposed_Roll_Price__c = pAWrap.proposedRollPrice; 
            pA.Proposed_Rotations__c = pAWrap.proposedRotations;
            pA.Proposed_Top_Load_Force__c= pAWrap.proposedTopLoadForce;
            pA.Proposed_Total_Stretch__c= pAWrap.proposedTotalStretch;
            pA.Proposed_Weight_oz__c= pAWrap.proposedWeightOz;
            pA.Serial_Number__c= pAWrap.serialNumber;
            pA.Waste_Stream_Pounds_Reduction__c= pAWrap.wasteStream;
            pA.Plastic_Straws_Saved__c = pAWrap.plasticStraws;
            pA.Plastic_Bags_Saved__c = pAWrap.plasticBags;
            pA.Plastic_Bottles_Saved__c = pAWrap.plasticBottles;
            pA.Personal_Vehicle_Emissions__c = pAWrap.personalVehicleEmissions;
            pA.Barrels_of_Oil__c = pAWrap.barrelsOil;
            pA.Homes_Powered__c = pAWrap.homesPowered;
            pA.Film__c = pAWrap.film;
            pA.Pallets__c = pAWrap.pallets;
            pA.Truckloads__c = pAWrap.truckloads;
/*removed the following for initial release and will be included in a later release if it is determined to use
            pA.BarrelInd__c = pAWrap.barrelInd;
            pA.CarInd__c = pAWrap.carInd;
            pA.CoreInd__c = pAWrap.coreInd;
            pA.HomeInd__c = pAWrap.homeInd;
            pA.PalletInd__c = pAWrap.palletInd;
            pA.PlasticBagInd__c = pAWrap.plasticBagInd;
            pA.PlasticBottleInd__c = pAWrap.plasticBottleInd;
            pA.PlasticStrawInd__c = pAWrap.plasticStrawInd;
            pA.TruckInd__c = pAWrap.truckInd;
*/
            pA.ownerId = pAWrap.ownerId;
            pA.PDF_Link__c = pAWrap.pdfLink;
            
            insert pA;
            
            //requery to get the name
            Product_Analysis__c newPA = new Product_Analysis__c ();
            newPA = [select id, name, Account__r.Name from Product_Analysis__c where id = :pA.id limit 1];
                       
/*removed the following for initial release and will be included in a later release if it is determined to use
            //system.debug('The product analysis run:'+ pA);
            System.enqueueJob(new RenderPAPDFQueueable(newPA.Id));
*/
            
            
            return newPA ;
            //return pA.id;
            //return pA;
        }
        return null;
        
    }
    
    global class pAWrapper {
        public String accId; 
        public double currentBottomLoadForce; 
        public double currentEstimatedAnnualCost;
        public double currentFilmThicknessGA;
        public double currentFilmWidthIN;
        public String currentItem;
        public String currentManufacturer;
        public double currentMiddleLoadForce; 
        public double currentRollLengthFT;
        public double currentRollPrice;
        public double currentRotations;
        public double currentTopLoadForce;
        public double currentTotalStretch;
        public double currentWeightOz;
        public String equipmentType;
        public String externalID;
        public String manufacturerModel;
        public double palletHeightInC;
        public double palletLengthtInC;
        public double palletsPerYear;
        public String palletType;
        public double palletWeightLbs;
        public double palletWidthIn;
        public double proposedAnnualSavings;
        public double proposedBottomLoadForce;
        public double proposedEstimatedAnnualCost;
        public double proposedFilmThicknessGa;
        public double proposedFilmWidthIn;
        public String proposedItem;
        public double proposedMiddleLoadForce;
        public double proposedPercentSavings;
        public double proposedRollLengthFt;
        public double proposedRollPrice;
        public double proposedRotations;
        public double proposedTopLoadForce;
        public double proposedTotalStretch;
        public double proposedWeightOz;
        public String serialNumber;
        public double wasteStream;
        public double plasticStraws;
        public double plasticBags;
        public double plasticBottles;
        public double personalVehicleEmissions;
        public double barrelsOil;
        public double homesPowered;
        public double film;
        public double pallets;
        public double truckloads;
/*removed the following for initial release and will be included in a later release if it is determined to use
        public boolean barrelInd;
        public boolean carInd;
        public boolean coreInd;
        public boolean homeInd;
        public boolean palletInd;
        public boolean plasticBagInd;
        public boolean plasticBottleInd;
        public boolean plasticStrawInd;
        public boolean truckInd;
*/
        public String ownerId;
        public String pdfLink;
        
        }
    
}