force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VENDOR_CODE__c.field-meta.xml
<CustomField>
    <fullName>VENDOR_CODE__c</fullName>
    <description>Legacy key field</description>
    <externalId>true</externalId>
    <label>VENDOR_CODE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zzProduct</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zzShip To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Unit_of_Measure__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_Measure__c</fullName>
    <label>Unit of Measure</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Vendor_Detail__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <label>Vendor Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor#</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grant_Access_Level_ATM__c/Grant_Access_Level_ATM__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Anyone who is added to an account team will have read/write access to all Oppty, Cases, Quotes, Account Plans
(If child record is added, code needs to be revised as well to reference the added record)
(Access levels are &quot;Read&quot; and &quot;Read/Write&quot;)</description>
    <label>Grant Access Level ATM</label>
</CustomObject>

force-app/main/default/objects/InactiveRecordTypes__c/InactiveRecordTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveRecordTypes</label>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <inlineHelpText>Requested Delivery Date updates the field &apos;Projected Delivery Date&apos; at the quote line. If different dates apply to lines, that can be updated in that line&apos;s &apos;Additional Details&apos;.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Cost_Unit_Factor__c</fullName>
    <label>Cost Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Costing_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Costing_unit_of_measure__c</fullName>
    <label>Costing UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Price_Unit_Factor__c</fullName>
    <label>Price Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Price_unit_of_measure__c</fullName>
    <label>Price/Cost UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Projected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Unit_Factor__c</fullName>
    <label>Quantity Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Quantity_unit_of_measure__c</fullName>
    <label>Qty UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Unisource_Item__c.field-meta.xml
<CustomField>
    <fullName>Unisource_Item__c</fullName>
    <label>Unisource Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Item__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Item__c</fullName>
    <label>Vendor Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Name</label>
    <referenceTo>Vendor_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxxEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Detail__c/Vendor_Detail__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Detail__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Will be fed over from EVO</description>
    <label>Active</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Detail__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <externalId>true</externalId>
    <label>Vendor Code</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QuoteTest.cls
@isTest
public class QuoteTest {

	private static Account testCustAccount;
	private static Ship_To__c testShipAccount;
	private static Quote__c testQuote;
	private static Quote_Line_Item__c[] testQLIs = new Quote_Line_Item__c[0];

	private static final Integer NUM_OF_OBJs = 5;
	private static final Integer NUM_OF_ACCT_PLANS = 5;
	private static final Integer NUM_OF_QUOTES = 5;
	private static final Integer NUM_OF_USERS = 5;

	private static final Integer NUM_TO_CHANGE = 2;
	private static final Integer NUM_OF_NEW_USERS = 2;

	private static Account testAccount;
	private static Contact testContact;
	private static List<User> testUsers;
	private static List<AccountTeamMember> testATMs;

	private static Account newAccount;
	private static List<User> newUsers;
	private static List<AccountTeamMember> newATMs;

	private static void setup()
	{
		// recordtype is NEEDED for test pass
		InactiveRecordTypes__c inactiveRT = new InactiveRecordTypes__c();
		inactiveRT.Name = CaseServices.EBUSINESS_RT_NAME;
		System.runAs( TestingUtils.ADMIN_USER )
		{
			insert inactiveRT;
		}
		Id testRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get( '02. Customer Inquiry' ).getRecordTypeId();
		Id customerRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get( 'Customer' ).getRecordTypeId();

		Grant_Access_Level_ATM__c acctPlansToAccessLvl = TestingUtils.createRelationshipToAccessLevelCS( AccountTeamMemberServices.ACCOUNT_PLANS_NAME, AccountTeamMemberServices.READ_ONLY_LEVEL, true );
		Grant_Access_Level_ATM__c quoteToAccessLvl = TestingUtils.createRelationshipToAccessLevelCS( AccountTeamMemberServices.QUOTES_NAME, AccountTeamMemberServices.READ_WRITE_LEVEL, true );

		testAccount = TestingUtils.createAccount( 'Test Account' );
		testAccount.RecordTypeId = customerRTId;
		insert testAccount;

		testContact = TestingUtils.createContact( 'John', 'Doe', true );
		testUsers = TestingUtils.createUsers( 'JohnD', 'Standard User', NUM_OF_USERS, true );
		testATMs = new List<AccountTeamMember>();
		for( User aUser : testUsers )
		{
			testATMs.add( TestingUtils.createAccountTeamMember( testAccount.Id, aUser.Id, false ) );
		}
		insert testATMs;
	}


	private static void setupNewAccountAndATMs()
	{
		newAccount = TestingUtils.createAccount( 'Steve Jobs' );
		insert newAccount;

		newUsers = TestingUtils.createUsers('PhilC', 'Standard User', NUM_OF_NEW_USERS, true );
		newATMs = new List<AccountTeamMember>();
		for( User aUser : newUsers )
		{
			newATMs.add( TestingUtils.createAccountTeamMember( newAccount.Id, aUser.Id, false ) );
		}
		insert newATMs;
	}

	static testMethod void testGrantQuoteAccessToATMs()
	{
		setup();

		Test.startTest();

			List<Quote__c> testQuotes = TestingUtils.createQuotes( NUM_OF_QUOTES, testAccount.Id, false );
			insert testQuotes;

		Test.stopTest();

		List<Quote__Share> actualQuoteShares = [ SELECT Id, AccessLevel
													FROM Quote__Share
													WHERE ParentId IN :testQuotes
														AND UserOrGroupId IN :testUsers ];

		System.assertEquals( NUM_OF_USERS * NUM_OF_QUOTES, actualQuoteShares.size(), 'There should be a Quote Share per Quote created' );
		for( Quote__Share quoteShare : actualQuoteShares )
		{
			System.assertEquals( BatchServices.EDIT, quoteShare.AccessLevel, 'The AccessLevel should be set based on Access Level value of Custom Setting' );
		}
	}

	static testMethod void testGrantAccessForMigratedQuotes()
	{
		setup();

		List<Quote__c> testQuotes = TestingUtils.createQuotes( NUM_OF_QUOTES, testAccount.Id, true );
		Set<Id> changedQuoteIds = new Set<Id>();

		Test.startTest();

			setupNewAccountAndATMs();
			for( Integer i = 0; i < NUM_TO_CHANGE; i++ )
			{
				testQuotes[i].Account__c = newAccount.Id;
				changedQuoteIds.add( testQuotes[i].Id );
			}
			update testQuotes;

		Test.stopTest();

		List<Quote__Share> actualOldQuoteShares = [ SELECT Id, ParentId, UserOrGroupId
													FROM Quote__Share
													WHERE ParentId IN :testQuotes
														AND UserOrGroupId IN :testUsers ];

		Set<Id> newUserIds = new Set<Id>();
		for( User aUser : newUsers )
		{
			newUserIds.add( aUser.Id );
		}

		final Integer EXPECTED_OLD_SHARE_SIZE = ( NUM_OF_QUOTES - NUM_TO_CHANGE ) * NUM_OF_USERS;

		System.assertEquals( EXPECTED_OLD_SHARE_SIZE, actualOldQuoteShares.size(), 'The sharing object should be removed from old Quotes upon migration' );
		for( Quote__Share quoteShare : actualOldQuoteShares )
		{
			System.assert( !changedQuoteIds.contains( quoteShare.ParentId ), 'The Quote Share record from old Quotes should not look upto the changed Quote record' );
			System.assert( !newUserIds.contains( quoteShare.UserOrGroupId ), 'The Quote Share record from old Quotes should not look upto the new User record' );
		}

		List<Quote__Share> actualNewQuoteShares = [ SELECT Id, ParentId, UserOrGroupId
																FROM Quote__Share
																WHERE ParentId IN :testQuotes
																	AND UserOrGroupId IN :newUsers ];

		final Integer EXPECTED_NEW_SHARE_SIZE = NUM_OF_NEW_USERS * NUM_TO_CHANGE;

		System.assertEquals( EXPECTED_NEW_SHARE_SIZE, actualNewQuoteShares.size(), 'The sharing object should be added to new Quotes upon migration' );
		for( Quote__Share quoteShare : actualNewQuoteShares )
		{
			System.assert( changedQuoteIds.contains( quoteShare.ParentId ), 'The Quote Share record from new Quotes should look upto the changed Quote record' );
			System.assert( newUserIds.contains( quoteShare.UserOrGroupId ), 'The Quote Share record from new Quotes should look upto the new User record' );
		}
	}

	public static testMethod void test_update_date()
	{
		setupTest();

		Test.startTest();

		testQuote.Requested_Delivery_Date__c = System.today() + 7;
		update testQuote;

		testQuote = [select Requested_Delivery_Date__c from Quote__c where Id = :testQuote.Id];
		testQLIs = [select Projected_Delivery_Date__c from Quote_Line_Item__c where Quote__c = :testQuote.Id];

		for(Quote_Line_Item__c qli : testQLIs)
		{
			System.assertEquals(testQuote.Requested_Delivery_Date__c, qli.Projected_Delivery_Date__c);
		}
		Test.stopTest();
	}

	private static void setupTest()
	{
		Id customerRTId = Schema.SObjectType.Account.getRecordTypeInfosByName().get( 'Customer' ).getRecordTypeId();
		testCustAccount = TestingUtils.createAccount('Test Customer');
		testCustAccount.RecordTypeId = customerRTId;
		testCustAccount.AccountNumber = '123456';
		testCustAccount.Ship_To_Code__c = '000001';
		testCustAccount.Active__c = 'Yes';
		insert testCustAccount;

		testShipAccount = new Ship_To__c( Name = 'Test Customer Location 1', Ship_To_Code__c = '000002', Bill_To_Account__c = testCustAccount.Id, Active__c = 'Yes' );
		insert testShipAccount;

		testQuote = TestingUtils.createQuotes( 1, testCustAccount.Id, false )[0];
		testQuote.Shipment_Method__c = 'Warehouse';
		testQuote.Requested_Delivery_Date__c = System.today();
		insert testQuote;

		List<Vendor_Detail__c> vendorDetails = TestingUtils.createVendorDetails( 2, 'TestVendor', false );
		vendorDetails[0].Vendor_Code__c = '001';
		vendorDetails[1].Vendor_Code__c = '002';
		insert vendorDetails;

		List<Product2> products = TestDataGeneration.createProducts( 2, 'TestProduct', false );
		products[0].ProductCode = '0001';
		products[0].Description = 'Test Description 1';
		products[0].Unisource_Item_Number_U_number__c = '001';
		products[0].Vendor_Product_Code__c = vendorDetails[0].Vendor_Code__c;
		products[0].Vendor__c = vendorDetails[0].Id;
		products[0].Unit_of_Measure__c = 'EA';
		products[0].Pricing_Costing_UOM__c = 'EA';
		products[0].Conversion_Factor__c = 10.01;

		products[1].ProductCode = '0002';
		products[1].Description = 'Test Description 2';
		products[1].Unisource_Item_Number_U_number__c = '002';
		products[1].Vendor_Product_Code__c = vendorDetails[1].Vendor_Code__c;
		products[1].Vendor__c = vendorDetails[1].Id;
		products[1].Unit_of_Measure__c = 'MA';
		products[1].Pricing_Costing_UOM__c = 'MA';
		products[1].Conversion_Factor__c = 20.02;
		insert products;

		Quote_Line_Item__c qli = new Quote_Line_Item__c( Quote__c=testQuote.Id );
		qli.Product__c = products[0].Id;
		qli.Product__r = products[0];
		qli.Product_Code__c = products[0].ProductCode;
		qli.Product_Description__c = products[0].Description;
		qli.Unisource_Item__c = products[0].Unisource_Item_Number_U_number__c;
		qli.Vendor_Item__c = products[0].Vendor_Product_Code__c;
		qli.Vendor_Name__c = products[0].Vendor__c;
		qli.Qty__c = 1;
		qli.Projected_Delivery_Date__c = System.today();
		qli.Quantity_unit_of_measure__c = products[0].Unit_of_Measure__c;
		qli.Price_unit_of_measure__c = products[0].Pricing_Costing_UOM__c;
		qli.Costing_unit_of_measure__c = products[0].Pricing_Costing_UOM__c;
		qli.Quantity_Unit_Factor__c = 1;
		qli.Price_Unit_Factor__c = products[0].Conversion_Factor__c;
		qli.Cost_Unit_Factor__c = products[0].Conversion_Factor__c;
		insert qli;
		testQLIs.add(qli);

		qli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
		qli.Product__c = products[1].Id;
		qli.Product__r = products[1];
		qli.Product_Code__c = products[1].ProductCode;
		qli.Product_Description__c = products[1].Description;
		qli.Unisource_Item__c = products[1].Unisource_Item_Number_U_number__c;
		qli.Vendor_Item__c = products[1].Vendor_Product_Code__c;
		qli.Vendor_Name__c = products[1].Vendor__c;
		qli.Qty__c = 1;
		qli.Projected_Delivery_Date__c = System.today();
		qli.Quantity_unit_of_measure__c = products[1].Unit_of_Measure__c;
		qli.Price_unit_of_measure__c = products[1].Pricing_Costing_UOM__c;
		qli.Costing_unit_of_measure__c = products[1].Pricing_Costing_UOM__c;
		qli.Quantity_Unit_Factor__c = 1;
		qli.Price_Unit_Factor__c = products[1].Conversion_Factor__c;
		qli.Cost_Unit_Factor__c = products[1].Conversion_Factor__c;
		insert qli;
		testQLIs.add(qli);
	}

}