force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Date_Quoted__c.field-meta.xml
<CustomField>
    <fullName>Date_Quoted__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>The date the quote information was given to the customer if different than when entered in SFDC</inlineHelpText>
    <label>Date Quoted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <inlineHelpText>Requested Delivery Date updates the field &apos;Projected Delivery Date&apos; at the quote line. If different dates apply to lines, that can be updated in that line&apos;s &apos;Additional Details&apos;.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <formula>/* OLD FORMULA */ 
/* 
IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.Division_Code__c, IF( Ship_To_Account__r.Legacy_Division_Cd__c = &quot;&quot;, Account__r.Legacy_Division_Cd__c, Ship_To_Account__r.Legacy_Division_Cd__c)) 
*/ 

IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Code__c, 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, BLANKVALUE(Account__r.Legacy_Division_Cd__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c))) 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Cost_Unit_Factor__c</fullName>
    <label>Cost Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Costing_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Costing_unit_of_measure__c</fullName>
    <label>Costing UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Item_Seq__c.field-meta.xml
<CustomField>
    <fullName>Item_Seq__c</fullName>
    <label>Item Seq</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Price_Unit_Factor__c</fullName>
    <label>Price Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Price_unit_of_measure__c</fullName>
    <label>Price/Cost UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Unit_Factor__c</fullName>
    <label>Quantity Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Quantity_unit_of_measure__c</fullName>
    <label>Qty UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Unisource_Item__c.field-meta.xml
<CustomField>
    <fullName>Unisource_Item__c</fullName>
    <label>Unisource Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Item__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Item__c</fullName>
    <label>Vendor Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Name</label>
    <referenceTo>Vendor_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxxEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Search_Order__c/Search_Order__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Houses the Search Order relative URL for Quoting 2.0</description>
    <label>Search Order</label>
</CustomObject>

force-app/main/default/objects/Search_Order__c/fields/Relative_URL__c.field-meta.xml
<CustomField>
    <fullName>Relative_URL__c</fullName>
    <description>Relative URL to Unisource&apos;s Search Order</description>
    <inlineHelpText>Relative URL to Unisource&apos;s Search Order</inlineHelpText>
    <label>Relative URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Division__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this an Active Division?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/fields/Division_Code__c.field-meta.xml
<CustomField>
    <fullName>Division_Code__c</fullName>
    <label>Division Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestViewQuoteQuoteContExt.cls
/**
 Objective: Test class to iron out the functionality of ViewQuoteQuoteContExt
 Developer: Hiremath, Naveen - Bluewolf
*/
@isTest
private class TestViewQuoteQuoteContExt {

    private static Account testCustAccount;
    private static Ship_To__c testShipAccount;
    private static Quote__c testQuote;
    private static Quote_Line_Item__c[] testQLIs = new Quote_Line_Item__c[0];

    static testmethod void doShare_whenAnUserSharesTheExistingQuote_returnsStandardSharingURLPageRef() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id=' + testQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        System.debug('Naveen: ' + testQuote.CreatedDate);ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(contExt.isValidQuote, 'The Quote must be valid.');
        System.assertNotEquals(null, contExt.doShare(), 'Sharing url must never be null');

    }

    static testmethod void doClone_whenAnUserClonesTheExistingQuote_returnsViewNewQuotePageRef() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id=' + testQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(contExt.isValidQuote, 'The Quote must be valid.');
        System.assertNotEquals(null, contExt.doClone(), 'Clone url must never be null');

    }

    static testmethod void doSearchOrder_whenAnUserSubmitsSearchOrderOnTheExistingQuote_returnsSearchOrderAbsoluteURLPageRef() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id=' + testQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(contExt.isValidQuote, 'The Quote must be valid.');
        System.assertNotEquals(null, [SELECT Relative_URL__c FROM Search_Order__c WHERE Name = 'Search Order'], 'Custom Setting for Search Order must not be null');
        //System.assertNotEquals(null, [SELECT Relative_URL__c FROM Search_Order__c WHERE Name = 'Search Order'].Relative_URL__c, 'Relative_URL__c from Search Order Custom Setting must have a value');
        //System.assertNotEquals(null, contExt.doSearchOrder(), 'Search Order page reference must never be null');

    }

    static testmethod void doShipToAddress_whenAnUserSelectsShipToAddressOnTheExistingQuote_returnsShipToAddressPageRef() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id=' + testQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(contExt.isValidQuote, 'The Quote must be valid.');
        System.assertNotEquals(null, contExt.doShipToAddress(), 'Ship To Address page reference must never be null');

    }

    static testmethod void doSendToFieldSourcing_whenAnUserSelectsSendToMerchandiserOnTheExistingQuote_returnsSendToMerchandiserPageRef() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id=' + testQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(contExt.isValidQuote, 'The Quote must be valid.');
        System.assertNotEquals(null, contExt.doSendToFieldSourcing(), 'Send To Merchandiser page reference will never be null');

    }

    static testmethod void doCancel_whenAnUserCancelsTheExistingQuote_returnsQuotesTabRelativeURLPageRef() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id=' + testQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(contExt.isValidQuote, 'The Quote must be valid.');
        System.assertNotEquals(null, contExt.doCancel(), 'Cancel page reference will never be null');

    }

    static testmethod void ViewQuoteQuoteContExt_validateProducts_returnsNothing() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id=' + testQuote.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(testQuote);
        ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(contExt.isValidQuote, 'The Quote must be valid.');
        System.assertNotEquals(null, contExt.productSearch, 'Product Search instance must never be null');
        System.assertEquals(testQuote.Id, contExt.quotesModel.getQuote().Id, 'QuotesModel instance must have same reference to the Quote record');
        System.assertNotEquals(null, contExt.linkToChangeOwner, 'Link to change owner refers the standard change owner');

    }

    static testmethod void ViewQuoteQuoteContExt_noValidQuoteId_returnsNothing() {

        Test.setCurrentPageReference(new PageReference(Page.ViewQuote.getURL() + '?id='));
        ApexPages.StandardController sc = new ApexPages.StandardController(new Quote__c());
        ViewQuoteQuoteContExt contExt = new ViewQuoteQuoteContExt(sc);

        System.assert(!contExt.isValidQuote, 'The Quote must be invalid.');
        System.assertEquals(1, Apexpages.getMessages().size(), 'A page message will be shown to the user about the invalid Quote');

    }

    static testMethod void testQuickAddProducts()
    {
        final Integer QUANTITY_VALUE = 10;

        Servicing_Division__c testServiceDivision = new Servicing_Division__c();
        testServiceDivision.Name = 'Test Service Division';
        testServiceDivision.Division_Code__c = 'TEST5';
        insert testServiceDivision;

        Id custRecTypeID = [select Id from RecordType where SobjectType = 'Account' and Name = 'Customer'].Id;
        testCustAccount = new Account(Name='Test Customer', RecordTypeId=custRecTypeID, AccountNumber='123456', Ship_To_Code__c='000001', Active__c='Yes');
        testCustAccount.Servicing_Division__c = testServiceDivision.Id;
        insert testCustAccount;

        testQuote = new Quote__c(Account__c=testCustAccount.Id, Date_Quoted__c = System.today(), Account__r=testCustAccount, Shipment_Method__c='Warehouse',Requested_Delivery_Date__c=System.today());
        insert testQuote;

        List<Product2> testProducts = TestDataGeneration.createProducts( 4, 'Test Product', false );
        Product2 validProduct = testProducts[0];
        validProduct.Division_Name__c = testServiceDivision.Id;
        validProduct.IsActive = true;
        validProduct.Stocking_Flag__c = true;
        validProduct.ProductCode = validProduct.Name;

        Product2 invalidDivisionProduct = testProducts[1];
        invalidDivisionProduct.IsActive = true;
        invalidDivisionProduct.Stocking_Flag__c = true;
        invalidDivisionProduct.ProductCode = invalidDivisionProduct.Name;

        Product2 inactiveProduct = testProducts[2];
        inactiveProduct.Division_Name__c = testServiceDivision.Id;
        inactiveProduct.isActive = false;
        inactiveProduct.Stocking_Flag__c = true;
        inactiveProduct.ProductCode = inactiveProduct.Name;

        Product2 unstockedProduct = testProducts[3];
        unstockedProduct.Division_Name__c = testServiceDivision.Id;
        unstockedProduct.isActive = true;
        unstockedProduct.Stocking_Flag__c = false;
        unstockedProduct.ProductCode = unstockedProduct.Name;

        insert testProducts;

        ApexPages.StandardController stdCont = new ApexPages.StandardController( testQuote );
        ViewQuoteQuoteContExt quoteCont = new ViewQuoteQuoteContExt( stdCont );

        Test.startTest();

            for( Integer index = 0; index < testProducts.size(); index++ )
            {
                quoteCont.quickAddItems[ index ].itemNumber = testProducts[ index ].ProductCode;
                quoteCont.quickAddItems[ index ].quantity = QUANTITY_VALUE;
            }

            quoteCont.quickAddProducts();

        Test.stopTest();

        List<Quote_Line_Item__c> insertedQLIs = [ SELECT Id, Item_Seq__c, Product__r.Division_Name__c FROM Quote_Line_Item__c WHERE Quote__c = :testQuote.Id ];
        System.assertEquals( 2, insertedQLIs.size(), 'Only items products that are active and in the quote\'s division can be quickadded' );
        System.assertEquals( 1, insertedQLIs[0].Item_Seq__c, 'The first line item should be assigned seq of 1 if it is quickadded' );
        System.assertEquals( insertedQLIs[0].Product__c, validProduct.Id, 'Only products that are active and in the quote\'s division can be quickadded' );
        System.assertEquals( insertedQLIs[0].Product__r.Division_Name__c, testServiceDivision.Id, 'Only products that are active and in the quote\'s division can be quickadded' );

        Set<String> remainingItemCodes = new Set<String>();
        for( ViewQuoteQuoteContExt.QuoteQuickAddLineItem quickAddItem : quoteCont.quickAddItems )
        {
            if( quickAddItem.itemNumber != '' && quickAddItem.itemNumber != null )
            {
                System.assert(quickAddItem.IsError, 'This quick add item should be marked as an error');
                remainingItemCodes.add( quickAddItem.itemNumber );
            }
        }
        System.assertEquals( 2, remainingItemCodes.size(), 'Items that cannot be quickadded should remain' );
        System.assert( remainingItemCodes.contains( invalidDivisionProduct.ProductCode ), 'Products that are not in the same division as the quote cannot be quickadded' );
        System.assert( remainingItemCodes.contains( inactiveProduct.ProductCode ), 'Products that are inactive cannot be quickadded' );
    }
    
    static testMethod void testQuickAddProductsDuplicates()
    {
        final Integer QUANTITY_VALUE = 10;
        final Integer QUICK_ADD_TOTAL = 3;

        Servicing_Division__c testServiceDivision = new Servicing_Division__c();
        testServiceDivision.Name = 'Test Service Division';
        testServiceDivision.Division_Code__c = 'TEST5';
        insert testServiceDivision;

        Id custRecTypeID = [select Id from RecordType where SobjectType = 'Account' and Name = 'Customer'].Id;
        testCustAccount = new Account(Name='Test Customer', RecordTypeId=custRecTypeID, AccountNumber='123456', Ship_To_Code__c='000001', Active__c='Yes');
        testCustAccount.Servicing_Division__c = testServiceDivision.Id;
        insert testCustAccount;

        testQuote = new Quote__c(Account__c=testCustAccount.Id, Date_Quoted__c = System.today(), Account__r=testCustAccount, Shipment_Method__c='Warehouse',Requested_Delivery_Date__c=System.today());
        insert testQuote;

        List<Product2> testProducts = TestDataGeneration.createProducts( 1, 'Test Product', false );
        Product2 validProduct = testProducts[0];
        validProduct.Division_Name__c = testServiceDivision.Id;
        validProduct.IsActive = true;
        validProduct.Stocking_Flag__c = true;
        validProduct.ProductCode = validProduct.Name;

        insert testProducts;

        ApexPages.StandardController stdCont = new ApexPages.StandardController( testQuote );
        ViewQuoteQuoteContExt quoteCont = new ViewQuoteQuoteContExt( stdCont );

        Test.startTest();

            for( Integer index = 0; index < QUICK_ADD_TOTAL; index++ )
            {
                quoteCont.quickAddItems[ index ].itemNumber = testProducts[ 0 ].ProductCode;
                quoteCont.quickAddItems[ index ].quantity = QUANTITY_VALUE;
            }

            quoteCont.quickAddProducts();

        Test.stopTest();

        List<Quote_Line_Item__c> insertedQLIs = [ SELECT Id, Item_Seq__c, Product__r.Division_Name__c FROM Quote_Line_Item__c WHERE Quote__c = :testQuote.Id ];
        System.assertEquals( QUICK_ADD_TOTAL, insertedQLIs.size(), 'Duplicate quick add products should be allowed' );
        
        List<String> remainingItemCodes = new List<String>();
        for( ViewQuoteQuoteContExt.QuoteQuickAddLineItem quickAddItem : quoteCont.quickAddItems )
        {
            if( quickAddItem.itemNumber != '' && quickAddItem.itemNumber != null )
            {
                remainingItemCodes.add( quickAddItem.itemNumber );
            }
        }
        System.assertEquals( 0, remainingItemCodes.size(), 'All Items Should have been cleared' );

    }

    private static void testSetupData() {

        ID custRecTypeID = [select Id from RecordType where SobjectType = 'Account' and Name = 'Customer'].Id;
        testCustAccount = new Account(Name='Test Customer', RecordTypeId=custRecTypeID, AccountNumber='123456', Ship_To_Code__c='000001', Active__c='Yes');
        insert testCustAccount;

        testShipAccount = new Ship_To__c(Name='Test Customer Location 1', Ship_To_Code__c='000002', Bill_To_Account__c=testCustAccount.Id, Active__c='Yes');
        insert testShipAccount;

        testQuote = new Quote__c(Account__c=testCustAccount.Id, Date_Quoted__c = System.today(), Account__r=testCustAccount, Shipment_Method__c='Warehouse',Requested_Delivery_Date__c=System.today());
        insert testQuote;

        //Product2[] products = [select Id, ProductCode, Description, Unisource_Item_Number_U_number__c, Vendor_Product_Code__c, Vendor__c, Unit_of_Measure__c, Pricing_Costing_UOM__c, Conversion_Factor__c from Product2 limit 2];
        Servicing_Division__c servicingDivision = TestDataGeneration.createServicingDivisions( 1, false )[0];
        servicingDivision.Active__c = true;
        insert servicingDivision;
        
        Product2[] products = TestDataGeneration.createProducts( 2, 'Test Product', false );
        for( Product2 aProduct : products )
        {
            aProduct.Description = 'Test Cup Product 123';
            aProduct.Stocking_Flag__c = true;
            aProduct.Division_Name__c = servicingDivision.Id;
        }
        insert products;
        
        
        Quote_Line_Item__c qli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        qli.Product__c = products[0].Id;
        qli.Product__r = products[0];
        qli.Product_Code__c = products[0].ProductCode;
        qli.Product_Description__c = products[0].Description;
        qli.Unisource_Item__c = products[0].Unisource_Item_Number_U_number__c;
        //qli.Vendor_Item__c = products[0].Vendor_Product_Code__c;
        //qli.Vendor_Name__c = products[0].Vendor__c;
        qli.Qty__c = 1;
        qli.Quantity_unit_of_measure__c = products[0].Unit_of_Measure__c;
        qli.Price_unit_of_measure__c = products[0].Pricing_Costing_UOM__c;
        qli.Costing_unit_of_measure__c = products[0].Pricing_Costing_UOM__c;
        qli.Quantity_Unit_Factor__c = 1;
        qli.Price_Unit_Factor__c = products[0].Conversion_Factor__c;
        qli.Cost_Unit_Factor__c = products[0].Conversion_Factor__c;
        insert qli;
        testQLIs.add(qli);

        qli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        qli.Product__c = products[1].Id;
        qli.Product__r = products[1];
        qli.Product_Code__c = products[1].ProductCode;
        qli.Product_Description__c = products[1].Description;
        qli.Unisource_Item__c = products[1].Unisource_Item_Number_U_number__c;
        //qli.Vendor_Item__c = products[1].Vendor_Product_Code__c;
        //qli.Vendor_Name__c = products[1].Vendor__c;
        qli.Qty__c = 1;
        qli.Quantity_unit_of_measure__c = products[1].Unit_of_Measure__c;
        qli.Price_unit_of_measure__c = products[1].Pricing_Costing_UOM__c;
        qli.Costing_unit_of_measure__c = products[1].Pricing_Costing_UOM__c;
        qli.Quantity_Unit_Factor__c = 1;
        qli.Price_Unit_Factor__c = products[1].Conversion_Factor__c;
        qli.Cost_Unit_Factor__c = products[1].Conversion_Factor__c;
        insert qli;
        testQLIs.add(qli);

    }


}