force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_Division_Desc__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Division_Desc__c</fullName>
    <description>Jan 2017 - Data fed in from data warehouse integration.</description>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Bill_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Number__c</fullName>
    <formula>Account.AccountNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.deactivated_user__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zzShip To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <formula>ShipToAccount__r.Address_Line1__c &amp;  ShipToAccount__r.Address_Line2__c 
&amp;&quot; - &quot; &amp;  
ShipToAccount__r.City__c 
&amp;&quot;,  &quot;&amp; 
ShipToAccount__r.State__c</formula>
    <label>zzShip To Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ShipToAccount__c.field-meta.xml
<CustomField>
    <fullName>ShipToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Primary Sales Rep Object 
Not required on any layouts or record types 
Field is pre-populated (but editable) with the Primary Sales Rep tied to the related Account 
When an Account Primary Sales Rep field is changed, each related Contact that has that has the same Primary Sales Rep as the Account prior to the action is updated so that Opportunity.Primary_Sales_Rep_Name__c = Account.Primary_Sales_Rep_Name__c</description>
    <label>Primary Sales Rep Name</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Bill_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Number__c</fullName>
    <formula>Account__r.AccountNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bill To Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Primary Sales Rep
When a new Quote is created from an Account or Opportunity Record, the Primary Sales Rep field is pre-populated (but editable) with the Primary Sales Rep tied to the related Account
When a new Quote is created from an Opportunity, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Opportunity’s related Account, regardless of the Primary Sales Rep listed on the Opportunity. 
When a new Quote is created from a Contact, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Contact’s related Account record, regardless of the Primary Sales Rep listed on the Contact. 
When a Quote is cloned, the new Quote’s Primary Sales Rep field on the new cloned Quote is pre-populated with the Primary Sales Rep from the Quote it was cloned from</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <label>Address Line2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Number__c</fullName>
    <label>Bill To Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Legacy_Division_Desc__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Division_Desc__c</fullName>
    <label>Legacy Division Desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CarlaShipToController.cls
public class CarlaShipToController {
public String searchText;
public String selectedShipToId {get; set;}
public String objectType;
public String accountNumber;
public Id recordId;
public Id accountId;

List<Ship_To__c> results;

public Boolean calledFromQuoteScreen = true;

public Quote__c currentQuote {get; set;}
public List<shipToWrapper> shipToMatches {get; set;} 
public ShipToWrapper noneOptionShipToWrapper{get; set;}

public ShipToWrapper selectedShipToWrapper {
        get{
                if (selectedShipToWrapper == null)
                {
                    selectedShipToWrapper = new shipToWrapper();
                        
                    for(shipToWrapper sw : shipToMatches)
                    {
                        if(sw.selected)
                        {
                            selectedShipToWrapper = sw;
                        }
                    }
                }
                return selectedShipToWrapper;   
        }       
        set;
        
}
/*
	Called from the Quote Screen
*/
public CarlaShipToController( ApexPages.StandardController stdController )
{
        currentQuote = (Quote__c) stdController.getRecord();
        shipToMatches = new List<shipToWrapper>();
        
        noneOptionShipToWrapper = new ShipToWrapper ();
        noneOptionShipToWrapper.shipTo.Name = 'None';
        shipToMatches.add(noneOptionShipToWrapper);
        searchText ='';
        doSearch();
}

/*
  Called from the Case and Contact Screen
*/
public CarlaShipToController()
{
        calledFromQuoteScreen = false;
        
        /*
        	Lets bring over the parameters
        */
        Map<String,String> params = ApexPages.currentPage().getParameters();
		recordId = params.get('recordId');
		accountId = (params.containsKey('accountId') && params.get('accountId') != '') ? params.get('accountId') : null;
		objectType = params.get('type');
		String name = params.get('name');
		accountNumber = params.get('accountNumber');
		String accountName = params.get('accountName');
        
        shipToMatches = new List<shipToWrapper>();
        
        noneOptionShipToWrapper = new ShipToWrapper ();
        noneOptionShipToWrapper.shipTo.Name = 'None';
        shipToMatches.add(noneOptionShipToWrapper);
        
        searchText ='';
        doSearch();
        
}

public String getSearchText () {
return searchText;
}
public void setSearchText (String s) {
searchText = s;
}
public List<shipToWrapper> getResults() {
return shipToMatches;
}
public PageReference doSearch() {

shipToMatches.clear();
shipToMatches.add (noneOptionShipToWrapper);
//Wrap the variable search term in percents 

//if (searchText==null||searchText=='')
//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid Search Term'));

Id searchAccountId = calledFromQuoteScreen ? currentQuote.Account__c : accountId;
String searchAccountNumber = calledFromQuoteScreen ? currentQuote.Account__r.AccountNumber : accountNumber;

String searchCriteria = '%'+searchtext+'%';

   if(searchText=='')
   {
	//Show all results if a search term has not been specified, called on page load
   results = [SELECT ID, Name, Bill_To_Number__c,
                                  Address_Line1__c, Address_Line2__c, Legacy_Division_Desc__c,
                                  City__c, State__c, Postal_Code__c, Ship_To_Code__c, Account_Owner__c
                   FROM Ship_To__c
                   WHERE Bill_To_Account__c = :searchAccountId
                   AND ( Ship_To_Code__c != :searchAccountNumber )
                   AND Active__c = 'Yes'
                   ORDER BY Ship_To_Code__c 
                   LIMIT 999];
   }else {
        
//SOQL
//12/182019 BAcklog#1797 Updated to display Servicing Div and Account owner(Ship to PSR)
results = [SELECT ID, Name, Bill_To_Number__c,
                                  Address_Line1__c, Address_Line2__c, Legacy_Division_Desc__c,
                                  City__c, State__c, Postal_Code__c, Ship_To_Code__c, Account_Owner__c
                   FROM Ship_To__c
                   WHERE Bill_To_Account__c = :searchAccountId
                   AND ( Ship_To_Code__c != :searchAccountNumber )
                   AND Active__c = 'Yes'
                   AND (Name like : searchCriteria 
                            OR Bill_To_Number__c like :searchCriteria
                            OR Ship_To_Code__c like :searchCriteria
                            OR Address_Line1__c like :searchCriteria
                            OR Address_Line2__c like :searchCriteria
                            OR City__c like :searchCriteria
                            OR State__c like :searchCriteria
                            OR Postal_Code__c like :searchCriteria) 
                  ORDER BY Ship_To_Code__c 
                  LIMIT 999 ];

   }
for( Ship_To__c resultFound : results)
        shipToMatches.add(new shipToWrapper( resultFound ));

return null;
}

 public PageReference saveShipToAddress()
    {
       if( !calledFromQuoteScreen )
       	return saveContactOrCase();
       
       //Get address
        String shipToAddress = '';
        
            if( selectedShipToWrapper.shipTo.Id != null)
            {
                try
                {
                       Integer.valueOf(selectedShipToWrapper.getAddress().substring(0, 6));
                }
                catch(Exception e)
                {
                        shipToAddress = selectedShipToWrapper.getAddress().substring(3);
                }
                shipToAddress = selectedShipToWrapper.getAddress().substring(9);
            }

         Savepoint sp = Database.setSavepoint();


        try
        {
            Quote__c quoteToUpdate = new Quote__c(Id=currentQuote.Id,
                                                  Ship_To_Address__c=shipToAddress);
                                                                                  

            // if the ship to is to be nulled, the primary sales rep comes from the quote's account
            if( selectedShipToWrapper.shipTo.Id == null )
            {
                quoteToUpdate.Ship_To__c = null;
            
                List<Account> quoteAccount = [ SELECT Id, Primary_Sales_Rep_Name__c 
                                                                           FROM Account 
                                                                           WHERE Id = :currentQuote.Account__c 
                                                                           LIMIT 1 ];
                if( !quoteAccount.isEmpty() )
                {
                        quoteToUpdate.Primary_Sales_Rep__c = quoteAccount[0].Primary_Sales_Rep_Name__c;
                }
            }
                        // otherwise pull the primary sales rep from the ship to itself
            else
            {
                quoteToUpdate.Ship_To__c = selectedShipToWrapper.shipTo.Id;
                List<Primary_Sales_Rep__c> primarySalesRep = [ SELECT Id 
                                                               FROM Primary_Sales_Rep__c 
                                                               WHERE sf_userid__c = :selectedShipToWrapper.shipTo.Account_Owner__c 
                                                               LIMIT 1 ];
                if( !primarySalesRep.isEmpty() )
                {
                        quoteToUpdate.Primary_Sales_Rep__c = primarySalesRep[0].Id;
                }
            }
            update quoteToUpdate;
        }
        catch(DmlException dmle)
        {
            for (Integer i=0; i < dmle.getNumDml(); i++)
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, dmle.getDmlMessage(i)));

            Database.rollback(sp);
            return null;
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            Database.rollback(sp);
            return null;
        }

        return new pageReference ('/'+currentQuote.Id);
        
    }

public PageReference saveContactOrCase()
{
	Schema.SObjectType targetType = Schema.getGlobalDescribe().get(objectType);
	SObject testObject = targetType.newSObject(recordId);
	
	if( objectType == 'Case' )
		testObject.put('ShipToAccount__c', selectedShipToWrapper.shipTo.Id);
	else if( objectType == 'Contact')
		testObject.put('Ship_To__c', selectedShipToWrapper.shipTo.Id);
	
	try{
		database.update (testObject);
	}
	catch(DmlException dmle)
    {
            for (Integer i=0; i < dmle.getNumDml(); i++)
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, dmle.getDmlMessage(i)));

            return null;
    }	
    
    return new pageReference ('/'+recordId);
}
   
public class shipToWrapper
{
        public Ship_To__c shipTo {get; set;}
        public Boolean selected {get; set;}
        
        public shipToWrapper(){
        
                this.shipTo = new Ship_To__c();
                this.selected = false;
        
        }
        
        public shipToWrapper( Ship_To__c shipTo )
        {
                this.shipTo = shipTo;
                this.selected = false;
        }

        public String getAddress ()
        {
                         
                        String curShipToAddress = '';
            if(shipTo.Ship_To_Code__c != null && shipTo.Ship_To_Code__c.length() >= 12 )
                        curShipToAddress = shipTo.Ship_To_Code__c.length() == 12 ? shipTo.Ship_To_Code__c.substring(6) + ' - ' : shipTo.Ship_To_Code__c.substring(10) + ' - ';
           
            curShipToAddress += shipTo.Name != null? shipTo.Name: '';
            curShipToAddress += shipTo.Address_Line1__c != null? '\n' + shipTo.Address_Line1__c: '';
            curShipToAddress += shipTo.Address_Line2__c != null? '\n' + shipTo.Address_Line2__c: '';
            curShipToAddress += shipTo.City__c != null? '\n' + shipTo.City__c: '';
            curShipToAddress += shipTo.State__c != null? ', ' + shipTo.State__c: '';
            curShipToAddress += shipTo.Postal_Code__c != null? ', ' + shipTo.Postal_Code__c: '';
            
            return curShipToAddress;
        }
        
        
}
}