force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.deactivated_user__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zzShip To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ShipToAccount__c.field-meta.xml
<CustomField>
    <fullName>ShipToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Primary Sales Rep Object 
Not required on any layouts or record types 
Field is pre-populated (but editable) with the Primary Sales Rep tied to the related Account 
When an Account Primary Sales Rep field is changed, each related Contact that has that has the same Primary Sales Rep as the Account prior to the action is updated so that Opportunity.Primary_Sales_Rep_Name__c = Account.Primary_Sales_Rep_Name__c</description>
    <label>Primary Sales Rep Name</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InactiveRecordTypes__c/InactiveRecordTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>InactiveRecordTypes</label>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Primary Sales Rep
When a new Quote is created from an Account or Opportunity Record, the Primary Sales Rep field is pre-populated (but editable) with the Primary Sales Rep tied to the related Account
When a new Quote is created from an Opportunity, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Opportunity’s related Account, regardless of the Primary Sales Rep listed on the Opportunity. 
When a new Quote is created from a Contact, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Contact’s related Account record, regardless of the Primary Sales Rep listed on the Contact. 
When a Quote is cloned, the new Quote’s Primary Sales Rep field on the new cloned Quote is pre-populated with the Primary Sales Rep from the Quote it was cloned from</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <label>Address Line2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCarlaShipToController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 */
@isTest
private class TestCarlaShipToController {
	
	 static Account TestAccount;
	 static Quote__c TestQuote;
	 static Ship_To__c TestShipTo;

    static {
    	TestAccount = TestingUtils.createAccount('TestAccount');
    	TestAccount.AccountNumber = '123456';
    	insert TestAccount;
        	
    	TestQuote = TestingUtils.createQuote(TestAccount);
    	insert TestQuote;
        	
    	TestShipTo = TestingUtils.createShipTo(TestAccount, 'TestShipTo');
    	TestShipto.Active__c = 'Yes';
    	insert TestShipTo;
    	
    	InactiveRecordTypes__c testCustomSetting = new InactiveRecordTypes__c();
		testCustomSetting.Name = CaseServices.EBUSINESS_RT_NAME;

		System.runAs( TestingUtils.ADMIN_USER )
		{
			insert testCustomSetting;
		}
    	
    }
    static testMethod void testPageConstructor() 
    {
    	/*
    	-- 1 : Create a account
    	-- 2 : Create a quote 
    	-- 3 : Create a few shiptos
    	-- 4 : Go To Ship to page
    	*/
    	
        TestQuote = [SELECT ID, Account__r.AccountNumber FROM Quote__c WHERE ID = :TestQuote.ID];   	
    	test.setCurrentPageReference (new Pagereference (Page.ShipToSearchBox.geturl ()+'?id='+TestQuote.Id));
    	ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller (TestQuote);
    	
    	
    	
    	Test.StartTest ();
    	
    	CarlaShipToController TestController = new CarlaShipToController (SC);
    	
    	
    	
    	Test.stopTest();
    	System.assert( !ApexPages.hasMessages( ApexPages.Severity.ERROR ), 'No error messages should have been created: ' + ApexPages.getMessages() );
    	system.assertequals(TestQuote.id, TestController.currentQuote.Id);
    	
    	system.assertnotequals (null, TestController.shipToMatches);
    	system.assertEquals(2, TestController.shipToMatches.size());
    	system.assertEquals ('None', TestController.shipToMatches[0].shipTo.Name);
    	system.assertEquals(testShipTo.id, TestController.shipToMatches[1].shipTo.id);
    	
    	
    }
     
    static testMethod void testFindShipTo() 
    {
    	/*
    	-- 1 : Create a account - Done on static block
    	-- 2 : Create a quote - Done on static block
    	-- 3 : Create a few shiptos - Done on static block
    	-- 3.5: Create additional shiptos
    	-- 4 : Go To Ship to page
    	-- 5 : Set search text
    	-- 5.5: Do search
    	-- 6 : Get results
    	*/
    	
    	Account TestAccount2 = TestingUtils.createAccount('TestAccount2');
    	insert TestAccount2;
    	
    	List <CarlaShipToController.ShipToWrapper> Results;
    		
    	List <Ship_To__c> DummieShipTos = TestingUtils.createShipTos(testAccount2, 'Dummie ShipTos', 5);
    	insert DummieShipTos;
    	TestQuote = [SELECT ID, Account__r.AccountNumber FROM Quote__c WHERE ID = :TestQuote.ID];
    	test.setCurrentPageReference (new Pagereference (Page.ShipToSearchBox.geturl ()+'?id='+TestQuote.Id));
    	ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller (TestQuote);
    	
    	
    	
    	
    	
    	Test.startTest();
    	
    	CarlaShipToController TestController = New CarlaShipToController (SC);
    	
    	system.debug ('-->'+ TestShipTo.Name);
    	testController.setSearchText('TestShipTo0');
    	testController.doSearch();    	
    	 	
    	Results = testController.getResults();
    	
    	Test.stopTest();
    	
    	system.assertEquals(2, results.size());
    	system.assertEquals ('None', results [0].shipTo.Name);
    	system.assertEquals(testShipTo.id, results[1].shipTo.id);
  }
  
  static testMethod void testExcludeMatchingShipTo() 
    {
    	/*
    	-- 1 : Create a account - Done on static block
    	-- 2 : Create a quote - Done on static block
    	-- 3 : Create a few shiptos - Done on static block
    	-- 3.5: Create additional shiptos where ship_to_code__c matches Bill_to__c
    	-- 4 : Go To Ship to page
    	-- 5 : Set search text
    	-- 5.5: Do search
    	-- 6 : Get results
    	*/
    	
    	    	
    	List <CarlaShipToController.ShipToWrapper> Results;
    		
    	List <Ship_To__c> TestShipTos = TestingUtils.createShipTos(testAccount, 'TestShipTo2', 5);
    	for (Ship_To__c TestShipTosCreated : TestShipTos)
    		TestShipTosCreated.Ship_To_Code__c = TestAccount.AccountNumber;
    	insert TestShipTos;
    	system.debug('-->'+[SELECT Ship_To_Code__c FROM Ship_To__c WHERE Id IN : TestShipTos]);
    	
    	TestQuote = [SELECT ID, Account__r.AccountNumber FROM Quote__c WHERE ID = :TestQuote.ID];
    	test.setCurrentPageReference (new Pagereference (Page.ShipToSearchBox.geturl ()+'?id='+TestQuote.Id));
    	ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller (TestQuote);
    	
    	
    	
    	
    	
    	Test.startTest();
    	
    	CarlaShipToController TestController = New CarlaShipToController (SC);
    	
    	testController.setSearchText('TestShipTo');
    	testController.doSearch();    	
    	 	
    	Results = testController.getResults();
    	
    	Test.stopTest();
    	
    	system.assertEquals(2, results.size());
    	system.assertEquals ('None', results [0].shipTo.Name);
    	system.assertEquals(testShipTo.id, results[1].shipTo.id);
  }
  static testMethod void testShipToAddressBuilder()
    	    {
    	    	
    	    	/*
    	-- 1 : Create a account - Done on static block
    	-- 2 : Create a quote - Done on static block
    	-- 3 : Create a few shiptos - Done on static block
    	-- 4 : Add address info to Ship To
    	-- 5 : Ensure address string is correct
    	
    	 	*/
    	 	
    	    	testShipTo.Address_Line1__c = '123 strat st';
    	    	testShipTo.Address_Line2__c = 'suite 100';
    	    	testShipTo.City__c = 'Weston';
    	    	testShipTo.State__c = 'FL';
    	    	testShipTo.Postal_Code__c = '33326';
    	    	testShipTo.Ship_To_Code__c = '123123456456';
    	    	
    	    	string expectedString = '456456 - TestShipTo0\n123 strat st\nsuite 100\nWeston, FL, 33326';
    	    	string actualString = '';
    	    	
    	    	carlaShipToController.shipToWrapper testWrapper = new carlaShipToController.shipToWrapper (testShipTo);
    	    
    	    	test.startTest ();
    	    	actualString = testWrapper.getAddress();
    	    	test.stopTest ();
    	    	system.assertEquals(expectedString, actualString, 'The get address message should return the correct concatenated string');
    	    }
  static testMethod void testSetNullOnShipTo()
    {
    	/*
    	-- 1 : Create a account - Done on static block
    	-- 2 : Create a quote - Done on static block
    	-- 3 : Create a few shiptos - Done on static block
    	-- 3.5: Create additional shiptos
    	-- 4 : Go To Ship to page
    	-- 5 : Choose None
    	-- 6 : Clear the ship to field on quote
    	
    	 	*/
    	
    	Primary_Sales_Rep__c testPSR = TestDataGeneration.createPSRs( 1, false )[0];
    	testPSR.SF_userid__c = UserInfo.getUserId();
    	insert testPSR;

    	Id custRecTypeID = [select Id from RecordType where SobjectType = 'Account' and Name = 'Customer'].Id;
        testAccount.RecordTypeId = custRecTypeID;
        testAccount.Primary_Sales_Rep_Name__c = testPSR.Id;
        update testAccount;

		

    	testQuote.Ship_To__c = testShipTo.Id;
		testQuote.Primary_Sales_Rep__c = null;
    	update testQuote;
	
		TestQuote = [SELECT ID, Account__r.AccountNumber FROM Quote__c WHERE ID = :TestQuote.ID];
		test.setCurrentPageReference (new Pagereference (Page.ShipToSearchBox.geturl ()+'?id='+testQuote.Id));
    	ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller (testQuote);
    	
    	
    	Test.startTest();
    	
    	CarlaShipToController TestController = New CarlaShipToController (SC);
    	
    	TestController.selectedShipToId = null;
    	
    	TestController.saveShipToAddress();
    	
    

			
    	Test.stopTest();

		System.assert( !ApexPages.hasMessages( ApexPages.Severity.ERROR ), 'No error messages should have been created: ' + ApexPages.getMessages() );
    	testQuote = [ SELECT Id, Ship_To__c, Primary_Sales_Rep__c FROM Quote__c WHERE Id = :testQuote.Id LIMIT 1 ];
    	System.assertEquals( null, testQuote.Ship_To__c, 'When selecting NONE for ship to addresses, the quotes ship to should be cleared' );
    	System.assertEquals( testPSR.Id, testQuote.Primary_Sales_Rep__c, 'When setting ShipTo to null, the quote should get the PSR from its account' );
    }

  static testMethod void testSetShipToPSROnQuote()
    {
    	/*
    	-- 1 : Create a account - Done on static block
    	-- 2 : Create a quote - Done on static block
    	-- 3 : Create a few shiptos - Done on static block
    	-- 3.5: Create additional shiptos
    	-- 4 : Go To Ship to page
    	-- 5 : Choose TestShipTo
    	-- 6 : Ensure that the psr on the quote gets set as the Account Owner of the PSR
    	
    	*/
    	User testUser;
		System.runAs( TestDataGeneration.ADMIN_USER )
		{
			testUser = TestDataGeneration.createUser( 'NUser', 'Standard User', true );
		}
    	
    	testShipTo.Account_Owner__c = testUser.id;
    	update testShipTo;
    	
    	List<Primary_Sales_Rep__c> testPSRs = TestDataGeneration.createPSRs( 2, false );
    	testPSRs[0].SF_userid__c = UserInfo.getUserId();
    	testPSRs[1].SF_userid__c = testUser.id;
    	insert testPSRs;

    	Id custRecTypeID = [select Id from RecordType where SobjectType = 'Account' and Name = 'Customer'].Id;
        testAccount.RecordTypeId = custRecTypeID;
        testAccount.Primary_Sales_Rep_Name__c = testPSRs[1].Id;
        update testAccount;

    	testQuote.Ship_To__c = testShipTo.Id;
		testQuote.Primary_Sales_Rep__c = null;
    	update testQuote;

		TestQuote = [SELECT ID, Account__r.AccountNumber FROM Quote__c WHERE ID = :TestQuote.ID];
		test.setCurrentPageReference (new Pagereference (Page.ShipToSearchBox.geturl ()+'?id='+testQuote.Id));
    	ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller (testQuote);
    	
    	
    	Test.startTest();
    	
    	CarlaShipToController TestController = New CarlaShipToController (SC);
    	
    	TestController.selectedShipToWrapper.shipTo = testShipTo;
    	
    	TestController.saveShipToAddress();
    	
    

			
    	Test.stopTest();

		System.assert( !ApexPages.hasMessages( ApexPages.Severity.ERROR ), 'No error messages should have been created: ' + ApexPages.getMessages() );
    	testQuote = [ SELECT Id, Ship_To__c, Primary_Sales_Rep__c FROM Quote__c WHERE Id = :testQuote.Id LIMIT 1 ];
    	System.assertEquals( testShipTo.Id, testQuote.Ship_To__c, 'A ShipTo on the quote should be populated' );
    	System.assertEquals( testPSRs[1].Id, testQuote.Primary_Sales_Rep__c, 'When setting ShipTo to null, the quote should get the PSR from its account' );
    }

  static testMethod void testSetShipToOnContact()
    {
    	/*
    	-- 1 : Create a account - Done on static block
    	-- 2 : Create a quote - Done on static block
    	-- 3 : Create a few shiptos - Done on static block
    	-- 3.5: Create additional shiptos
    	-- 4: Create a Contact
    	-- 4.5 : Go To Ship to page
    	-- 5 : Select the test shipto
    	-- 6 : Ensure that the contact gets set with the correct shipto
    	
    	*/
		
		Contact testContact = TestingUtils.createContact('Test', 'Contact', false);
		
		testContact.AccountId = testAccount.id;
		
		insert testContact;

		PageReference testPageRef = new Pagereference (Page.ShipToSearchBoxGeneric.geturl() );
		testPageRef.getParameters().put('recordid', testContact.Id);
		testPageRef.getParameters().put('accountId', testAccount.id);
		testPageRef.getParameters().put('type', 'Contact');
		testPageRef.getParameters().put('name', testContact.Name);
		testPageRef.getParameters().put('accountNumber', testAccount.AccountNumber);
		testPageRef.getParameters().put('accountName', testAccount.Name);

		test.setCurrentPageReference ( testPageRef );
    	
    	Test.startTest();
    	
	    	CarlaShipToController TestController = New CarlaShipToController ();
	    	
	    	TestController.selectedShipToWrapper.shipTo = testShipTo;
	    	
	    	TestController.saveShipToAddress();
			
    	Test.stopTest();

		System.assert( !ApexPages.hasMessages( ApexPages.Severity.ERROR ), 'No error messages should have been created: ' + ApexPages.getMessages() );
    	testContact = [ SELECT Id, Ship_To__c FROM Contact WHERE Id = :testContact.Id LIMIT 1 ];
    	System.assertEquals( testShipTo.Id, testContact.Ship_To__c, 'A ShipTo on the contact should be populated' );
    }
 
  static testMethod void testSetShipToOnCase()
    {
    	/*
    	-- 1 : Create a account - Done on static block
    	-- 2 : Create a quote - Done on static block
    	-- 3 : Create a few shiptos - Done on static block
    	-- 3.5: Create additional shiptos
    	-- 4: Create a Case
    	-- 4.5 : Go To Ship to page
    	-- 5 : Select the test shipto
    	-- 6 : Ensure that the contact gets set with the correct shipto
    	
    	*/
		
		List<RecordType>email2CaseRTypes = [Select id from 
											RecordType where DeveloperName = :AttachmentServices.EMAIL_2_CASE_RTYPE
											and SObjectType = 'Case' 
											and IsActive = true limit 1];
		
		System.assert(email2CaseRTypes.size() > 0, 'Fax RecordType Does Not Exist');
		
		Case testCase = TestingUtils.createCase( email2CaseRTypes[0].id );
		
		testCase.AccountId = testAccount.id;
		testCase.Subject = 'Test Subj';
		
		insert testCase;

		PageReference testPageRef = new Pagereference (Page.ShipToSearchBoxGeneric.geturl() );
		testPageRef.getParameters().put('recordid', testCase.Id);
		testPageRef.getParameters().put('accountId', testAccount.id);
		testPageRef.getParameters().put('type', 'Case');
		testPageRef.getParameters().put('name', testCase.Subject);
		testPageRef.getParameters().put('accountNumber', testAccount.AccountNumber);
		testPageRef.getParameters().put('accountName', testAccount.Name);

		test.setCurrentPageReference ( testPageRef );
    	
    	Test.startTest();
    	
	    	CarlaShipToController TestController = New CarlaShipToController ();
	    	
	    	TestController.selectedShipToWrapper.shipTo = testShipTo;
	    	
	    	TestController.saveShipToAddress();
			
    	Test.stopTest();

		System.assert( !ApexPages.hasMessages( ApexPages.Severity.ERROR ), 'No error messages should have been created: ' + ApexPages.getMessages() );
    	testCase = [ SELECT Id, ShipToAccount__c FROM Case WHERE Id = :testCase.Id LIMIT 1 ];
    	System.assertEquals( testShipTo.Id, testCase.ShipToAccount__c, 'A ShipTo on the case should be populated' );
    }

}