force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <inlineHelpText>Requested Delivery Date updates the field &apos;Projected Delivery Date&apos; at the quote line. If different dates apply to lines, that can be updated in that line&apos;s &apos;Additional Details&apos;.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <formula>/* OLD FORMULA */ 
/* 
IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.Division_Code__c, IF( Ship_To_Account__r.Legacy_Division_Cd__c = &quot;&quot;, Account__r.Legacy_Division_Cd__c, Ship_To_Account__r.Legacy_Division_Cd__c)) 
*/ 

IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Code__c, 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, BLANKVALUE(Account__r.Legacy_Division_Cd__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c))) 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Contract_Price_Cd__c.field-meta.xml
<CustomField>
    <fullName>Contract_Price_Cd__c</fullName>
    <description>This how the price is determined.</description>
    <label>Price Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Cost_Unit_Factor__c</fullName>
    <label>Cost Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Costing_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Costing_unit_of_measure__c</fullName>
    <label>Costing UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cust_Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Cust_Item_Code__c</fullName>
    <label>Cust Item Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Extended_Cost__c</fullName>
    <label>Extd&apos;d Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Extended_Price__c.field-meta.xml
<CustomField>
    <fullName>Extended_Price__c</fullName>
    <label>Ext Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Price_Unit_Factor__c</fullName>
    <label>Price Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Price_unit_of_measure__c</fullName>
    <label>Price/Cost UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Projected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Unit_Factor__c</fullName>
    <label>Quantity Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Quantity_unit_of_measure__c</fullName>
    <label>Qty UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Unisource_Item__c.field-meta.xml
<CustomField>
    <fullName>Unisource_Item__c</fullName>
    <label>Unisource Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Item__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Item__c</fullName>
    <label>Vendor Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Name</label>
    <referenceTo>Vendor_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxxEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Division__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this an Active Division?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestQuoteLineItemsCont.cls
/**
 Objective: Test class to validate the functionality for QuoteLineItemsCont
 Developer: Hiremath, Naveen - Bluewolf
*/
@isTest
private class TestQuoteLineItemsCont {

    
    private static Account testCustAccount;
    private static Ship_To__c testShipAccount;
    private static Quote__c testQuote;
    private static Product2[] products;
    private static Quote_Line_Item__c[] testQLIs = new Quote_Line_Item__c[0];

    private static void populateProducts() {

        //products = [select Id, ProductCode, Description, Unisource_Item_Number_U_number__c, Vendor_Product_Code__c, Vendor__c, Unit_of_Measure__c, Pricing_Costing_UOM__c, Conversion_Factor__c from Product2 limit 2];
        Servicing_Division__c servicingDivision = TestDataGeneration.createServicingDivisions( 1, false )[0];
        servicingDivision.Active__c = true;
        insert servicingDivision;
        
        products = TestDataGeneration.createProducts( 2, 'Test Product', false );
        for( Product2 aProduct : products )
        {
            aProduct.Description = 'Test Cup Product 123';
            aProduct.Stocking_Flag__c = true;
            aProduct.Division_Name__c = servicingDivision.Id;
        }
        insert products;
    }

    private static void testSetupData() {
        ID prosRecTypeID = [select Id from RecordType where SobjectType = 'Account' and Name = 'Prospect'].Id;
        testCustAccount = new Account(Name='Test Customer', RecordTypeId=prosRecTypeID, AccountNumber='123456', Ship_To_Code__c='000001');
        insert testCustAccount;

        testShipAccount = new Ship_To__c(Name='Test Customer Location 1', Ship_To_Code__c='000002', Bill_To_Account__c=testCustAccount.Id, Active__c='Yes');
        insert testShipAccount;

        testQuote = new Quote__c(Account__c=testCustAccount.Id, Shipment_Method__c='Warehouse',Requested_Delivery_Date__c=System.today());
        insert testQuote;

        populateProducts();

        Quote_Line_Item__c qli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        qli.Product__c = products[0].Id;
        qli.Product__r = products[0];
        qli.Product_Code__c = products[0].ProductCode;
        qli.Product_Description__c = products[0].Description;
        qli.Unisource_Item__c = products[0].Unisource_Item_Number_U_number__c;
        qli.Vendor_Item__c = products[0].Vendor_Product_Code__c;
        //qli.Vendor_Name__c = products[0].Vendor__c;
        qli.Qty__c = 1;
        qli.Quantity_unit_of_measure__c = products[0].Unit_of_Measure__c;
        qli.Price_unit_of_measure__c = products[0].Pricing_Costing_UOM__c;
        qli.Costing_unit_of_measure__c = products[0].Pricing_Costing_UOM__c;
        qli.Quantity_Unit_Factor__c = 1;
        qli.Price_Unit_Factor__c = products[0].Conversion_Factor__c;
        qli.Cost_Unit_Factor__c = products[0].Conversion_Factor__c;
        qli.Projected_Delivery_Date__c = System.today();
        insert qli;
        testQLIs.add(qli);

        qli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        qli.Product__c = products[1].Id;
        qli.Product__r = products[1];
        qli.Product_Code__c = products[1].ProductCode;
        qli.Product_Description__c = products[1].Description;
        qli.Unisource_Item__c = products[1].Unisource_Item_Number_U_number__c;
        qli.Vendor_Item__c = products[1].Vendor_Product_Code__c;
        //qli.Vendor_Name__c = products[1].Vendor__c;
        qli.Qty__c = 1;
        qli.Quantity_unit_of_measure__c = products[1].Unit_of_Measure__c;
        qli.Price_unit_of_measure__c = products[1].Pricing_Costing_UOM__c;
        qli.Costing_unit_of_measure__c = products[1].Pricing_Costing_UOM__c;
        qli.Quantity_Unit_Factor__c = 1;
        qli.Price_Unit_Factor__c = products[1].Conversion_Factor__c;
        qli.Cost_Unit_Factor__c = products[1].Conversion_Factor__c;
        qli.Projected_Delivery_Date__c = System.today();
        insert qli;
        testQLIs.add(qli);
    }
    /*
    private static testMethod void doCreate_AddASearchedProductToTheQuote_returnsNothing() {

        Boolean NO_CLONE = false;

        testSetupData();
        String singleProductSelected = simulateSingleProductSelection(NO_CLONE);

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsCreate.getURL() + '?results=' + singleProductSelected));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doCreate();
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), 'Only a single QLI must be created and the success will be true');
        System.assertEquals(Consts.EMPTY_STRING, String.valueOf(jsonObject.get('message')), 'A single QLI must be created, the message will be empty');
        System.assertEquals(1, Integer.valueOf(jsonObject.getValue('results').values.size()), 'Results must have a single record');

    }

    private static testMethod void doCreate_CloneAnExistingQLI_returnsNothing() {

        Boolean DO_CLONE = true;

        testSetupData();
        String singleProductSelected = simulateSingleProductSelection(DO_CLONE);

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsCreate.getURL() + '?results=' + singleProductSelected));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doCreate();
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), 'A single QLI must be created and the success will be true');
        System.assertEquals(Consts.EMPTY_STRING, String.valueOf(jsonObject.get('message')), 'A single QLI must be created, the message will be empty');
        System.assertEquals(1, Integer.valueOf(jsonObject.getValue('results').values.size()), 'Results must have a single record');

    }

    private static testMethod void doUpdate_ASingleQLI_returnsNothing() {

        Boolean ALWAYS_A_SINGLE_RECORD_WILL_BE_UPDATED_AT_A_GIVEN_TIME = true;

        testSetupData();
        String singleUpdateRecord = simulateSingleProductSelection(ALWAYS_A_SINGLE_RECORD_WILL_BE_UPDATED_AT_A_GIVEN_TIME);

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsUpdate.getURL() + '?results=' + singleUpdateRecord));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doUpdate();
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );

        System.assertEquals(1, Integer.valueOf(jsonObject.get('total')), 'A single QLI must be updated');
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), 'Always a single QLI will be updated and the success will be true');
        System.assertEquals(Consts.EMPTY_STRING, String.valueOf(jsonObject.get('message')), 'Always a single QLI will be updated, the message will be empty');
        System.assertEquals(1, Integer.valueOf(jsonObject.getValue('results').values.size()), 'Results must have a single record');

    }
    */
    private static testMethod void testQLICalculationsStandardQTYUOM() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItems.getURL() + '?quoteId=' + testQuote.Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

       //Create a qli with some test values
        Quote_Line_Item__c testQli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        testQli.Qty__c = 1;
        testQli.Quantity_Unit_Factor__c = 1;
        testQli.Price__c = 1.00;
        testQli.Price_Unit_Factor__c = 1;
        testQli.Cost__c = 1.00;
        testQli.Cost_Unit_Factor__c = 1;

       QuoteLineItemModel qliModel = new QuoteLineItemModel( new QuotesModel( new Quote__c (Id=testQuote.Id)), testQli );

       Test.startTest();

           cont.calcExtendedPrice( qliModel );

       Test.stopTest();

       System.assertEquals( 1, testQli.Extended_Price__c );
       System.assertEquals( 1, testQli.Extended_Cost__c );
    }

    private static testMethod void testQLICalculationsNegativeQTYandNegativePriceUOM() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItems.getURL() + '?quoteId=' + testQuote.Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

       //Create a qli with some test values
        Quote_Line_Item__c testQli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        testQli.Qty__c = 100;
        testQli.Quantity_Unit_Factor__c = 1;
        testQli.Price__c = 1.00;
        testQli.Price_Unit_Factor__c = -500;
        testQli.Cost__c = 1.00;
        testQli.Cost_Unit_Factor__c = 1;

       //Create a qli with some test values
        Quote_Line_Item__c testQli2 = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        testQli2.Qty__c = 20;
        testQli2.Quantity_Unit_Factor__c = -500;
        testQli2.Price__c = 1.00;
        testQli2.Price_Unit_Factor__c = 1;
        testQli2.Cost__c = 1.00;
        testQli2.Cost_Unit_Factor__c = 1;

        QuoteLineItemModel qliModel = new QuoteLineItemModel( new QuotesModel( new Quote__c (Id=testQuote.Id)), testQli );
        QuoteLineItemModel qliModel2 = new QuoteLineItemModel( new QuotesModel( new Quote__c (Id=testQuote.Id)), testQli2 );

        Test.startTest();

           cont.calcExtendedPrice( qliModel );
           cont.calcExtendedPrice( qliModel2 );

        Test.stopTest();

        System.assertEquals( 50000, testQli.Extended_Price__c );
        System.assertEquals( 100, testQli.Extended_Cost__c );

        System.assertEquals( 0.04, testQli2.Extended_Price__c );
        System.assertEquals( 0.04, testQli2.Extended_Cost__c );
    }

    private static testMethod void testIsUpdateableQuote() {

        testSetupData();
        Quote__c testQuote2 = testQuote.clone(false, false, false, false);
        testQuote2.Shipment_Method__c = null;

        Test.startTest();
            Boolean testQuoteIsUpdateable = QuoteLineItemsCont.isUpdateableQuote(testQuote);
            Boolean testQuote2IsUpdateable = QuoteLineItemsCont.isUpdateableQuote(testQuote2);
        Test.stopTest();

        System.assert(testQuoteIsUpdateable, 'We expect the Quote with a Shipment Method to be updateable');
        System.assert(!testQuote2IsUpdateable, 'We expect the Quote without a Shipment Method to not be updateable');
    }

    private static testMethod void testQLICalculationsPositiveQTYandPositivePriceUOM() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItems.getURL() + '?quoteId=' + testQuote.Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

       //Create a qli with some test values
        Quote_Line_Item__c testQli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        testQli.Qty__c = 100;
        testQli.Quantity_Unit_Factor__c = 1;
        testQli.Price__c = 1.00;
        testQli.Price_Unit_Factor__c = 2;
        testQli.Cost__c = 1.00;
        testQli.Cost_Unit_Factor__c = 1;

       //Create a qli with some test values
        Quote_Line_Item__c testQli2 = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        testQli2.Qty__c = 20;
        testQli2.Quantity_Unit_Factor__c = 2;
        testQli2.Price__c = 1.00;
        testQli2.Price_Unit_Factor__c = 1;
        testQli2.Cost__c = 1.00;
        testQli2.Cost_Unit_Factor__c = 1;

        QuoteLineItemModel qliModel = new QuoteLineItemModel( new QuotesModel( new Quote__c (Id=testQuote.Id)), testQli );
        QuoteLineItemModel qliModel2 = new QuoteLineItemModel( new QuotesModel( new Quote__c (Id=testQuote.Id)), testQli2 );

        Test.startTest();

            cont.calcExtendedPrice( qliModel );
            cont.calcExtendedPrice( qliModel2 );

        Test.stopTest();

        System.assertEquals( 50, testQli.Extended_Price__c );
        System.assertEquals( 100, testQli.Extended_Cost__c );

        System.assertEquals( 40, testQli2.Extended_Price__c );
        System.assertEquals( 40, testQli2.Extended_Cost__c );
    }

    private static testMethod void testQLICalculationsPLPositiveQTYandPositivePriceUOM() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItems.getURL() + '?quoteId=' + testQuote.Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

       //Create a qli with some test values
        Quote_Line_Item__c testQli = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        testQli.Qty__c = 100;
        testQli.Quantity_Unit_Factor__c = 1;
        testQli.Price__c = 1.00;
        testQli.Price_Unit_Factor__c = 50;
        testQli.Cost__c = 1.00;
        testQli.Cost_Unit_Factor__c = 1;

       //Create a qli with some test values
        Quote_Line_Item__c testQli2 = new Quote_Line_Item__c(Quote__c=testQuote.Id);
        testQli2.Qty__c = 20;
        testQli2.Quantity_Unit_Factor__c = 50;
        testQli2.Price__c = 1.00;
        testQli2.Price_Unit_Factor__c = 1;
        testQli2.Cost__c = 1.00;
        testQli2.Cost_Unit_Factor__c = 1;

        QuoteLineItemModel qliModel = new QuoteLineItemModel( new QuotesModel( new Quote__c (Id=testQuote.Id)), testQli );
        QuoteLineItemModel qliModel2 = new QuoteLineItemModel( new QuotesModel( new Quote__c (Id=testQuote.Id)), testQli2 );

        Test.startTest();

            cont.calcExtendedPrice( qliModel );
            cont.calcExtendedPrice( qliModel2 );

        Test.stopTest();

        System.assertEquals( 2, testQli.Extended_Price__c );
        System.assertEquals( 100, testQli.Extended_Cost__c );

        System.assertEquals( 1000, testQli2.Extended_Price__c );
        System.assertEquals( 1000, testQli2.Extended_Cost__c );
    }

    private static testMethod void doRead_AllQLIOnAQuote_returnsNothing() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItems.getURL() + '?quoteId=' + testQuote.Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doRead();
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), '2 QLIs must be fetched and the success will be true');
        System.assertEquals(Consts.EMPTY_STRING, String.valueOf(jsonObject.get('message')), '2 QLIs must be fetched and the message will be empty');
        System.assertEquals(2, Integer.valueOf(jsonObject.get('total')), '2 QLIs must be present in JSON response');
        System.assertEquals(2, Integer.valueOf(jsonObject.getValue('results').values.size()), 'Results must have a two records');
    }

    private static testMethod void doReload_AllQLIOnAQuote_returnsNothing() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsReload.getURL() + '?quoteId=' + testQuote.Id + '&qliIds=' + testQLIs[0].Id + ',' + testQLIs[1].Id + '&itemSeq=1,2'));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doReload();
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), '2 QLIs must be reloaded and the success will be true');
        System.assertEquals(Consts.EMPTY_STRING, String.valueOf(jsonObject.get('message')), '2 QLIs must be reloaded, the message will be empty');
        System.assertEquals(2, Integer.valueOf(jsonObject.get('total')), '2 QLIs must be present in JSON response');
        System.assertEquals(2, Integer.valueOf(jsonObject.getValue('results').values.size()), 'Results must have a two records');
    }
    
    private static testMethod void doDelete_ASingleQLI_returnsNothing() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsDelete.getURL() + '?results=' + testQLIs[0].Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doDelete();
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );
        System.assertEquals(1, Integer.valueOf(jsonObject.get('total')), 'A single QLI must be deleted');
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), 'A single QLI must be deleted and the success will be true');
        System.assertEquals(Consts.EMPTY_STRING, String.valueOf(jsonObject.get('message')), 'A single QLI must be deleted, the message will be empty');

    }

    private static testMethod void doCalc_OnMultipleQLI_returnsNothing() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsCalc.getURL() + '?quoteId=' + testQuote.Id + '&qliIds=' + testQLIs[0].Id + ',' + testQLIs[1].Id + '&qliCloned=1,2'));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doCalc();
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );
        System.assertEquals(2, Integer.valueOf(jsonObject.get('total')), 'Two records must be calculated');
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), 'Calc Operation must be a success');
        System.assertEquals(2, Integer.valueOf(jsonObject.getValue('results').values.size()), 'Results must have a 2 records');

    }
    
    /*
    This test is not a comprehensive unit test of the assignqlivalues function. We will only test for the following:
    
    1) 11/5 - Map ItemPriceCode to Contract_Price_Cd__c
    2) 9/25 - Ensuring that the mappings of CustomerItemNumber to Cust_Item_Code__c are successful when the values in the P&A call are not empty
    3) 11/18 - Removed testing of Copr_Acct__c value
    */
    private static testMethod void testAssignQLIValues()
    {
        testSetupData();
        
        final String SAMPLE_CODE = 'code'; 
        final String SAMPLE_IS_NATIONAL_ACCOUNTS_PRICE = 'Y';
        final String SAMPLE_CUSTOMER_ITEM_NUMBER = '10036509';
        
        QuoteLineItemModel testQLIModel = new QuoteLineItemModel(new QuotesModel(testQuote),QuoteLineItemServices.getQuoteLineItems(testQuote.ID)[0]); 
        
        PricingAndAvailability.ItemDetailsClass itemDetails = new PricingAndAvailability.ItemDetailsClass();
        itemDetails.CustomerItemNumber = SAMPLE_CUSTOMER_ITEM_NUMBER; 
        itemDetails.ItemPriceCode=SAMPLE_CODE;
        
        testQLIModel.getPAndA().Response.ItemDetails.add(itemDetails);
        
        Test.startTest();
            QuoteLineItemsCont testController = new QuoteLineItemsCont();
            testController.assignQLIValues(testQLIModel, testQuote);
        Test.stopTest();
        
        System.assertEquals(SAMPLE_CODE,testQLIModel.getQuoteLineItem().Contract_Price_Cd__c,'We expect to map the ItemPriceCode from the P&A call to the Contract_Price_Cd__c');
        System.assertEquals(SAMPLE_CUSTOMER_ITEM_NUMBER,testQLIModel.getQuoteLineItem().Cust_Item_Code__c,'We expect to map the CustomerItemNumber from the P&A call to the Cust_Item_Code__c');
    }

    private static testMethod void testAssignQLIValues_WhenShipmentMethodDirect()
    {
        testSetupData();
        testQuote.Shipment_Method__c = Consts.SHIP_METHOD_DIRECT;

        QuoteLineItemModel testQLIModel = new QuoteLineItemModel(new QuotesModel(testQuote),QuoteLineItemServices.getQuoteLineItems(testQuote.ID)[0]); 
        
        PricingAndAvailability.ItemDetailsClass itemDetails = new PricingAndAvailability.ItemDetailsClass();
        itemDetails.ItemCostStandard = '24.40';
        itemDetails.ItemPricePerUOM = '24.14';

        testQLIModel.getPAndA().Response.ItemDetails.add(itemDetails);        

        Test.startTest();
            QuoteLineItemsCont testController = new QuoteLineItemsCont();
            testController.assignQLIValues(testQLIModel, testQuote);
        Test.stopTest();
        //Sujitha Damidi: commented on 1/11/2019 for Backlog#00683
        // Objective:Direct shipment method not to default to zero and to pull Warehouse pricing 
        //System.assertEquals(0, testQLIModel.getQuoteLineItem().Cost__c , 'We expect the Cost to be set to 0 when the Shipment Method is Direct');
       // System.assertEquals(0, testQLIModel.getQuoteLineItem().Price__c , 'We expect the Price to be set to 0 when the Shipment Method is Direct');
       // System.assertEquals(0, testQLIModel.getQuoteLineItem().Start_Price__c , 'We expect the Start Price to be set to 0 when the Shipment Method is Direct');
    } 
    
    private static testMethod void testAssignQLIValues_WhenValuesEmptyFromPACALL()
    {
        testSetupData();
        
        QuoteLineItemModel testQLIModel = new QuoteLineItemModel(new QuotesModel(testQuote),QuoteLineItemServices.getQuoteLineItems(testQuote.ID)[0]); 
        
        PricingAndAvailability.ItemDetailsClass itemDetails = new PricingAndAvailability.ItemDetailsClass();
        itemDetails.CustomerItemNumber = QuoteLineItemsCont.EMPTY_NOTE;
        itemDetails.ItemPriceCode = QuoteLineItemsCont.EMPTY_NOTE;
        
        testQLIModel.getPAndA().Response.ItemDetails.add(itemDetails);
        
        Test.startTest();
            QuoteLineItemsCont testController = new QuoteLineItemsCont();
            testController.assignQLIValues(testQLIModel, testQuote);
        Test.stopTest();
        
        System.assertEquals(null, testQLIModel.getQuoteLineItem().Contract_Price_Cd__c, 'We do not expect to directly map ItemPriceCode from the P&A call to the Contract_Price_Cd__c field when the value is tagged as empty. Instead we will map a null value.');
        System.assertEquals(null,testQLIModel.getQuoteLineItem().Cust_Item_Code__c,'We do not expect to directly map CustomerItemNumber from the P&A call to the Cust_Item_Code__c field when the value is tagged as empty. Instead we will map a null value.');    
    } 
        
    
    private static testMethod void testReturnNullIfEmptyLikeString_PositiveTest()
    {
        Test.startTest(); 
            String result = QuoteLineItemsCont.returnNullIfEmptyLikeString(QuoteLineItemsCont.EMPTY_NOTE);
        Test.stopTest();
        
        System.assertEquals(null,result,'When the specified string matches the string the P&A call returns when the field value is empty, we do not want to store that string. Instead we want to store a null value');
    }
    
    private static testMethod void testReturnNullIfEmptyLikeString_NegativeTest()
    {
        final String sampleString = 'TEST';
        
        Test.startTest();
            String result = QuoteLineItemsCont.returnNullIfEmptyLikeString(sampleString);
        Test.stopTest();
        
        System.assertEquals(sampleString,result,'When the specified string does not match the string the P&A call returns when the field value is empty, we want to store that string.');
    } 

    private static testMethod void doUpdatePA_OnMultipleQLI_returnsNothing() {

        testSetupData();

        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsUpdatePA.getURL() + '?quoteId=' + testQuote.Id + '&qliIds=' + testQLIs[0].Id + ',' + testQLIs[1].Id + '&itemSeq=1,2'));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doUpdatePA();
        System.assert(String.isNotBlank(cont.errorMessage) && 
                      cont.errorMessage.contains(
                            QuoteLineItemsCont.ELIGIBILITY_ERROR.substring(3,
                                                                           QuoteLineItemsCont.ELIGIBILITY_ERROR.length())
                            ),
                      'We expect an Eligibility Error message: ' + cont.errorMessage
                      );
        System.assertNotEquals(null, cont.json, 'A JSON string response must be generated');

        JSONObject jsonObject = new JSONObject( new JSONObject.JSONTokener(cont.json) );
        System.assertEquals(2, Integer.valueOf(jsonObject.get('total')), 'Two records must be calculated');
        System.assertEquals(true, Boolean.valueOf(jsonObject.get('success')), 'Calc Operation must be a success');
        System.assertEquals(2, Integer.valueOf(jsonObject.getValue('results').values.size()), 'Results must have a 2 records');

    }

    private static testMethod void doQtyUOM_AlwaysOnASingleQLI_returnsNothing() {

        testSetupData();

        //'%26' url encoded code for '&'
        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsQtyUOM.getURL() + '?query=' + testQuote.Id + '%26' + testQLIs[0].Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doQtyUOM();
        System.assertNotEquals(Consts.EMPTY_STRING, cont.json, 'A JSON string array must be generated');

    }

    private static testMethod void doPriceUOM_AlwaysOnASingleQLI_returnsNothing() {

        testSetupData();

        //'%26' url encoded code for '&'
        Test.setCurrentPageReference(new PageReference(Page.QuoteLineItemsPriceUOM.getURL() + '?query=' + testQuote.Id + '%26' + testQLIs[0].Id));
        QuoteLineItemsCont cont = new QuoteLineItemsCont();

        cont.doPriceUOM();
        System.assertNotEquals(Consts.EMPTY_STRING, cont.json, 'A JSON string array must be generated');

    }

    private static testMethod void testSpecialCharacters_SuchAsQuote()
    {
        testSetupData();
        
        testQLIs[0].Type_Of_Quote__c = 'test with quote "';
        
        update testQLIs[0];
        
        QuoteLineItemsCont cont = new QuoteLineItemsCont();
        
        String generatedJson = cont.generateJSONForLineItem( testQLIs[0], testQuote.Id, false );
    
        System.assert( generatedJson.contains('\"')); 
    }
    
    private static testMethod void testSpecialCharacters_SuchAsLineBreak()
    {
        testSetupData();
        
        testQLIs[0].Product_Code__c = 'test \r with \n quote "';
        
        update testQLIs[0];
        
        QuoteLineItemsCont cont = new QuoteLineItemsCont();
        
        String generatedJson = cont.generateJSONForLineItem( testQLIs[0], testQuote.Id, false );
    
        System.assert( generatedJson.contains('test   with   quote')); 
    }

    private static String simulateSingleProductSelection(Boolean isCloned_isUpdate) {

        String jsonObject = '{';
        jsonObject += '\"quoteId\":\"' + testQuote.Id + '\",';
        jsonObject += '\"itemSeq\":\"' + '1' + '\",';
        jsonObject += '\"qliSpecialItem\":' + false + ',';
        jsonObject += '\"qliSpecialProduct\":' + false + ',';
        jsonObject += '\"qliQty\":\"' + '1' + '\",';
        jsonObject += '\"qliProdId\":\"' + products[0].Id + '\",';
        jsonObject += '\"qliProdCode\":\"' + products[0].ProductCode + '\",';
        jsonObject += '\"qliProdDesc\":\"' + products[0].Description + '\",';
        jsonObject += '\"qliUOM\":\"' + products[0].Unit_of_Measure__c + '\",';
        jsonObject += '\"qliPrice\":\"' + '0' + '\",';
        jsonObject += '\"qliPriceUOM\":\"' + products[0].Pricing_Costing_UOM__c + '\",';
        jsonObject += '\"qliPriceCode\":\"' + 'null' + '\",';
        jsonObject += '\"qliExtendedPrice\":\"' + '0' + '\",';
        jsonObject += '\"qliExtendedCost\":\"' + '0' + '\",';
        jsonObject += '\"qliGTMPercent\":\"' + '0' + '\",';
        jsonObject += '\"qliVendor\":\"' + products[0].Vendor__c + '\",';
        jsonObject += '\"qliComments\":\"' + 'null' + '\",';
        jsonObject += '\"qliBid\":\"' + 'null' + '\",';
        jsonObject += '\"qliMinMfgQty\":\"' + 'null' + '\",';
        jsonObject += '\"qliCost\":\"' + '0' + '\",';
        jsonObject += '\"qliProjDel\":\"' + 'null' + '\",';
        jsonObject += '\"qliVendorItem\":\"' + products[0].Vendor_Product_Code__c + '\",';
        jsonObject += '\"qliMfgTol\":\"' + 'null' + '\",';
        jsonObject += '\"qliLDC\":\"' + 'null' + '\",';
        jsonObject += '\"qliGTMDollar\":\"' + '0' + '\",';
        jsonObject += '\"qliVendorContact\":\"' + 'null' + '\",';
        jsonObject += '\"qliUnisourceItem\":\"' + products[0].Unisource_Item_Number_U_number__c + '\",';
        jsonObject += '\"qliPriceUnitFactor\":\"' + products[0].Conversion_Factor__c + '\",';
        jsonObject += '\"qliCostUnitFactor\":\"' + products[0].Conversion_Factor__c + '\",';
        if(isCloned_isUpdate)
            jsonObject += '\"id\":\"' + testQLIs[0].Id + '\",';
        jsonObject += '\"qliCloned\":' + isCloned_isUpdate;
        jsonObject += '}';

        return jsonObject;

    }
    
    /*
    This test is not a comprehensive unit test of the generateJSONForLineItem function. We will only test for the following:
        1) Whether the ID field, and the Quote__c field are captured in the resulting JSON (existing functionality as of 10/1/2013)
        2) Whether the Future Dev Cost field is captured in the resulting JSON (new functionality as of 10/1/2013)
    */
    private static testMethod void testGenerateJSONForLineItem()
    {
        final Decimal sampleDevCost = 3.1;
        
        testSetupData();
        testQLIs[0].Future_Dev_Cost__c = sampleDevCost;
        
        Test.startTest();
            QuoteLineItemsCont testController = new QuoteLineItemsCont();   
            String resultingJSON = testController.generateJSONForLineItem(testQLIs[0], testQLIs[0].Quote__c, false).removeEnd(',');
        Test.stopTest();
        JSONParser parser = JSON.createParser(resultingJSON);
        Boolean idEncountered = false;
        Boolean quoteIDEncountered = false;
        Boolean qliFutureDevCostEncountered = false;
        while (parser.nextToken() != null) {
            if ((parser.getCurrentToken() == JSONToken.FIELD_NAME)){
                String fieldName = parser.getText();
                parser.nextToken();
                if(fieldName == 'id') {
                   System.assertEquals(testQLIs[0].Id,parser.getText(),'We expect to get store the right qli ID in the JSON');
                   idEncountered = true;
                } else if(fieldName == 'quoteID'){
                    System.assertEquals(testQLIs[0].Quote__c,parser.getText(),'We expect to get store the right quote ID in the JSON');
                    quoteIDEncountered = true;
                }
                else if(fieldName == 'qliFutDevCost'){
                    System.assertEquals(sampleDevCost,Decimal.valueOf(parser.getText()),'We expect to get store the right dev cost in the JSON');
                    qliFutureDevCostEncountered = true;
                }
            }
        }
        
        System.assert(idEncountered,'We expect to store the qli ID in the JSON');
        System.assert(quoteIDEncountered,'We expect to store the quote ID in the JSON');
        System.assert(qliFutureDevCostEncountered,'We expect to store the qli future dev ID in the JSON');
    }


    private static testMethod void testcheckEligibility_True()
    {
        testSetupData();
        Boolean expectedValue = true;
        QuoteLineItemModel testQLIModel = new QuoteLineItemModel(new QuotesModel(testQuote),QuoteLineItemServices.getQuoteLineItems(testQuote.ID)[0]); 
        
        PricingAndAvailability.ItemEligibilityClass itemEligibility = new PricingAndAvailability.ItemEligibilityClass();
        itemEligibility.EligibilityFlag = 'Y';
        itemEligibility.ExceptionFlag = 'N';
        
        testQLIModel.getPAndA().Response.ItemEligibility.add(itemEligibility);
        
        Test.startTest();
            QuoteLineItemsCont testController = new QuoteLineItemsCont();
            Boolean returnedValue = testController.checkEligibility(testQLIModel);
        Test.stopTest();
        
        System.assertEquals(expectedValue, returnedValue, 'We expect the correct value to be returned');
        System.assertEquals(expectedValue, testQLIModel.getQuoteLineItem().Updated_P_A__c, 'We expect the Updated P&A field to match the expected value.');
    }

    private static testMethod void testcheckEligibility_False()
    {
        testSetupData();
        Boolean expectedValue = false;
        QuoteLineItemModel testQLIModel = new QuoteLineItemModel(new QuotesModel(testQuote),QuoteLineItemServices.getQuoteLineItems(testQuote.ID)[0]); 
        
        PricingAndAvailability.ItemEligibilityClass itemEligibility = new PricingAndAvailability.ItemEligibilityClass();
        itemEligibility.EligibilityFlag = 'N';
        itemEligibility.ExceptionFlag = 'N';
        
        testQLIModel.getPAndA().Response.ItemEligibility.add(itemEligibility);
        
        Test.startTest();
            QuoteLineItemsCont testController = new QuoteLineItemsCont();
            Boolean returnedValue = testController.checkEligibility(testQLIModel);
        Test.stopTest();
        
        System.assertEquals(expectedValue, returnedValue, 'We expect the correct value to be returned');
        System.assertEquals(expectedValue, testQLIModel.getQuoteLineItem().Updated_P_A__c, 'We expect the Updated P&A field to match the expected value.');
    }


}