force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Required on all Layouts except &quot;Opportunity Layout - System Admin&quot; 
When new Opportunity created from account page, PSR field is pre-populated (editable) with PSR from related Account. 
When a Lead is converted and an opportunity created, the PSR field from the Lead is mapped to the PSR name on Opportunity. 
When Account PSR field is changed, Account Trigger updates each related open Opportunity that has the same PSR as related Account prior to the action 
Reps granted Read/Write access to an Opportunity when the PSR field is saved or edited with their PSR record ID. If the field on the record is changed, the previous PSR associated rep still has access</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChatterAutoFollowBatch.cls
global class ChatterAutoFollowBatch implements Database.Batchable<SObject>, Database.Stateful, Schedulable
{
	
	public static final String BATCH_NAME = 'Auto Follow Opportunities and Active Accounts Through Chatter';
	public String query;
	public String dateOrderField;
	global DateGetters.DateGetter dateGetter;
	global EntitySubscriptionSorters.EntitySubscriptionSorter sortPreference;
	
	global String errors = '';

	global ChatterAutoFollowBatch() { 
		dateGetter = DateGetterFactory.getDateGetter(DateGetterFactory.GETTER_LAST_MODIFIED_DATE);
		sortPreference = EntitySubscriptionSorterFactory.getEntitySubscriptionSorter(EntitySubscriptionSorterFactory.OnlyHaveOpportunities);
	}
	
	global ChatterAutoFollowBatch(DateGetters.DateGetter howToGetDateField, EntitySubscriptionSorters.EntitySubscriptionSorter howToPrioritize) {
		 dateGetter = howToGetDateField;
		 sortPreference = howToPrioritize;  
	}

	// builds dynamic query
	global database.querylocator start( Database.BatchableContext bc )
	{
		Set<Id> salesProfileIds = ChatterServices.getSalesProfileIds();
		String profileIds = ChatterServices.generateProfileFilter( salesProfileIds );
		query = 'SELECT Id FROM User WHERE IsActive = true AND ProfileId IN ' + profileIds;

		/*
		When unit-testing, the above query will result in this error:
		'No more than one executeBatch can be called from within a testmethod.
		Please make sure the iterable returned from your start method matches the
		batch size, resulting in one executeBatch invocation.'

		The below code limits the users we test to those we created during that day,
		which effectively includes the users in our unit-test.

		*/

		If (test.isRunningTest())
		{
			query += ' AND CreatedDate >= TODAY';
		}

		return Database.getQueryLocator( query );
	}

	// performs functionality from service class
	global void execute( Database.BatchableContext BC, List<User> scope )
	{
		Set<String> CLOSED_STAGE_NAMES = ChatterServices.CLOSED_STAGE_NAMES;
		
		List<Primary_Sales_Rep__c> primarySalesReps = [SELECT Id FROM Primary_Sales_Rep__c WHERE SF_userid__c IN : scope];

		String oppQuery = 'SELECT Id, Primary_Sales_Rep_Name__c, OwnerId, ' + dateGetter.getFieldName(Opportunity.SObjectType) +  ' FROM Opportunity ' +
													'WHERE (NOT StageName IN: CLOSED_STAGE_NAMES) AND (OwnerId IN :scope ' +
														'OR Primary_Sales_Rep_Name__c IN :primarySalesReps)';
														
		List<Opportunity> opportunityMatches = Database.query( oppQuery );

		String accountQuery = 'SELECT Id, Primary_Sales_Rep_Name__c, OwnerId,' + dateGetter.getFieldName(Account.SObjectType) + ' FROM Account WHERE ' 
		 + '( OwnerId IN :scope OR Primary_Sales_Rep_Name__c IN :primarySalesReps ) AND Active__c=\'Yes\'';
		
		List<Account> accountMatches = Database.query( accountQuery );
		
		List<SObject> opportunitiesAndAccounts = new List<SObject>();
		opportunitiesAndAccounts.addAll((List<SObject>) accountMatches);
		opportunitiesAndAccounts.addAll((List<SObject>) opportunityMatches);
		

		errors = ChatterServices.subscribePSRandOwnerToSObject(opportunitiesAndAccounts,dateGetter,sortPreference);
	}

	// if error, build message and send email
	global void finish( Database.BatchableContext bc )
	{
		AsyncApexJob job = [ SELECT Id, Status, NumberOfErrors,
								JobItemsProcessed, TotalJobItems,
								CreatedBy.Email
							FROM AsyncApexJob
							WHERE Id =:bc.getJobId() ];

		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		mail.setToAddresses( BatchServices.ERROR_EMAILS  );
		mail.setSubject( 'Batch to ' + BATCH_NAME + ' ' + job.Status );

		String emailBody = 'Batch to ' + BATCH_NAME + ' processed '
							+ job.TotalJobItems
							+ ' batches with '
							+ job.NumberOfErrors
							+ ' failures.';

		if( errors != '' )
		{
			emailBody += '\n\n\nThe following errors occured:\n' + errors;
		}

		mail.setPlainTextBody( emailBody );
		Messaging.sendEmail( new Messaging.SingleEmailMessage[]{ mail } );
	}

	// executes schedulable batch
	global void execute( SchedulableContext sc )
	{
		Database.executeBatch( new ChatterAutoFollowBatch() );
	}
}