force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Ship To Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Date_Quoted__c.field-meta.xml
<CustomField>
    <fullName>Date_Quoted__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>The date the quote information was given to the customer if different than when entered in SFDC</inlineHelpText>
    <label>Date Quoted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Quote_Stage__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Additional Follow-up Required</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Customer Lost Job</fullName>
            </value>
            <value>
                <fullName>Lost Relationship</fullName>
            </value>
            <value>
                <fullName>Lost to Competition</fullName>
            </value>
            <value>
                <fullName>Mfg Took Direct</fullName>
            </value>
            <value>
                <fullName>Non-competitive Cost</fullName>
            </value>
            <value>
                <fullName>Price Too High</fullName>
            </value>
            <value>
                <fullName>Product Availability</fullName>
            </value>
            <value>
                <fullName>Product Quality</fullName>
            </value>
            <value>
                <fullName>Quoting Response Time</fullName>
            </value>
            <value>
                <fullName>Veritiv Performance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <color>#E27001</color>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <color>#66E9BD</color>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#F96FB7</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Sent to Customer</fullName>
                <color>#0B6FCE</color>
                <label>Sent to Customer</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <color>#CC0000</color>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Won</fullName>
                <color>#009900</color>
                <label>Won</label>
            </value>
            <value>
                <fullName>Returned From Field Sourcing</fullName>
                <color>#641CCF</color>
                <label>Returned From Field Sourcing</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <color>#8F6429</color>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Requires Additional Follow-up</fullName>
                <color>#CC33CC</color>
                <label>Requires Additional Follow-up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <inlineHelpText>Requested Delivery Date updates the field &apos;Projected Delivery Date&apos; at the quote line. If different dates apply to lines, that can be updated in that line&apos;s &apos;Additional Details&apos;.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <formula>/* OLD FORMULA */ 
/* 
IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.Division_Code__c, IF( Ship_To_Account__r.Legacy_Division_Cd__c = &quot;&quot;, Account__r.Legacy_Division_Cd__c, Ship_To_Account__r.Legacy_Division_Cd__c)) 
*/ 

IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Code__c, 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, BLANKVALUE(Account__r.Legacy_Division_Cd__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c))) 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/System_Code__c.field-meta.xml
<CustomField>
    <fullName>System_Code__c</fullName>
    <formula>IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.System_Code__c, IF( Ship_To_Account__r.Legacy_System_Cd__c = &quot;&quot;, Account__r.Legacy_System_Cd__c, Ship_To_Account__r.Legacy_System_Cd__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>System Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Division__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this an Active Division?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/fields/Division_Code__c.field-meta.xml
<CustomField>
    <fullName>Division_Code__c</fullName>
    <label>Division Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/fields/System_Code__c.field-meta.xml
<CustomField>
    <fullName>System_Code__c</fullName>
    <label>System Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestViewQuoteContExtAdditionalTests.cls
@isTest
public with sharing class TestViewQuoteContExtAdditionalTests {
	
	public static Quote__c testQuote;
	
	public static void setupData(){
	    Account testCustAccount = new Account(Name='Test Customer', AccountNumber='123456', Ship_To_Code__c='000001', Active__c='Yes');
        insert testCustAccount;
		
		Servicing_Division__c testServiceDivision1 = new Servicing_Division__c();
		testServiceDivision1.Name = 'Test Unisource Division';
		testServiceDivision1.Division_Code__c = 'Un1';
		testServiceDivision1.System_Code__c = 'UN';
		insert testServiceDivision1;

		Servicing_Division__c testServiceDivision2 = new Servicing_Division__c();
		testServiceDivision2.Name = 'Test Xpedx Division';
		testServiceDivision2.Division_Code__c = 'Xp1';
		testServiceDivision2.System_Code__c = 'X';
		insert testServiceDivision2;
		
		testQuote = new Quote__c(Account__c=testCustAccount.Id, Date_Quoted__c = System.today(), Account__r=testCustAccount, Shipment_Method__c='Warehouse',Requested_Delivery_Date__c=System.today());
        insert testQuote;
        
	}
	
	public static testMethod  void testProductSearchDivisions() {
		
		Account testCustAccount = new Account(Name='Test Customer', AccountNumber='123456', Ship_To_Code__c='000001', Active__c='Yes');
        insert testCustAccount;
		
		Servicing_Division__c testServiceDivision1 = new Servicing_Division__c();
		testServiceDivision1.Name = 'Test Unisource Division';
		testServiceDivision1.Division_Code__c = 'Un1';
		testServiceDivision1.System_Code__c = 'UN';
		insert testServiceDivision1;

		Servicing_Division__c testServiceDivision2 = new Servicing_Division__c();
		testServiceDivision2.Name = 'Test Xpedx Division';
		testServiceDivision2.Division_Code__c = 'Xp1';
		testServiceDivision2.System_Code__c = 'X';
		insert testServiceDivision2;
		
		testQuote = new Quote__c(Account__c=testCustAccount.Id, Date_Quoted__c = System.today(), Account__r=testCustAccount, Shipment_Method__c='Warehouse',Requested_Delivery_Date__c=System.today());
        insert testQuote;
        
        ApexPages.StandardController stdCont = new ApexPages.StandardController( testQuote );
        ViewQuoteQuoteContExt quoteCont = new ViewQuoteQuoteContExt( stdCont );
		
		Test.startTest();
			List<Servicing_Division__c> divisions = ServicingDivisionServices.getActiveServiceDivisions();
		Test.stopTest();
		
		
		
		System.assertEquals(1, divisions.size(), 'We expect back only the division that does not contain an X in the system code field.');
		System.assertEquals('Test Unisource Division', divisions[0].Name, 'We expect back only the division that does not contain an X in the system code field.'); 
	}
	
	
	
	
	public static testMethod  void testRenderSalesOrderNumberField_true() {
		
		setupData();
        
        ApexPages.StandardController stdCont = new ApexPages.StandardController( testQuote );
        stdCont.getRecord().put('Quote_Stage__c', QuoteInformationExt.QUOTE_WON_STAGE);
        ViewQuoteQuoteContExt quoteCont = new ViewQuoteQuoteContExt( stdCont );		
		
		Test.startTest();
			Boolean result = quoteCont.renderSalesOrderNumberField;
		Test.stopTest();
		
		
		
		System.assertEquals(true, result, 'We expect to render the Sales Order number field when the Quote is in stage won.');
	}
	
	public static testMethod  void testRenderSalesOrderNumberField_false() {
		
		setupData();
        
        ApexPages.StandardController stdCont = new ApexPages.StandardController( testQuote );
        stdCont.getRecord().put('Quote_Stage__c', QuoteInformationExt.QUOTE_LOST_STAGE);
        ViewQuoteQuoteContExt quoteCont = new ViewQuoteQuoteContExt( stdCont );
		
		
		Test.startTest();
			Boolean result = quoteCont.renderSalesOrderNumberField;
		Test.stopTest();
		
		
		
		System.assertEquals(false, result, 'We expect to not render the Sales Order number field when the Quote is in stage lost.');
	}
	
	public static testMethod  void testRenderLostReasonCommentsField_true() {
		
		setupData();
        
        ApexPages.StandardController stdCont = new ApexPages.StandardController( testQuote );
		stdCont.getRecord().put('Quote_Stage__c', QuoteInformationExt.QUOTE_LOST_STAGE);
		stdCont.getRecord().put('Lost_Reason__c', QuoteInformationExt.QUOTE_LOST_REASON_OTHER);
		ViewQuoteQuoteContExt quoteCont = new ViewQuoteQuoteContExt( stdCont );
		
		
		Test.startTest();
			Boolean result = quoteCont.renderLostReasonCommentsField;
		Test.stopTest();
		
		
		
		System.assertEquals(true, result, 'We expect to render the Lost Reason Comments field when the Quote is in stage lost.');
	}
	
	public static testMethod  void testRenderLostReasonCommentsField_false() {
		
		setupData();
        
        ApexPages.StandardController stdCont = new ApexPages.StandardController( testQuote );
        stdCont.getRecord().put('Quote_Stage__c', QuoteInformationExt.QUOTE_WON_STAGE);
        ViewQuoteQuoteContExt quoteCont = new ViewQuoteQuoteContExt( stdCont );		
		
		Test.startTest();
			Boolean result = quoteCont.renderLostReasonCommentsField;
		Test.stopTest();
		
		
		
		System.assertEquals(false, result, 'We expect to not render the Lost Reason Comments field when the Quote is in stage won.');
	}
	
	
}