force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>This is &quot;Delete Flag&quot; field from existing system. Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>FALSE</fullName>
                <isActive>false</isActive>
                <label>FALSE</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestShipToLookupController.cls
@isTest
private class TestShipToLookupController
{
	static testMethod void testShipToLookupController()
	{
		Account testAccount = new Account(Name='Test Account');
		insert testAccount;
		Contact testContact = new Contact(AccountId = testAccount.Id, LastName = 'Johnson', FirstName='John');
		insert testContact;

		Test.setCurrentPageReference(new PageReference('/apex/ShipToLookup?id=' +
				testContact.Id + '&type=Contact&name=' + testContact.Name + '&accountId=' +
				testAccount.Id + '&accountName=' + testAccount.Name));

		ShipToLookupController shipToController = new ShipToLookupController();
		//We show the none option
		System.assert(shipToController.showShipTos);

		Ship_To__c shipTo = new Ship_To__c(Bill_To_Account__c = testAccount.Id, Address_Line1__c = '123 test Street', Active__c = 'Yes');
		insert shipTo;

		shipToController = new ShipToLookupController();
		System.assert(shipToController.showShipTos);

		/*
		//We can save a blank shipto
		
		shipToController.saveShipTo();
		System.assert(ApexPages.hasMessages());
		System.assertEquals(ApexPages.Severity.ERROR, ApexPages.getMessages()[0].getSeverity());
		*/
		shipToController.shipToId = shipTo.Id;
		shipToController.saveShipTo();
		testContact = [SELECT Id, Ship_To__c FROM Contact WHERE Id = :testContact.Id];
		System.assertEquals(shipToController.shipToId, testContact.Ship_To__c);
	}
}