force-app/main/default/objects/Account/fields/Bill_To_Number_to_Merge_With__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Number_to_Merge_With__c</fullName>
    <inlineHelpText>Enter the Customer&apos;s Bill To number in this field.  The Prospect will be merged with the Customer that has this Bill To number.</inlineHelpText>
    <label>Bill To Number to Merge With</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Customer_Selling_Margin_Rate__c.field-meta.xml
<CustomField>
    <fullName>Customer_Selling_Margin_Rate__c</fullName>
    <inlineHelpText>Choose your target margin percentage for this opportunity</inlineHelpText>
    <label>Customer Selling Margin Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Expected_Billing_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Billing_Date__c</fullName>
    <inlineHelpText>The date when you expect the order(s) to be billed in accounting.</inlineHelpText>
    <label>Expected Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prod_Category__c.field-meta.xml
<CustomField>
    <fullName>Prod_Category__c</fullName>
    <description>Any changes here should also be made on the following objects - Vendor Detail, Contact, Work Orders and Form Assembly Work Order.  It&apos;s a dependent picklist to Segment.  We have some Dashboards that filter on some values for Specialists, so changes need to be vetted against those dashboards.</description>
    <inlineHelpText>Choose one or more by holding the control button (ctrl, bottom left of your keyboard) down as you select multiple product categories</inlineHelpText>
    <label>Prod Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Opportunity_Segment__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADHESIVES</fullName>
            </value>
            <value>
                <fullName>AEROSPACE</fullName>
            </value>
            <value>
                <fullName>AMENITIES</fullName>
            </value>
            <value>
                <fullName>AQUEOUS MEDIA</fullName>
            </value>
            <value>
                <fullName>AQUEOUS PRINTERS</fullName>
            </value>
            <value>
                <fullName>AUTODESK - PRODUCT</fullName>
            </value>
            <value>
                <fullName>AUTODESK SUBSCRIPTION - NEW</fullName>
            </value>
            <value>
                <fullName>AUTODESK SUBSCRIPTION - RENEWAL</fullName>
            </value>
            <value>
                <fullName>BAGS</fullName>
            </value>
            <value>
                <fullName>BINDERY</fullName>
            </value>
            <value>
                <fullName>BLANKETS</fullName>
            </value>
            <value>
                <fullName>BOND &amp; WRITING</fullName>
            </value>
            <value>
                <fullName>CAN LINERS</fullName>
            </value>
            <value>
                <fullName>CAN LINERS-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>CANNABIS PACKAGING</fullName>
            </value>
            <value>
                <fullName>CARBONLESS</fullName>
            </value>
            <value>
                <fullName>CHEMICALS</fullName>
            </value>
            <value>
                <fullName>CHEMICALS-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>CHIPBOARD</fullName>
            </value>
            <value>
                <fullName>COATED BOARD - ROLLS</fullName>
            </value>
            <value>
                <fullName>COATED BOARD - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED DOMESTIC - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED IMPORT - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED - ROLLS</fullName>
            </value>
            <value>
                <fullName>COLD CHAIN</fullName>
            </value>
            <value>
                <fullName>COMPUTER &amp; LAPTOP</fullName>
            </value>
            <value>
                <fullName>CORRUGATED</fullName>
            </value>
            <value>
                <fullName>CUSHIONING</fullName>
            </value>
            <value>
                <fullName>DESIGN</fullName>
            </value>
            <value>
                <fullName>DIGITAL PAPER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BillToPromptControllerExtenstion.cls
public class BillToPromptControllerExtenstion 
{
	public Account account {get; set;}
	public Boolean showBillToPrompt {get; set;}
	public Boolean isSubmitted {get; set;}
	public Boolean isReminded {get; set;}
	
	public static final String CLOSED_WON_STAGE = '8- Closed Won';
	public static final RecordType PROSPECT_ACCOUNT_RECORD_TYPE = [SELECT Id, Name, SObjectType
																	 FROM RecordType
																	 WHERE SObjectType = 'Account'
																	  AND Name = 'Prospect'];
	
	public BillToPromptControllerExtenstion(ApexPages.StandardController stdController)
	{
		String recordId = stdController.getRecord().Id;
		Boolean hasClosedWonOpportunity;
		
		if(recordId.startsWith('001')) //account
		{
			account = getAccountById(recordId);
			Integer closedWonOppCount =  [SELECT Count() 
											FROM Opportunity 
											WHERE AccountId = :recordId 
											 AND  StageName = :CLOSED_WON_STAGE];
			hasClosedWonOpportunity = (closedWonOppCount > 0);
		}
		else if(recordId.startsWith('006')) //opportunity
		{
			Opportunity opportunity = [SELECT Id, Name, StageName, AccountId
							FROM Opportunity
							WHERE Id = :recordId];
			account = getAccountById(opportunity.AccountId);
			hasClosedWonOpportunity = (opportunity.StageName == CLOSED_WON_STAGE);
		}
		
					  
		showBillToPrompt = (hasClosedWonOpportunity
							 && account.Bill_To_Number_to_Merge_With__c == null
							 && account.RecordTypeId == PROSPECT_ACCOUNT_RECORD_TYPE.Id);
		isSubmitted = false;
		isReminded = false;
	}
	
	/*
	* create task to remind user in 7 days
	*/
	public void createRemindMeLaterTask()
	{
		Integer reminderInterval = 7;
		Date reminderDate = Date.today().addDays(reminderInterval);
		Datetime reminderDateTime = Datetime.now().addDays(reminderInterval);

		Task billToReminder = new Task();
		billToReminder.ActivityDate = reminderDate;
		billToReminder.ReminderDateTime = reminderDateTime;
		billToReminder.IsReminderSet = true;
		billToReminder.WhatId = account.Id;
		billToReminder.Subject = 'Enter bill to number for account '+account.Name;
		billToReminder.Description = 'Enter bill to number for account '+account.Name;
		billToReminder.OwnerId = UserInfo.getUserId(); 
		
		try
		{
			insert billToReminder;
			isReminded = true;
			showBillToPrompt = false;
		}
		catch(Exception ex)
		{
			System.debug(ex);
		}
	}
	
	public void submit()
	{
		if(account.Bill_To_Number_to_Merge_With__c == null 
		   || account.Bill_To_Number_to_Merge_With__c == '')
		{
			return;
		}
		
		try
		{
			update account;
			isSubmitted = true;
			showBillToPrompt = false;
		}
		catch(Exception ex)
		{
			System.debug(ex);
		}
	}
	
	private Account getAccountById(String accountId)
	{
		Account acc = [SELECT Id, Name, Bill_To_Number_to_Merge_With__c, RecordTypeId 
						FROM Account 
						WHERE Id = :accountId];
		return acc;
	}
	

	
	@testVisible
	private static Account createProspectAccount()
	{
		Account account = new Account(Name='prospect account', RecordTypeId = PROSPECT_ACCOUNT_RECORD_TYPE.Id);
		insert account;
		return account;
	}
	@testVisible
	private static Account createNonProspectAccount()
	{
		RecordType customerRecordType = [SELECT Id, Name, SObjectType
											 FROM RecordType
											 WHERE SObjectType = 'Account'
											  AND Name = 'Customer'];
		
		Account account = new Account(Name='customer account', RecordTypeId = customerRecordType.Id);
		insert account;
		return account;							  
	}
	@testVisible
	private static Opportunity createClosedWonOpportunity(String accountId)
	{
		Opportunity opp = TestingUtils.createOpportunities(1, accountId, 'test opp', false)[0];
		opp.StageName = CLOSED_WON_STAGE;
		opp.Expected_Billing_Date__c = Date.today();
		opp.Customer_Selling_Margin_Rate__c = 50;
		opp.Prod_Category__c = 'CARBONLESS';
										 
		insert opp;
		return opp;
	}
	@testVisible
	private static Opportunity createNonClosedWonOpportunity(String accountId)
	{
		Opportunity opp = TestingUtils.createOpportunities(1, accountId, 'test opp', false)[0];
		opp.StageName = '1 - Prospect';
		opp.Customer_Selling_Margin_Rate__c = 50;
		opp.Prod_Category__c = 'CARBONLESS';
		insert opp;	
		return opp;
	}
}