force-app/main/default/objects/Account/fields/Chain_Account__c.field-meta.xml
<CustomField>
    <fullName>Chain_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chain Accounts</relationshipLabel>
    <relationshipName>ChainAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_System_Cd__c.field-meta.xml
<CustomField>
    <fullName>Legacy_System_Cd__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>03 = SFDSW
MA = SFDMA
NU = SFDNU
PC = SFDPC
X = MAX</inlineHelpText>
    <label>Legacy System Cd*</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Natl_Acct_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Natl_Acct_Group_ID__c</fullName>
    <description>Unify Group Code from DW</description>
    <label>Natl Acct Group ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/VOS_Business_Group__c.field-meta.xml
<CustomField>
    <fullName>VOS_Business_Group__c</fullName>
    <description>Field used to identify Saalfeld, fed in by Data Warehouse</description>
    <label>VOS Business Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zilliant_Active__c.field-meta.xml
<CustomField>
    <fullName>Zilliant_Active__c</fullName>
    <description>Updated by data warehouse. 
N – Customer not in Zilliant
Y – Customer in Legacy Zilliant
AI - Customer in Zilliant IQ</description>
    <inlineHelpText>N – Customer not in Zilliant
Y – Customer in Legacy Zilliant
AI - Customer in Zilliant IQ</inlineHelpText>
    <label>Zilliant-Active</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Custom object to represent a scheduled CPL. Records only saved if they are scheduled for external. External/Internal records can be download for xls and pdf and the values pulled in are based on the filter selections of the custom fields on this object.</description>
    <label>Customer Price List</label>
    <nameField>
        <label>Customer Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Price_List__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the contract. Used for the Internal record type.</description>
    <label>Agreement</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <description>Free-form email address section</description>
    <inlineHelpText>This field is required to schedule a CPL.

Use a line break to separate multiple email recipients.</inlineHelpText>
    <label>Customer Email</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Displays as a multi-select in the CPL form but is a text field. Defaults to All Divisions which searches for all products in the agreement, but if a user selects one or multiple among the list of servicing divisions on the products of published contract line items then the query will only search for the selections. Filter selections available is both controlling and dynamic to Class and Brand</description>
    <inlineHelpText>Search All Divisions within the agreement or search to filter the results.</inlineHelpText>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Level_Filter__c.field-meta.xml
<CustomField>
    <fullName>Level_Filter__c</fullName>
    <description>Either searches within the agreement or changes the query so also show products where the set and subset match the line items that are priced at Set and Subset level.</description>
    <inlineHelpText>Select Item Level (Expand Sets and Subsets) to show products with matching sets and subsets outside of the agreement.</inlineHelpText>
    <label>Level Filter</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Line Level</fullName>
                <default>true</default>
                <label>Agreement Line Level</label>
            </value>
            <value>
                <fullName>Item Level (Expand Sets and Subsets)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/New_Or_Changed_Only__c.field-meta.xml
<CustomField>
    <fullName>New_Or_Changed_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A filter on the CPL form where if TRUE then it will only show records that have been published or created since ___</description>
    <label>New Or Changed Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Purchased_Stocked_Filter__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Stocked_Filter__c</fullName>
    <description>Looks at the Is_Stocked flag on the product or the 12 Month Sales Volume field on the contract line to determine whether the product should be shown or not.</description>
    <inlineHelpText>Filter to show all agreement lines, just stocked products, or just products the customer has purchased in the past 12 months.</inlineHelpText>
    <label>Purchased/Stocked Filter</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Show All Agreement Lines</fullName>
                <default>true</default>
                <label>Show All Agreement Lines</label>
            </value>
            <value>
                <fullName>Show Purchased Agreement Lines Only</fullName>
            </value>
            <value>
                <fullName>Show Stock Agreement Lines Only</fullName>
            </value>
            <value>
                <fullName>Show Purchased Or Stocked Agreement Lines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Regional_National_Filter__c.field-meta.xml
<CustomField>
    <fullName>Regional_National_Filter__c</fullName>
    <description>Either shows products just on this agreement, on the agreement&apos;s parent (regional), or on the agreement&apos;s grandparent (national)</description>
    <label>Regional/National Filter</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Show Current and Chain Account Pricing</fullName>
                <default>true</default>
                <label>Show Current and Chain Account Pricing</label>
            </value>
            <value>
                <fullName>Show National Agreement Lines (if any)</fullName>
            </value>
            <value>
                <fullName>Ignore Regional Chain AND National Agreement Lines (if any)</fullName>
            </value>
            <value>
                <fullName>Show Chain Accounts Only</fullName>
            </value>
            <value>
                <fullName>Show Regional Chain AND National Agreement Lines (if any)</fullName>
                <isActive>false</isActive>
                <label>Show Regional Chain AND National Agreement Lines (if any)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A text value that does not change the data of the CPL, but will change the name and email shown on the CPL. The list of users are the account owners of the Ship To&apos;s on the Agreement&apos;s Account.  

It is a lookup to the user object so the Name and Email field can be easily retrieved.</description>
    <inlineHelpText>Whose name and email should appear on the CPL?</inlineHelpText>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/TXN_History__c.field-meta.xml
<CustomField>
    <fullName>TXN_History__c</fullName>
    <description>Only one active value, 12 Months, to correspond with the Purchased filter which will only show products that have been purchased within this TXN History date range (12 Months)</description>
    <label>TXN History</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purchased_Stocked_Filter__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
                <default>true</default>
                <label>All</label>
            </value>
            <value>
                <fullName>Last 12 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <description>Schedule a branded pdf or xls to be sent to your customer</description>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Customer_Price_List__c/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Download an xls - for internal use only.</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/NationalAccountsPricing__c/NationalAccountsPricing__c.object-meta.xml
<CustomObject>
    <description>Pricing for national accounts</description>
    <label>National Accounts Pricing</label>
    <nameField>
        <label>Short Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Accounts Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NationalAccountsPricing__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/CompositeKey__c.field-meta.xml
<CustomField>
    <fullName>CompositeKey__c</fullName>
    <label>CompositeKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/NationalAccountGroupID__c.field-meta.xml
<CustomField>
    <fullName>NationalAccountGroupID__c</fullName>
    <externalId>true</externalId>
    <label>National Account Group ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/Set__c.field-meta.xml
<CustomField>
    <fullName>Set__c</fullName>
    <label>Set</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/Subset__c.field-meta.xml
<CustomField>
    <fullName>Subset__c</fullName>
    <label>Subset</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CPLXLSControllerTest.cls
@isTest
public class CPLXLSControllerTest 
{
    @testSetup static void createPolicyType(){
        List<zpl__PolicyType__c> lPolicyType = new List<zpl__PolicyType__c>{new zpl__PolicyType__c(Name = 'CWT Fixed', zpl__PolicyTypeId__c = 'cwtFixed'), 
            																new zpl__PolicyType__c(Name = 'Fixed Price', zpl__PolicyTypeId__c = 'fixedPrice'),
            																new zpl__PolicyType__c(Name = 'List Down', zpl__PolicyTypeId__c = 'listDown'), 
            																new zpl__PolicyType__c(Name = 'Maintain GTM', zpl__PolicyTypeId__c = 'maintainGTM'),
            																new zpl__PolicyType__c(Name = 'Natl Account', zpl__PolicyTypeId__c = 'nationalAccount')};
       insert lPolicyType;
    }
    
    @isTest
    public static void controller_testExternalWithId()
    {
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('VOS_Business_Group__c').assign('SA')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .tag('Products');

        insert UnitTest.get('Products').getList();
        
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200);
            //.property('Bracket1Value__c').assign(100)
            //.property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200);
            //.property('Bracket1Value__c').assign(100)
            //.property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    @isTest
    public static void controller_testExternalNoId()
    {
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('VOS_Business_Group__c').assign('SA')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .tag('Products');

        insert UnitTest.get('Products').getList();
        
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200);
            //.property('Bracket1Value__c').assign(100)
            //.property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200);
            //.property('Bracket1Value__c').assign(100)
            //.property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    @isTest
    public static void controller_testExternalNoIdNoSA()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('Natl_Acct_Group_ID__c').assign('NACID')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .property('Name').assign('00000003')
            .property('productCode').assign('00000003')
            .property('Class__c').assign('CS')
            .property('Brand__c').assign('BD')
            .property('System_ID__c').assign('03')
            .tag('Products');

        insert UnitTest.get('Products').getList();
        
        UnitTest.addData(SObjectFactory.build(1, NationalAccountsPricing__c.SObjectType))
            .property('NationalAccountGroupID__c').assign('NACID')
            .property('Class__c').assign('A')
            .property('Name').assign('00000003')
            .property('CompositeKey__c').assign('SWtestNA')
            .tag('National');
        
        insert UnitTest.get('National').getList();

 
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('zpl__EffectiveDate__c').assign(Date.today())
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id) 
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];
       
        UnitTest.addData(SObjectFactory.build(numberOfEachClassification, Servicing_Division__c.SObjectType))
            .tag('Divisions');

        insert UnitTest.get('Divisions').getList();   


        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        //ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Regional Chain AND National Agreement Lines (if any)');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }

    @isTest
    public static void controller_testExternalNoIdNoSANoBracket()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
        .tag('Chain Account');
        
        insert UnitTest.get('Chain Account').getList();
        
        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('Chain_Account__c').assignFrom('Chain Account')
            .property('OwnerId').assignFrom('User')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();
        
        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .tag('Products');

        insert UnitTest.get('Products').getList();
 
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Brand_Desc__c').assign('BD')
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id) 
            .property('Brand__c').assign('BD')
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];
       
        UnitTest.addData(SObjectFactory.build(numberOfEachClassification, Servicing_Division__c.SObjectType))
            .tag('Divisions');

        insert UnitTest.get('Divisions').getList();   


        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }

    @isTest
    public static void controller_testNewExternalScenario()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();
        
        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
        .property('RecordTypeId').assign(Schema.SObjectType.Account.getRecordTypeInfosByName().get('Chain Account').getRecordTypeId())
        .tag('Chain Account');
        
        insert UnitTest.get('Chain Account').getList();
        
        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('Natl_Acct_Group_ID__c').assign('NACID')
            .property('Legacy_System_Cd__c').assign('SW')
            .property('Chain_Account__c').assignFrom('Chain Account')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(numberOfEachClassification, Servicing_Division__c.SObjectType))
            .tag('Divisions');

        insert UnitTest.get('Divisions').getList();  
        
        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('Division__c').assignFrom('Divisions')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();
 
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Subset')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        .property('productCode').assign('00000003')
        .property('Brand__c').assign('BD')
        .property('Subset__c').assign('0001')
        .property('Set__c').assign('0001')
        .property('System_ID__c').assign('03')
        .tag('Products');

        insert UnitTest.get('Products').getList();
        
        UnitTest.addData(SObjectFactory.build(50, NationalAccountsPricing__c.SObjectType))
            .property('NationalAccountGroupID__c').assign('NACID')
            .property('Class__c').assign('A')
            .property('Name').assign('00000003')
            .property('CompositeKey__c').assign('SW')
            .tag('National');
        
        insert UnitTest.get('National').getList();
        /*
        UnitTest.addData(SObjectFactory.build(1, Customer_Price_List__c.SObjectType))
            .property('Customer_Email__c').assign('me@gmail.com')
            .property('Agreement__c').assignFrom('Agreement')
            .tag('cpl');

        insert UnitTest.get('cpl').getList();
        
        Customer_Price_List__c cpl = (Customer_Price_List__c) UnitTest.get('cpl').getList()[0];
        */
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Class__c').assign('A')
            .property('Class_Desc__c').assign('Desc')
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assignFrom('Set Level') 
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Class__c').assign('A')
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];    
         
        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        //ApexPages.currentPage().getParameters().put('id', cpl.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show National Agreement Lines (if any)');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');        
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    @isTest
    public static void controller_testInternalNoId()
    {
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .tag('Products');

        insert UnitTest.get('Products').getList();

        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        }       

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show National Agreement Lines (if any)');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    @isTest
    public static void controller_testInternalNoIdNoBracket()
    {
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .tag('Products');

        insert UnitTest.get('Products').getList();

        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        }       

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }

    @isTest
    public static void controller_testExternalNoIdSetSubset()
    {
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('VOS_Business_Group__c').assign('SA')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        //UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        //    .tag('Products');
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        .property('productCode').assign('00000003')
        .property('Brand__c').assign('BD')
        .property('Subset__c').assign('0001')
        .property('Set__c').assign('0001')
        .property('System_ID__c').assign('03')
        .tag('Products');
       
       
        insert UnitTest.get('Products').getList();

        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Set__c').assign('0001')
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Item Level (Expand Sets and Subsets)');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }

    @isTest
    public static void getCountsAndHeaders_test()
    {
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('VOS_Business_Group__c').assign('SA')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .tag('Products');

        insert UnitTest.get('Products').getList();

        
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        }  
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Item Level (Expand Sets and Subsets)');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    @isTest
    public static void controller_testInternalNoIdNoBracketNational()
    {
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('Natl_Acct_Group_ID__c').assign('NACID')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
            .property('Name').assign('00000003')
            .property('productCode').assign('00000003')
            .property('Class__c').assign('CS')
            .property('Brand__c').assign('BD')
            .property('System_id__c').assign('03')
            .tag('Products');


        insert UnitTest.get('Products').getList();
        
        UnitTest.addData(SObjectFactory.build(50, NationalAccountsPricing__c.SObjectType))
            .property('NationalAccountGroupID__c').assign('NACID')
            .property('Class__c').assign('A')
            .property('Name').assign('00000003')
            .property('CompositeKey__c').assign('SW')
            .tag('National');
               
        
        insert UnitTest.get('National').getList();


        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        }       

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Bracket1MinQty__c').assign(100)
            .property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        //ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Regional Chain AND National Agreement Lines (if any)');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    @isTest
    public static void rodneyExternalTest()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')            
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        //UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        //    .tag('Products');
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        .property('productCode').assign('00000003')
        .property('description').assign('00000003 test')
        .property('Brand__c').assign('BD')
        .property('Subset__c').assign('0001')
        .property('Class__c').assign('A')
        .property('Set__c').assign('0001')
        .property('System_ID__c').assign('03')
        .tag('Products');
       
       
        insert UnitTest.get('Products').getList();

        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
        
        UnitTest.addData(SObjectFactory.build(1, zpl__PolicyType__c.SObjectType))
            .tag('Fixed Price Policy')
            .property('Name').assign('Fixed Price')
            .property('zpl__Description__c').assign('Fixed Price');
        insert UnitTest.get('Fixed Price Policy').getList();
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__PolicyType__c').assignFrom('Fixed Price Policy')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Set__c').assign('0001')
            .property('Class__c').assign('A')
            .property('Class_Desc__c').assign('Desc')
            .property('Description__c').assign('00000003 test')
            .property('zpl__PolicyValue__c').assign(10)
            .property('PricingCost__c').assign(5)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Item Level (Expand Sets and Subsets)');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    /*@isTest
    public static void rodneyInternalTest()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')            
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        //UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        //    .tag('Products');
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        .property('productCode').assign('00000003')
        .property('description').assign('00000003 test')
        .property('Brand__c').assign('BD')
        .property('Subset__c').assign('0001')
        .property('Class__c').assign('A')
        .property('Set__c').assign('0001')
        .property('System_ID__c').assign('03')
        .tag('Products');
       
       
        insert UnitTest.get('Products').getList();

        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
        
        UnitTest.addData(SObjectFactory.build(1, zpl__PolicyType__c.SObjectType))
            .tag('Fixed Price Policy')
            .property('Name').assign('Fixed Price')
            .property('zpl__Description__c').assign('Fixed Price');
        insert UnitTest.get('Fixed Price Policy').getList();
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__PolicyType__c').assignFrom('Fixed Price Policy')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Set__c').assign('0001')
            .property('Class__c').assign('A')
            .property('Class_Desc__c').assign('Desc')
            .property('Description__c').assign('00000003 test')
            .property('zpl__PolicyValue__c').assign(10)
            .property('PricingCost__c').assign(5)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Item Level (Expand Sets and Subsets)');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }*/
    
    @isTest
    public static void rodneySaalfieldTest()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')        
            .property('VOS_Business_Group__c').assign('SA')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        //UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        //    .tag('Products');
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        .property('productCode').assign('00000003')
        .property('Brand__c').assign('BD')
        .property('Subset__c').assign('0001')
        .property('Class__c').assign('A')
        .property('Set__c').assign('0001')
        .property('System_ID__c').assign('03')
        .tag('Products');
       
       
        insert UnitTest.get('Products').getList();

        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Set__c').assign('0001')
            .property('Class__c').assign('A')
            .property('Class_Desc__c').assign('Desc')
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Item Level (Expand Sets and Subsets)');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    @isTest
    public static void rodneyExternalSubsetTest()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();

        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')            
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();

        //UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        //    .tag('Products');
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        .property('productCode').assign('00000003')
        .property('Brand__c').assign('BD')
        .property('Subset__c').assign('0001')
        .property('Class__c').assign('A')
        .property('Set__c').assign('0001')
        .property('System_ID__c').assign('03')
        .tag('Products');
       
       
        insert UnitTest.get('Products').getList();

        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Subset')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Set__c').assign('0001')
            .property('Class__c').assign('A')
            .property('Class_Desc__c').assign('Desc')
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            //.property('Bracket1MinQty__c').assign(100)
            //.property('Bracket2MinQty__c').assign(200)
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];

        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show Current and Chain Account Pricing');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Item Level (Expand Sets and Subsets)');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
    
    @isTest
    public static void controller_testNewInternalScenario()
    {
        Integer numberOfEachClassification = 5;
        Integer numberOfAgreementLineItems = 50;

        UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
            .tag('User');

        insert UnitTest.get('User').getList();
        
        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
        .property('RecordTypeId').assign(Schema.SObjectType.Account.getRecordTypeInfosByName().get('Chain Account').getRecordTypeId())
        .tag('Chain Account');
        
        insert UnitTest.get('Chain Account').getList();
        
        UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
            .tag('Account')
            .property('OwnerId').assignFrom('User')
            .property('Natl_Acct_Group_ID__c').assign('NACID')
            .property('Legacy_System_Cd__c').assign('SW')
            .property('Chain_Account__c').assignFrom('Chain Account')
            .property('Zilliant_Active__c').assign('AI');

        insert UnitTest.get('Account').getList();

        UnitTest.addData(SObjectFactory.build(numberOfEachClassification, Servicing_Division__c.SObjectType))
            .tag('Divisions');

        insert UnitTest.get('Divisions').getList();  
        
        UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
            .tag('Agreement')
            .property('Division__c').assignFrom('Divisions')
            .property('AccountId').assignFrom('Account');

        insert UnitTest.get('Agreement').getList();
 
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Subset')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
        .property('productCode').assign('00000003')
        .property('Brand__c').assign('BD')
        .property('Subset__c').assign('0001')
        .property('Set__c').assign('0001')
        .property('System_ID__c').assign('03')
        .tag('Products');

        insert UnitTest.get('Products').getList();
        
        UnitTest.addData(SObjectFactory.build(50, NationalAccountsPricing__c.SObjectType))
            .property('NationalAccountGroupID__c').assign('NACID')
            .property('Class__c').assign('A')
            .property('Name').assign('00000003')
            .property('CompositeKey__c').assign('SW')
            .tag('National');
        
        insert UnitTest.get('National').getList();
        /*
        UnitTest.addData(SObjectFactory.build(1, Customer_Price_List__c.SObjectType))
            .property('Customer_Email__c').assign('me@gmail.com')
            .property('Agreement__c').assignFrom('Agreement')
            .tag('cpl');

        insert UnitTest.get('cpl').getList();
        
        Customer_Price_List__c cpl = (Customer_Price_List__c) UnitTest.get('cpl').getList()[0];
        */
        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Current Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Class__c').assign('A')
            .property('Class_Desc__c').assign('Desc')
            .property('isCurrent__c').assign(True)
            .branch('C QTYPriceBreak|C Normal');

        UnitTest.get('C QTYPriceBreak')
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Current Agreement Line Items').getList();

        UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
            .tag('Future Agreement Line Items')
            .property('zpl__Contract__c').assignFrom('Agreement')
            .property('zpl__Product__c').assignFrom('Products')
            .property('zpl__EffectiveDate__c').assign(Date.today().addDays(3))
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assignFrom('Set Level') 
            .property('Brand__c').assign('BD')
            .property('Subset__c').assign('0001')
            .property('Class__c').assign('A')
            .property('isCurrent__c').assign(True)
            .branch('F QTYPriceBreak|F Normal');

        UnitTest.get('F QTYPriceBreak')
            .property('Net_Price__c').assign(200)
            //.property('Bracket1Value__c').assign(100)
            .property('Bracket2Value__c').assign(200);
            
        insert UnitTest.get('Future Agreement Line Items').getList();

        Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
        User salesRep = (User) UnitTest.get('User').getList()[0];    
         
        PageReference cplPage = Page.cplXLS;
        Test.setCurrentPage(cplPage);

        ApexPages.currentPage().getParameters().put('Agreement__c', agreement.Id);
        //ApexPages.currentPage().getParameters().put('id', cpl.Id);
        ApexPages.currentPage().getParameters().put('RecordTypeId', Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        ApexPages.currentPage().getParameters().put('Sales_Rep__c', salesRep.Id);
        ApexPages.currentPage().getParameters().put('Effective_Date__c', String.valueOf(Date.today()));
        ApexPages.currentPage().getParameters().put('Regional_National_Filter__c', 'Show National Agreement Lines (if any)');
        ApexPages.currentPage().getParameters().put('Purchased_Stocked_Filter__c', 'Show All Agreement Lines');        
        ApexPages.currentPage().getParameters().put('TXN_History__c', 'All');
        ApexPages.currentPage().getParameters().put('Level_Filter__c', 'Agreement Line Level');
        ApexPages.currentPage().getParameters().put('New_Or_Changed_Only__c', 'false');

        Test.startTest();
        CPLXLSController CPLXLSController = new CPLXLSController();
        Test.stopTest();
    }
}