force-app/main/default/objects/Account/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <description>Client Number for 3PL</description>
    <label>Client Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VENDOR_CODE__c.field-meta.xml
<CustomField>
    <fullName>VENDOR_CODE__c</fullName>
    <description>Legacy key field</description>
    <externalId>true</externalId>
    <label>VENDOR_CODE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009TNjAAM</description>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Vendor_Detail__c/Vendor_Detail__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Detail__c/fields/Vendor_Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Client_Number__c</fullName>
    <label>Vendor Client Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Detail__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <externalId>true</externalId>
    <label>Vendor Code</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VendorObjectToVendorAccountTests.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class VendorObjectToVendorAccountTests 
{
    static testMethod void insertOneVendorObject() 
    {
        Vendor_Detail__c vendorObject = new Vendor_Detail__c(Name='Best Buy',
        													 Vendor_Code__c = 'VC-12345',
        													 Vendor_Client_Number__c = '123456');
        
        insert vendorObject;
        
        Id vendorAccountId = [select Id from RecordType where SObjectType = 'Account' and Name = 'Vendor'].Id;
        
        System.assert([select count() 
        			   from Account 
        			   where Name = :vendorObject.Name 
        			   and Vendor_Code__c = :vendorObject.Vendor_Code__c
        			   and Client_Number__c = :vendorObject.Vendor_Client_Number__c
        			   and RecordTypeId = :vendorAccountId] >= 1);         
    }
}