force-app/main/default/objects/Account/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <description>Client Number for 3PL</description>
    <label>Client Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VENDOR_CODE__c.field-meta.xml
<CustomField>
    <fullName>VENDOR_CODE__c</fullName>
    <description>Legacy key field</description>
    <externalId>true</externalId>
    <label>VENDOR_CODE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009TNjAAM</description>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Vendor_Detail__c/Vendor_Detail__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Detail__c/fields/Vendor_Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Client_Number__c</fullName>
    <label>Vendor Client Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Detail__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <externalId>true</externalId>
    <label>Vendor Code</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AIQ_VendorDetailTriggerHandlerTest.cls
@isTest
private class AIQ_VendorDetailTriggerHandlerTest {
    
    @TestSetup
    private static void testSetup() {
        Vendor_Detail__c vendorObject = getVendorDetail();
        insert vendorObject;
    }
    
    @isTest
    private static void insertVendorDetail() {
        Id vendorAccountId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Vendor'].Id;
        
        System.assert([SELECT count() 
        			   FROM Account 
        			   WHERE Name = 'Best Buy' 
        			   AND Vendor_Code__c = 'VC-12345'
        			   AND Client_Number__c = '123456'
        			   AND RecordTypeId = :vendorAccountId] >= 1, 'Should be equal 1');         
    }
    
    @isTest
    private static void updateVendorDetail() {
        Vendor_Detail__c vendorObject = [SELECT Id, Name, Vendor_Code__c 
                                         FROM Vendor_Detail__c 
                                         WHERE Name = 'Best Buy'];
        vendorObject.Name = 'Best Buy is updated';
        update vendorObject;
        
        System.assert([SELECT Name 
        			   FROM Vendor_Detail__c 
        			   WHERE Name = 'Best Buy is updated'].Name == 'Best Buy is updated', 'Should be equal');
    }
    
    @isTest
    private static void deleteVendorDetail() {
        Vendor_Detail__c vendorObject = [SELECT Id, Name, Vendor_Code__c 
                                         FROM Vendor_Detail__c 
                                         WHERE Name = 'Best Buy'];
        vendorObject.Name = 'Best Buy is deleted';
        delete vendorObject;
        
        System.assert([SELECT Id, Name 
        			   FROM Vendor_Detail__c 
        			   WHERE Name = 'Best Buy is deleted'].isEmpty(), 'Should be empty');
        
    }
    
    private static Vendor_Detail__c getVendorDetail() {
        return new Vendor_Detail__c(Name = 'Best Buy',
                                    Vendor_Code__c = 'VC-12345',
                                    Vendor_Client_Number__c = '123456');
    }
}