force-app/main/default/objects/Account/fields/Credit_Action_for_Setup__c.field-meta.xml
<CustomField>
    <fullName>Credit_Action_for_Setup__c</fullName>
    <description>After IT pings credit, they will send back a code to the Prospect record that indicates which next step the rep needs to take.

1 - Credit App is needed
2 - Bill To setup needed
3 - Ship To setup needed
4 - National account - must be handled by NAM team, send email to that box
5 - Other - Email generated to both Rep and the credit group mailbox containing all the details</description>
    <inlineHelpText>1 - Credit App is needed
2 - Bill To setup needed
3 - Ship To setup needed
4 - National account - must be handled by NAM team, send email to that box
5 - Other - Email generated to both Rep and the credit group mailbox containing all the details</inlineHelpText>
    <label>Credit - Action for Setup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Credit_Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the user that is submitting the data to Credit.  Sales Support will most likely initiate the process, so we need to save that user for emails down the line.</description>
    <label>Credit - Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/D_U_N_S__c.field-meta.xml
<CustomField>
    <fullName>D_U_N_S__c</fullName>
    <description>Field being feed from the Datawarehouse for existing customers.  Used as unique key to integrate with Hoover&apos;s. Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>Use the Get D&amp;B button to find this information - do NOT type it in directly</inlineHelpText>
    <label>D-U-N-S Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Domestic_Ultimate_Duns_Number__c.field-meta.xml
<CustomField>
    <fullName>Domestic_Ultimate_Duns_Number__c</fullName>
    <description>Fed in from DW</description>
    <label>Domestic Ultimate Duns Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Equipment_Account__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used on Prospect to identify if the customer needs to be set up as an Equipment account</description>
    <inlineHelpText>Check this box if this customer needs to be set up as an Equipment account</inlineHelpText>
    <label>Equipment Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Ultimate_Duns_Number__c.field-meta.xml
<CustomField>
    <fullName>Global_Ultimate_Duns_Number__c</fullName>
    <description>Fed in from DW</description>
    <label>Global Ultimate Duns Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_Division_Cd__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Division_Cd__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Legacy Division Cd*</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_System_Cd__c.field-meta.xml
<CustomField>
    <fullName>Legacy_System_Cd__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>03 = SFDSW
MA = SFDMA
NU = SFDNU
PC = SFDPC
X = MAX</inlineHelpText>
    <label>Legacy System Cd*</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prospect_Segment__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Segment__c</fullName>
    <description>Require this field on the Prospect account.  Then use a workflow to convert this selection to the proper code for the Segment (F, P, M, L).  This is the code that comes in from DW on Customer Accounts.  Not required on 3PL prospects, as there is no matching Segment for them. 

Any changes to the picklist values should be coordinated with Brainshark administration and should also be made on the following objects - Vendor Detail, Opportunity, Contact, Lead, Work Orders.

1/29/18 - AL - Made this an unrestriced picklist because it was causing validation errors when converting to existing accounts</description>
    <label>Prospect Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facility Solutions</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Publishing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.

Used on Prospect for the rep to fill in before submitting Credit Application</description>
    <label>Sales Rep Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/Credit_Application__c.object-meta.xml
<CustomObject>
    <description>When a customer fills out a credit app via Form Assembly, their responses will be saved on this object</description>
    <label>Credit Application</label>
    <nameField>
        <label>Credit Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credit Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Applications</relationshipLabel>
    <relationshipName>Credit_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_City__c.field-meta.xml
<CustomField>
    <fullName>Bank_City__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Contact__c.field-meta.xml
<CustomField>
    <fullName>Bank_Contact__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Bank_Contact_Email__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Fax__c.field-meta.xml
<CustomField>
    <fullName>Bank_Fax__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Phone__c.field-meta.xml
<CustomField>
    <fullName>Bank_Phone__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_State__c.field-meta.xml
<CustomField>
    <fullName>Bank_State__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank State</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Bank_Zip__c.field-meta.xml
<CustomField>
    <fullName>Bank_Zip__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Bank Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Credit_Action_for_Setup__c.field-meta.xml
<CustomField>
    <fullName>Credit_Action_for_Setup__c</fullName>
    <description>Formula to grab field from Account for displaying on Credit App object
01 - Credit App is needed
02 - Bill To setup needed
03 - Ship To setup needed
04 - National account - must be handled by NAM team, send email to that box
05 - Other - Email generated to both Rep and the credit group mailbox containing all the details</description>
    <formula>TEXT(Account__r.Credit_Action_for_Setup__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>01 - Credit App is needed
02 - Bill To setup needed
03 - Ship To setup needed
04 - National account - must be handled by NAM team, send email to that box
05 - Other - Email generated to both Rep and the credit group mailbox containing all the details</inlineHelpText>
    <label>Credit - Action for Setup</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Credit_Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Credit_Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the person that originally initiated the Customer Setup on the Account</description>
    <label>Credit Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Credit_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Federal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Federal_ID_Number__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Federal ID Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Shipto_City__c.field-meta.xml
<CustomField>
    <fullName>Shipto_City__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Shipto City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Shipto_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipto_Name__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Shipto Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Shipto_Phone__c.field-meta.xml
<CustomField>
    <fullName>Shipto_Phone__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Shipto Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Shipto_Postal_Zip__c.field-meta.xml
<CustomField>
    <fullName>Shipto_Postal_Zip__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Shipto Postal/Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Shipto_Street2__c.field-meta.xml
<CustomField>
    <fullName>Shipto_Street2__c</fullName>
    <description>Shipto_Street__c</description>
    <label>Shipto Street2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Shipto_Street__c.field-meta.xml
<CustomField>
    <fullName>Shipto_Street__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Shipto Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Tax_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Tax_Contact_Name__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Tax Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Tax_Dept_Phone__c.field-meta.xml
<CustomField>
    <fullName>Tax_Dept_Phone__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Tax Dept Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/Tax_Status__c.field-meta.xml
<CustomField>
    <fullName>Tax_Status__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>Tax Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exempt</fullName>
            </value>
            <value>
                <fullName>Taxable</fullName>
            </value>
            <value>
                <fullName>State Exempt - NH, OR, MT, DE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit_Application__c/fields/W_9__c.field-meta.xml
<CustomField>
    <fullName>W_9__c</fullName>
    <description>From Credit Application filled out by customer</description>
    <label>W-9</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditAppTriggerHandlerTest.cls
@isTest
public class CreditAppTriggerHandlerTest {

    @isTest static void insertCreditApp() {

        Test.setMock(HttpCalloutMock.class, new CredAppCalloutMock());
        Test.startTest();

        // Create 50 accounts for test class
        List<Account> accList = new List<Account>();
        for(Integer i = 0 ; i < 50 ; i++){
            Account tempAcc = new Account();
            tempAcc.Name = 'Test Acc ' + i;
            tempAcc.Credit_Action_for_Setup__c = '1';
            tempAcc.D_U_N_S__c = '111';
            tempAcc.Sales_Rep_Code__c = '111';
            tempAcc.OwnerId = UserInfo.getUserId();
            tempAcc.Credit_Submitted_By__c = UserInfo.getUserId();
            tempAcc.Legacy_Division_Cd__c = '111';
            tempAcc.Legacy_System_Cd__c = '03';
            tempAcc.Prospect_Segment__c = 'Print';
            tempAcc.Equipment_Account__c = true;
            tempAcc.Global_Ultimate_Duns_Number__c = '111';
            tempAcc.Domestic_Ultimate_Duns_Number__c = '111';
            tempAcc.D_B_Doing_Business_As__c = 'test';
            accList.add(tempAcc);
        }
        insert accList;
        
        // Create 50 Credit Apps
        List<Credit_Application__c> credList = new List<Credit_Application__c>();
        for(Integer i = 0 ; i < 50 ; i++){
            Credit_Application__c temp = new Credit_Application__c();
            temp.Name = 'Test CredApp ' + i;
            temp.Account__c = accList[i].Id;
            temp.Federal_ID_Number__c = '111';
            temp.W_9__c = 'Yes';
            temp.Bank_Name__c = 'test';
            temp.Bank_Contact__c = 'test';
            temp.Bank_Contact_Email__c = 'test@gmail.com';
            temp.Bank_Account_Number__c = '111';
            temp.Bank_Account_Type__c = 'Checking';
            temp.Bank_City__c = 'Atlanta';
            temp.Bank_State__c = 'GA';
            temp.Bank_Zip__c = '30332';
            temp.Bank_Phone__c = '6784929393';
            temp.Bank_Fax__c = '6784929898';
            temp.Shipto_Name__c = 'test';
            temp.Shipto_Street__c = '123 main st';
            temp.Shipto_Street2__c = 'unit A';
            temp.Shipto_City__c = 'Atlanta';
            temp.Shipto_Postal_Zip__c = '30332';
            temp.Shipto_Phone__c = '6784928776';
            temp.Tax_Status__c = 'Exempt';
            temp.Tax_Contact_Name__c = 'test';
            temp.Tax_Dept_Phone__c = '6784920909';
            temp.Tax_Dept_Email__c = 'test@gmail.com';
            temp.Tax_Exempt_Type__c = 'Resale';
            temp.Tax_Exempt_Products__c = 'Equipment';
            temp.Tax_Exempt_Other__c = 'test';
            temp.Tax_Exempt_States__c = 'Alabama';
            temp.A_P_Contact__c = 'test';
            temp.A_P_Email__c = 'test@gmail.com';
            temp.A_P_Phone__c = '6784927766';
            temp.Invoice_Requirements__c = 'Other';
            temp.Back_Orders_Accepted__c = true;
            temp.Purchase_Order_Required__c = true;
            temp.Method_of_Invoice_Delivery__c = 'Mail';
            temp.Delivery_Email_Address__c = 'test@gmail.com';
            temp.Portal_Website_Address__c = 'www.test.com';
            temp.Shipto_Name__c = 'test';
            temp.Shipto_Street__c = '123 Main St';
            temp.Shipto_Street2__c = 'Unit A';
            temp.Shipto_City__c = 'Atlanta';
            temp.Shipto_State__c = 'GA';
            temp.Shipto_Postal_Zip__c = '30332';
            temp.Shipto_Phone__c = '6784926575';
            temp.Tax_Status__c = 'Exempt';
            temp.Tax_Contact_Name__c = 'test';
            temp.Tax_Dept_Phone__c = '6784929733';
            temp.Tax_Dept_Email__c = 'test@gmail.com';
            temp.Tax_Exempt_Type__c = 'Resale';
            temp.Tax_Exempt_Products__c = 'Equipment';
            temp.Tax_Exempt_Other__c = 'test';
            temp.Tax_Exempt_States__c = 'Alabama';
            credList.add(temp);
        }
        insert credList;

        List<String> creds = new List<String>();
        for (Credit_Application__c cred : credList) {
            creds.add(cred.Id);
        }
        CredAppTriggerHandler.sendCreditAppDataAPI(creds);
        Test.stopTest();

        // Verify we receive a status code from the CredAppCalloutMock class
        Credit_Application__c verifyCred = [SELECT Id, Response_code__c FROM Credit_Application__c WHERE Id IN :creds LIMIT 1];

        system.assertEquals('200', verifyCred.Response_code__c, 'Wrong status code received');
    }
}