force-app/main/default/objects/Account/fields/Customer_Link_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Link_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be updated by System Admins for all accounts that are part of the Customer Link project.  If updated, it allows them to enter and Account Plan for record type Customer Link</description>
    <label>Customer Link Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
<CustomObject>
    <description>Account Plan related to Account.</description>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>Account_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Plan__c/fields/Customer_Link_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Link_Account__c</fullName>
    <formula>Account__r.Customer_Link_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Link Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Plan__c/fields/Financial_year__c.field-meta.xml
<CustomField>
    <fullName>Financial_year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
                <default>true</default>
                <label>2016</label>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Plan__c/fields/Fiscal_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Quarter__c</fullName>
    <inlineHelpText>Select the quarter that this plan represents.</inlineHelpText>
    <label>Fiscal Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q1: Jan-Mar</fullName>
            </value>
            <value>
                <fullName>Q2: Apr-Jun</fullName>
            </value>
            <value>
                <fullName>Q3: Jul-Sept</fullName>
            </value>
            <value>
                <fullName>Q4: Oct-Dec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Plan__c/fields/FY_Sales_Budget__c.field-meta.xml
<CustomField>
    <fullName>FY_Sales_Budget__c</fullName>
    <inlineHelpText>Based on this account plan, this is the amount of sales expected for the year.</inlineHelpText>
    <label>Sales $ Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account_Plan__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>R00N700000021yvCEAQ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Plan__c/fields/Selling_Margin_PCT_Budget__c.field-meta.xml
<CustomField>
    <fullName>Selling_Margin_PCT_Budget__c</fullName>
    <inlineHelpText>Enter the Selling Margin percent of the Sales budget.  Do not enter any decimals - the Selling Margin % Budget field will calculate this number as a percentage.</inlineHelpText>
    <label>Selling Margin % Budget</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.deactivated_user__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountPlanSetOwnerTest.cls
/**
 * Modified By Deepak Chawla on 2019-10-29.
  Added condition to select Account if they have Customer_Link_Account__c field set to True
 */
@isTest(seeAllData = false)
public class AccountPlanSetOwnerTest {
    
    
  /*  @testSetup static void testSetupData() {
       
    }
    */
    static testMethod void setOwnerTest(){ //should cover the insert case
        
         Account acc = new Account();
        acc.Name = 'test';
        acc.Customer_Link_Account__c = true;
        insert acc;
        
        primary_sales_rep__c psr = new primary_sales_rep__c();
        psr.Name = 'sfdc admin';
        psr.Network_ID__c = 'alias';
        insert psr;
        
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'test.test@kasdj.com',
            Username = 'test@amamdakdjbama.com',
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Network_Id__c = 'alias',
            country = 'USA'
        );
        
        insert u;
        
        Account someAccount = [SELECT Name FROM Account WHERE Customer_Link_Account__c  = True LIMIT 1][0];
        List<User> userList = [SELECT Name, Network_Id__c FROM User WHERE IsActive = true and id=:u.id LIMIT 200];
        List<String> userNetIds = new List<String>();
        for(User someUser : userList){
            userNetIds.add(someUser.Network_Id__c);
        }
        system.debug('userNetIds'+userNetIds);
        Primary_Sales_Rep__c someRep = [SELECT Name, Network_ID__c FROM Primary_Sales_Rep__c WHERE Network_Id__c IN :userNetIds LIMIT 1][0];
        Account_Plan__c somePlan = new Account_Plan__c(Name = 'somePlan',
                                              Account__c = someAccount.Id,
                                              Primary_Sales_Rep__c = someRep.Id,
                                              Financial_year__c = '2016',
                                              Fiscal_Quarter__c = 'Q1: Jan-Mar',
                                              Review_Date__c = Date.TODAY(),
                                              FY_Sales_Budget__c = 1,
                                              Selling_Margin_PCT_Budget__c = 1);
        test.starttest();
            insert somePlan;
        test.stoptest();
    }
}