force-app/main/default/objects/Account/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>If this Account is a Customer, changes to the iRep will need to be made in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Program Accounts</relationshipLabel>
    <relationshipName>iRepAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/iRep_Code__c.field-meta.xml
<CustomField>
    <fullName>iRep_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>iRep Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/iRep_Info_Varies__c.field-meta.xml
<CustomField>
    <fullName>iRep_Info_Varies__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to be checked if the Ship Tos under this Bill To have differing iReps across records</description>
    <label>iRep Info Varies</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/iRep_Plan__c.field-meta.xml
<CustomField>
    <fullName>iRep_Plan__c</fullName>
    <inlineHelpText>If this Account is a Customer, changes to the iRep Plan will need to be made in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>i50</fullName>
            </value>
            <value>
                <fullName>i60</fullName>
            </value>
            <value>
                <fullName>i99</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/iRep_Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>iRep_Plan_Code__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>iRep Plan Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>iRep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/iRep_Code__c.field-meta.xml
<CustomField>
    <fullName>iRep_Code__c</fullName>
    <label>iRep Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/iRep_Plan__c.field-meta.xml
<CustomField>
    <fullName>iRep_Plan__c</fullName>
    <formula>IF( iRep_Plan_Code__c =&quot;X&quot;, &quot;i99&quot;, 
IF( iRep_Plan_Code__c =&quot;T&quot;, &quot;i20&quot;, 
IF( iRep_Plan_Code__c =&quot;O&quot;, &quot;i50&quot;, 
IF( iRep_Plan_Code__c =&quot;S&quot;, &quot;i60&quot;, 
IF( iRep_Plan_Code__c =&quot;x&quot;, &quot;i99&quot;, 
IF( iRep_Plan_Code__c =&quot;t&quot;, &quot;i20&quot;, 
IF( iRep_Plan_Code__c =&quot;o&quot;, &quot;i50&quot;, 
IF( iRep_Plan_Code__c =&quot;s&quot;, &quot;i60&quot;, 



&quot;&quot;))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>iRep Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/iRep_Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>iRep_Plan_Code__c</fullName>
    <label>iRep Plan Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShipToServices.cls
public class ShipToServices {

	/*
		used to update the irepinfovaries checkbox on accounts as well as populate account irep and irep plan fields
		this method is used on insert and delete of shiptos
	*/
	public static void updateIRepInfoForAccounts( Map<Id, Ship_To__c> incomingShipTos )
	{
		Map<Id, List<Ship_To__c>> accountIdsToShipTos = groupShipTosByAccountId( incomingShipTos.values() );

		List<Account> accountsToUpdate = getAccountsToUpdate( accountIdsToShipTos.keySet() );

		doUpdateOnAccounts( accountsToUpdate, accountIdsToShipTos );
	}

	/*
		this method takes in a list of shiptos and groups them together in lists based on their accountIds
		used on insert and delete because it does not need to filter out accounts that may not be updated
	*/
	private static Map<Id, List<Ship_To__c>> groupShipTosByAccountId( List<Ship_To__c> shipTos )
	{
		Map<Id, List<Ship_To__c>> accountIdToShipTos = new Map<Id, List<Ship_To__c>>();

		for( Ship_To__c shipTo : shipTos )
        {
            if(shipTo.iRep__c != null){
                if( !accountIdToShipTos.containsKey( shipTo.Bill_To_Account__c ) )
                {
                    accountIdToShipTos.put( shipTo.Bill_To_Account__c, new List<Ship_To__c>() );
                }
                accountIdToShipTos.get( shipTo.Bill_To_Account__c ).add( shipTo );
            }
            
		}

		return accountIdToShipTos;
	}

	/*
		looks through the map of shiptos grouped by accountId and makes a query to find all shiptos beloning to accounts passed in
		then it looks through all the shipto records and keeps track of which ireps have been seen across shiptos for each account
		finally, create an instance of each account for update
	*/
	private static List<Account> getAccountsToUpdate( Set<Id> accountIds )
	{
		Map<Id, Account> accountsToUpdate = new Map<Id, Account>();
		for( Account account : [ SELECT Id, iRep_Info_Varies__c, Primary_Sales_Rep_Name__c, iRep__c, iRep_Code__c,
										( SELECT Id, iRep__c, iRep_Code__c, iRep_Plan__c, iRep_Plan_Code__c FROM Ship_Tos__r ORDER BY LastModifiedDate DESC, Id DESC )
									FROM Account
									WHERE Id IN :accountIds ] )
		{
			Set<Id> iRepIds = new Set<Id>();

			// do not try to find another irep if the code and irep are already filled in
			Boolean iRepfound = account.iRep__c != null && account.iRep_Code__c != null;
            //Made changes to see this will help with trigger error
			//List<Ship_To__c> shipTosForAccount = account.getSObjects( 'Ship_Tos__r' );
			//for( Ship_To__c shipTo : shipTosForAccount )
			for( Ship_To__c shipTo : Account.Ship_Tos__r )
			{
				if( !iRepFound && account.Primary_Sales_Rep_Name__c != null
					&& shipTo.iRep__c == account.Primary_Sales_Rep_Name__c && account.iRep__c != shipTo.iRep__c )
				{
					account.iRep__c = account.Primary_Sales_Rep_Name__c;
					account.iRep_Plan__c = shipTo.iRep_Plan__c;
					account.iRep_Plan_Code__c = shipTo.iRep_Plan_Code__c;
					iRepfound = true;
					accountsToUpdate.put( account.Id, account );
				}

				iRepIds.add( shipTo.iRep__c );
			}
			if( !iRepfound )
			{
				//get the latest shipTo from the list and use that shipTos irep
				//Changed the code to see if trigger is fixed.
				//Ship_To__c tempShipTo = getLatestShipToForAccount( shipTosForAccount );
                Ship_To__c tempShipTo = getLatestShipToForAccount( Account.Ship_Tos__r);
               
				if(tempShipTo != null && account.iRep__c != tempShipTo.iRep__c)
				{
					account.iRep__c = tempShipTo.iRep__c;
					account.iRep_Plan__c = tempShipTo.iRep_Plan__c;
					account.iRep_Plan_Code__c = tempShipTo.iRep_Plan_Code__c;
					accountsToUpdate.put( account.Id, account );
				}
			}

			Boolean shipTosHaveMoreThanOneIRep = iRepIds.size() > 1;
			if( account.iRep_Info_Varies__c != shipTosHaveMoreThanOneIRep )
			{
				account.iRep_Info_Varies__c = shipTosHaveMoreThanOneIRep;
				accountsToUpdate.put( account.Id, account );
			}
		}

		return accountsToUpdate.values();
	}

	private static Ship_To__c getLatestShipToForAccount(List<Ship_To__c> allShipToForAccount)
	{
		//get the latest shipTo from this list
		for(Ship_To__c shipTo : allShipToForAccount)
		{
			if(shipTo.iRep__c != null)
				return shipTo;
		}
		return null;
	}

	/*
		executes dml for any accounts passed in, needs to take a map referencing trigger.new records for error handling
	*/
	private static void doUpdateOnAccounts( List<Account> accountsToUpdate, Map<Id, List<Ship_To__c>> accountIdToShipToMap )
	{
		if( !accountsToUpdate.isEmpty() )
		{
			try
			{
				update accountsToUpdate;
			}
			catch( System.DmlException ex )
			{
				for( Integer index = 0; index < ex.getNumDml(); index++ )
				{
					Id errorAccountId = accountsToUpdate[ ex.getDmlIndex( index ) ].Id;
					for( Ship_To__c errorShipTo : accountIdToShipToMap.get( errorAccountId ) )
					{
						errorShipTo.addError( ex.getDmlMessage( index ) );
					}
				}
			}
		}
	}
}