force-app/main/default/objects/Account/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>If this Account is a Customer, changes to the iRep will need to be made in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Program Accounts</relationshipLabel>
    <relationshipName>iRepAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/iRep_Plan__c.field-meta.xml
<CustomField>
    <fullName>iRep_Plan__c</fullName>
    <inlineHelpText>If this Account is a Customer, changes to the iRep Plan will need to be made in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>i50</fullName>
            </value>
            <value>
                <fullName>i60</fullName>
            </value>
            <value>
                <fullName>i99</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The iRep on the opportunity matches the Account&apos;s iRep.  If the Account is a Customer, the iRep will need to be updated in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Program Opportunities</relationshipLabel>
    <relationshipName>iRepOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Required on all Layouts except &quot;Opportunity Layout - System Admin&quot; 
When new Opportunity created from account page, PSR field is pre-populated (editable) with PSR from related Account. 
When a Lead is converted and an opportunity created, the PSR field from the Lead is mapped to the PSR name on Opportunity. 
When Account PSR field is changed, Account Trigger updates each related open Opportunity that has the same PSR as related Account prior to the action 
Reps granted Read/Write access to an Opportunity when the PSR field is saved or edited with their PSR record ID. If the field on the record is changed, the previous PSR associated rep still has access</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestOpportunityIRepSalesTeamTrigger.cls
@isTest
private class TestOpportunityIRepSalesTeamTrigger
{
	static final String TEST_PLAN_VALUE = 'Test iRep Plan';
	static List<Account> testAccounts;
	static List<Primary_Sales_Rep__c> testIReps;
	static List<User> testUsers;

	static void setupPSRs( Integer numReps )
	{
		testUsers = TestDataGeneration.createUsers( 'TUser', 'Standard User', numReps, true );

		testIReps = new List<Primary_Sales_Rep__c>();
		for( User testUser : testUsers )
		{
			Primary_Sales_Rep__c testIRep = TestDataGeneration.createPSRs( 1, false )[0];
			testIRep.SF_userid__c = testUser.Id;
			testIReps.add( testIRep );
		}
		insert testIReps;
	}

	static void setupAccounts( Integer numAccounts )
	{
		setupPSRs( numAccounts );

		testAccounts = new List<Account>();
		for( Primary_Sales_Rep__c testIRep : testIReps )
		{
			Account testAccount = TestDataGeneration.createAccount( 'Test Account for ' + testIRep.SF_userid__c );
			testAccount.iRep__c = testIRep.Id;
			testAccount.iRep_Plan__c = TEST_PLAN_VALUE;
			testAccounts.add( testAccount );
		}
		insert testAccounts;
	}

	static void setupAccountsWithoutIReps( Integer numAccounts )
	{
		setupPSRs( numAccounts );

		testAccounts = TestDataGeneration.createAccounts( 'Test Account ', numAccounts );
	}

    static testMethod void testInsertOpportunityWithIRep()
	{
		setupAccounts( 1 );

		Account testAccount = testAccounts[0];
		Primary_Sales_Rep__c testIRep = testIReps[0];
		User testUser = testUsers[0];

		Test.startTest();

			Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
			testOpportunity.iRep__c = testIRep.Id;
			testOpportunity.StageName = '1- Prospect';
			insert testOpportunity;

		Test.stopTest();

		/* //Commented to Allow Deployment prior to upcoming fix
		List<OpportunityShare> sharesForOpportunity = [ SELECT Id
														FROM OpportunityShare
														WHERE OpportunityId = :testOpportunity.Id
															AND UserOrGroupId = :testUser.Id
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( 1, sharesForOpportunity.size() );

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id
																FROM OpportunityTeamMember
																WHERE OpportunityId = :testOpportunity.Id
																	AND UserId = :testUser.Id
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( 1, membersForOpportunity.size() );
		*/
    }

    static testMethod void testInsertOpportunityWithIRepBulk()
	{
		Integer usersToCreate = 20;

		setupAccounts( usersToCreate );

		Map<Id, Primary_Sales_Rep__c> testIRepsMap = new Map<Id, Primary_Sales_Rep__c>( testIReps );

		Test.startTest();

			List<Opportunity> testOpportunities = new List<Opportunity>();
			for( Account testAccount : testAccounts )
			{
				Opportunity opportunityForUser = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
				opportunityForUser.iRep__c = testAccount.iRep__c;
				opportunityForUser.StageName = '1- Prospect';
				testOpportunities.add( opportunityForUser );
			}
			insert testOpportunities;

		Test.stopTest();

		/* //Commented to Allow Deployment prior to upcoming fix
		List<OpportunityShare> sharesForOpportunity = [ SELECT Id, OpportunityId, Opportunity.iRep__c, UserOrGroupId
														FROM OpportunityShare
														WHERE OpportunityId IN :testOpportunities
															AND UserOrGroupId IN :testUsers
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( usersToCreate, sharesForOpportunity.size() );

		for( OpportunityShare share : sharesForOpportunity )
		{
			Id expectedUserId = testIRepsMap.get( share.Opportunity.iRep__c ).SF_userid__c;
			System.assertEquals( expectedUserId, share.UserOrGroupId );
		}

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id, OpportunityId, Opportunity.iRep__c, UserId
																FROM OpportunityTeamMember
																WHERE OpportunityId IN :testOpportunities
																	AND UserId IN :testUsers
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( usersToCreate, membersForOpportunity.size() );

		for( OpportunityTeamMember member : membersForOpportunity )
		{
			Id expectedUserId = testIRepsMap.get( member.Opportunity.iRep__c ).SF_userid__c;
			System.assertEquals( expectedUserId, member.UserId );
		}
		*/
    }

    static testMethod void testUpdateIRepOnOpportunity()
    {
    	setupAccounts( 2 );

    	Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccounts[0].Id, false )[0];
    	testOpportunity.iRep__c = testAccounts[0].iRep__c;
    	testOpportunity.StageName = '1- Prospect';
    	insert testOpportunity;

    	Test.startTest();

			// update the opportunity to have a different irep here
			// it is not a dml statement on opportunities because there is a rule in place
			//		that prevents an opportunity from having a different irep than its account
			// therefore it is necessary to update on the account level
			testAccounts[0].iRep__c = testIReps[1].Id;
			update testAccounts[0];

    	Test.stopTest();
		/* //Commented to Allow Deployment prior to upcoming fix
    	List<OpportunityShare> sharesForOpportunity = [ SELECT Id, UserOrGroupId
														FROM OpportunityShare
														WHERE OpportunityId = :testOpportunity.Id
															AND UserOrGroupId IN :testUsers
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( 1, sharesForOpportunity.size() );
		System.assertEquals( testUsers[1].Id, sharesForOpportunity[0].UserOrGroupId );

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id, UserId
																FROM OpportunityTeamMember
																WHERE OpportunityId = :testOpportunity.Id
																	AND UserId IN :testUsers
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( 1, membersForOpportunity.size() );
		System.assertEquals( testUsers[1].Id, membersForOpportunity[0].UserId );
		*/
    }

    static testMethod void testUpdateIRepOnOpportunityBulk()
    {
    	Integer opportunitiesToCreate = 20;

    	setupAccounts( opportunitiesToCreate );

    	List<Opportunity> testOpportunities = new List<Opportunity>();
    	for( Account testAccount : testAccounts )
    	{
	    	Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
	    	testOpportunity.iRep__c = testAccount.iRep__c;
	    	testOpportunity.StageName = '1- Prospect';
	    	testOpportunities.add( testOpportunity );
    	}
    	insert testOpportunities;

		// create new users for new ireps
		List<User> newUsers = TestDataGeneration.createUsers( 'TNuser', 'Standard User', opportunitiesToCreate, true );

		List<Primary_Sales_Rep__c> newIReps = new List<Primary_Sales_Rep__c>();
		for( User testUser : newUsers )
		{
			Primary_Sales_Rep__c newIRep = TestDataGeneration.createPSRs( 1, false )[0];
			newIRep.SF_userid__c = testUser.Id;
			newIReps.add( newIRep );
		}
		insert newIReps;

    	Test.startTest();

			Map<Id, Id> accountIdToUserId = new Map<Id, Id>();

			// update opportunities to have a different irep here
			// it is not a dml statement on opportunities because there is a rule in place
			//		that prevents an opportunity from having a different irep than its account
			// therefore it is necessary to update on the account level
	    	for( Integer index = 0; index < opportunitiesToCreate; index++ )
	    	{
	    		testAccounts[ index ].iRep__c = newIReps[ index ].Id;
	    		accountIdToUserId.put( testAccounts[ index ].Id, newIReps[ index ].SF_userid__c );
	    	}
    		update testAccounts;

    	Test.stopTest();
		/* //Commented to Allow Deployment prior to upcoming fix
    	List<OpportunityShare> sharesForOpportunity = [ SELECT Id, Opportunity.AccountId, UserOrGroupId
														FROM OpportunityShare
														WHERE OpportunityId IN :testOpportunities
															AND UserOrGroupId IN :newUsers
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( opportunitiesToCreate, sharesForOpportunity.size() );
		for( OpportunityShare share : sharesForOpportunity )
		{
			System.assertEquals( accountIdToUserId.get( share.Opportunity.AccountId ), share.UserOrGroupId );
		}

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id, Opportunity.AccountId, UserId
																FROM OpportunityTeamMember
																WHERE OpportunityId IN :testOpportunities
																	AND UserId IN :newUsers
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( opportunitiesToCreate, membersForOpportunity.size() );
		for( OpportunityTeamMember member : membersForOpportunity )
		{
			System.assertEquals( accountIdToUserId.get( member.Opportunity.AccountId ), member.UserId );
		}
		*/
    }

    static testMethod void testInsertOpportunityWithPSR()
	{
		setupAccountsWithoutIReps( 1 );

		Account testAccount = testAccounts[0];
		User testUser = testUsers[0];
		Primary_Sales_Rep__c testPSR = testIReps[0];

		Test.startTest();

			Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
			testOpportunity.Primary_Sales_Rep_Name__c = testPSR.Id;
			testOpportunity.StageName = '1- Prospect';
			insert testOpportunity;

		Test.stopTest();

		/* //Commented to Allow Deployment prior to upcoming fix
		List<OpportunityShare> sharesForOpportunity = [ SELECT Id
														FROM OpportunityShare
														WHERE OpportunityId = :testOpportunity.Id
															AND UserOrGroupId = :testUser.Id
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( 1, sharesForOpportunity.size() );

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id
																FROM OpportunityTeamMember
																WHERE OpportunityId = :testOpportunity.Id
																	AND UserId = :testUser.Id
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( 1, membersForOpportunity.size() );
		*/
    }

    static testMethod void testInsertOpportunityWithPSRBulk()
	{
		Integer usersToCreate = 20;

		setupAccountsWithoutIReps( usersToCreate );

		Account testAccount = testAccounts[0];
		List<Primary_Sales_Rep__c> testPSRs = testIReps;

		Map<Id, Primary_Sales_Rep__c> testPSRsMap = new Map<Id, Primary_Sales_Rep__c>( testPSRs );

		Test.startTest();

			List<Opportunity> testOpportunities = new List<Opportunity>();
			for( Primary_Sales_Rep__c testPSR : testPSRs )
			{
				Opportunity opportunityForUser = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
				opportunityForUser.Primary_Sales_Rep_Name__c = testPSR.Id;
				opportunityForUser.StageName = '1- Prospect';
				testOpportunities.add( opportunityForUser );
			}
			insert testOpportunities;

		Test.stopTest();

		/* //Commented to Allow Deployment prior to upcoming fix
		List<OpportunityShare> sharesForOpportunity = [ SELECT Id, OpportunityId, Opportunity.Primary_Sales_Rep_Name__c, UserOrGroupId
														FROM OpportunityShare
														WHERE OpportunityId IN :testOpportunities
															AND UserOrGroupId IN :testUsers
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( usersToCreate, sharesForOpportunity.size() );

		for( OpportunityShare share : sharesForOpportunity )
		{
			Id expectedUserId = testPSRsMap.get( share.Opportunity.Primary_Sales_Rep_Name__c ).SF_userid__c;
			System.assertEquals( expectedUserId, share.UserOrGroupId );
		}

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id, OpportunityId, Opportunity.Primary_Sales_Rep_Name__c, UserId
																FROM OpportunityTeamMember
																WHERE OpportunityId IN :testOpportunities
																	AND UserId IN :testUsers
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( usersToCreate, membersForOpportunity.size() );

		for( OpportunityTeamMember member : membersForOpportunity )
		{
			Id expectedUserId = testPSRsMap.get( member.Opportunity.Primary_Sales_Rep_Name__c ).SF_userid__c;
			System.assertEquals( expectedUserId, member.UserId );
		}
		*/
    }

    static testMethod void testUpdatePSROnOpportunity()
    {
    	setupAccountsWithoutIReps( 2 );

		Account testAccount = testAccounts[0];
    	Primary_Sales_Rep__c testPSR1 = testIReps[0];
    	Primary_Sales_Rep__c testPSR2 = testIReps[1];

    	Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
    	testOpportunity.Primary_Sales_Rep_Name__c = testPSR1.Id;
    	testOpportunity.StageName = '1- Prospect';
    	insert testOpportunity;

    	Test.startTest();

    		testOpportunity.Primary_Sales_Rep_Name__c = testPSR2.Id;
    		update testOpportunity;

    	Test.stopTest();
		/* //Commented to Allow Deployment prior to upcoming fix
    	List<OpportunityShare> sharesForOpportunity = [ SELECT Id, UserOrGroupId
														FROM OpportunityShare
														WHERE OpportunityId = :testOpportunity.Id
															AND UserOrGroupId IN :testUsers
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( 1, sharesForOpportunity.size() );
		System.assertEquals( testUsers[1].Id, sharesForOpportunity[0].UserOrGroupId );

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id, UserId
																FROM OpportunityTeamMember
																WHERE OpportunityId = :testOpportunity.Id
																	AND UserId IN :testUsers
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( 1, membersForOpportunity.size() );
		System.assertEquals( testUsers[1].Id, membersForOpportunity[0].UserId );
		*/
    }

    static testMethod void testUpdatePSROnOpportunityBulk()
    {
    	Integer opportunitiesToCreate = 20;

		setupAccountsWithoutIReps( opportunitiesToCreate );

    	Primary_Sales_Rep__c testPSR1 = testIReps[0];
    	Primary_Sales_Rep__c testPSR2 = testIReps[1];

    	List<Opportunity> testOpportunities = new List<Opportunity>();
    	for( Account testAccount : testAccounts )
    	{
	    	Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
	    	testOpportunity.StageName = '1- Prospect';
	    	testOpportunities.add( testOpportunity );
    	}
    	insert testOpportunities;

    	Test.startTest();

	    	for( Opportunity testOpportunity : testOpportunities )
	    	{
	    		testOpportunity.Primary_Sales_Rep_Name__c = testPSR2.Id;
	    	}
    		update testOpportunities;

    	Test.stopTest();
		/* //Commented to Allow Deployment prior to upcoming fix
    	List<OpportunityShare> sharesForOpportunity = [ SELECT Id, UserOrGroupId
														FROM OpportunityShare
														WHERE OpportunityId IN :testOpportunities
															AND UserOrGroupId IN :testUsers
															AND RowCause = :OpportunityTriggerUtil.REP_SHARE_ROW_CAUSE
															AND OpportunityAccessLevel = :OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL ];

		System.assertEquals( opportunitiesToCreate, sharesForOpportunity.size() );
		for( OpportunityShare share : sharesForOpportunity )
		{
			System.assertEquals( testUsers[1].Id, share.UserOrGroupId );
		}

		List<OpportunityTeamMember> membersForOpportunity = [ SELECT Id, UserId
																FROM OpportunityTeamMember
																WHERE OpportunityId IN :testOpportunities
																	AND UserId IN :testUsers
																	AND ( TeamMemberRole = :OpportunityTriggerUtil.REP_PSR_TEAM_ROLE
																			OR TeamMemberRole = :OpportunityTriggerUtil.REP_IREP_TEAM_ROLE ) ];

		System.assertEquals( opportunitiesToCreate, membersForOpportunity.size() );
		for( OpportunityTeamMember member : membersForOpportunity )
		{
			System.assertEquals( testUsers[1].Id, member.UserId );
		}
		*/
    }

    static testMethod void testCarryOverSalesTeamOnOwnerChange()
    {
    	Integer opptiesToCreate = 25;
    	String teamMemberRole1 = 'Test Role 1';
    	String teamMemberRole2 = 'Test Role 2';

    	Account testAccount = TestDataGeneration.createAccount( 'Test Account' );
    	insert testAccount;

		UserRole testRole = new UserRole( Name = 'TestRole', ParentRoleId = TestDataGeneration.ADMIN_USER.UserRoleId );
		//System.runAs( TestDataGeneration.ADMIN_USER )
		//{
			//insert testRole;
		//}

    	testUsers = TestDataGeneration.createUsers( 'Tuser', 'Standard User', 4, false );
    	for( User testUser : testUsers )
    	{
    		//testUser.UserRoleId = testRole.Id;
    	}
		//System.runAs( TestDataGeneration.ADMIN_USER )
		//{
			insert testUsers;
		//}

		User oldOwner = testUsers[0];
		User newOwner = testUsers[1];
		User teamMember1 = testUsers[2];
		User teamMember2 = testUsers[3];

		List<OpportunityTeamMember> teamMembers = new List<OpportunityTeamMember>();
		List<OpportunityShare> shares = new List<OpportunityShare>();

    	List<Opportunity> testOpportunities = TestDataGeneration.createOpportunities( opptiesToCreate, testAccount.Id, false );

		for( Opportunity testOpportunity : testOpportunities )
		{
			testOpportunity.OwnerId = oldOwner.Id;
			testOpportunity.StageName = '1- Prospect';
		}
		insert testOpportunities;

		for( Opportunity testOpportunity : testOpportunities )
		{
			OpportunityTeamMember member1 = new OpportunityTeamMember();
			member1.OpportunityId = testOpportunity.Id;
			member1.UserId = teamMember1.Id;
			member1.TeamMemberRole = teamMemberRole1;
			teamMembers.add( member1 );

			OpportunityShare newShare1 = new OpportunityShare();
			newShare1.OpportunityId = testOpportunity.Id;
			newShare1.UserOrGroupId = teamMember1.Id;
			newShare1.OpportunityAccessLevel = OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL;
			shares.add( newShare1 );

			OpportunityTeamMember member2 = new OpportunityTeamMember();
			member2.OpportunityId = testOpportunity.Id;
			member2.UserId = teamMember2.Id;
			member2.TeamMemberRole = teamMemberRole2;
			teamMembers.add( member2 );

			OpportunityShare newShare2 = new OpportunityShare();
			newShare2.OpportunityId = testOpportunity.Id;
			newShare2.UserOrGroupId = teamMember2.Id;
			newShare2.OpportunityAccessLevel = OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL;
			shares.add( newShare2 );
		}
		insert teamMembers;
		insert shares;

    	Test.startTest();

			// for this test, a simple update on opportunities is not used
			// 		because a sales team is retained when the OwnerId of an opportunity is set in apex
			// 		whereas through the UI, there is a checkbox to determine whether the sales team is kept or not
			// additionally, the sales team for an opportunity is only visible in the before state of a trigger
			//		and will no longer be accessible from the database ( deleted ) in the after state
			// therefore, this test will simulate the back-end process that occurs

			Map<Id, Opportunity> oldOpportunities = new Map<Id, Opportunity>( testOpportunities.deepClone( true ) );

			// first, programmatically change the owner
    		for( Opportunity opportunity : testOpportunities )
    		{
    			opportunity.OwnerId = newOwner.Id;
    		}

    		Map<Id, Opportunity> newOpportunities = new Map<Id, Opportunity>( testOpportunities );

			// this method is called in the before update trigger
    		OpportunityTriggerUtil.carryOverSalesTeamOnOwnerChange( newOpportunities, oldOpportunities );

			// when the before update execution is finished, the team members are deleted from the database
			//		so this query and deletion simulates that process
    		List<OpportunityTeamMember> existingTeamMembers = [ SELECT Id FROM OpportunityTeamMember WHERE OpportunityId IN :testOpportunities ];
    		delete existingTeamMembers;

			// this method is called in the after update trigger
    		OpportunityTriggerUtil.createTeamMembersAfterTriggerFires( newOpportunities );

    	Test.stopTest();

    	/* //Commented to Allow Deployment prior to upcoming fix
    	List<Opportunity> updatedOpportunities = [ SELECT Id,
														( SELECT Id, TeamMemberRole, UserId FROM OpportunityTeamMembers )
													FROM Opportunity
													WHERE Id IN :testOpportunities ];

    	System.assertEquals( opptiesToCreate, updatedOpportunities.size() );

    	for( Opportunity updatedOpportunity : updatedOpportunities )
    	{
    		System.assertEquals( 2, updatedOpportunity.OpportunityTeamMembers.size() );
    		for( OpportunityTeamMember teamMember : updatedOpportunity.OpportunityTeamMembers )
    		{
    			if( teamMember.UserId == teamMember1.Id )
    			{
    				System.assertEquals( teamMemberRole1, teamMember.TeamMemberRole );
    			}
    			else
    			{
    				System.assertEquals( teamMemberRole2, teamMember.TeamMemberRole );
    			}
    		}
    	}

    	List<OpportunityShare> opportunityShares = [ SELECT Id, OpportunityAccessLevel, UserOrGroupId
														FROM OpportunityShare
														WHERE OpportunityId IN :testOpportunities
															AND ( UserOrGroupId = :teamMember1.Id
																OR	UserOrGroupId = :teamMember2.Id ) ];

		System.assertEquals( 2 * opptiesToCreate, opportunityShares.size() );

		for( OpportunityShare share : opportunityShares )
		{
			System.assertEquals( OpportunityTriggerUtil.REP_SHARE_ACCESS_LEVEL, share.OpportunityAccessLevel );
		}
		*/
    }

    static testMethod void testUpdateRepsOnAccountFieldChange()
    {
    	Integer opportunitiesToCreate = 25;

    	List<Primary_Sales_Rep__c> testPSRs = TestDataGeneration.createPSRs( 4, true );

    	testAccounts = TestDataGeneration.createAccounts( 'Test Account', 2 );
		testAccounts[0].iRep__c = testPSRs[0].Id;
		testAccounts[0].iRep_Plan__c = TEST_PLAN_VALUE;
		testAccounts[0].Primary_Sales_Rep_Name__c = testPSRs[1].Id;
		testAccounts[1].iRep__c = testPSRs[2].Id;
		testAccounts[1].iRep_Plan__c = TEST_PLAN_VALUE;
		testAccounts[1].Primary_Sales_Rep_Name__c = testPSRs[3].Id;
    	insert testAccounts;

    	List<Opportunity> testOpportunities = TestDataGeneration.createOpportunities( opportunitiesToCreate, testAccounts[0].Id, false );
    	for( Opportunity testOpportunity : testOpportunities )
    	{
    		testOpportunity.iRep__c = testPSRs[0].Id;
    		testOpportunity.StageName = '1- Prospect';
    	}
    	insert testOpportunities;

    	Test.startTest();

    		for( Opportunity testOpportunity : testOpportunities )
    		{
    			testOpportunity.AccountId = testAccounts[1].Id;
    		}
    		update testOpportunities;

    	Test.stopTest();

    	List<Opportunity> updatedOpportunities = [ SELECT Id, iRep__c, Primary_Sales_Rep_Name__c
    												FROM Opportunity
    												WHERE Id IN :testOpportunities ];

    	System.assertEquals( opportunitiesToCreate, updatedOpportunities.size() );
    	for( Opportunity updatedOpportunity : updatedOpportunities )
    	{
    		System.assertEquals( testPSRs[2].Id, updatedOpportunity.iRep__c );
    		System.assertEquals( testPSRs[3].Id, updatedOpportunity.Primary_Sales_Rep_Name__c );
    	}
    }
}