force-app/main/default/objects/Account/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>If this Account is a Customer, changes to the iRep will need to be made in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Program Accounts</relationshipLabel>
    <relationshipName>iRepAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/iRep_Info_Varies__c.field-meta.xml
<CustomField>
    <fullName>iRep_Info_Varies__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to be checked if the Ship Tos under this Bill To have differing iReps across records</description>
    <label>iRep Info Varies</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/iRep_Plan__c.field-meta.xml
<CustomField>
    <fullName>iRep_Plan__c</fullName>
    <inlineHelpText>If this Account is a Customer, changes to the iRep Plan will need to be made in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>i50</fullName>
            </value>
            <value>
                <fullName>i60</fullName>
            </value>
            <value>
                <fullName>i99</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Needs_Batch_Processing__c.field-meta.xml
<CustomField>
    <fullName>Needs_Batch_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Needs Batch Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Previous_iRep_ID__c.field-meta.xml
<CustomField>
    <fullName>Previous_iRep_ID__c</fullName>
    <label>Previous iRep ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The iRep on the opportunity matches the Account&apos;s iRep.  If the Account is a Customer, the iRep will need to be updated in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Program Opportunities</relationshipLabel>
    <relationshipName>iRepOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/iRep_Plan_Stamp__c.field-meta.xml
<CustomField>
    <fullName>iRep_Plan_Stamp__c</fullName>
    <label>iRep Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>i20</fullName>
            </value>
            <value>
                <fullName>i50</fullName>
            </value>
            <value>
                <fullName>i60</fullName>
            </value>
            <value>
                <fullName>i99</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Required on all Layouts except &quot;Opportunity Layout - System Admin&quot; 
When new Opportunity created from account page, PSR field is pre-populated (editable) with PSR from related Account. 
When a Lead is converted and an opportunity created, the PSR field from the Lead is mapped to the PSR name on Opportunity. 
When Account PSR field is changed, Account Trigger updates each related open Opportunity that has the same PSR as related Account prior to the action 
Reps granted Read/Write access to an Opportunity when the PSR field is saved or edited with their PSR record ID. If the field on the record is changed, the previous PSR associated rep still has access</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestSyncOpportunityRepsToAccountBatch.cls
@isTest
private class TestSyncOpportunityRepsToAccountBatch {

	static final String ACCOUNT_ACCESS_LEVEL = 'Edit';
	static final String OPPTY_ACCESS_LEVEL = 'Edit';
	static final String TEST_SUBORDINATE_ROLE_NAME = 'Underling';
	static final String TEST_SUPERIOR_ROLE_NAME = 'Overling';

	static User testUser;
	static User testOwner;
	static UserRole subordinateRole;
	static UserRole superiorRole;

	static void setupRoles()
	{
		testUser = TestDataGeneration.createUser( 'TUser', 'Standard User', false );
		testOwner = TestDataGeneration.createUser( 'TOwner', 'Standard User', false );

		//System.runAs( TestDataGeneration.ADMIN_USER )
		//{
			superiorRole = new UserRole( Name = TEST_SUPERIOR_ROLE_NAME );
			//insert superiorRole;

			subordinateRole = new UserRole( Name = TEST_SUBORDINATE_ROLE_NAME, ParentRoleId = superiorRole.Id );
			//insert subordinateRole;

			//testUser.UserRoleId = subordinateRole.Id;
			//testOwner.UserRoleId = superiorRole.Id;

			insert new List<User>{ testUser, testOwner };
		///}
	}

    static testMethod void testNonHierarchyUserCannotEditSalesTeam()
	{
		setupRoles();

		Opportunity testOpportunity;
		Account testAccount = TestDataGeneration.createAccount( 'Test Account' );

		//System.runAs( TestDataGeneration.ADMIN_USER )
		//{
			testAccount.OwnerId = testOwner.Id;
			insert testAccount;

			testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, false )[0];
			testOpportunity.OwnerId = testOwner.Id;
			testOpportunity.StageName = '1- Prospect';
			insert testOpportunity;

			AccountShare acctShare = TestDataGeneration.createAccountShare( testUser.Id, testAccount.Id, ACCOUNT_ACCESS_LEVEL, OPPTY_ACCESS_LEVEL );
			insert acctShare;
		//}

		Primary_Sales_Rep__c newPSR = TestDataGeneration.createPSRs( 1, false )[0];
		newPSR.SF_userid__c = testUser.Id;
		insert newPSR;

		Test.startTest();

			testAccount.Primary_Sales_Rep_Name__c = newPSR.Id;
			System.runAs( testUser )
			{
				try
				{
					update testAccount;
				}
				catch( System.DmlException ex )
				{
					//System.assert( false, 'Dml exceptions in this situation should have been caught' );
				}
			}

		Test.stopTest();

		Account updatedAccount = [ SELECT Id, Needs_Batch_Processing__c FROM Account WHERE Id = :testAccount.Id LIMIT 1 ];

		// assert sync flag is set
		//System.assert( updatedAccount.Needs_Batch_Processing__c );
    }

    static testMethod void testExecute()
    {
    	setupRoles();

    	Integer accountsToCreate = 10;
    	Integer opportunitiesPerAccount = 5;

    	Primary_Sales_Rep__c newPSR = TestDataGeneration.createPSRs( 1, false )[0];
		newPSR.SF_userid__c = testUser.Id;
		insert newPSR;

    	List<Account> testAccounts = TestDataGeneration.createAccounts( 'Test Accounts ', accountsToCreate );
    	for( Account testAccount : testAccounts )
    	{
    		testAccount.Primary_Sales_Rep_Name__c = newPSR.Id;
    		testAccount.Needs_Batch_Processing__c = true;
    		testAccount.OwnerId = testOwner.Id;
    	}

    	List<Opportunity> testOpportunities = new List<Opportunity>();

    	//System.runAs( TestDataGeneration.ADMIN_USER )
    	//{
	    	insert testAccounts;

	    	List<AccountShare> newShares = new List<AccountShare>();
	    	for( Account testAccount : testAccounts )
	    	{
	    		for( Opportunity testOpportunity : TestDataGeneration.createOpportunities( opportunitiesPerAccount, testAccount.Id, false ) )
	    		{
	    			testOpportunity.OwnerId = testOwner.Id;
	    			testOpportunities.add( testOpportunity );
	    		}

				AccountShare acctShare = TestDataGeneration.createAccountShare( testUser.Id, testAccount.Id, ACCOUNT_ACCESS_LEVEL, OPPTY_ACCESS_LEVEL );
				newShares.add( acctShare );
	    	}
	    	insert testOpportunities;
	    	insert newShares;
    	
        //}

		Test.startTest();

			SyncOpportunityRepsToAccountBatch job = new SyncOpportunityRepsToAccountBatch();
			job.query += ' AND Id IN ' + flattenAccountListForQuery( testAccounts ) + ' LIMIT 200 ';

			Database.executeBatch( job );

		Test.stopTest();

		List<Opportunity> updatedOpportunities = [ SELECT Id, Primary_Sales_Rep_Name__c, Account.Needs_Batch_Processing__c,
														( SELECT Id FROM OpportunityTeamMembers WHERE UserId = :testUser.Id )
													FROM Opportunity
													WHERE Id IN :testOpportunities ];

		System.assertEquals( testOpportunities.size(), updatedOpportunities.size() );

		for( Opportunity updatedOpportunity : updatedOpportunities )
		{
			System.assert( !updatedOpportunity.Account.Needs_Batch_Processing__c );
			//System.assertEquals( 1, updatedOpportunity.OpportunityTeamMembers.size() );
			System.assertEquals( newPSR.Id, updatedOpportunity.Primary_Sales_Rep_Name__c );
		}

    }

	/*
		when accounts change ireps, only opportunities under the account that have the same
		value for its irep should be changed as well
	*/
	static testMethod void testOnlyUpdateOpportunitiesWithSameIRepAsAccount()
	{
		Integer accountsToCreate = 5;
    	Integer opportunitiesWithSameIRep = 4;
    	Integer opportunitiesWithDiffIRep = 4;
    	final String PLAN_STAMP_VALUE = 'TEST PLAN';

    	List<Primary_Sales_Rep__c> iReps = TestDataGeneration.createPSRs( 3, true );
    	Primary_Sales_Rep__c oldAccountIRep = iReps[0];
    	Primary_Sales_Rep__c newAccountIRep = iReps[1];
    	Primary_Sales_Rep__c alternativeOpportunityIRep = iReps[2];

    	List<Account> testAccounts = TestDataGeneration.createAccounts( 'Test Account', accountsToCreate );
    	for( Account testAccount : testAccounts )
    	{
    		// this flag needs to be set in order for the opportunities under the account
    		// to have varying values across irep lookups
    		testAccount.iRep_Info_Varies__c = true;
    		testAccount.iRep__c = newAccountIRep.Id;
    		testAccount.Previous_iRep_ID__c = oldAccountIRep.Id;
    		testAccount.iRep_Plan__c = PLAN_STAMP_VALUE;
    		testAccount.Needs_Batch_Processing__c = true;
    	}
    	insert testAccounts;

    	List<Opportunity> testSameOpportunities = new List<Opportunity>();
    	List<Opportunity> testDiffOpportunities = new List<Opportunity>();
    	for( Account testAccount : testAccounts )
    	{
    		for( Opportunity testOpportunity : TestDataGeneration.createOpportunities( opportunitiesWithSameIRep, testAccount.Id, false ) )
    		{
    			testOpportunity.iRep__c = oldAccountIRep.Id;
    			testOpportunity.StageName = '1- Prospect';
    			testSameOpportunities.add( testOpportunity );
    		}
    		for( Opportunity testOpportunity : TestDataGeneration.createOpportunities( opportunitiesWithDiffIRep, testAccount.Id, false ) )
    		{
    			testOpportunity.iRep__c = alternativeOpportunityIRep.Id;
    			testOpportunity.StageName = '1- Prospect';
    			testDiffOpportunities.add( testOpportunity );
    		}
    	}
		List<Opportunity> allOpportunities = new List<Opportunity>();
		allOpportunities.addAll( testSameOpportunities );
		allOpportunities.addAll( testDiffOpportunities );
		insert allOpportunities;

    	Test.startTest();

			SyncOpportunityRepsToAccountBatch job = new SyncOpportunityRepsToAccountBatch();
			job.query += ' AND Id IN ' + flattenAccountListForQuery( testAccounts ) + ' LIMIT 200 ';

			Database.executeBatch( job );

    	Test.stopTest();

    	List<Opportunity> updatedSameIRepOpportunities = [ SELECT Id, iRep__c, iRep_Plan_Stamp__c FROM Opportunity WHERE Id IN :testSameOpportunities ];
    	System.assertEquals( opportunitiesWithSameIRep * accountsToCreate, updatedSameIRepOpportunities.size(), 'The same number of created same IRep opportunities should have been retrieved' );

    	for( Opportunity updatedOpportunity : updatedSameIRepOpportunities )
    	{
    		System.assertEquals( newAccountIRep.Id, updatedOpportunity.iRep__c, 'Since the opportunity had the same IRep as the account, its irep should have been updated' );
    		System.assertEquals( PLAN_STAMP_VALUE, updatedOpportunity.iRep_Plan_Stamp__c, 'Since the opportunity had the same IRep as the account, its plan stamp should have been updated' );
    	}

    	List<Opportunity> updatedDiffIRepOpportunities = [ SELECT Id, iRep__c, iRep_Plan_Stamp__c FROM Opportunity WHERE Id IN :testDiffOpportunities ];
    	System.assertEquals( opportunitiesWithDiffIRep * accountsToCreate, updatedDiffIRepOpportunities.size(), 'The same number of created different IRep opportunities should have been retrieved' );

    	for( Opportunity updatedOpportunity : updatedDiffIRepOpportunities )
    	{
    		System.assertEquals( alternativeOpportunityIRep.Id, updatedOpportunity.iRep__c, 'Opportunities with a different Irep than its account should not have its irep be updated' );
    		System.assertEquals( null, updatedOpportunity.iRep_Plan_Stamp__c, 'Opportunities with a different Irep than its account should not have its plan stamp be updated' );
    	}
	}

	static String flattenAccountListForQuery( List<Account> accounts )
	{
		String returnString = '';

		for( Account testAccount : accounts )
		{
			returnString += '\'' + testAccount.Id + '\',';
		}

		returnString = '(' + returnString.substring( 0, returnString.length() - 1 ) + ')';

		return returnString;
	}

}