force-app/main/default/objects/Account/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <inlineHelpText>If this Account is a Customer, changes to the iRep will need to be made in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Program Accounts</relationshipLabel>
    <relationshipName>iRepAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_BDM_RVP__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_BDM_RVP__c</fullName>
    <label>Email - iRep BDM/RVP</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_Dir__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_Dir__c</fullName>
    <label>Email - iRep Level 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_DMD__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_DMD__c</fullName>
    <label>Email - iRep DMD</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_GSM__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_GSM__c</fullName>
    <label>Email - iRep Level 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_Pres__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_Pres__c</fullName>
    <label>Email - iRep Sales Leader</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_TL__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_TL__c</fullName>
    <label>Email - iRep TL</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_VP__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_VP__c</fullName>
    <label>Email - iRep Level 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_iRep_ZM_SM__c.field-meta.xml
<CustomField>
    <fullName>Email_iRep_ZM_SM__c</fullName>
    <label>Email - iRep Level 3a</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_PSR_Dir__c.field-meta.xml
<CustomField>
    <fullName>Email_PSR_Dir__c</fullName>
    <defaultValue>$User.Dir_Email__c</defaultValue>
    <label>Email - PSR Level 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_PSR_DMD__c.field-meta.xml
<CustomField>
    <fullName>Email_PSR_DMD__c</fullName>
    <label>Email - PSR DMD</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/iRep__c.field-meta.xml
<CustomField>
    <fullName>iRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The iRep on the opportunity matches the Account&apos;s iRep.  If the Account is a Customer, the iRep will need to be updated in Synygy.  If the Account is a Prospect, this can be updated by RVPs and VPs.</inlineHelpText>
    <label>iRep</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Primary_Sales_Rep__c.iRep_Indicator__c</field>
            <operation>equals</operation>
            <value>Y</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>iRep Program Opportunities</relationshipLabel>
    <relationshipName>iRepOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lost_Date__c.field-meta.xml
<CustomField>
    <fullName>Lost_Date__c</fullName>
    <label>Lost Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contact - Left Company</fullName>
            </value>
            <value>
                <fullName>Contact - Not Responsive</fullName>
            </value>
            <value>
                <fullName>Customer - Bad Timing, Will Revisit</fullName>
            </value>
            <value>
                <fullName>Customer - Credit Issues</fullName>
            </value>
            <value>
                <fullName>Customer - Location Closed</fullName>
            </value>
            <value>
                <fullName>Customer - Lost/Cancelled Project</fullName>
            </value>
            <value>
                <fullName>Customer - Under Existing Contract</fullName>
            </value>
            <value>
                <fullName>Lost to Competition - Bid</fullName>
            </value>
            <value>
                <fullName>Lost to Competition - Incumbent</fullName>
            </value>
            <value>
                <fullName>Lost to Competition - Other</fullName>
            </value>
            <value>
                <fullName>Lost to Competition - Vendor Took Direct</fullName>
            </value>
            <value>
                <fullName>Oppty - Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Oppty - Expired</fullName>
            </value>
            <value>
                <fullName>Oppty - Low Volume</fullName>
            </value>
            <value>
                <fullName>Oppty - Not Real</fullName>
            </value>
            <value>
                <fullName>Oppty - Transferred Between Reps</fullName>
            </value>
            <value>
                <fullName>Product - Quality</fullName>
            </value>
            <value>
                <fullName>Product - Unable to find Vendor</fullName>
            </value>
            <value>
                <fullName>VRTV - Non-competitive Cost/Price</fullName>
            </value>
            <value>
                <fullName>VRTV - Service Level</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Required on all Layouts except &quot;Opportunity Layout - System Admin&quot; 
When new Opportunity created from account page, PSR field is pre-populated (editable) with PSR from related Account. 
When a Lead is converted and an opportunity created, the PSR field from the Lead is mapped to the PSR name on Opportunity. 
When Account PSR field is changed, Account Trigger updates each related open Opportunity that has the same PSR as related Account prior to the action 
Reps granted Read/Write access to an Opportunity when the PSR field is saved or edited with their PSR record ID. If the field on the record is changed, the previous PSR associated rep still has access</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PSR_BDM_RVP_Email__c.field-meta.xml
<CustomField>
    <fullName>PSR_BDM_RVP_Email__c</fullName>
    <defaultValue>$User.BDM_RVP_Email__c</defaultValue>
    <label>Email - PSR BDM/RVP</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PSR_GSM_Email__c.field-meta.xml
<CustomField>
    <fullName>PSR_GSM_Email__c</fullName>
    <defaultValue>$User.GSM_Email__c</defaultValue>
    <label>Email - PSR Level 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PSR_Pres_Email__c.field-meta.xml
<CustomField>
    <fullName>PSR_Pres_Email__c</fullName>
    <defaultValue>$User.Pres_Email__c</defaultValue>
    <label>Email - PSR Sales Leader</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PSR_TL_Email__c.field-meta.xml
<CustomField>
    <fullName>PSR_TL_Email__c</fullName>
    <defaultValue>$User.TL_Email__c</defaultValue>
    <label>Email - PSR TL</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PSR_VP_Email__c.field-meta.xml
<CustomField>
    <fullName>PSR_VP_Email__c</fullName>
    <defaultValue>$User.Vice_President_Email__c</defaultValue>
    <label>Email - PSR Level 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PSR_ZM_SM_Email__c.field-meta.xml
<CustomField>
    <fullName>PSR_ZM_SM_Email__c</fullName>
    <defaultValue>$User.ZM_SM_Email__c</defaultValue>
    <label>Email - PSR Level 3a</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/email_bdm_rvp__c.field-meta.xml
<CustomField>
    <fullName>email_bdm_rvp__c</fullName>
    <label>Email - BDM/RVP</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/email_dir__c.field-meta.xml
<CustomField>
    <fullName>email_dir__c</fullName>
    <label>Email - Level 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Email_DMD__c.field-meta.xml
<CustomField>
    <fullName>Email_DMD__c</fullName>
    <label>Email - DMD</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/email_pres__c.field-meta.xml
<CustomField>
    <fullName>email_pres__c</fullName>
    <label>Email - Sales Leader</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Email_TL__c.field-meta.xml
<CustomField>
    <fullName>Email_TL__c</fullName>
    <label>Email - TL</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/email_vp__c.field-meta.xml
<CustomField>
    <fullName>email_vp__c</fullName>
    <label>Email - Level 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/email_zm_sm__c.field-meta.xml
<CustomField>
    <fullName>email_zm_sm__c</fullName>
    <label>Email - Level 3a</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/GSM_Email__c.field-meta.xml
<CustomField>
    <fullName>GSM_Email__c</fullName>
    <label>Email - Level 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Email_DMD__c.field-meta.xml
<CustomField>
    <fullName>Email_DMD__c</fullName>
    <label>Email - DMD</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User/fields/GSM_Email__c.field-meta.xml
<CustomField>
    <fullName>GSM_Email__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <description>AVP Mail Id</description>
    <label>Email - Level 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestPrimarySalesRepServices.cls
@isTest
private class TestPrimarySalesRepServices
{
    static List<Primary_Sales_Rep__c> psrs;
    static List<Primary_Sales_Rep__c> iReps;

    static Integer numUsersToCreate = 5;
    static Integer numPSRsToCreate = 2;
    static Integer numIRepsToCreate = numPSRsToCreate;
    static Integer numOpptysPerPSR = 10;

    static void setup()
    {

        datetime dt = datetime.now();
        string temp = string.valueOf(dt.millisecond()) + string.valueOf(dt.second());
        List<User> testUsers = TestDataGeneration.createUsers( 'Test3'+temp, 'Standard User', numUsersToCreate, true );

        psrs = new List<Primary_Sales_Rep__c>();
        iReps = new List<Primary_Sales_Rep__c>();

        for( User user : testUsers )
        {
            for( Primary_Sales_Rep__c psr : TestDataGeneration.createPSRs( numPSRsToCreate, false ) )
            {
                psr.SF_userid__c = user.Id;
                psrs.add( psr );
            }

            for( Primary_Sales_Rep__c psr : TestDataGeneration.createPSRs( numIRepsToCreate, false ) )
            {
                psr.SF_userid__c = user.Id;
                iReps.add( psr );
            }
        }

        insert psrs;
        insert iReps;
    }

    static testMethod void testGetOpportunitiesByPSR()
    {
        setup();

        List<Opportunity> psrOpportunities = new List<Opportunity>();
        List<Opportunity> iRepOpportunities = new List<Opportunity>();
        List<Opportunity> closedIRepOpportunities = new List<Opportunity>();

        Account testAccount = TestDataGeneration.createAccount( 'Test Account' );

        for( Primary_Sales_Rep__c psr : psrs )
        {
            for( Opportunity opportunity : TestDataGeneration.createOpportunities( numOpptysPerPSR, testAccount.Id, false ) )
            {
                opportunity.Primary_Sales_Rep_Name__c = psr.Id;
                psrOpportunities.add( opportunity );
                
            }
        }
        
        
        System.debug('psrOpportunities'+psrOpportunities.size());
        
        for( Primary_Sales_Rep__c iRep : iReps )
        {
            for( Opportunity opportunity : TestDataGeneration.createOpportunities( numOpptysPerPSR, testAccount.Id, false ) )
            {
                opportunity.iRep__c = iRep.Id;
                iRepOpportunities.add( opportunity );
            }

            for( Opportunity opportunity : TestDataGeneration.createOpportunities( numOpptysPerPSR, testAccount.Id, false ) )
            {
                opportunity.iRep__c = iRep.Id;
                opportunity.StageName = '0- Closed Lost';
                opportunity.Lost_Date__c = Date.today();
                opportunity.Lost_Reason__c = 'Price';
                closedIRepOpportunities.add( opportunity );
            }
        }

        insert psrOpportunities;
        insert iRepOpportunities;
        insert closedIRepOpportunities;

        Test.startTest();
			system.debug('psrs'+psrs);
            List<Opportunity> relatedPSROpportunities =  PrimarySalesRepServices.getOpportunitiesByPSR( psrs );
            List<Opportunity> relatedIRepOpportunities = PrimarySalesRepServices.getOpportunitiesByPSR( iReps );
			System.debug('relatedPSROpportunities'+relatedPSROpportunities);
        Test.stopTest();

        Map<Id, Opportunity> psrOppMap = new Map<Id, Opportunity>(psrOpportunities);
        Map<Id, Opportunity> iRepOppMap = new Map<Id, Opportunity>(iRepOpportunities);

        //System.debug('psrOpportunities.size()'+psrOpportunities.size()+'-->relatedPSROpportunities.size()'+relatedPSROpportunities.size());
        
        
        if(psrOpportunities.size() == relatedPSROpportunities.size()){
             System.assertEquals(psrOpportunities.size(), relatedPSROpportunities.size());
        }
       

        for(Opportunity opportunity : relatedPSROpportunities)
        {
            System.assert(psrOppMap.containsKey(opportunity.Id));
        }

        System.assertEquals(iRepOpportunities.size(), relatedIRepOpportunities.size());

        for(Opportunity opportunity : closedIRepOpportunities)
        {
            System.assert(!iRepOppMap.containsKey(opportunity.Id), 'Should only include open opportunities');
        }


        for(Opportunity opportunity : relatedIRepOpportunities)
        {
            System.assert(iRepOppMap.containsKey(opportunity.Id));
        }

    }

    static testMethod void testCopyPSREmailFields()
    {
        Primary_Sales_Rep__c testPSR = TestDataGeneration.createPSRs( 1, false )[0];

        testPSR.email_zm_sm__c  = 'bob@unisourcelink.com';
        testPSR.email_vp__c     = 'dan@unisourcelink.com';
        testPSR.email_pres__c   = 'george@unisourcelink.com';
        testPSR.email_dir__c    = 'frank@unisourcelink.com';
        testPSR.email_bdm_rvp__c = 'mike@unisourcelink.com';
        testPSR.GSM_Email__c    = 'jason@unisourcelink.com';
        testPSR.Email_TL__c     = 'hank@unisourcelink.com';
        testPSR.Email_DMD__c    = 'joe@unisourcelink.com';

        insert testPSR;

        Account testAccount = TestDataGeneration.createAccount( 'Test Account' );

        Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, true )[0];

        Test.startTest();

            Opportunity returnedOpportunity = PrimarySalesRepServices.copyPSREmailFields( testOpportunity, testPSR );

        Test.stopTest();

        System.assertEquals( testPSR.email_zm_sm__c,    returnedOpportunity.PSR_ZM_SM_Email__c);
        System.assertEquals( testPSR.email_vp__c   ,    returnedOpportunity.PSR_VP_Email__c);
        System.assertEquals( testPSR.email_pres__c  , returnedOpportunity.PSR_Pres_Email__c);
        System.assertEquals( testPSR.email_dir__c   , returnedOpportunity.Email_PSR_Dir__c);
        System.assertEquals( testPSR.email_bdm_rvp__c, returnedOpportunity.PSR_BDM_RVP_Email__c);
        System.assertEquals( testPSR.GSM_Email__c   , returnedOpportunity.PSR_GSM_Email__c);
        System.assertEquals( testPSR.Email_TL__c    , returnedOpportunity.PSR_TL_Email__c);
        System.assertEquals( testPSR.Email_DMD__c   , returnedOpportunity.Email_PSR_DMD__c);

    }

    static testMethod void testCopyiRepEmailFields()
    {
        Primary_Sales_Rep__c testPSR = TestDataGeneration.createPSRs( 1, false )[0];

        testPSR.email_zm_sm__c  = 'bob@unisourcelink.com';
        testPSR.email_vp__c     = 'dan@unisourcelink.com';
        testPSR.email_pres__c   = 'george@unisourcelink.com';
        testPSR.email_dir__c    = 'frank@unisourcelink.com';
        testPSR.email_bdm_rvp__c = 'mike@unisourcelink.com';
        testPSR.GSM_Email__c    = 'jason@unisourcelink.com';
        testPSR.Email_TL__c     = 'hank@unisourcelink.com';
        testPSR.Email_DMD__c    = 'joe@unisourcelink.com';

        insert testPSR;

        Account testAccount = TestDataGeneration.createAccount( 'Test Account' );

        Opportunity testOpportunity = TestDataGeneration.createOpportunities( 1, testAccount.Id, true )[0];

        Test.startTest();

            Opportunity returnedOpportunity = PrimarySalesRepServices.copyIRepEmailFields( testOpportunity, testPSR );

        Test.stopTest();

        System.assertEquals( testPSR.email_zm_sm__c,    returnedOpportunity.Email_iRep_ZM_SM__c);
        System.assertEquals( testPSR.email_vp__c   ,    returnedOpportunity.Email_iRep_VP__c);
        System.assertEquals( testPSR.email_pres__c  , returnedOpportunity.Email_iRep_Pres__c);
        System.assertEquals( testPSR.email_dir__c   , returnedOpportunity.Email_iRep_Dir__c);
        System.assertEquals( testPSR.email_bdm_rvp__c, returnedOpportunity.Email_iRep_BDM_RVP__c);
        System.assertEquals( testPSR.GSM_Email__c   , returnedOpportunity.Email_iRep_GSM__c);
        System.assertEquals( testPSR.Email_TL__c    , returnedOpportunity.Email_iRep_TL__c);
        System.assertEquals( testPSR.Email_DMD__c   , returnedOpportunity.Email_iRep_DMD__c);
    }

    static testMethod void testUpdateOpportunityEmailFieldsFromPSRs()
    {
        setup();

        String psrValueToSet = 'dan@unisourcelink.com';
        String iRepValueToSet = 'joe@unisourcelink.com';

        List<Opportunity> psrOpportunities = new List<Opportunity>();
        List<Opportunity> iRepOpportunities = new List<Opportunity>();
        List<Opportunity> mixedOpportunities = new List<Opportunity>();

        Account testAccount = TestDataGeneration.createAccount( 'Test Account' );

        for( Primary_Sales_Rep__c psr : psrs )
        {
            for( Opportunity opportunity : TestDataGeneration.createOpportunities( numOpptysPerPSR, testAccount.Id, false ) )
            {
                opportunity.Primary_Sales_Rep_Name__c = psr.Id;
                psrOpportunities.add( opportunity );
            }
        }

        for( Primary_Sales_Rep__c iRep : iReps )
        {
            for( Opportunity opportunity : TestDataGeneration.createOpportunities( numOpptysPerPSR, testAccount.Id, false ) )
            {
                opportunity.iRep__c = iRep.Id;
                iRepOpportunities.add( opportunity );
            }
        }

        Integer index = 0;
        for( Opportunity opportunity : TestDataGeneration.createOpportunities( numPSRsToCreate, testAccount.Id, false ) )
        {
            opportunity.Primary_Sales_Rep_Name__c = psrs[index].Id;
            opportunity.iRep__c = iReps[index].Id;
            mixedOpportunities.add( opportunity );

            index++;
        }
        
        insert psrOpportunities;
        insert iRepOpportunities;
        insert mixedOpportunities;

        Test.startTest();

            for( Primary_Sales_Rep__c psr : psrs )
            {
                psr.email_zm_sm__c = psrValueToSet;
            }

            for( Primary_Sales_Rep__c iRep : iReps )
            {
                iRep.email_zm_sm__c = iRepValueToSet;
            }

            List<Primary_Sales_Rep__c> psrsAndIReps = new List<Primary_Sales_Rep__c>();
            psrsAndIReps.addAll( psrs );
            psrsAndIReps.addAll( iReps );

            PrimarySalesRepServices.updateOpportunityEmailFieldsFromPSRs( psrsAndIReps );

        Test.stopTest();

        for( Opportunity updatedPSROppty : [ SELECT Id, PSR_ZM_SM_Email__c, Email_iRep_ZM_SM__c FROM Opportunity WHERE Id IN :psrOpportunities ] )
        {
            //System.assertEquals( psrValueToSet, updatedPSROppty.PSR_ZM_SM_Email__c );
        }

        Integer i = 0;
        for( Opportunity updatedIRepOppty : [ SELECT Id, PSR_ZM_SM_Email__c, Email_iRep_ZM_SM__c FROM Opportunity WHERE Id IN :iRepOpportunities ] )
        {
            System.assertEquals( iRepValueToSet, updatedIRepOppty.Email_iRep_ZM_SM__c );
        }

        for( Opportunity updatedMixedOppty : [ SELECT Id, PSR_ZM_SM_Email__c, Email_iRep_ZM_SM__c FROM Opportunity WHERE Id IN :mixedOpportunities ] )
        {
            System.assertEquals( iRepValueToSet, updatedMixedOppty.Email_iRep_ZM_SM__c );
           // System.assertEquals( psrValueToSet, updatedMixedOppty.PSR_ZM_SM_Email__c );
        }
    }

    static testMethod void testInsertPSRWithUser()
    {
        String testEmailValue = 'dan@unisourcelink.com.test';

        User testUser = TestDataGeneration.createUser( 'TUser', 'Standard User', false );
        testUser.Email_DMD__c = testEmailValue;

        //System.runAs( TestDataGeneration.ADMIN_USER )
       // {
            insert testUser;
       // }

        Primary_Sales_Rep__c testPSR = TestDataGeneration.createPSRs( 1, false )[0];
        testPSR.SF_userid__c = testUser.Id;

        Test.startTest();

            insert testPSR;

        Test.stopTest();

        List<Primary_Sales_Rep__c> updatedPSR = [ SELECT Id, Email_DMD__c FROM Primary_Sales_Rep__c WHERE Id = :testPSR.Id ];

       // System.assertEquals( testEmailValue, updatedPSR[0].Email_DMD__c, 'PSR should sync upon create when it looks up to a user.' );
    }

    static testMethod void testUpdatePSRWithUser()
    {
        String testEmailValue = 'dan@unisourcelink.com.test';

        User testUser = TestDataGeneration.createUser( 'TUser', 'Standard User', false );
        testUser.Email_DMD__c = testEmailValue;

       // System.runAs( TestDataGeneration.ADMIN_USER )
       // {
            insert testUser;
       // }

        Primary_Sales_Rep__c testPSR = TestDataGeneration.createPSRs( 1, true )[0];

        Test.startTest();

            testPSR.SF_userid__c = testUser.Id;
            update testPSR;

        Test.stopTest();

        List<Primary_Sales_Rep__c> updatedPSR = [ SELECT Id, Email_DMD__c FROM Primary_Sales_Rep__c WHERE Id = :testPSR.Id ];

        //System.assertEquals( testEmailValue, updatedPSR[0].Email_DMD__c, 'PSR should sync upon update when the user lookup changes' );
    }

    static testMethod void testSyncPSRUserLookupByNetwork()
    {
        User testUser = TestDataGeneration.createUser( 'NUser', 'Standard User', true );

        Primary_Sales_Rep__c testPSR = TestDataGeneration.createPSRs( 1, false )[0];
        testPSR.Network_ID__c = testUser.Network_Id__c;

        Test.startTest();

            insert testPSR;

        Test.stopTest();

        List<Primary_Sales_Rep__c> updatedPSR = [ SELECT Id, SF_userid__c FROM Primary_Sales_Rep__c WHERE Id = :testPSR.Id ];

        System.assertEquals( 1, updatedPSR.size() );
        System.assertEquals( testUser.Id, updatedPSR[0].SF_userid__c );
    }

    static testMethod void testSyncPSRUserLookupByNetworkBulk()
    {
        Integer usersToCreate = 30;

        List<User> testUsers = TestDataGeneration.createUsers( 'TUser', 'Standard User', usersToCreate, true );

        Map<String, User> networkIdToUser = new Map<String, User>();
        for( User testUser : testUsers )
        {
            networkIdToUser.put( testUser.Network_Id__c, testUser );
        }

        List<Primary_Sales_Rep__c> testPSRs = new List<Primary_Sales_Rep__c>();
        for( User testUser : testUsers )
        {
            Primary_Sales_Rep__c psrForUser = TestDataGeneration.createPSRs( 1, false )[0];
            psrForUser.Network_ID__c = testUser.Network_Id__c;
            testPSRs.add( psrForUser );
        }

        Test.startTest();

            insert testPSRs;

        Test.stopTest();

        List<Primary_Sales_Rep__c> updatedPSRs = [ SELECT Id, Network_ID__c, SF_userid__c FROM Primary_Sales_Rep__c WHERE Id IN :testPSRs ];

        for( Primary_Sales_Rep__c updatedPSR : updatedPSRs )
        {
            System.assertEquals( networkIdToUser.get( updatedPSR.Network_ID__c ).Id, updatedPSR.SF_userid__c );
        }
    }
    
    static testMethod void testPSRInsertWithoutCoupledUser() {
        Primary_Sales_Rep__c testPSR = TestDataGeneration.createPSRs( 1, false )[0];
        
            Test.startTest();
                insert testPSR;
            Test.stopTest();
                
            List<Primary_Sales_Rep__c> updatedPSRs = [Select Id, SF_userid__c From Primary_Sales_Rep__c Where Id = :testPSR.Id];
            System.assertEquals(null, updatedPSRs[0].SF_userid__c);
    }

}