force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Primary Sales Rep
When a new Quote is created from an Account or Opportunity Record, the Primary Sales Rep field is pre-populated (but editable) with the Primary Sales Rep tied to the related Account
When a new Quote is created from an Opportunity, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Opportunity’s related Account, regardless of the Primary Sales Rep listed on the Opportunity. 
When a new Quote is created from a Contact, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Contact’s related Account record, regardless of the Primary Sales Rep listed on the Contact. 
When a Quote is cloned, the new Quote’s Primary Sales Rep field on the new cloned Quote is pre-populated with the Primary Sales Rep from the Quote it was cloned from</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestUpdateQuoteSharesOnAcctChange.cls
@isTest
private class TestUpdateQuoteSharesOnAcctChange {

	private static final String ACCESS_ERROR_MESSAGE = 'Changing account owner to current quote owner has thrown error.';
	private static final String TEST_FAIL = ' Test failed!';
	private static final String INSUFFICIENT_ACCESS_ERROR = 'INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY';

	private static final Integer NUMBER_OF_TEST_QUOTES = 25;

	private static User acctOwnerTestUser, otherAcctOwnerTestUser, quoteOwnerTestUser;
	private static Account someTestAccount;
	
	private static List<Quote__c> genTestQuotes( Integer howMany, Id ownerId, Id accountId  ) {
		
		List<Quote__c> newTestQuotes = new List<Quote__c>();
		
		for ( Integer i = 0; i < howMany; i++ )
			newTestQuotes.add( new Quote__c( OwnerId=ownerId, Account__c=accountId ) );
			
		return newTestQuotes;
		
	}
	
	private static String getPrefix( Id anId ) {
		
		if ( anId == null )
			return '';
		
		String idString = (String)anId;
		return idString.substring(0, 3);
		
	}

	private static testMethod void changeSingleAccountOwner() {
		
		Integer futureCalls = 0;
		
		testSetup();
					
		List<Quote__c> testQuotes = genTestQuotes( NUMBER_OF_TEST_QUOTES, quoteOwnerTestUser.Id, someTestAccount.Id );
		insert testQuotes;
		
		Set<Id> quoteIds = new Set<Id>();
		for ( Quote__c quoteForId : testQuotes )
			quoteIds.add( quoteForId.Id );
		
		List<Quote__Share> relatedQuoteShares = [ SELECT Id, UserOrGroupId, parentId FROM Quote__Share WHERE parentId IN :testQuotes ]; 

		String userPrefix = getPrefix( quoteOwnerTestUser.Id );
		
		for ( Quote__Share aQuoteShare : relatedQuoteShares ) {
			
			if ( getPrefix( aQuoteShare.UserOrGroupId ) == userPrefix && aQuoteShare.UserOrGroupId != quoteOwnerTestUser.Id )
				System.AssertEquals( acctOwnerTestUser.Id, aQuoteShare.UserOrGroupId );
			
		}
			
		Test.startTest();
		
			someTestAccount.OwnerId = otherAcctOwnerTestUser.Id;
			update someTestAccount;
			futureCalls = Limits.getFutureCalls();
		
       
		Test.stopTest();

		relatedQuoteShares = [ SELECT Id, UserOrGroupId FROM Quote__Share WHERE parentId IN :testQuotes ]; 

		for ( Quote__Share aQuoteShare : relatedQuoteShares ) {
			
			if ( getPrefix( aQuoteShare.UserOrGroupId ) == userPrefix && aQuoteShare.UserOrGroupId != quoteOwnerTestUser.Id )			
				System.AssertEquals( otherAcctOwnerTestUser.Id, aQuoteShare.UserOrGroupId );			
			
		}
		//System.assertEquals(1, futureCalls, 'We expect one future call to take place.');

	}

	private static testMethod void changeFromSameOwner() {
		
		Integer futureCalls = 0;
		
		testSetup();
		
		quoteOwnerTestUser = acctOwnerTestUser;
					
		List<Quote__c> testQuotes = genTestQuotes( NUMBER_OF_TEST_QUOTES, quoteOwnerTestUser.Id, someTestAccount.Id );
		insert testQuotes;
		
		Set<Id> quoteIds = new Set<Id>();
		for ( Quote__c quoteForId : testQuotes )
			quoteIds.add( quoteForId.Id );
		
		List<Quote__Share> relatedQuoteShares = [ SELECT Id, UserOrGroupId, parentId FROM Quote__Share WHERE parentId IN :testQuotes ]; 

		String userPrefix = getPrefix( quoteOwnerTestUser.Id );
		
		for ( Quote__Share aQuoteShare : relatedQuoteShares ) {
			
			if ( getPrefix( aQuoteShare.UserOrGroupId ) == userPrefix && aQuoteShare.UserOrGroupId != quoteOwnerTestUser.Id )
				System.AssertEquals( acctOwnerTestUser.Id, aQuoteShare.UserOrGroupId );
			
		}
			
		Test.startTest();
		
			someTestAccount.OwnerId = otherAcctOwnerTestUser.Id;
			update someTestAccount;
			futureCalls = Limits.getFutureCalls();
		Test.stopTest();

		relatedQuoteShares = [ SELECT Id, UserOrGroupId FROM Quote__Share WHERE parentId IN :testQuotes ]; 

		for ( Quote__Share aQuoteShare : relatedQuoteShares ) {
			
			if ( getPrefix( aQuoteShare.UserOrGroupId ) == userPrefix && aQuoteShare.UserOrGroupId != quoteOwnerTestUser.Id )			
				System.AssertEquals( otherAcctOwnerTestUser.Id, aQuoteShare.UserOrGroupId );			
			
		}
		//System.assertEquals(1, futureCalls, 'We expect one future call to take place.');

	}
	
	private static testMethod void insufficientAccessFromAddingCurrentOwner() {
		
		testSetup();
		
		List<Quote__c> testQuotes = genTestQuotes( NUMBER_OF_TEST_QUOTES, quoteOwnerTestUser.Id, someTestAccount.Id );
		insert testQuotes;
		
		Set<Id> quoteIds = new Set<Id>();
		for ( Quote__c quoteForId : testQuotes )
			quoteIds.add( quoteForId.Id );
		
		List<Quote__Share> relatedQuoteShares = [ SELECT Id, UserOrGroupId, parentId FROM Quote__Share WHERE parentId IN :testQuotes ]; 

		String userPrefix = getPrefix( quoteOwnerTestUser.Id );
		
		for ( Quote__Share aQuoteShare : relatedQuoteShares ) {
			
			if ( getPrefix( aQuoteShare.UserOrGroupId ) == userPrefix && aQuoteShare.UserOrGroupId != quoteOwnerTestUser.Id )
				System.AssertEquals( acctOwnerTestUser.Id, aQuoteShare.UserOrGroupId );
			
		}
			
		Test.startTest();
		
			someTestAccount.OwnerId = quoteOwnerTestUser.Id;
			
			try {
				
				update someTestAccount;
				
			} catch( System.Dmlexception dmlEx ) {
				
				if ( dmlEx.getMessage().contains( INSUFFICIENT_ACCESS_ERROR ) )
					System.assert( False, ACCESS_ERROR_MESSAGE + TEST_FAIL );
				
			}
				
		Test.stopTest();

	}
	
	///////////////////////////////////////////////////
	/////		Test Data Generation Functions
	///////////////////////////////////////////////////

	private static void testSetup() {
		
		Id profId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id;
		
		acctOwnerTestUser = genTestUser( 'acctOwner@bluewolf.com', 'acctOwne', profId );
		quoteOwnerTestUser = genTestUser( 'quoteOwner@bluewolf.com', 'quoteOwn', profId );
		otherAcctOwnerTestUser = genTestUser( 'otherAcctOwner@bluewolf.com', 'otherAcc', profId );
		
		insert new List<User>{ acctOwnerTestUser, quoteOwnerTestUser, otherAcctOwnerTestUser };
		
		Primary_Sales_Rep__c psr = TestingUtils.createPSRs( 1, 'tst', 'n', true )[0];
		
		someTestAccount = new Account( ownerId = acctOwnerTestUser.Id, Primary_Sales_Rep_Name__c = psr.Id, Name = 'test account', CurrencyIsoCode = 'USD'  );
		insert someTestAccount;
		
	}
	
    private static User genTestUser( String userName, String alias, Id profTypeId ) {
    	
    	User testUser = new User( 	FirstName=userName, 
									LastName=userName, 
									Email=userName,
									EmailEncodingKey='ISO-8859-1',
									CommunityNickname=userName,
									LocaleSidKey='en_US',
									TimeZoneSidKey='America/Puerto_Rico',
									LanguageLocaleKey='en_US',
									Alias=alias,
									Network_Id__c=alias,
									Username=userName,
									Country='USA'   );
									
		if ( profTypeId != null )
    		testUser.ProfileId = profTypeId;
    	
    	return testUser;
    	
    }

}