force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division_Name__c</fullName>
    <description>Pulls the Servicing Division Name. Currently used in the Account &amp; Lead Visibility page for searching divisions.</description>
    <formula>Servicing_Division__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Number__c</fullName>
    <externalId>true</externalId>
    <label>Ship To Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <formula>/* OLD FORMULA */ 
/* 
IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.Division_Code__c, IF( Ship_To_Account__r.Legacy_Division_Cd__c = &quot;&quot;, Account__r.Legacy_Division_Cd__c, Ship_To_Account__r.Legacy_Division_Cd__c)) 
*/ 

IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Code__c, 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, BLANKVALUE(Account__r.Legacy_Division_Cd__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c))) 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division_Name__c</fullName>
    <formula>IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Desc__c, BLANKVALUE(Account__r.Servicing_Division__r.Name, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Name)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Desc__c, 

BLANKVALUE(Account__r.Legacy_Division_Desc__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Name, 
BLANKVALUE(Account__r.Legacy_Division_Desc__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Name))) 
))</formula>
    <label>Servicing Division Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Number__c</fullName>
    <formula>IF(LEN(Ship_To__r.Ship_To_Code__c) = 12, RIGHT( Ship_To__r.Ship_To_Code__c , 6), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ship To Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Vendor_Lookup__c</field>
            <operation>equals</operation>
            <valueField>$Source.Vendor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxcEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendToSalesRepQLIControllerExtension.cls
public class SendToSalesRepQLIControllerExtension
{
    //Properties
    public final ApexPages.StandardSetController qliSetController;
    public Quote__c quote {get; set;}
    public Attachment attachment {get; set;}
    public List<Attachment> existingAttachments {get; set;}
    public Set<Id> attIds {get; set;}
    public Boolean hasExistingAttachments {get; set;}
    public String currentAttId {get; set;}
    
    public SendToSalesRepQLIControllerExtension(ApexPages.StandardSetController stdSetController)
    {
        qliSetController = stdSetController;
        initNewAttachment();
        attIds = new Set<Id>();
    
        //Validation rules
        if(!isValidQuote)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This page cannot be accessed directly.  It can only be reached from the "Send to Sales Rep" button on a quote record.'));
            return;
        }
        if(!hasSelectedRecords)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No Quote Line Items have been selected. Please click the "Back" button and select at least one record.'));
            return;
        }
        //Validation rules passed, continue
        quote = [select Name, Account__r.Name, Account__r.RecordType.Name, Servicing_Division__c, Servicing_Division_Name__c, Account__r.AccountNumber, Account__r.Primary_Sales_Rep_Name__r.Contact__c, Ship_To_Number__c, Customer_Contact__c, Shipment_Method__c from Quote__c where Id = :ApexPages.currentPage().getParameters().get('id')];
        
        emailAdditionalTo = '';
        emailCC = '';
        emailBCC = '';
    }
   
    public Quote_Line_Item__c email
    {
        get
        {
            if(email == null && isValidQuote)
                email = new Quote_Line_Item__c(Vendor_Contact__c = quote.Account__r.Primary_Sales_Rep_Name__r.Contact__c);

            return email;
        }
        set
        {
            email = value;
        }
    }
    
    public String emailAdditionalTo {get; set;}
    
    public String emailCC {get; set;}
    
    public String emailBCC {get; set;}
    
    public boolean isValidQuote
    {
        get
        {
            if(isValidQuote == null)
            {
                if(ApexPages.currentPage().getParameters().get('id') == null)
                {
                    isValidQuote = false;
                    return isValidQuote;
                }
                else
                {
                    isValidQuote = true;
                    return isValidQuote;
                }
            }
            return isValidQuote;
        }
        set
        {
            isValidQuote = value;
        }
    }
    
    public Boolean hasSelectedRecords
    {
        get
        {
            if(this.qliSetController.getSelected().size() > 0)
                return true;
            else
                return false;
        }
    }
    //Methods
    private String[] removeBlanks(String[] emailAddresses)
    {
        String[] returnAddresses = new String[0];
        for(Integer i=0; i < emailAddresses.size(); i++)
        {
            emailAddresses[i] = emailAddresses[i].trim();
            if(emailAddresses[i].length() > 0) returnAddresses.add(emailAddresses[i]);
        }
        return returnAddresses;
    }
    public void initNewAttachment()
    {
        attachment = new Attachment(ParentId = ApexPages.currentPage().getParameters().get('id'));
        hasExistingAttachments = false;
        existingAttachments = new List<Attachment>();
    }
    
    public void addAttachment()
    {
        if (attachment.Body != null)
        {
            insert attachment;
            existingAttachments.add(attachment);
            attIds.add(attachment.id);
        }
        initNewAttachment();
        existingAttachments = [SELECT Id, ParentId, Name, BodyLength, LastModifiedDate FROM Attachment WHERE Id in :attIds];
        hasExistingAttachments = true;
    }   
    
    public void removeAttachment()
    {
        attIds.remove(currentAttId);
        delete [SELECT Id FROM Attachment WHERE Id = :currentAttId];
        initNewAttachment();
        existingAttachments = [SELECT Id, ParentId, Name, BodyLength, LastModifiedDate FROM Attachment WHERE Id in :attIds];
        if (attIds.size()>0)
            hasExistingAttachments = true;
        else
            hasExistingAttachments = false;
        
    }
         
         
    public List<Attachment> updateExistingAttachmentsList()
    {   
        List<Attachment> attchList = [SELECT Id, Body, ParentId, Name, BodyLength, LastModifiedDate FROM Attachment WHERE Id in :attIds];
        if (attachment != null)
        {
            attchList.add(attachment);
        } 
        return attchList;
    }
    
    public PageReference sendQuote()
    {
        Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
        emailMsg.setTargetObjectId(email.Vendor_Contact__c);
        emailMsg.setWhatId(quote.Id);
        
        String department = [Select Department From User Where Id = :UserInfo.getUserId() Limit 1].Department;
        //Add title query parm and file name         
        String fileName = '';
        
        /* Removing Websource Templates -> Falling back to Defaults */
        /*
        if(department == 'Websource')
        {
            emailMsg.setTemplateId([select Id from EmailTemplate where DeveloperName = 'Sales_Rep_Quote_Template_Websource'].Id);
            fileName = 'Websource Sales Rep Quote.pdf';
        }
        else
        */
        {
            emailMsg.setTemplateId([select Id from EmailTemplate where DeveloperName = 'Sales_Rep_Quote_Template'].Id);
            fileName = 'Unisource Sales Rep Quote.pdf';
        }
        
        String[] emailAddresses = emailAdditionalTo.split(';');
        emailMsg.setToAddresses(removeBlanks(emailAddresses));
        
        emailAddresses = emailCC.split(';');
        emailMsg.setCcAddresses(removeBlanks(emailAddresses));
        
        emailAddresses = emailBCC.split(';');
        emailMsg.setBccAddresses(removeBlanks(emailAddresses));
        
        //Prepare URL for PDF page
        String quoteURL = Page.Quote.getURL() + '?id=' + quote.Id;
        //Add QLI Ids query parms
        for(Integer i=0; i < this.qliSetController.getSelected().size(); i++)
        {
            if(this.qliSetController.getSelected()[i].get('Id') == null)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The information required to send this email has been reset due to a previous error message.  Please recreate the email by going back to the quote and clicking the "Send to Sales Rep" button again.'));
                return null;
            }
            quoteURL += '&qlid' + i + '=' + this.qliSetController.getSelected()[i].get('Id');
        }
        
        //Instantitiate PDF page
        quoteURL += '&title=Sales Rep';
        PageReference quotePage = new PageReference(quoteURL);
        //Prepare attachment to quote
        Attachment quoteAttachment = new Attachment();
        Blob content;
        if (Test.IsRunningTest()){
            content=Blob.valueOf('UNIT.TEST');
        }
        else{
            content=quotePage.getContent();
        }
        quoteAttachment.Body = content;
        quoteAttachment.Name = fileName;
        quoteAttachment.ParentId = quote.Id;        
        
        //Insert attachment to email
        Messaging.EmailFileAttachment emailAttachment = new Messaging.EmailFileAttachment();
        emailAttachment.setFileName(fileName);
        emailAttachment.setBody(content);
        
        List<Messaging.EmailFileAttachment>  fileAttachmentList = new List<Messaging.EmailFileAttachment> ();
        Messaging.EmailFileAttachment[]  fileAttachments = new Messaging.EmailFileAttachment[]{};
        List<Attachment>  attchList = updateExistingAttachmentsList();
    
        for (Attachment att : attchList)
        {
           if (att.Body != null)
           {
                Messaging.EmailFileAttachment myAtt = new Messaging.EmailFileAttachment();
                myAtt.setFileName(att.Name);
                myAtt.setBody(att.Body);
                fileAttachmentList.add(myAtt);
            }       
        }
         
        fileAttachments.addAll(fileAttachmentList);
        fileAttachments.add(emailAttachment);
        
        emailMsg.setFileAttachments(fileAttachments);
        
        Savepoint sp = Database.setSavepoint();
        Messaging.SendEmailResult[] sers;
        //Insert PDF as quote attachment & send email
        try
        {
            System.debug('turkey'+quoteAttachment);
            insert quoteAttachment;
            sers = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {emailMsg});
        }
        catch(DmlException dmle)
        {
            for (Integer i=0; i < dmle.getNumDml(); i++)
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, dmle.getDmlMessage(i)));

            Database.rollback(sp);
            return null;
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            Database.rollback(sp);
            return null;
        }
        
        Boolean allSuccessful = true;
        for(Messaging.SendEmailResult ser : sers)
        {
            if(!ser.isSuccess())
            {
                allSuccessful = false;
                break;
            }
        }
        if(allSuccessful)       
            return qliSetController.cancel();
        else
        {
            for(Messaging.SendEmailResult ser : sers)
            {
                for(Database.Error de : ser.getErrors())
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, de.getMessage()));
            }
            return null;
        }
    }
    
   
}