force-app/main/default/objects/Account/fields/Primary_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nov 2016 - Data fed in from data warehouse integration when Account is a Customer. 
Apr 2017 - Lookup field to the Primary Sales Rep Object. 
When Account PSR field is changed (by system or user), each related open Opportunity that had the same PSR as its related account is updated with the new PSR from the account 
A batch can be run to update each Opportunity&apos;s PSR field to equal the PSR on its related account 
When a lead with a blank value in the Primary Sales Rep field is converted to a New Account, the Account Primary Sales Rep field is automatically populated with the Primary Sales Rep associated with the User who converted the lead. 
When a Quote’s related Account is changed, the Quote’s PSR will change to equal the PSR on the new related Account regardless of the Quote Stage 
If a user adds anyone as the Primary Sales Rep field on a Lead, the New Account Primary Sales Rep field will be populated with the Primary Sales Rep that was tied to the Lead.</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Primary Sales Rep
When a new Quote is created from an Account or Opportunity Record, the Primary Sales Rep field is pre-populated (but editable) with the Primary Sales Rep tied to the related Account
When a new Quote is created from an Opportunity, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Opportunity’s related Account, regardless of the Primary Sales Rep listed on the Opportunity. 
When a new Quote is created from a Contact, the Primary Sales Rep field on the Quote object is pre-populated with the Primary Sales Rep from the Contact’s related Account record, regardless of the Primary Sales Rep listed on the Contact. 
When a Quote is cloned, the new Quote’s Primary Sales Rep field on the new cloned Quote is pre-populated with the Primary Sales Rep from the Quote it was cloned from</description>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <color>#E27001</color>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <color>#66E9BD</color>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#F96FB7</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Sent to Customer</fullName>
                <color>#0B6FCE</color>
                <label>Sent to Customer</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <color>#CC0000</color>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Won</fullName>
                <color>#009900</color>
                <label>Won</label>
            </value>
            <value>
                <fullName>Returned From Field Sourcing</fullName>
                <color>#641CCF</color>
                <label>Returned From Field Sourcing</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <color>#8F6429</color>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Requires Additional Follow-up</fullName>
                <color>#CC33CC</color>
                <label>Requires Additional Follow-up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestQuoteModel.cls
@isTest
private class TestQuoteModel {

    private static List<Quote__c> testQuotes;
    private static List<User> testOwners;
    private static Account someTestAccount;
    private static User merchUser;
    private static User nonMerchUser;

    private static void setupData(Integer batchSize)
    {
        UserRole merchRole = new UserRole( Name = 'Merch -1');
        UserRole nonMerchRole = new UserRole( Name = 'not merch');
        
        System.RunAs( TestingUtils.ADMIN_USER)
        {
            insert merchRole;
            insert nonMerchRole;
        }
        
        merchUser = TestingUtils.createUser( 'testMU', 'CS - Lightning Console', false );
        nonMerchUser = TestingUtils.createUser( 'testMU2', 'CS - Lightning Console', false );
        
        merchUser.userRoleId = merchRole.Id;
        nonMerchUser.userRoleId = nonMerchRole.Id;
        
        System.RunAs( TestingUtils.ADMIN_USER)
        {
            insert new List<User>{merchUser, nonMerchUser};
        }
        setupTestAccount();
        setupQuotes(batchSize);
    }

    private static void setupTestAccount()
    {
        Primary_Sales_Rep__c psr = new Primary_Sales_Rep__c();
        psr.name = 'test';
        psr.Network_ID__c = '234';
        psr.Email__c ='ert.sdfg@test.com';
        insert psr;
        
        
        someTestAccount = new Account(Primary_Sales_Rep_Name__c = [SELECT Id FROM Primary_Sales_Rep__c LIMIT 1].Id, Name = 'test account', CurrencyIsoCode = 'USD'  );
        insert someTestAccount;
    }

    private static void setupQuotes(Integer batchSize)
    {   
        testQuotes = new List<Quote__c>();
        for(Integer i=0; i<batchSize; i++)
        {
            Quote__c q = new Quote__c(Account__c=someTestAccount.Id, Quote_Stage__c=QuoteModel.WITH_FIELD_SOURCING);
            testQuotes.add(q);
        }
        insert testQuotes;
    }
    
    private static testmethod void testReturnQuoteToRequester_MerchOwner()
    {
        setupData(1);
         
        for(Quote__c q : testQuotes)
        {
            q.OwnerId = merchUser.Id;
        }
        
        Test.startTest();
        
        update testQuotes;
        
        testQuotes = [select Id, Quote_Stage__c from Quote__c where Id in :testQuotes];
        
        for(Quote__c updatedQuote : testQuotes)
        {
            System.assertEquals(QuoteModel.WITH_FIELD_SOURCING, updatedQuote.Quote_Stage__c);
        }
        
        Test.stopTest();
    }

    private static testmethod void testReturnQuoteToRequester_NonMerchOwner()
    {
        setupData(1);
         
        for(Quote__c q : testQuotes)
        {
            q.OwnerId = nonMerchUser.Id;
        }
        
        Test.startTest();
        
        update testQuotes;
        
        testQuotes = [select Id, Quote_Stage__c from Quote__c where Id in :testQuotes];
        
        for(Quote__c updatedQuote : testQuotes)
        {
          //  System.assertEquals(QuoteModel.RETURNED_FROM_FIELD_SOURCING, updatedQuote.Quote_Stage__c);
         // System.assertEquals(QuoteModel.WITH_FIELD_SOURCING, updatedQuote.Quote_Stage__c);
          
          
        }
        
        Test.stopTest();
    }
    
    private static testmethod void testReturnQuoteToRequester_MerchOwner_Batch()
    {
        setupData(50);
         
        for(Quote__c q : testQuotes)
        {
            q.OwnerId = merchUser.Id;
        }
        
        Test.startTest();
        
        update testQuotes;
        
        testQuotes = [select Id, Quote_Stage__c from Quote__c where Id in :testQuotes];
        
        for(Quote__c updatedQuote : testQuotes)
        {
            System.assertEquals(QuoteModel.WITH_FIELD_SOURCING, updatedQuote.Quote_Stage__c);
        }
        
        Test.stopTest();
    }
    
    private static testmethod void testReturnQuoteToRequester_NonMerchOwner_Batch()
    {
        setupData(50);
         
        for(Quote__c q : testQuotes)
        {
            q.OwnerId = nonMerchUser.Id;
        }
        
        Test.startTest();
        
        update testQuotes;
        
        testQuotes = [select Id, Quote_Stage__c from Quote__c where Id in :testQuotes];
        
        for(Quote__c updatedQuote : testQuotes)
        {
           // System.assertEquals(QuoteModel.RETURNED_FROM_FIELD_SOURCING, updatedQuote.Quote_Stage__c);
          // System.assertEquals(QuoteModel.WITH_FIELD_SOURCING, updatedQuote.Quote_Stage__c);
           
        }
        Test.stopTest();
    }
    
    private static testmethod void testReturnQuoteToRequester_Mixed_Batch()
    {
        setupData(50);
        
        Map<Id, String> quoteIdToExpectedStage = new Map<Id, String>();
        
        for(Integer i=0; i<25; i++)
        {
            Quote__c q = testQuotes[i];
            q.OwnerId = nonMerchUser.Id;
            quoteIdToExpectedStage.put(q.Id, QuoteModel.RETURNED_FROM_FIELD_SOURCING);
        }
        
        for(Integer i=25; i<50; i++)
        {
            Quote__c q = testQuotes[i];
            q.OwnerId = merchUser.Id;
            quoteIdToExpectedStage.put(q.Id, QuoteModel.WITH_FIELD_SOURCING);
        }
        
        Test.startTest();
        
        update testQuotes;
        
        testQuotes = [select Id, Quote_Stage__c from Quote__c where Id in :testQuotes];
        
        for(Quote__c updatedQuote : testQuotes)
        {
           // System.assertEquals(quoteIdToExpectedStage.get(updatedQuote.Id), updatedQuote.Quote_Stage__c);
           
           String s = quoteIdToExpectedStage.get(updatedQuote.Id);
           //System.assertEquals(quoteIdToExpectedStage.get(updatedQuote.Id), s);
           
        }
        
        Test.stopTest();
    }
    
}