force-app/main/default/objects/Account/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>Nov 2016 - Data fed in from data warehouse integration.</description>
    <label>Stratification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zilliant_Active__c.field-meta.xml
<CustomField>
    <fullName>Zilliant_Active__c</fullName>
    <description>Updated by data warehouse. 
N – Customer not in Zilliant
Y – Customer in Legacy Zilliant
AI - Customer in Zilliant IQ</description>
    <inlineHelpText>N – Customer not in Zilliant
Y – Customer in Legacy Zilliant
AI - Customer in Zilliant IQ</inlineHelpText>
    <label>Zilliant-Active</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvoAAE</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Brands__c/Brands__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Common Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Price_List__c/Customer_Price_List__c.object-meta.xml
<CustomObject>
    <description>Custom object to represent a scheduled CPL. Records only saved if they are scheduled for external. External/Internal records can be download for xls and pdf and the values pulled in are based on the filter selections of the custom fields on this object.</description>
    <label>Customer Price List</label>
    <nameField>
        <label>Customer Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Price_List__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the contract. Used for the Internal record type.</description>
    <label>Agreement</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Customer Price Lists</relationshipLabel>
    <relationshipName>Customer_Price_Lists</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Brands__c.field-meta.xml
<CustomField>
    <fullName>Brands__c</fullName>
    <description>Displays as a multi-select in the CPL form but is a text field. Defaults to All Brands which searches for all brands, but if a user selects one or multiple then the query will only search for the selections. Filter selections available is both controlling and dynamic to all CBSS selections and Division.</description>
    <inlineHelpText>Search All Brands within the agreement or search to filter the results.</inlineHelpText>
    <label>Brands</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Classes__c.field-meta.xml
<CustomField>
    <fullName>Classes__c</fullName>
    <label>Classes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <description>Free-form email address section</description>
    <inlineHelpText>This field is required to schedule a CPL.

Use a line break to separate multiple email recipients.</inlineHelpText>
    <label>Customer Email</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Displays as a multi-select in the CPL form but is a text field. Defaults to All Divisions which searches for all products in the agreement, but if a user selects one or multiple among the list of servicing divisions on the products of published contract line items then the query will only search for the selections. Filter selections available is both controlling and dynamic to Class and Brand</description>
    <inlineHelpText>Search All Divisions within the agreement or search to filter the results.</inlineHelpText>
    <label>Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Regional_National_Filter__c.field-meta.xml
<CustomField>
    <fullName>Regional_National_Filter__c</fullName>
    <description>Either shows products just on this agreement, on the agreement&apos;s parent (regional), or on the agreement&apos;s grandparent (national)</description>
    <label>Regional/National Filter</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Show Current and Chain Account Pricing</fullName>
                <default>true</default>
                <label>Show Current and Chain Account Pricing</label>
            </value>
            <value>
                <fullName>Show National Agreement Lines (if any)</fullName>
            </value>
            <value>
                <fullName>Ignore Regional Chain AND National Agreement Lines (if any)</fullName>
            </value>
            <value>
                <fullName>Show Chain Accounts Only</fullName>
            </value>
            <value>
                <fullName>Show Regional Chain AND National Agreement Lines (if any)</fullName>
                <isActive>false</isActive>
                <label>Show Regional Chain AND National Agreement Lines (if any)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/fields/Segments__c.field-meta.xml
<CustomField>
    <fullName>Segments__c</fullName>
    <description>Displays as a multi-select in the CPL form but is a text field. Defaults to All Segments which searches for all products in the agreement, but if a user selects one or multiple among the list of segments on the products of published contract line items then the query will only search for the selections. Filter selections available is both controlling and dynamic to Class and Brand and Division</description>
    <inlineHelpText>Search All Segments within the agreement or search to filter the results.</inlineHelpText>
    <label>Segments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Price_List__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <description>Schedule a branded pdf or xls to be sent to your customer</description>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CPLViewControllerTest.cls
@isTest
public class CPLViewControllerTest 
{
    @testSetup static void createPolicyType(){
        List<zpl__PolicyType__c> lPolicyType = new List<zpl__PolicyType__c>{new zpl__PolicyType__c(Name = 'CWT Fixed', zpl__PolicyTypeId__c = 'cwtFixed'), 
            																new zpl__PolicyType__c(Name = 'Fixed Price', zpl__PolicyTypeId__c = 'fixedPrice'),
            																new zpl__PolicyType__c(Name = 'List Down', zpl__PolicyTypeId__c = 'listDown'), 
            																new zpl__PolicyType__c(Name = 'Maintain GTM', zpl__PolicyTypeId__c = 'maintainGTM'),
            																new zpl__PolicyType__c(Name = 'Natl Account', zpl__PolicyTypeId__c = 'nationalAccount')};
       insert lPolicyType;
    }
    
	@isTest
	public static void CPLView_Fields_test() 
	{
		Test.startTest();
		List<FieldSetMember> fields = CPLViewController.CPLView_Fields;
		Test.stopTest();

		System.assert(fields != null, 'We expect the field set to not be null.');
		System.assert(fields.size() > 0, 'We expect the field set to be populated.');
	}

	@isTest
	public static void getDefaultCPL_test()
	{
		Id recordTypeId = Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get('External').getRecordTypeId();

		Test.startTest();
		Customer_Price_List__c cpl = CPLViewController.getDefaultCPL(recordTypeId);
		Test.stopTest();

		System.assertEquals(cpl.Id, null, 'We expect there to be no Id on the CPL.');
		System.assert(cpl.Regional_National_Filter__c != null, 'We expect the default fields to be populated.');
	}

	@isTest
	public static void getCPLById_test()
	{
		UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
			.tag('Account')
            .property('Zilliant_Active__c').assign('AI');

		insert UnitTest.get('Account').getList();

		UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
			.tag('Agreement')
			.property('AccountId').assignFrom('Account');

		insert UnitTest.get('Agreement').getList();

		UnitTest.addData(SObjectFactory.build(1, Customer_Price_List__c.SObjectType))
			.tag('Customer Price List')
			.property('Agreement__c').assignFrom('Agreement')
			.property('Regional_National_Filter__c').assign('Show Current and Chain Account Pricing')
            .property('Customer_Email__c').assign('test@test.com');

		insert UnitTest.get('Customer Price List').getList();

		Customer_Price_List__c cpl = (Customer_Price_List__c) UnitTest.get('Customer Price List').getList()[0];

		Test.startTest();
		Customer_Price_List__c actual = CPLViewController.getCPLById(cpl.Id);
		Test.stopTest();

		System.assert(actual != null, 'We expect a valid CPL to be returned.');
		System.assertEquals(cpl.Regional_National_Filter__c, actual.Regional_National_Filter__c, 'We expect the original and the queried record to be the same');
	}

	@isTest
	public static void getRecordTypeById_testSuccess()
	{
		String expectedRecordTypeName = 'External';
		String recordTypeId = Schema.SObjectType.Customer_Price_List__c.getRecordTypeInfosByName().get(expectedRecordTypeName).getRecordTypeId();
		
		Test.startTest();
		String actualRecordTypeName = CPLViewController.getRecordTypeById(recordTypeId);
		Test.stopTest();

		System.assertEquals(expectedRecordTypeName, actualRecordTypeName, 'We expect the returned record type name to match the input id.');
	}

	@isTest
	public static void getRecordTypeById_testNull()
	{	
		Test.startTest();
		try 
		{
			String actualRecordTypeName = CPLViewController.getRecordTypeById(null);
		}
		catch (AuraHandledException e)
		{
			System.assertEquals('Attempt to de-reference a null object', e.getMessage(), 'We expect an error to be thrown of the correct type and message.');
		}
		Test.stopTest();
	}

	@isTest
	public static void getSalesRepOptions_testMultiple()
	{
		Integer numberOfShipTos = 5;
		Integer numberOfUsers = numberOfShipTos + 1;

		List<User> users = new List<User>();
		for (Integer i = 0; i < numberOfUsers; i++)
		{
			User user = new User(
				IsActive = true,
				LastName = 'Doe',
				LocaleSidKey = 'en_US',
				LanguageLocaleKey = 'en_US',
				EmailEncodingKey = 'ISO-8859-1',
				Email = 'testxxx000' +'@test.com',
				TimeZoneSidKey = 'America/New_York',
				ProfileId = (Id) SObjectParentProviders.standardProfileProvider.getValue(),
				Country = 'USA',
				Alias = 'ALIAS' + i, //new SObjectFieldProviders.UniqueFixedLengthStringProvider('abc', 7),
				Network_Id__c = 'ALIAS' + i, //User.Alias,
				CommunityNickname = (String) new SObjectFieldProviders.UniqueStringProvider('johndoe').getValue(),
				Username = (String) new SObjectFieldProviders.UniqueStringProvider('test_xyz=test@example.com').getValue()
			);

			users.add(user);
		}

		UnitTest.addData(users)
			.tag('Users');

		insert UnitTest.get('Users').getList();

		UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
			.tag('Account')
			.property('OwnerId').assignFrom('Users')
            .property('Zilliant_Active__c').assign('AI');

		insert UnitTest.get('Account').getList();

		UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
			.tag('Agreement')
			.property('AccountId').assignFrom('Account');

		insert UnitTest.get('Agreement').getList();

		UnitTest.addData(SObjectFactory.build(numberOfShipTos, Ship_To__c.SObjectType))
			.tag('Ship Tos')
			.property('Bill_To_Account__c').assignFrom('Account')
			.property('Account_Owner__c').assignFrom('Users');

		insert UnitTest.get('Ship Tos').getList();

		Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];

		Test.startTest();
		List<User> salesRepOptions = CPLViewController.getSalesRepOptions(agreement.Id);
		Test.stopTest();

		System.assertEquals(1 + numberOfShipTos, salesRepOptions.size(), 'We expect the correct number of sales rep options to be returned.');
	}

	@isTest
	public static void getSalesRepOptions_testSingle()
	{
		UnitTest.addData(SObjectFactory.build(1, User.SObjectType))
			.tag('User');

		insert UnitTest.get('User').getList();

		UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
			.tag('Account')
			.property('OwnerId').assignFrom('User')
            .property('Zilliant_Active__c').assign('AI');

		insert UnitTest.get('Account').getList();

		UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
			.tag('Agreement')
			.property('AccountId').assignFrom('Account');

		insert UnitTest.get('Agreement').getList();

		Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];

		Test.startTest();
		List<User> salesRepOptions = CPLViewController.getSalesRepOptions(agreement.Id);
		Test.stopTest();

		System.assertEquals(1, salesRepOptions.size(), 'We expect the correct number of sales rep options to be returned.');
	}

	@isTest
	public static void getCustomerPriceListName_test()
	{
		String testAccountName = 'Test Account';

		UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
			.tag('Account')
			.property('Name').assign(testAccountName)
            .property('Zilliant_Active__c').assign('AI');

		insert UnitTest.get('Account').getList();

		UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
			.tag('Agreement')
			.property('AccountId').assignFrom('Account');

		insert UnitTest.get('Agreement').getList();

		Contract agreement = (Contract) UnitTest.get('Agreement').getList()[0];
		String expectedCPLName = 'CPL: ' + testAccountName;

		Test.startTest();
		String actualCPLName = CPLViewController.getCustomerPriceListName(agreement.Id);
		Test.stopTest();

		System.assertEquals(expectedCPLName, actualCPLName, 'We expect the generated CPL name to include the correct account name');
	}

	@isTest
	public static void getDependentPicklistValues_testNoFilters()
	{
		Integer numberOfEachClassification = 5;
		Integer numberOfAgreementLineItems = 5;

		UnitTest.addData(SObjectFactory.build(numberOfEachClassification, Servicing_Division__c.SObjectType))
			.tag('Divisions');

		insert UnitTest.get('Divisions').getList();

		List<String> segments = new List<String>();
		List<String> classes = new List<String>();
		List<String> brands = new List<String>();

		for (Integer i = 0; i < numberOfEachClassification; i++)
		{
			segments.add('Test Segment ' + i);
			classes.add('Test Class ' + i);
			brands.add('Test Brand ' + i);
		}

		UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
			.tag('Account')
            .property('Zilliant_Active__c').assign('AI');

		insert UnitTest.get('Account').getList();

		UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
			.tag('Agreement')
			.property('AccountId').assignFrom('Account');

		insert UnitTest.get('Agreement').getList();

		UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
			.tag('Products');

		insert UnitTest.get('Products').getList();
		
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
		UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
			.tag('Agreement Line Items')
			.property('zpl__Contract__c').assignFrom('Agreement')
			.property('zpl__Product__c').assignFrom('Products')
			.property('Division__c').assignFrom('Divisions')
			.property('Segment__c').assignFrom(segments)
			.property('Class__c').assignFrom(classes)
			.property('Brand__c').assignFrom(brands)            
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('zpl__LineLevel__c').assign(level.id)
            .property('Net_Price__c').assign(200);

		insert UnitTest.get('Agreement Line Items').getList();

		UnitTest.addData(SObjectFactory.build(1, Customer_Price_List__c.SObjectType))
			.tag('Customer Price List')
			.property('Agreement__c').assignFrom('Agreement')
			.property('Effective_Date__c').assign(Date.today());

		Customer_Price_List__c cpl = (Customer_Price_List__c) UnitTest.get('Customer Price List').getList()[0];
		
		Test.startTest();
		Map<String, List<CPLViewController.DependentPicklistOption>> actualOptions = CPLViewController.getDependentPicklistValues(cpl);
		Test.stopTest();

		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Division__c').size(), 'We expect the correct number of options to be returned for divisions.');
		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Segments__c').size(), 'We expect the correct number of options to be returned for segments.');
		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Classes__c').size(), 'We expect the correct number of options to be returned for classes.');
		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Brands__c').size(), 'We expect the correct number of options to be returned for brands.');
	}

	@isTest
	public static void getDependentPicklistValues_testSingleFilter()
	{
		Integer numberOfEachClassification = 5;
		Integer numberOfAgreementLineItems = 5;

		UnitTest.addData(SObjectFactory.build(numberOfEachClassification, Servicing_Division__c.SObjectType))
			.tag('Divisions');

		insert UnitTest.get('Divisions').getList();

		List<String> segments = new List<String>();
		List<String> classes = new List<String>();
		List<String> brands = new List<String>();

		for (Integer i = 0; i < numberOfEachClassification; i++)
		{
			segments.add('Test Segment ' + i);
			classes.add('Test Class ' + i);
			brands.add('Test Brand ' + i);
		}

		UnitTest.addData(SObjectFactory.build(1, Account.SObjectType))
			.tag('Account')
            .property('Zilliant_Active__c').assign('AI');

		insert UnitTest.get('Account').getList();

		UnitTest.addData(SObjectFactory.build(1, Contract.SObjectType))
			.tag('Agreement')
			.property('AccountId').assignFrom('Account');

		insert UnitTest.get('Agreement').getList();

		UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, Product2.SObjectType))
			.tag('Products');

		insert UnitTest.get('Products').getList();
        UnitTest.addData(SObjectFactory.build(1, zpl__ProductSelectorConfiguration__c.SObjectType))
            .tag('Product Selector Configuration to Contract')
            .property('zpl__TargetObject__c').assign('Contract')
            .property('name').assign('Add Contract Products')
            .property('zpl__UniqueNickname__c').assign('DefaultContract');
        insert UnitTest.get('Product Selector Configuration to Contract').getList();
        zpl__ProductSelectorConfiguration__c testPSconfig = (zpl__ProductSelectorConfiguration__c) UnitTest.get('Product Selector Configuration to Contract').getList()[0];
        UnitTest.addData(SObjectFactory.build(1, zpl__LineLevel__c.SObjectType))
            .tag('Set Level')
            .property('Name').assign('Set')
            .property('zpl__Position__c').assign(2)
            .property('zpl__ProductSelectorConfiguration__c').assign(testPSconfig.Id);
        insert UnitTest.get('Set Level').getList();
        zpl__LineLevel__c level = (zpl__LineLevel__c) UnitTest.get('Set Level').getList()[0];
        List<String> levelValue = new List<String>();
        for (Integer i = 0; i < numberOfAgreementLineItems; i++)
        {
            levelValue.add('Test LevelValue ' + i);
        } 
        
		UnitTest.addData(SObjectFactory.build(numberOfAgreementLineItems, zpl__ContractLineItem__c.SObjectType))
			.tag('Agreement Line Items')
			.property('zpl__Contract__c').assignFrom('Agreement')
			.property('zpl__Product__c').assignFrom('Products')
			.property('Division__c').assignFrom('Divisions')
			.property('Segment__c').assignFrom(segments)
			.property('Class__c').assignFrom(classes)
			.property('Brand__c').assignFrom(brands)
            .property('zpl__Status__c').assign('Published')
            .property('zpl__LevelValue__c').assignFrom(levelValue)
            .property('Net_Price__c').assign(200)
            .property('zpl__LineLevel__c').assign(level.id);

		insert UnitTest.get('Agreement Line Items').getList();

		UnitTest.addData(SObjectFactory.build(1, Customer_Price_List__c.SObjectType))
			.tag('Customer Price List')
			.property('Agreement__c').assignFrom('Agreement')
			.property('Effective_Date__c').assign(Date.today())
			.property('Brands__c').assign(String.join(brands, ';'));

		Customer_Price_List__c cpl = (Customer_Price_List__c) UnitTest.get('Customer Price List').getList()[0];
		
		Test.startTest();
		Map<String, List<CPLViewController.DependentPicklistOption>> actualOptions = CPLViewController.getDependentPicklistValues(cpl);
		Test.stopTest();

		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Division__c').size(), 'We expect the correct number of options to be returned for divisions.');
		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Segments__c').size(), 'We expect the correct number of options to be returned for segments.');
		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Classes__c').size(), 'We expect the correct number of options to be returned for classes.');
		System.assertEquals(numberOfAgreementLineItems, actualOptions.get('Brands__c').size(), 'We expect the correct number of options to be returned for brands.');
	}
}