force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Servicing_Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division_Name__c</fullName>
    <description>Pulls the Servicing Division Name. Currently used in the Account &amp; Lead Visibility page for searching divisions.</description>
    <formula>Servicing_Division__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <color>#E27001</color>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <color>#66E9BD</color>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#F96FB7</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Sent to Customer</fullName>
                <color>#0B6FCE</color>
                <label>Sent to Customer</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <color>#CC0000</color>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Won</fullName>
                <color>#009900</color>
                <label>Won</label>
            </value>
            <value>
                <fullName>Returned From Field Sourcing</fullName>
                <color>#641CCF</color>
                <label>Returned From Field Sourcing</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <color>#8F6429</color>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Requires Additional Follow-up</fullName>
                <color>#CC33CC</color>
                <label>Requires Additional Follow-up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <formula>/* OLD FORMULA */ 
/* 
IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.Division_Code__c, IF( Ship_To_Account__r.Legacy_Division_Cd__c = &quot;&quot;, Account__r.Legacy_Division_Cd__c, Ship_To_Account__r.Legacy_Division_Cd__c)) 
*/ 

IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Code__c, 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, BLANKVALUE(Account__r.Legacy_Division_Cd__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c))) 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division_Name__c</fullName>
    <formula>IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Desc__c, BLANKVALUE(Account__r.Servicing_Division__r.Name, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Name)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Desc__c, 

BLANKVALUE(Account__r.Legacy_Division_Desc__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Name, 
BLANKVALUE(Account__r.Legacy_Division_Desc__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Name))) 
))</formula>
    <label>Servicing Division Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuotesModel.cls
/**
 Objective: Container that holds all the business logic attached 
 			with Quote__c and handles all the processing  
 			delegated by QuotesQuoteContExt
 Developer: Hiremath, Naveen - Bluewolf     
*/
public with sharing class QuotesModel {
	/*
	private final static String DIRECT_QUOTE = 'Direct';
	private final static String WITH_MERCHANDISER = 'With Merchandiser';
	*/
	/**
	 Maintain a reference to Quote__c object
	*/
	private final Quote__c quote;
	
	/**
	 Immutable reference to Quote Line Item Model
	*/
	private final QuoteLineItemModel quoteLineItemModel;
	
	/**
	 Quote__c enjoys a "has-a" relationship with Product2 
	*/
	private final ProductModel productModel;
	
	private Boolean enableRetryOnCreateOrder;
	
	/**
	 Accessor method that returns a reference to Quote__c
	*/
	public Quote__c getQuote() {
		
		return this.quote;
		
	}
	
	/**
	 Getter that returns a reference to the aggregated
	 product Model instance 
	*/
	public ProductModel getProductModel() {
		
		return this.productModel;
		
	}
	
	/**
	 Getter that returns a reference to the aggregated
	 Quote Line Item Model instance
	*/
	public QuoteLineItemModel getQuoteLineItemModel() {
		
		return this.quoteLineItemModel;
	}
	
	/**
	 Calculate Pricing and Availability for this product
	*//*
	public List<String> getPandAForProduct(final Integer rowIndex) {
		
		return quoteLineItemModel.getPandAForProduct(rowIndex);
			
	}*/
	/*
	public Boolean getEnableRetryOnCreateOrder() {
		
		return this.enableRetryOnCreateOrder;
	}*/
	/*
	public PageReference getQuotes() {
	
		PageReference quotes = Page.Quotes;
		quotes.getParameters().put('id', this.quote.Id);
		
		return quotes.setRedirect(false); 
			
	}*/
	/*
	public PageReference getSendToMerchandiser() {
	
		PageReference merchandiserQuoting = Page.SendToMerchandiser;
		merchandiserQuoting.getParameters().put('id', this.quote.Id);
		
		return merchandiserQuoting.setRedirect(false);
			
	}*/
	/*
	public void setEnableRetryOnCreateOrder(Boolean value) {
		
		this.enableRetryOnCreateOrder = value;
		
	}*/
	
	/**
	 Adding Quote Line Items on a Quote is dependent on the 
	 product search results
	*//*
	public void addQLI(ProductModel productSearch) {

		quoteLineItemModel.createQLI(productSearch.getSearchResults());
			
	}*/
	
	/**
	 Special Line Item is a default customizable QLI on the quote
	*//*
	public void addSpecialQLI() {
		
		quoteLineItemModel.createSpecialQLI();
	}*/
	
	/**
	 Move the selected line item to thrash container
	*//*
	public void deleteQLI(final Integer rowIndex) {
		
		quoteLineItemModel.deleteQLI(rowIndex);
		
	}*/
	
	/**
	 Clone the line item at the given index 
	*//*
	public void cloneQLI(final Integer rowIndex) {
	
		quoteLineItemModel.cloneQLI(rowIndex);
			
	}*/
	
	/**
	 Perform calculation on Extended Price
	*//*
	public String calcExtendedPrice(final Integer rowIndex) {
	
		return quoteLineItemModel.calcExtendedPrice(rowIndex);
			
	}*/
	
	/**
	 Show Pricing and Availability for this product
	*//*
	public String showPandAForProduct(final Integer rowIndex) {
		
		return quoteLineItemModel.showPandAForProduct(rowIndex);
			
	}*/
	/*
	public List<String> validateCreateOrder() {
	
		List<String> pageMessages = new List<String>();
		
		if(quote.Account__r.RecordType.Name == 'Prospect') {	
				
			pageMessages.add('Orders cannot be created for Prospect accounts.');
			
		}
		
		if(quote.Ship_To__c == null) {
			
			pageMessages.add('A Ship To address must be selected before creating an order.  Please go back to the quote and click the "Select Ship To Address" button before clicking the "Create Order" button.');
			
		}
		
		if(quote.Expiration_Date__c < System.today()) {
			
			pageMessages.add('This quote has expired and cannot be submitted for an order request.');
			
		}
		
		pageMessages.addAll(quoteLineItemModel.validateLineItems(productModel.getFreightCodes()));
		
		this.enableRetryOnCreateOrder = (pageMessages.isEmpty()) ? Consts.ENABLE : Consts.DISABLE;
		
		return pageMessages;
		
	}*/
	
	/**
	 Orders can be created against a quote
	*//*
	public List<String> createOrder() {
		
		List<String> pageMessages = quoteLineItemModel.createOrder();
					
		return pageMessages; 
			
	}*/
	
	/**
	 Before line items are saved they must be checked for freight lines
	 and price 
	*//*
	public List<String> validateSave() {
		
		List<String> messages = new List<String>();
		
		// Quote header validation rules
        if(this.quote.Shipment_Method__c == DIRECT_QUOTE && 
           !quoteLineItemModel.validateFreightLines(productModel.getFreightCodes())) {
        	  
            messages.add(Consts.PAGE_MSG_NO_FREIGHT_LINES_ON_DIRECT_QUOTE);
            return messages;
            
        }
        
        messages = quoteLineItemModel.validateCostUOMPriceUOMMismatch();
        if(!messages.isEmpty()) return messages;
        
        return messages;
        
	}*/
	
	/**
	 Invokes upsert on the selected line items and delete on
	 the line items that were moved to thrash
	*//*
	public void saveQLI() {
	
		quoteLineItemModel.upsertQLIs();
		quoteLineItemModel.deleteQLIs();
		
	}*/
	
	/**
	 Add the selected freight to our selected products basket
	*//*
	public void addFreight() {
	
		String freightName = productModel.getSelectedFreight();
		String freightCode = productModel.getSelectedFreightCode();
		
		if(freightName != Consts.SELECT_OPTION_NONE && 
		   freightCode != Consts.SELECT_OPTION_NONE) {
			
			quoteLineItemModel.createFreight(freightCode, freightName);
			
		}
		
	}*/
	
	/**
	 Check to see the state of Quote_Stage__c
	*//*
	public String validateSendToMerchandiser() {
	
		String message;
		if(this.quote.Quote_Stage__c == WITH_MERCHANDISER) {
			message = 'This Quote is already marked as \'With Merchandiser\'.  If you would like to update the Primary Merchandising Segment, please do so, otherwise, please hit \'Cancel\' to return to the Quote.';	
		}
		
		return message;
		
	}*/
	
	/**
	 Update the quote stage
	*//*
	public List<String> saveMerchandiserStage() {
	
		List<String> messages = new List<String>();		
		this.quote.Quote_Stage__c = WITH_MERCHANDISER;
		
		try {
			update quote;
		}
		catch(Exception e) {			
			messages.add(e.getMessage());
		}	
		
		return messages;
		
	}*/
	
	/**
	 Identifies the default service division for this 
	 quote
	*/
	private void selectDefaultDivison() {
	
		List<String> defaultDivisionToBeSelected = new List<String>();
		 
		for(Servicing_Division__c div :productModel.getServiceDivisions()) {
			
			if(quote.Servicing_Division_Name__c == div.Name) {
				
				defaultDivisionToBeSelected.add(div.Id);
				break;				
			}
			
		}
		
		productModel.setSelectedDivisions(defaultDivisionToBeSelected);	
	}
	
	/**
	 Instantiates QuotesModel with a quote and a ProductModel 
	 that maintains a 'has-a' relationship
	*/
	public QuotesModel(Quote__c quote, ProductModel productModel) {
		
		this(quote);
		
		/*
		 Maintain an aggregation to Product Model that 
		 facilitates product search 
		*/
		this.productModel = productModel;
		
		/*
		 The default division name for this quote must be 
		 selected
		*/
		this.selectDefaultDivison();
		
		/**
		 A Quote can have existing Quote Line Items 
		*/
		/*
		List<Quote_Line_Item__c> existingQuoteLineItems = QuoteLineItemServices.getQuoteLineItems(quote.Id);
		this.quoteLineItemModel = (!existingQuoteLineItems.isEmpty()) ?
								  new QuoteLineItemModel(this, new Quote_Line_Item__c(), existingQuoteLineItems) :
								  new QuoteLineItemModel(this, new Quote_Line_Item__c());
		*/
	}
	
	/**
	 Explicit constructor that accepts a Quote__c reference
	 and with no aggregations 
	*/
	public QuotesModel(Quote__c quote) {
		
		this.quote = QuoteServices.getQuote(quote.Id);
			
	}

}