force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ship_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Number__c</fullName>
    <externalId>true</externalId>
    <label>Ship To Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009OvZAAU</description>
    <label>Prospect</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Customer Comments (will print on Quote)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Number_of_Orders_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Orders_Submitted__c</fullName>
    <label>Total Times Processed for Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <inlineHelpText>Requested Delivery Date updates the field &apos;Projected Delivery Date&apos; at the quote line. If different dates apply to lines, that can be updated in that line&apos;s &apos;Additional Details&apos;.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <formula>/* OLD FORMULA */ 
/* 
IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.Division_Code__c, IF( Ship_To_Account__r.Legacy_Division_Cd__c = &quot;&quot;, Account__r.Legacy_Division_Cd__c, Ship_To_Account__r.Legacy_Division_Cd__c)) 
*/ 

IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Code__c, 
BLANKVALUE(Account__r.Legacy_Division_Cd__c, BLANKVALUE(Account__r.Servicing_Division__r.Division_Code__c, BLANKVALUE(Account__r.Legacy_Division_Cd__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Division_Code__c))) 
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Ship_To__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Ship_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Number__c</fullName>
    <formula>IF(LEN(Ship_To__r.Ship_To_Code__c) = 12, RIGHT( Ship_To__r.Ship_To_Code__c , 6), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ship To Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/System_Code__c.field-meta.xml
<CustomField>
    <fullName>System_Code__c</fullName>
    <formula>IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, Account__r.Servicing_Division__r.System_Code__c, IF( Ship_To_Account__r.Legacy_System_Cd__c = &quot;&quot;, Account__r.Legacy_System_Cd__c, Ship_To_Account__r.Legacy_System_Cd__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>System Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Bid_number_Contract_number__c.field-meta.xml
<CustomField>
    <fullName>Bid_number_Contract_number__c</fullName>
    <label>Bid #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Price_unit_of_measure__c</fullName>
    <label>Price/Cost UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Projected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Quantity_unit_of_measure__c</fullName>
    <label>Qty UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Special_Item__c.field-meta.xml
<CustomField>
    <fullName>Special_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Name</label>
    <referenceTo>Vendor_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxxEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Division__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Area for SFDC Admins to put notes</description>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/fields/System_Code__c.field-meta.xml
<CustomField>
    <fullName>System_Code__c</fullName>
    <label>System Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Address_Line1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line1__c</fullName>
    <label>Address Line1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Address_Line2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line2__c</fullName>
    <label>Address Line2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Ship_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Number__c</fullName>
    <externalId>true</externalId>
    <label>Ship To Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OrderRequestQLIControllerExtension.cls
public class OrderRequestQLIControllerExtension
{
    private final ApexPages.StandardSetController qliSetController;
    public List<Quote_Line_Item__c> selectedQuoteLineItems {get; private set;}
    private final Set<String> SUNDRY_CODES = new Set<String>{'CFREIGHT', 'CFREIGHT3P', 'NFREIGHT',
																'SFREIGHT', 'UFREIGHT', 'UFREIGHT3P'};

    public OrderRequestQLIControllerExtension(ApexPages.StandardSetController stdSetController)
    {
        qliSetController = stdSetController;
        
        showRetry = true;
        
        //Validation rules
        if(!isValidQuote)
        {
            showRetry = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This page cannot be accessed directly.  It can only be reached from the "Create Order" button on a quote record.'));
            return;
        }
        if(!hasSelectedRecords)
        {
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No Quote Line Items have been selected. Please click the "Back" button and select at least one record.'));
            showRetry = false;
            isValidQuote = false;
            return;
        }
        //Validation rules passed, continue
    }
    //Properties
    public Quote__c quote {get; set;}
    
    public Boolean showRetry {get; set;}
    
    public Boolean isValidQuote
    {
        get
        {
            if(isValidQuote == null)
            {
                if(ApexPages.currentPage().getParameters().get('id') == null)
                {
                    isValidQuote = false;
                    return isValidQuote;
                }
                else
                {
                    isValidQuote = true;
                    return isValidQuote;
                }
            }
            return isValidQuote;
        }
        set
        {
            isValidQuote = value;
        }
    }
    
    public Boolean hasSelectedRecords
    {
        get
        {
            if(this.qliSetController.getSelected().size() > 0)
                return true;
            else
                return false;
        }
    }
    //Methods
    public PageReference postOrderRequest()
    {
        //Validation rules
        if(!isValidQuote)
            return null;
        //Validation rules passed, continue 
        //Get quote header values
        quote = [select Id, Expiration_Date__c, Name, Account__r.Name, Account__r.AccountNumber, Account__r.RecordType.Name, Customer_Contact__r.Name, Ship_To_Number__c, Ship_To__c, Ship_To__r.Name, Ship_To__r.State__c, Ship_To__r.Postal_Code__c, Ship_To__r.City__c, Ship_To__r.Address_Line2__c, Ship_To__r.Address_Line1__c, Servicing_Division__c, System_Code__c, Shipment_Method__c, Requested_Delivery_Date__c, Comments__c, PO_Number__c, Number_of_Orders_Submitted__c from Quote__c where Id = :ApexPages.currentPage().getParameters().get('id')];
        //Post query validation rules
        if(quote.Account__r.RecordType.Name == 'Prospect')
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Orders cannot be created for Prospect accounts.'));
            isValidQuote = false;
            showRetry = false;
            return null;
        }
        if(quote.Ship_To__c == null)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'A Ship To address must be selected before creating an order.  Please go back to the quote and click the "Select Ship To Address" button before clicking the "Create Order" button.'));
            isValidQuote = false;
            showRetry = false;
            return null;
        }
        if(quote.Expiration_Date__c < System.today())
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This quote has expired and cannot be submitted for an order request.'));
            isValidQuote = false;
            showRetry = false;
            return null;
        }
        //Validation rules passed, continue 
        //Assign header values to request header
        OrderRequest ordReq = new OrderRequest();
        ordReq.Request.Header.QuoteNum = quote.Name;
    	ordReq.Request.Header.BillToCode = quote.Account__r.AccountNumber;
    	ordReq.Request.Header.BillToName = quote.Account__r.Name;
    	ordReq.Request.Header.CustomerContactName = quote.Customer_Contact__r.Name;
    	ordReq.Request.Header.ShipToCode = quote.Ship_To_Number__c;
    	ordReq.Request.Header.ShipToName = quote.Ship_To__r.Name;
    	ordReq.Request.Header.ShipToStreet = quote.Ship_To__r.Address_Line1__c + quote.Ship_To__r.Address_Line2__c == null? '' :', ' + quote.Ship_To__r.Address_Line2__c;
    	ordReq.Request.Header.ShipToCity = quote.Ship_To__r.City__c;
    	ordReq.Request.Header.ShipToState = quote.Ship_To__r.State__c;
    	ordReq.Request.Header.ShipToZip = quote.Ship_To__r.Postal_Code__c;
    	ordReq.Request.Header.DivisionCode = quote.Servicing_Division__c;
    	ordReq.Request.Header.SystemCode = quote.System_Code__c;
    	ordReq.Request.Header.RequestedDeliveryDate = quote.Requested_Delivery_Date__c;
    	ordReq.Request.Header.ShipmentMethod = quote.Shipment_Method__c;
    	// Temporarily stop passing CustomerComments field as per Michelle on 8/10
    	//ordReq.Request.Header.CustomerComments = quote.Comments__c;
    	ordReq.Request.Header.PoNumber = quote.PO_Number__c;
        //Loop through selected rows
        Double unitPriceTotal = 0;
        
        selectedQuoteLineItems = (List<Quote_Line_Item__c>)this.qliSetController.getSelected();
        selectedQuoteLineItems = [select Id, Special_Item__c, Projected_Delivery_Date__c, Cost__c, Product_Code__c,
        							Qty__c, Quantity_unit_of_measure__c, Product_Description__c, Price__c, Price_unit_of_measure__c,
        							Bid_number_Contract_number__c, Vendor_Name__r.Name 
        							from Quote_Line_Item__c where Id in :selectedQuoteLineItems
        							order by CreatedDate ASC];
        
        for(Quote_Line_Item__c qli : selectedQuoteLineItems)
        {
        	//Line items validation rules
        	if(qli.Special_Item__c)
        	{
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Orders cannot be created for special item lines.  Please go back to the quote and do not select any special items before clicking the "Create Order" button.'));
	            isValidQuote = false;
	            showRetry = false;
        		return null;
        	} 
        	if(qli.Projected_Delivery_Date__c == null)
        	{
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Projected Delivery Date is required on all quote line items being submitted for an order request.  Please edit the line items that are being submitted and add projected delivery dates.'));
	            isValidQuote = false;
	            showRetry = false;
        		return null;
        	}
        	if(quote.Shipment_Method__c == 'Direct' && 
        		(!SUNDRY_CODES.contains(qli.Product_Code__c)) &&
        		(qli.Cost__c == 0 || qli.Cost__c == null))
        	{
	            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Cost is required for all item codes being submitted for a Direct order request.  Please edit the item codes that are being submitted to include the Cost.'));
	            isValidQuote = false;
	            showRetry = false;
        		return null;
        	} 
        	//Validation rules passed, continue
        	OrderRequest.DetailClass detail = new OrderRequest.DetailClass();

	    	detail.Quantity = qli.Qty__c;
	    	detail.QuantityUOM = qli.Quantity_unit_of_measure__c;
	    	detail.ProjectedDeliveryDate = qli.Projected_Delivery_Date__c;
	    	detail.ProductCode = qli.Product_Code__c;
	    	detail.ProductDescription = qli.Product_Description__c;
	    	detail.UnitPrice = qli.Price__c;
	    	detail.UnitPriceUOM = qli.Price_unit_of_measure__c;
	    	detail.UnitCost = qli.Cost__c;
	    	// Temporarily stop passing BidNumber field as per Michelle on 8/10
	    	//detail.BidNumber = qli.Bid_number_Contract_number__c;

	    	unitPriceTotal += qli.Price__c == null? 0: qli.Price__c;
	    	ordReq.Request.Details.add(detail);
        }
    	ordReq.Request.Header.TotalPrice = unitPriceTotal;
        try
        {
        	ordReq.postData();
        }
        catch(Exception e)
        {
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        	return null;
        }

		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Status Code: ' + ordReq.Response.StatusCode + ', Status Message: ' + ordReq.Response.StatusMessage));
		if(ordReq.Response.StatusCode == '202')
		{
			try
			{
				Double numberTimesSubmitted = 0;
				if(quote.Number_of_Orders_Submitted__c == null)
					numberTimesSubmitted = 1;
				else
					numberTimesSubmitted = quote.Number_of_Orders_Submitted__c + 1;
					
				Quote__c quoteToUpdate = new Quote__c( Id=quote.Id,
														Quote_Stage__c = 'Won', 
														Number_of_Orders_Submitted__c = numberTimesSubmitted,
														Last_Submitted_Timestamp__c = System.now());				
				update quoteToUpdate;
				Task taskToInsert = new Task(WhoId=quote.Customer_Contact__c, WhatId=quote.Id, OwnerId=UserInfo.getUserId());
				taskToInsert.Subject = 'Quote Converted to Order';
				taskToInsert.Description = '' + ordReq.Request.Header;
				for(OrderRequest.DetailClass detail : ordReq.Request.Details)
					taskToInsert.Description += '\n\n' + detail;
				taskToInsert.Status = 'Completed';
				taskToInsert.Priority = 'Normal';
				taskToInsert.ActivityDate = System.today();
				insert taskToInsert;
				showRetry = false;
			}
			catch(Exception e)
			{
	        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
	        	return null;
			}
		}
		return null;
    }
}