force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FAP_Specification__c/FAP_Specification__c.object-meta.xml
<CustomObject>
    <description>All dynamic requirements for items on the FAP can be designated in this object</description>
    <label>FAP Specification</label>
    <nameField>
        <label>FAP Definitions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FAP Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FAP_Specification__c/fields/Attachment_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Prefix__c</fullName>
    <label>Attachment Prefix</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAP_Specification__c/fields/File_Varies_by_Opp__c.field-meta.xml
<CustomField>
    <fullName>File_Varies_by_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if this box is checked then the contract will be attached to the opportunity</description>
    <label>File Varies by Opp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pull the division from the opportunity owner&apos;s User record</description>
    <label>zzUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Opportunities (Servicing Division)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestFileAttachmentController.cls
@isTest
private class TestFileAttachmentController
{
	static Account testAccount;
	static Servicing_Division__c  testServicingDivision;
	static Opportunity testOpportunity;
	static Contract existingContractForAccount;
	static String documentType;
	static final String documentTypeAbbr = 'Prefix';
	static final String fileName = 'TestFile.pdf';
	static final String expectedFileName = documentTypeAbbr + fileName;

	
	static void setup(Boolean variesByOpportunity)
	{
		documentType =  (new List<String>(ContractFileManagementCtrl.POSSIBLE_DOCUMENT_TYPES))[0];
		FAP_Specification__c aDocType = TestingUtils.createFAPSpecification(documentType, new Map<String,Object> {'Attachment_Prefix__c'=>documentTypeAbbr,'File_Varies_by_Opp__c'=>variesByOpportunity}, true);

		testServicingDivision = TestingUtils.createServicingDivision( true );
		testAccount = TestingUtils.createAccount( 'TestAccount', false );
		testAccount.Servicing_Division__c = testServicingDivision.ID;
		insert testAccount;
		testOpportunity = TestingUtils.createOpportunity( testAccount.Id, 'TestOpp', true );
	}
	
	private static testMethod void testAttachFile_NewContract_AttachToAccount()
	{
		setup(ContractFileManagementCtrl.FILE_ON_ACCOUNT);
		Blob bodyOfAttachment = Blob.valueOf( 'Some important attachment' );
		
		FileAttachmentController controller = setupControllerForNewContract(bodyOfAttachment);
		
		Test.startTest();
			controller.attachFile();
		Test.stopTest();
		
		System.assertEquals( true, ApexPages.hasMessages(), 'There should be a page messages on success: ' + ApexPages.getMessages() );
		System.assertEquals( ApexPages.Severity.CONFIRM, ApexPages.getMessages()[0].getSeverity(), 'There should be a confirm page messages on success: ' + ApexPages.getMessages() );
		
		List<Contract> newContracts = [ SELECT Opportunity__c, AccountId, Document_Type__c, Division__c, 
											( SELECT Id, ParentId, Name FROM Attachments) 
											FROM Contract];
		
		System.assertEquals( 1, newContracts.size(), 'There should be one new contract created ' );									
		System.assertEquals( testAccount.Id, newContracts[0].AccountId, 'The new contract should be linked to the right account.' );
		System.assertEquals( null, newContracts[0].Opportunity__c, 'The new contract should not be linked to an opportunity' );
		System.assertEquals( testServicingDivision.Id, newContracts[0].Division__c, 'The new contract should have the same servicing division as that of its account.' );
		System.assertEquals( documentType, newContracts[0].Document_Type__c, 'The new contract should have the specified document type' );
		
		System.assertEquals( 1, newContracts[0].Attachments.size(), 'There should be one new attachment created ' + newContracts[0].Attachments );
		
		Attachment attachedFile = [Select ID, Name, Body From Attachment WHERE ParentId=:newContracts[0].ID]; //Need to do this query seperately to get Body
		
		System.assertEquals( expectedFileName, attachedFile.Name, 'The attachment that is created should have the prefix added to its name' );	
		System.assertEquals(bodyOfAttachment.toString(), attachedFile.Body.toString(),'The attachment body should be updated to reflect the new attachment');
	}
	
	private static FileAttachmentController setupControllerForNewContract(Blob bodyOfAttachment)
	{
		FileAttachmentController controller = new FileAttachmentController();
		controller.accountId = testAccount.Id;
		controller.opportunityId = testOpportunity.Id;
		controller.divisionId = testServicingDivision.Id;
		controller.attachType = documentType;
		controller.existingContractId = null;
		controller.existingAttachmentId = null;
		
		controller.attachment.Name = fileName;
		controller.attachment.Body = bodyOfAttachment; 
		return controller;
	}
	
	private static testMethod void testAttachFile_NewContract()
	{
		setup(ContractFileManagementCtrl.FILE_ON_OPPORTUNITY);
		Blob bodyOfAttachment = Blob.valueOf( 'Some important attachment' );
		FileAttachmentController controller = setupControllerForNewContract(bodyOfAttachment);
		
		Test.startTest();
			controller.attachFile();
		Test.stopTest();
		
		System.assertEquals( true, ApexPages.hasMessages(), 'There should be a page messages on success: ' + ApexPages.getMessages() );
		System.assertEquals( ApexPages.Severity.CONFIRM, ApexPages.getMessages()[0].getSeverity(), 'There should be a confirm page messages on success: ' + ApexPages.getMessages() );
		
		List<Contract> newContracts = [ SELECT Opportunity__c, AccountId, Document_Type__c, Division__c, 
											( SELECT Id, ParentId, Name FROM Attachments) 
											FROM Contract];
		
		System.assertEquals( 1, newContracts.size(), 'There should be one new contract created ' );									
		System.assertEquals( testAccount.Id, newContracts[0].AccountId, 'The new contract should be linked to the right account.' );
		System.assertEquals( testOpportunity.Id, newContracts[0].Opportunity__c, 'The new contract should be linked to the right opportunity.' );
		System.assertEquals( testServicingDivision.Id, newContracts[0].Division__c, 'The new contract should have the same servicing division as that of its account.' );
		System.assertEquals( documentType, newContracts[0].Document_Type__c, 'The new contract should have the specified document type' );
		
		System.assertEquals( 1, newContracts[0].Attachments.size(), 'There should be one new attachment created ' + newContracts[0].Attachments );
		
		Attachment attachedFile = [Select ID, Name, Body From Attachment WHERE ParentId=:newContracts[0].ID]; //Need to do this query seperately to get Body
		
		System.assertEquals( expectedFileName, attachedFile.Name, 'The attachment that is created should have the prefix added to its name' );	
		System.assertEquals(bodyOfAttachment.toString(), attachedFile.Body.toString(),'The attachment body should be updated to reflect the new attachment');	
											
	}
	
	private static testMethod void testAttachFile_ExistingContract()
	{
		final Blob newAttachmentBody = Blob.valueOf( 'Some important attachment' );
		setup(ContractFileManagementCtrl.FILE_ON_OPPORTUNITY);
		Contract testContract = TestingUtils.createContract( testAccount.ID, testAccount.Servicing_Division__c, false );
		testContract.Document_Type__c = documentType;
		testContract.Opportunity__c = testOpportunity.Id;
		insert testContract;
		
		Attachment testOldAttachment = new Attachment();
		testOldAttachment.Name = 'TestAttachment';
		testOldAttachment.Body = blob.valueOf( 'test Attachment body' );
		testOldAttachment.ParentId = testContract.Id;
		insert testOldAttachment;
		
		FileAttachmentController controller = new FileAttachmentController();
		controller.existingContractId = testContract.Id;
		controller.existingAttachmentId = testOldAttachment.Id;
		controller.attachType = documentType;
		
		controller.attachment.Name = fileName;
		controller.attachment.Body = newAttachmentBody;
		Test.startTest();
			controller.attachFile();
		Test.stopTest();
		
		System.assertEquals( true, ApexPages.hasMessages(), 'There should be a confirm page messages on success: ' + ApexPages.getMessages() );
		System.assertEquals( ApexPages.Severity.CONFIRM, ApexPages.getMessages()[0].getSeverity(), 'There should be a confirm page messages on success: ' + ApexPages.getMessages() );
		List<Contract> contracts = [ SELECT Opportunity__c, AccountId, Document_Type__c, Division__c, 
											( SELECT Id, ParentId, Name FROM Attachments) 
											FROM Contract];
											
		
		System.assertEquals( 1, contracts.size(), 'There should be only be one contract' );									
		System.assertEquals( testContract.Id, contracts[0].Id, 'The only contract that exists is the one that existed before. No new contracts should have been created or deleted' );
		System.assertEquals( testAccount.Id, contracts[0].AccountId, 'The contract should still lookup to the right account' );
		System.assertEquals( testOpportunity.Id, contracts[0].Opportunity__c, 'The contract should still lookup to the right opportunity' );
		System.assertEquals( testServicingDivision.Id, contracts[0].Division__c, 'The contract should still lookup to the right servicing division.' );
		System.assertEquals( documentType, contracts[0].Document_Type__c, 'The contract should still have the same document type' );
		
		System.assertEquals( 1, contracts[0].Attachments.size(), 'There should only be one attachment associated to the contract ' + contracts[0].Attachments);
		
		Attachment attachedFile = [Select ID, Name, Body From Attachment WHERE ParentId=:contracts[0].ID]; //Need to do this query seperately to get Body
		
		System.assertEquals( testOldAttachment.Id, attachedFile.Id, 'The attachment id should be the same' );
		System.assertEquals( expectedFileName, attachedFile.Name, 'The attachment name should change to that of the prefix+new attachment name' );		
		System.assertEquals(newAttachmentBody.toString(), attachedFile.Body.toString(),'The attachment body should be updated to reflect the new attachment');			
	}
	
	private static testMethod void testAttachFile_ExistingContractButNoExistingAttachment() {
		final Blob newAttachmentBody = Blob.valueOf( 'Some important attachment' );
		setup(ContractFileManagementCtrl.FILE_ON_OPPORTUNITY);
		Contract testContract = TestingUtils.createContract( testAccount.ID, testAccount.Servicing_Division__c, false );
		testContract.Document_Type__c = documentType;
		testContract.Opportunity__c = testOpportunity.Id;
		insert testContract;
		
		FileAttachmentController controller = new FileAttachmentController();
		controller.existingContractId = testContract.Id;
		controller.existingAttachmentId = null;
		controller.attachType = documentType;
		
		controller.attachment.Name = fileName;
		controller.attachment.Body = newAttachmentBody;
		Test.startTest();
			controller.attachFile();
		Test.stopTest();
		
		System.assertEquals( true, ApexPages.hasMessages(), 'There should be a confirm page messages on success: ' + ApexPages.getMessages() );
		System.assertEquals( ApexPages.Severity.CONFIRM, ApexPages.getMessages()[0].getSeverity(), 'There should be a confirm page messages on success: ' + ApexPages.getMessages() );
		List<Contract> contracts = [ SELECT Opportunity__c, AccountId, Document_Type__c, Division__c, 
											( SELECT Id, ParentId, Name FROM Attachments) 
											FROM Contract];
											
		
		System.assertEquals( 1, contracts.size(), 'There should be only be one contract' );									
		System.assertEquals( testContract.Id, contracts[0].Id, 'The only contract that exists is the one that existed before. No new contracts should have been created or deleted' );
		System.assertEquals( testAccount.Id, contracts[0].AccountId, 'The contract should still lookup to the right account' );
		System.assertEquals( testOpportunity.Id, contracts[0].Opportunity__c, 'The contract should still lookup to the right opportunity' );
		System.assertEquals( testServicingDivision.Id, contracts[0].Division__c, 'The contract should still lookup to the right servicing division.' );
		System.assertEquals( documentType, contracts[0].Document_Type__c, 'The contract should still have the same document type' );
		
		System.assertEquals( 1, contracts[0].Attachments.size(), 'There should only be one attachment associated to the contract ' + contracts[0].Attachments);
		
		Attachment attachedFile = [Select ID, Name, Body From Attachment WHERE ParentId=:contracts[0].ID]; //Need to do this query seperately to get Body
		
		System.assertEquals( expectedFileName, attachedFile.Name, 'The attachment name should change to that of the prefix+new attachment name' );		
		System.assertEquals(newAttachmentBody.toString(), attachedFile.Body.toString(),'The attachment body should be updated to reflect the new attachment');	
		
	}
}