force-app/main/default/objects/Account/fields/Servicing_Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division_Name__c</fullName>
    <description>Pulls the Servicing Division Name. Currently used in the Account &amp; Lead Visibility page for searching divisions.</description>
    <formula>Servicing_Division__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Servicing Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009TNjAAM</description>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Apex_Class_Error_Emails__c/Apex_Class_Error_Emails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specify what users get error emails from failing apex code.</description>
    <label>Apex Class Error Emails</label>
</CustomObject>

force-app/main/default/objects/Apex_Class_Error_Emails__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Count_of_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Line_Items__c</fullName>
    <label>Count of Line Items</label>
    <summaryForeignKey>Quote_Line_Item__c.Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments (will not print)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Stage__c.field-meta.xml
<CustomField>
    <fullName>Quote_Stage__c</fullName>
    <label>Quote Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <color>#E27001</color>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <color>#66E9BD</color>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#F96FB7</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Sent to Customer</fullName>
                <color>#0B6FCE</color>
                <label>Sent to Customer</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <color>#CC0000</color>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Won</fullName>
                <color>#009900</color>
                <label>Won</label>
            </value>
            <value>
                <fullName>Returned From Field Sourcing</fullName>
                <color>#641CCF</color>
                <label>Returned From Field Sourcing</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <color>#8F6429</color>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Requires Additional Follow-up</fullName>
                <color>#CC33CC</color>
                <label>Requires Additional Follow-up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Requested_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Date__c</fullName>
    <inlineHelpText>Requested Delivery Date updates the field &apos;Projected Delivery Date&apos; at the quote line. If different dates apply to lines, that can be updated in that line&apos;s &apos;Additional Details&apos;.</inlineHelpText>
    <label>Requested Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Servicing_Division_Name__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division_Name__c</fullName>
    <formula>IF(Account__r.RecordTypeId = &quot;012700000009OvZ&quot;, 
/* RecordTypeId = Prospect */ 
BLANKVALUE(Account__r.Legacy_Division_Desc__c, BLANKVALUE(Account__r.Servicing_Division__r.Name, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Name)), 
/* RecordTypeId = Customer */ 
BLANKVALUE(Ship_To__r.Legacy_Division_Desc__c, 

BLANKVALUE(Account__r.Legacy_Division_Desc__c, 
BLANKVALUE(Account__r.Servicing_Division__r.Name, 
BLANKVALUE(Account__r.Legacy_Division_Desc__c, Account__r.Primary_Sales_Rep_Name__r.Servicing_Division__r.Name))) 
))</formula>
    <label>Servicing Division Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Shipment_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Method__c</fullName>
    <label>Shipment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>TSB Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vendor_Comments__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Comments__c</fullName>
    <label>Vendor Comments (will print on Quote)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Send_to_field_sourcing__mdt/Send_to_field_sourcing__mdt.object-meta.xml
<CustomObject>
    <description>Quote field values to work order field mapping with default values for work order if Quote fields are null.</description>
    <label>Send to field sourcing</label>
    <pluralLabel>Send to field sourcings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Send_to_field_sourcing__mdt/fields/Field_Data_Numeric_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Data_Numeric_Value__c</fullName>
    <description>Specifies the default number field value for work order if the quote api name field value is blank</description>
    <label>Field Data Numeric Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Send_to_field_sourcing__mdt/fields/Field_Data_Origin_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Data_Origin_API_Name__c</fullName>
    <description>this field will store a quote field api name to be mapped onto work order records when created via the send to field sourcing process on quotes.</description>
    <label>Field Data Origin API name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Send_to_field_sourcing__mdt/fields/Field_Data_Text_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Data_Text_Value__c</fullName>
    <description>this field will store a text value to be mapped onto work order records when created via the send to field sourcing process on quotes if the quote api name field is blank.</description>
    <label>Field Data Text Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Send_to_field_sourcing__mdt/fields/Work_Order_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Field_API_Name__c</fullName>
    <description>this field will store the work order field api name that values will be mapped to when created via the send to field sourcing process on quotes based on the other field values in the metadata record.</description>
    <label>Work Order Field API Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FieldSourcingQuotingController.cls
public with sharing class FieldSourcingQuotingController {
    public List<WorkOrder> workOrdersWithQuoteId;
    public final String EMAIL_SUBJECT = Label.SendToFieldSourcingErrorEmailSubject;
    public Quote__c merchandiserQuote {get; private set;}
    public static final String WITH_FIELD_SOURCING = 'With Field Sourcing';
    
    public List<Send_to_field_sourcing__mdt> quoteToWorkOrderFieldMap{
        get{
            if(quoteToWorkOrderFieldMap == null){
                quoteToWorkOrderFieldMap = [SELECT Id, Field_Data_Origin_API_Name__c, Field_Data_Numeric_Value__c, Field_Data_Text_Value__c, Work_Order_Field_API_Name__c
                                       FROM Send_to_field_sourcing__mdt];
            }
            return quoteToWorkOrderFieldMap;
        }
        set;
    }
    public FieldSourcingQuotingController(ApexPages.StandardController stdController)
    {   
        merchandiserQuote = (Quote__c)stdController.getRecord();

    }
    public WorkOrder thisWorkOrder{get;set;}
    public Boolean noWorkOrders {
        get{
            if(noWorkOrders == null){
                workOrdersWithQuoteId = [SELECT Id, WorkOrderNumber  FROM WorkOrder WHERE Quote__c =: merchandiserQuote.Id];
                
                if(workOrdersWithQuoteId.isEmpty()){
                    noWorkOrders = true;
                }
                else{
                    noWorkOrders = false;
                    thisWorkOrder = workOrdersWithQuoteId[0];
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Work Order ' + workOrdersWithQuoteId[0].WorkOrderNumber + ' ' + Label.SendToFieldSourcingExistingWorkOrder));
                }
            }
            return noWorkOrders;
        
        }set;
    }
    
    public String buildSqlStatement(Id objectId, String objectApiName){
        String sqlString = 'SELECT ';
                                                                         
        for(Send_to_field_sourcing__mdt field : quoteToWorkOrderFieldMap ){
            if(String.isNotBlank(field.Field_Data_Origin_API_Name__c)){
                sqlString += field.Field_Data_Origin_API_Name__c + ', ';
                
            }
            
        }
        sqlString += 'Id FROM ' 
                        + objectApiName + ' WHERE ID = \'' + objectId + '\'';
        
        return sqlString;
    }
    
    public WorkOrder buildWorkOrder(Id quoteId){
        
        WorkOrder newWorkOrder = new WorkOrder();
        
        List<Quote__c> requestFields = [SELECT Id, Name, Servicing_Division_Name__c, Count_of_Line_Items__c, Shipment_Method__c, Requested_Delivery_Date__c, Subject__c, Vendor_Comments__c, Internal_Comments__c 
                                            FROM Quote__c WHERE Id =: quoteId];
                                            
        String requestFieldValue = 'Quote Number: ' + requestFields[0].Name + '\n'
                                        + ' Servicing Division Name: ' + requestFields[0].Servicing_Division_Name__c + '\n'
                                        + ' Shipment Method: ' + requestFields[0].Shipment_Method__c + '\n'
                                        + ' Number of Line Items: ' + requestFields[0].Count_of_Line_Items__c + '\n'
                                        + ' Possible Expected Delivery Date: ' + requestFields[0].Requested_Delivery_Date__c + '\n'
                                        + ' Subject: ' + requestFields[0].Subject__c + '\n'
                                        + ' Internal Comments: ' + requestFields[0].Internal_Comments__c + '\n'
                                        + ' Vendor Comments: ' + requestFields[0].Vendor_Comments__c;
        
        List<Quote__c> recapturedQuote = Database.query(buildSqlStatement(quoteId, 'Quote__c'));
        
        if(!quoteToWorkOrderFieldMap.isEmpty() && !recapturedQuote.isEmpty()){
            for(Send_to_field_sourcing__mdt field : quoteToWorkOrderFieldMap ){
                if(!String.isBlank(String.valueOf(field.Field_Data_Origin_API_Name__c))){
                    newWorkOrder.put('Quote__c', quoteId);
                    newWorkOrder.put('Request__c', requestFieldValue);
                    newWorkOrder.put(field.Work_Order_Field_API_Name__c, recapturedQuote[0].get(field.Field_Data_Origin_API_Name__c));
                }
                else{
                     if(!String.isBlank(String.valueOf(field.Field_Data_Text_Value__c))){
                        newWorkOrder.put('Quote__c', quoteId);
                        newWorkOrder.put('Request__c', requestFieldValue);
                        newWorkOrder.put(field.Work_Order_Field_API_Name__c, field.Field_Data_Text_Value__c);
                    }
                    else if(!String.isBlank(String.valueOf(field.Field_Data_Numeric_Value__c))){
                        newWorkOrder.put('Quote__c', quoteId);
                        newWorkOrder.put('Request__c', requestFieldValue);
                        newWorkOrder.put(field.Work_Order_Field_API_Name__c, field.Field_Data_Numeric_Value__c);
                    }
                    else{
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.SendToFieldSourcingErrorText)); 
                        String body = 'Quote Id: ' + quoteId + 'message';
                        sendErrorEmail(body);
                        newWorkOrder = null;
                        break;
                    }
                }
            }
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.SendToFieldSourcingErrorText));
            Quote__c quoteForEmail = [SELECT Id, Account__r.Name FROM Quote__c WHERE Id =: merchandiserQuote.Id];
            String body = Label.SendToFieldSourcingErrorEmailBody 
                            + '\n Quote Id: ' + merchandiserQuote.Id 
                            + '\n Account Name: ' + quoteForEmail.Account__r.Name 
                            + '\n User Name: ' + UserInfo.getName();
            sendErrorEmail(body);
            newWorkOrder = null;
        }
        return newWorkOrder;
    }
    
    public void populateWorkOrders(WorkOrder wo) {
        try{
            upsert wo;
            thisWorkOrder = wo;
            noWorkOrders = false;
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.SendToFieldSourcingSuccess));
        }
        catch(Exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.SendToFieldSourcingErrorText)); 
            
            Quote__c quoteForEmail = [SELECT Id, Account__r.Name FROM Quote__c WHERE Id =: merchandiserQuote.Id];       
            String body = Label.SendToFieldSourcingErrorEmailBody 
                            + '\n Quote Id: ' + merchandiserQuote.Id 
                            + '\n Account Name: ' + quoteForEmail.Account__r.Name 
                            + '\n User Name: ' + UserInfo.getName();
            sendErrorEmail(body);
        }
    }
    public void sendErrorEmail(String body){
        List<Messaging.SingleEmailMessage> allMail = new List<Messaging.SingleEmailMessage>();
        Map<String, Apex_Class_Error_Emails__c> emailRecipients = Apex_Class_Error_Emails__c.getAll();
        
        for(Apex_Class_Error_Emails__c adminRecord : emailRecipients.values()){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId((Id) adminRecord.User_ID__c);
            mail.setSubject(EMAIL_SUBJECT);
            mail.setPlainTextBody(body);
            allMail.add(mail);
        }
        try{
            Messaging.sendEmail( allMail ); 
        }
        catch(Exception ex){
            
        }
    }
    public void saveAndSetStage()
    {
        merchandiserQuote.Quote_Stage__c = WITH_FIELD_SOURCING;
        try
        {
            update merchandiserQuote;
            WorkOrder workOrderToCreate = buildWorkOrder(merchandiserQuote.Id);

            if(workOrderToCreate != null){
                populateWorkOrders(workOrderToCreate);
            }
        }
        catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        
    }
    
    public PageReference returnToQuote()
    {
        return new PageReference('/' + merchandiserQuote.Id);
    }
    public PageReference goToWorkOrder()
    {
        return new PageReference('/' + thisWorkOrder.Id);
    }
}