force-app/main/default/objects/Account/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Servicing Division does not exist or is inactive.  Please use an active Division.</errorMessage>
        <filterItems>
            <field>Servicing_Division__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000swa5</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Id</field>
            <operation>equals</operation>
            <value>00e70000000j606</value>
        </filterItems>
        <infoMessage>1 OR 2 OR 3</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AIQ_CWTItem__c/AIQ_CWTItem__c.object-meta.xml
<CustomObject>
    <label>CWT Item</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CWT Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AIQZilliantConfiguration__c/AIQZilliantConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AIQZilliantConfiguration</label>
</CustomObject>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/BatchJobSize__c.field-meta.xml
<CustomField>
    <fullName>BatchJobSize__c</fullName>
    <label>Batch Job Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/ComparisonPrecision__c.field-meta.xml
<CustomField>
    <fullName>ComparisonPrecision__c</fullName>
    <description>decimal comparison precision</description>
    <inlineHelpText>decimal comparison precision</inlineHelpText>
    <label>Comparison Precision</label>
    <precision>18</precision>
    <scale>17</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/EffectiveDateHorizon__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDateHorizon__c</fullName>
    <description>number of the days we look back to find the previous active line</description>
    <inlineHelpText>number of the days we look back to find the previous active line</inlineHelpText>
    <label>Effective Date Horizon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/FESEnabledLineLevel__c.field-meta.xml
<CustomField>
    <fullName>FESEnabledLineLevel__c</fullName>
    <description>line separated list of Line Level Names that FES has to run for</description>
    <inlineHelpText>line separated list of Line Level Names that FES has to run for</inlineHelpText>
    <label>FESEnabledLineLevel</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/FESRequestSize__c.field-meta.xml
<CustomField>
    <fullName>FESRequestSize__c</fullName>
    <label>FES Request Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/FESThreads__c.field-meta.xml
<CustomField>
    <fullName>FESThreads__c</fullName>
    <description>Number of parallel apex jobs launched</description>
    <inlineHelpText>Number of parallel apex jobs launched</inlineHelpText>
    <label>FES Threads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/GetPriceDataFormula__c.field-meta.xml
<CustomField>
    <fullName>GetPriceDataFormula__c</fullName>
    <label>GetPriceDataFormula</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/GetPriceDataFormulaEE__c.field-meta.xml
<CustomField>
    <fullName>GetPriceDataFormulaEE__c</fullName>
    <description>used for Entity Evaluation service</description>
    <inlineHelpText>used for Entity Evaluation service</inlineHelpText>
    <label>GetPriceDataFormulaEE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/GetRecommendationsFormula__c.field-meta.xml
<CustomField>
    <fullName>GetRecommendationsFormula__c</fullName>
    <label>GetRecommendationsFormula</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/LineScoreThreshold__c.field-meta.xml
<CustomField>
    <fullName>LineScoreThreshold__c</fullName>
    <description>line score threshold that tolerates price decrease</description>
    <inlineHelpText>line score threshold that tolerates price decrease</inlineHelpText>
    <label>Line Score Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/LineSourceSyncExclusions__c.field-meta.xml
<CustomField>
    <fullName>LineSourceSyncExclusions__c</fullName>
    <description>Comma separated list of line sources that need to be excluded from Zcloud sync. Only applied when set.</description>
    <inlineHelpText>Comma separated list of line sources that need to be excluded from Zcloud sync. Only applied when set.</inlineHelpText>
    <label>LineSourceSyncExclusions</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/ManagersPermissionSet__c.field-meta.xml
<CustomField>
    <fullName>ManagersPermissionSet__c</fullName>
    <label>Managers Permission Set</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/NotificationGroup__c.field-meta.xml
<CustomField>
    <fullName>NotificationGroup__c</fullName>
    <description>list email addresses separated by new line &quot;\r\n&quot;</description>
    <inlineHelpText>list email addresses separated by new line &quot;\r\n&quot;</inlineHelpText>
    <label>Notification Group</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/runCLIZcloudSync__c.field-meta.xml
<CustomField>
    <fullName>runCLIZcloudSync__c</fullName>
    <defaultValue>true</defaultValue>
    <label>runCLIZcloudSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/runContractZcloudSync__c.field-meta.xml
<CustomField>
    <fullName>runContractZcloudSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>runContractZcloudSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/runProductZCloudSync__c.field-meta.xml
<CustomField>
    <fullName>runProductZCloudSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>runProductZCloudSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/runZCloudSync__c.field-meta.xml
<CustomField>
    <fullName>runZCloudSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>runZCloudSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/SalesAdminProfiles__c.field-meta.xml
<CustomField>
    <fullName>SalesAdminProfiles__c</fullName>
    <label>SalesAdminProfiles</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/UserSyncExclusions__c.field-meta.xml
<CustomField>
    <fullName>UserSyncExclusions__c</fullName>
    <description>list of users excluded from Zcloud sync process. Applied when sync flag set to TRUE.</description>
    <inlineHelpText>list of users excluded from Zcloud sync process. Applied when sync flag set to TRUE.</inlineHelpText>
    <label>UserSyncExclusions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/NationalAccountsPricing__c.object-meta.xml
<CustomObject>
    <description>Pricing for national accounts</description>
    <label>National Accounts Pricing</label>
    <nameField>
        <label>Short Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Accounts Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NationalAccountsPricing__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/CompositeKey__c.field-meta.xml
<CustomField>
    <fullName>CompositeKey__c</fullName>
    <label>CompositeKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/NationalAccountGroupID__c.field-meta.xml
<CustomField>
    <fullName>NationalAccountGroupID__c</fullName>
    <externalId>true</externalId>
    <label>National Account Group ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NationalAccountsPricing__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Servicing_Division__c/Servicing_Division__c.object-meta.xml
<CustomObject>
    <description>Used as lookup on PSR, Prospect, and Quote.  Also used as division names for Quote Product Search.  Any name changes to a Servicing Division can have repercussions throughout the system - beware when making any updates to these records.</description>
    <label>Servicing Division</label>
    <nameField>
        <label>Servicing Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Servicing_Division__c/fields/Division_Code__c.field-meta.xml
<CustomField>
    <fullName>Division_Code__c</fullName>
    <label>Division Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Servicing_Division__c.field-meta.xml
<CustomField>
    <fullName>Servicing_Division__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicing Division</label>
    <referenceTo>Servicing_Division__c</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AIQ_TestDataFactory.cls
@IsTest
public class AIQ_TestDataFactory {
    private static final List<String> LINE_LEVEL_NAMES = new List<String>{
        'Item',
        'Subset',
        'Set',
        'BrandVendor',
        'Brand',
        'ClassVendor',
        'Class'
    };

    public static List<Account> initializeAccounts(Account prototype, Integer numberOfRecords, Boolean isMock) {
        Map<String, Object> populatedFields = prototype == null ? new Map<String, Object>() : prototype.getPopulatedFieldsAsMap();

        system.debug('Data factory start for Accounts');
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Account acct = prototype == null ? new Account() : prototype.clone(false, true);
            if (isMock) {
                acct.Id = (String) AIQts_ApexMocks.generateId(new Account().getSObjectType());
            }
            acct.Name = 'zTestData' + i;
            accounts.add(acct);
        }
        if (!isMock) {
            insert accounts;
        }
        system.debug('Data factory end for Accounts. Output size => ' + accounts.size());
        return accounts;
    }

    public static List<Servicing_Division__c> initializeDivisions(
        Servicing_Division__c prototype,
        Integer numberOfRecords,
        Boolean isMock
    ) {
        Map<String, Object> populatedFields = prototype == null ? new Map<String, Object>() : prototype.getPopulatedFieldsAsMap();

        system.debug('Data factory start for Division');
        List<Servicing_Division__c> divisions = new List<Servicing_Division__c>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Servicing_Division__c div = prototype == null ? new Servicing_Division__c() : prototype.clone(false, true);
            if (isMock) {
                div.Id = (String) AIQts_ApexMocks.generateId(new Servicing_Division__c().getSObjectType());
            }
            div.Name = 'TestDiv' + i;
            divisions.add(div);
        }
        if (!isMock) {
            insert divisions;
        }
        system.debug('Data factory end for Divisions. Output size => ' + divisions.size());
        return divisions;
    }

    public static List<Contract> initializeContracts(Contract prototype, Integer numberOfRecords, Boolean isMock) {
        List<Contract> objectList = new List<Contract>();
        prototype.recalculateFormulas();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Contract entityObj = prototype == null ? new Contract() : prototype.clone(false, true);
            if (isMock) {
                entityObj.Id = (String) AIQts_ApexMocks.generateId(new Contract().getSObjectType());
            }
            objectList.add(entityObj);
        }
        if (!isMock) {
            insert objectList;
        }
        return objectList;
    }

    public static List<zpl__ContractLineItem__c> initializeContractsLines(
        zpl__ContractLineItem__c prototype,
        Integer numberOfRecords,
        Boolean isMock
    ) {
        return initializeContractsLines(prototype, numberOfRecords, isMock, true);
    }

    public static List<zpl__ContractLineItem__c> initializeContractsLines(
        zpl__ContractLineItem__c prototype,
        Integer numberOfRecords,
        Boolean isMock,
        Boolean isRecalculateFormulas
    ) {
        List<zpl__ContractLineItem__c> objectList = new List<zpl__ContractLineItem__c>();
        if (isRecalculateFormulas) {
            prototype.recalculateFormulas();
        }
        for (Integer i = 0; i < numberOfRecords; i++) {
            zpl__ContractLineItem__c entityObj = prototype == null ? new zpl__ContractLineItem__c() : prototype.clone(false, true);
            if (isMock) {
                entityObj.Id = (String) AIQts_ApexMocks.generateId(new zpl__ContractLineItem__c().getSObjectType());
                entityObj.zpl__ContractLineItemId__c = entityObj.zpl__ContractLineItemId__c == null
                    ? AIQ_CommonUtil.getGuid()
                    : entityObj.zpl__ContractLineItemId__c;
            }
            objectList.add(entityObj);
        }
        if (!isMock) {
            insert objectList;
        }
        return objectList;
    }

    public static AIQZilliantConfiguration__c initializeZilliantConfiguration() {
        return initializeZilliantConfiguration(null, false);
    }

    public static AIQZilliantConfiguration__c initializeZilliantConfiguration(AIQZilliantConfiguration__c prototype, Boolean isMock) {
        AIQZilliantConfiguration__c entity = prototype == null ? new AIQZilliantConfiguration__c() : prototype.clone(false, true);
        entity.GetPriceDataFormula__c = 'f_getAPIContractLineData';
        entity.GetRecommendationsFormula__c = 'testFormula';
        entity.ManagersPermissionSet__c = 'TestPermSet';
        entity.SalesAdminProfiles__c = 'System Administrator\n' + 'Pricing\n' + 'Sales Admin - Lightning\n';
        entity.BatchJobSize__c = 200;
        entity.EffectiveDateHorizon__c = 180;
        entity.LineScoreThreshold__c = 101;
        entity.FESEnabledLineLevel__c = 'Item\nSet\nSubset';
        entity.FESRequestSize__c = 20;
        entity.NotificationGroup__c = 'andriy.sukh@zilliant.com \n andriy.sukh@zilliant.com';
        entity.GetPriceDataFormulaEE__c = 'f_getAPIContractLineData';
        entity.FESThreads__c = 1;
        entity.runZcloudSync__c = true;
        entity.runCLIZcloudSync__c = true;
        entity.runContractZcloudSync__c = true;
        entity.runProductZCloudSync__c = true;
        entity.LineSourceSyncExclusions__c = 'C';
        entity.UserSyncExclusions__c = 'andriy.sukh@zilliant.com';
        entity.ComparisonPrecision__c = 0.001;

        if (!isMock) {
            insert entity;
        }
        return entity;
    }

    public static NationalAccountsPricing__c initializeNationalAccountsPricing(NationalAccountsPricing__c prototype, Boolean isMock) {
        NationalAccountsPricing__c entity = prototype == null ? new NationalAccountsPricing__c() : prototype.clone(false, true);
        if (prototype == null) {
            entity.Name = '00000003';
            entity.NationalAccountGroupID__c = 'testNA';
            entity.Class__c = 'A';
            entity.Price__c = 1;
            entity.CompositeKey__c = 'SWtestNA';
        }
        if (!isMock) {
            insert entity;
        }
        return entity;
    }

    public static zpl__ProductSelectorConfiguration__c initializeProductSelectorConfiguration(
        zpl__ProductSelectorConfiguration__c prototype,
        Boolean isMock
    ) {
        zpl__ProductSelectorConfiguration__c entity = prototype == null
            ? new zpl__ProductSelectorConfiguration__c()
            : prototype.clone(false, true);
        if (prototype == null) {
            entity.Name = 'Add Contract Products';
            entity.zpl__TargetObject__c = 'Contract';
            entity.zpl__UniqueNickname__c = 'DefaultContract';
        }
        if (!isMock) {
            insert entity;
        }
        return entity;
    }

    public static Map<String, zpl__LineLevel__c> initializeAllLineLevels(zpl__LineLevel__c prototype, Boolean isMock) {
        Map<String, zpl__LineLevel__c> allLineLevels = new Map<String, zpl__LineLevel__c>();
        for (Integer i = 0; i < LINE_LEVEL_NAMES.size(); i++) {
            String levelName = LINE_LEVEL_NAMES[i];
            zpl__LineLevel__c lineLevel = prototype == null ? new zpl__LineLevel__c() : prototype.clone(false, true);
            lineLevel.Name = levelName;
            lineLevel.zpl__LineLevelId__c = levelName;
            lineLevel.zpl__Position__c = i;
            if (isMock) {
                lineLevel.Id = (String) AIQts_ApexMocks.generateId(new zpl__LineLevel__c().getSObjectType());
            }
            allLineLevels.put(levelName, lineLevel);
        }
        if (!isMock) {
            Database.insert(allLineLevels.values());
        }
        return allLineLevels;
    }

    public static List<AIQ_CWTItem__c> initializeCWTItems(AIQ_CWTItem__c prototype,Integer numberOfRecords, Boolean isMock) {
        List<AIQ_CWTItem__c> objectList = new List<AIQ_CWTItem__c>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            AIQ_CWTItem__c entityObj = prototype == null ? new AIQ_CWTItem__c() : prototype.clone(false, true);
            if (isMock) {
                entityObj.Id = (String) AIQts_ApexMocks.generateId(new AIQ_CWTItem__c().getSObjectType());
            }
            objectList.add(entityObj);
        }
        if (!isMock) {
            insert objectList;
        }
        return objectList;
    }

    public static zpl__LineLevel__c initializeLineLevel(zpl__LineLevel__c prototype, Boolean isMock) {
        zpl__LineLevel__c entity = prototype == null ? new zpl__LineLevel__c() : prototype.clone(false, true);
        if (isMock) {
            entity.Id = (String) AIQts_ApexMocks.generateId(new zpl__LineLevel__c().getSObjectType());
        }

        if (prototype == null) {
            entity.Name = 'Item';
            entity.zpl__LineLevelId__c = 'Item';
            entity.zpl__Position__c = 1;
            entity.zpl__ProductSelectorConfiguration__c = (String) AIQts_ApexMocks.generateId(
                new zpl__ProductSelectorConfiguration__c().getSObjectType()
            );
        }
        if (!isMock) {
            insert entity;
        }
        return entity;
    }

    public static zpl__QuickActionConfig__c initializeQuickActionConfig(zpl__QuickActionConfig__c prototype, Boolean isMock) {
        zpl__QuickActionConfig__c entity = prototype == null ? new zpl__QuickActionConfig__c() : prototype.clone(false, true);
        if (prototype == null) {
            entity.Name = 'Test Name';
            entity.SObjectType__c = 'zpl__ContractLineItem__c';
        }
        if (!isMock) {
            insert entity;
        }
        return entity;
    }

    public static zpl__QuickActionField__c initializeQuickActionField(
        zpl__QuickActionField__c prototype,
        Id quickActionConfigId,
        Boolean isMock
    ) {
        zpl__QuickActionField__c entity = prototype == null ? new zpl__QuickActionField__c() : prototype.clone(false, true);
        if (prototype == null) {
            entity.Name = 'Test field';
            entity.DisplayMode__c = 'COMBOBOX';
            entity.QuickActionConfig__c = quickActionConfigId;
            entity.Position__c = '1.1';
            entity.Field_Action__c = 'Reset';
        }
        if (!isMock) {
            insert entity;
        }
        return entity;
    }

    public static List<Ship_To__c> initializeShipTo(Ship_To__c prototype, Integer numberOfRecords, Boolean isMock) {
        List<Ship_To__c> objectList = new List<Ship_To__c>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Ship_To__c entityObj = prototype == null ? new Ship_To__c() : prototype.clone(false, true);
            if (isMock) {
                entityObj.Id = (String) AIQts_ApexMocks.generateId(new Ship_To__c().getSObjectType());
            }
            entityObj.Name = 'Test Ship' + i;
            objectList.add(entityObj);
        }
        if (!isMock) {
            insert objectList;
        }
        return objectList;
    }

    public static zpl__ProductUOM__c initializeProductUOM(
            zpl__ProductUOM__c prototype,
            Boolean isMock
    ) {
        zpl__ProductUOM__c entityObj = prototype == null ? new zpl__ProductUOM__c() : prototype.clone(false, true);
        if (isMock) {
            entityObj.Id = (String) AIQts_ApexMocks.generateId(new zpl__ProductUOM__c().getSObjectType());
        }

        if (!isMock) {
            insert entityObj;
        }
        return entityObj;
    }

    public static zpl__PolicyType__c initializePolicyType(
            zpl__PolicyType__c prototype,
            Boolean isMock
    ) {
        zpl__PolicyType__c entityObj = prototype == null ? new zpl__PolicyType__c() : prototype.clone(false, true);
        if (isMock) {
            entityObj.Id = (String) AIQts_ApexMocks.generateId(new zpl__PolicyType__c().getSObjectType());
        }

        if (!isMock) {
            insert entityObj;
        }
        return entityObj;
    }

    public static zpl__IQAnywhereConfiguration__c initializeIQAnywhereConfig(
            zpl__IQAnywhereConfiguration__c prototype,
            Boolean isMock
    ) {
        zpl__IQAnywhereConfiguration__c entity = prototype == null ? new zpl__IQAnywhereConfiguration__c() : prototype.clone(false, true);
        if (prototype == null) {
            entity.Name = 'f_getAPIContractLineData';
            entity.zpl__SourceObject__c = 'zpl__ContractLineItem__c';
        }

        if (isMock) {
            entity.Id = (String) AIQts_ApexMocks.generateId(new zpl__IQAnywhereConfiguration__c().getSObjectType());
        }

        if (!isMock) {
            upsert entity;
        }
        return entity;
    }

    public static List<Product2> initializeProduct2s(
            Product2 prototype,
            Integer numberOfRecords,
            Boolean isMock
    ) {
        List<Product2> product2s = new List<Product2>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            Product2 product2 = prototype == null ? new Product2() : prototype.clone(false, true);
            product2.Name = 'Product ' + i;
            product2.System_id__c = '03';
            product2.ProductCode = '00000001';
            product2.isActive = true;
            product2.Division_Code__c = '01';
            product2.List_Price__c = 1.0;
            product2.Pricing_Costing_UOM__c= 'SH';
            product2.WMS_UOM__c = 'X';
            if (isMock) {
                product2.Id = AIQts_ApexMocks.generateId(new Product2().getSObjectType());
            }
            product2s.add(product2);
        }
        if (!isMock) {
            insert product2s;
        }
        return product2s;
    }
}