force-app/main/default/objects/Account/fields/VENDOR_CODE__c.field-meta.xml
<CustomField>
    <fullName>VENDOR_CODE__c</fullName>
    <description>Legacy key field</description>
    <externalId>true</externalId>
    <label>VENDOR_CODE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Vendor.recordType-meta.xml
<RecordType>
    <fullName>Vendor</fullName>
    <active>true</active>
    <description>Record Type ID 012700000009TNjAAM</description>
    <label>Vendor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Vendor_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field needs to be populated in order to associate this contact with a Quote Line Item.  The value should match the account name.</inlineHelpText>
    <label>Vendor Lookup</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>That Vendor Contact does not exist or is inactive.</errorMessage>
        <filterItems>
            <field>$Source.Inactive__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>If the contact is not available, please create the contact on the Vendor Account and then select the contact on this Quote Line Item.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Vendor_Detail__c</referenceTo>
    <relationshipLabel>Vendor Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Detail__c/Vendor_Detail__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Detail__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <externalId>true</externalId>
    <label>Vendor Code</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestContactVendorTrigger.cls
/*

 */
@isTest
private class TestContactVendorTrigger {

    static testMethod void testContactCreationWithAccountVendor() 
    {
    	//create a vendor account
    	Account testAcct = TestingUtils.createAccount('Test Acct');
    	testAcct.VENDOR_CODE__c = 'B1U3';
    	testAcct.RecordTypeId = ContactServices.ACCOUNT_VENDOR_RTYPE_ID;
    	
    	insert testAcct;
    	
     	//Create a vendor detail
     	Vendor_Detail__c testVendorDetail = Testingutils.createVendorDetails(1, 'Test Vendor Detail', false)[0];
     	testVendorDetail.Vendor_Code__c = 'B1U3';
     	
     	insert testVendorDetail;
     	
     	//create a contact
     	Contact testContact = TestingUtils.createContact('Test', 'User', false);
     	testContact.RecordTypeId = ContactServices.CONTACT_VENDOR_RTYPE_ID;
     	testContact.AccountId = testAcct.Id;
     	
     	Test.StartTest();
     		insert testContact;
     	Test.StopTest();
     	
     	testContact = [Select id, Vendor_Lookup__c from Contact where Id = :testContact.Id];
     	
     	System.assertEquals( testVendorDetail.Id, testContact.Vendor_Lookup__c);
     		   
    }

    static testMethod void testUpdateContactAccount() 
    {
    	//create a vendor account
    	Account testAcct = TestingUtils.createAccount('Test Acct');
    	testAcct.VENDOR_CODE__c = 'B1U3';
    	testAcct.RecordTypeId = ContactServices.ACCOUNT_VENDOR_RTYPE_ID;
    	
    	insert testAcct;

    	//create another vendor account
    	Account testAcct2 = TestingUtils.createAccount('Test Acct');
    	testAcct2.VENDOR_CODE__c = 'B1U3W';
    	testAcct2.RecordTypeId = ContactServices.ACCOUNT_VENDOR_RTYPE_ID;
    	
    	insert testAcct2;
    	
     	//Create a vendor detail
     	Vendor_Detail__c testVendorDetail = Testingutils.createVendorDetails(1, 'Test Vendor Detail', false)[0];
     	testVendorDetail.Vendor_Code__c = 'B1U3';
     	
     	insert testVendorDetail;
     	
     	//Create another vendor detail
     	Vendor_Detail__c testVendorDetail2 = Testingutils.createVendorDetails(1, 'Test Vendor Detail2', false)[0];
     	testVendorDetail2.Vendor_Code__c = 'B1U3W';
     	
     	insert testVendorDetail2;
     	
     	//create a contact
     	Contact testContact = TestingUtils.createContact('Test', 'User', false);
     	testContact.RecordTypeId = ContactServices.CONTACT_VENDOR_RTYPE_ID;
     	testContact.AccountId = testAcct.Id;
     	
 		insert testContact;
 		
 		//Change the account of the contact
     	testContact.AccountId = testAcct2.Id;
     	
     	Test.StartTest();
     		update testContact;
     	Test.StopTest();
     	
     	testContact = [Select id, Vendor_Lookup__c from Contact where Id = :testContact.Id];
     	
     	System.assertEquals( testVendorDetail2.Id, testContact.Vendor_Lookup__c);
     		   
    }
}