force-app/main/default/objects/Account/fields/Zilliant_Active__c.field-meta.xml
<CustomField>
    <fullName>Zilliant_Active__c</fullName>
    <description>Updated by data warehouse. 
N – Customer not in Zilliant
Y – Customer in Legacy Zilliant
AI - Customer in Zilliant IQ</description>
    <inlineHelpText>N – Customer not in Zilliant
Y – Customer in Legacy Zilliant
AI - Customer in Zilliant IQ</inlineHelpText>
    <label>Zilliant-Active</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/zpl__CustomerId__c.field-meta.xml
<CustomField>
    <fullName>zpl__CustomerId__c</fullName>
    <description>The unique identifier of the customer.</description>
    <externalId>true</externalId>
    <inlineHelpText>The unique identifier of the customer. Part of the managed package. 
Master Customer ID field for Deal Manager.</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AIQ_SyncAccountFilterTest.cls
@IsTest
public class AIQ_SyncAccountFilterTest {
    
    @IsTest
    static void testAccountSyncFilterPositive(){
        Account record1 = new Account(Name='account1', zpl__CustomerId__c = 'externalIdAccount1', Zilliant_Active__c = 'AI');
        Account record2 = new Account(Name='account1', zpl__CustomerId__c = 'externalIdAccount1', Zilliant_Active__c = 'Y');
        AIQ_SyncAccountFilter filter = new AIQ_SyncAccountFilter('Account', 'AIQ_SyncDownFieldSet');
        Boolean result = filter.include(record1, record2);
        system.assertEquals(true, result);
    }
    
    @IsTest
    static void testAccountSyncFilterPositive2(){
        Account record1 = new Account(Name='account1', zpl__CustomerId__c = 'externalIdAccount1', Zilliant_Active__c = 'Y');
        Account record2 = new Account(Name='account1', zpl__CustomerId__c = 'externalIdAccount1', Zilliant_Active__c = 'AI');
        AIQ_SyncAccountFilter filter = new AIQ_SyncAccountFilter('Account', 'AIQ_SyncDownFieldSet');
        Boolean result = filter.include(record1, record2);
        system.assertEquals(true, result);
    }
    
    @IsTest
    static void testAccountSyncFilterNegative(){
        Account record1 = new Account(Name='account1', zpl__CustomerId__c = 'externalIdAccount1', Zilliant_Active__c = 'Y');
        Account record2 = new Account(Name='account2', zpl__CustomerId__c = 'externalIdAccount1', Zilliant_Active__c = 'Y');
        AIQ_SyncAccountFilter filter = new AIQ_SyncAccountFilter('Account', 'AIQ_SyncDownFieldSet');
        Boolean result = filter.include(record1, record2);
        system.assertEquals(false, result);
    }

}