force-app/main/default/objects/Account/fields/zpl__CustomerId__c.field-meta.xml
<CustomField>
    <fullName>zpl__CustomerId__c</fullName>
    <description>The unique identifier of the customer.</description>
    <externalId>true</externalId>
    <inlineHelpText>The unique identifier of the customer. Part of the managed package. 
Master Customer ID field for Deal Manager.</inlineHelpText>
    <label>Customer Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AIQZilliantConfiguration__c/AIQZilliantConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AIQZilliantConfiguration</label>
</CustomObject>

force-app/main/default/objects/AIQZilliantConfiguration__c/fields/ZcloudSyncUserId__c.field-meta.xml
<CustomField>
    <fullName>ZcloudSyncUserId__c</fullName>
    <label>ZcloudSyncUserId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AIQ_AccountTriggerHandler.cls
public without sharing class AIQ_AccountTriggerHandler {

    public static void runSyncDown() {
        Boolean hasToRun = true;
        //User runUser = new User(Id=UserInfo.getUserId());
        if(!Test.isRunningTest()){ hasToRun = (Boolean) AIQZilliantConfiguration__c.getInstance().get(AIQ_Constants.ACCOUNT_EXTERNAL_ID);
            //runUser = (AIQZilliantConfiguration__c.getInstance().get('ZcloudSyncUserId__c') != null ? new User(Id=(Id) AIQZilliantConfiguration__c.getInstance().get('ZcloudSyncUserId__c')) : runUser);
        }

        if(hasToRun){ 
            zpf.GenericSynchronizedDomainObject.triggerHandler(new AIQ_SyncAccountFilter('Account', AIQ_Constants.ACCOUNT_SYNC_DOWN_FIELDSET_NAME), 'zpl__CustomerId__c');
        }
    }
}