force-app/main/default/objects/Migration_File__c/Migration_File__c.object-meta.xml
<CustomObject>
    <label>Migration File</label>
    <nameField>
        <displayFormat>MF-{0000}</displayFormat>
        <label>Migration File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Migration Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Migration_File__c/fields/Bulk_JobId__c.field-meta.xml
<CustomField>
    <fullName>Bulk_JobId__c</fullName>
    <label>Bulk JobId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_File__c/fields/Failed_Record__c.field-meta.xml
<CustomField>
    <fullName>Failed_Record__c</fullName>
    <label>Failed Record</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Migration_File__c/fields/Job_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Job_End_Time__c</fullName>
    <label>Job End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Migration_File__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Generated</fullName>
            </value>
            <value>
                <fullName>Job Submitted</fullName>
            </value>
            <value>
                <fullName>Job Inprogress</fullName>
            </value>
            <value>
                <fullName>Job Successful</fullName>
            </value>
            <value>
                <fullName>Job Failed</fullName>
            </value>
            <value>
                <fullName>Job Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Migration_File__c/fields/Migration_Object__c.field-meta.xml
<CustomField>
    <fullName>Migration_Object__c</fullName>
    <label>Migration Object</label>
    <referenceTo>Migration_Object__c</referenceTo>
    <relationshipLabel>Migration Files</relationshipLabel>
    <relationshipName>Migration_Files</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Migration_File__c/fields/Successful_Record__c.field-meta.xml
<CustomField>
    <fullName>Successful_Record__c</fullName>
    <label>Successful Record</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Migration_Object__c/Migration_Object__c.object-meta.xml
<CustomObject>
    <label>Migration Object</label>
    <nameField>
        <label>Migration Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Migration Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Migration_Object__c/fields/Destination_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Destination_External_Id__c</fullName>
    <label>Destination External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Failed_Record__c.field-meta.xml
<CustomField>
    <fullName>Failed_Record__c</fullName>
    <label>Failed Record</label>
    <summarizedField>Migration_File__c.Failed_Record__c</summarizedField>
    <summaryForeignKey>Migration_File__c.Migration_Object__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <label>Named Credential</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DestinationOrg</fullName>
                <label>B2B</label>
            </value>
            <value>
                <fullName>Imperial_Dade_SIT1</fullName>
            </value>
            <value>
                <fullName>B2B_ID_UAT</fullName>
                <label>B2B ID UAT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <label>Object Api Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>insert</fullName>
            </value>
            <value>
                <fullName>upsert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Successful_Record__c.field-meta.xml
<CustomField>
    <fullName>Successful_Record__c</fullName>
    <label>Successful Record</label>
    <summarizedField>Migration_File__c.Successful_Record__c</summarizedField>
    <summaryForeignKey>Migration_File__c.Migration_Object__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Migration_Object__c/fields/Total_Records__c.field-meta.xml
<CustomField>
    <fullName>Total_Records__c</fullName>
    <label>Total Records</label>
    <summarizedField>Migration_File__c.Total_Records__c</summarizedField>
    <summaryForeignKey>Migration_File__c.Migration_Object__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/BulkJobQueueable.cls
/**
 * @description       : 
 * @author            : Abhishek
 * @group             : RafterOne
 * @last modified on  : 01-30-2023
 * @last modified by  : Abhishek
 * Modifications Log
 * Ver   Date         Author     Modification
 * 1.0   01-24-2023   Abhishek   Initial Version
**/
public with sharing class BulkJobQueueable implements Queueable,Database.AllowsCallouts{

    public String  migrationObjectId {get;set;}

    public BulkJobQueueable(String migrationObjectId){
        this.migrationObjectId = migrationObjectId ;
    }

    public void submitMigrationBulk(){
        List<Migration_File__c> migrationFiles = [SELECT Id,Migration_Object__c,Migration_Object__r.Named_Credential__c,Migration_Object__r.Destination_External_Id__c,Migration_Object__r.Object_Api_Name__c,Migration_Object__r.Operation__c  FROM Migration_File__c WHERE Migration_Object__c=:migrationObjectId AND  Bulk_JobId__c=null AND Job_Status__c='Data Generated' LIMIT 1];
        if(!migrationFiles.isEmpty()){
            //Submit BULK JOB
            Migration_File__c mfile = migrationFiles.get(0);
            system.debug(mfile.Id);
            List<Attachment> attachments = [SELECT Id,Body FROM Attachment WHERE parentId =:mfile.Id LIMIT 1];
            if(!attachments.isEmpty()){
                Attachment attch = attachments.get(0);
                String csvStr = attch.Body.toString() ;
                String bulkJobId = BulkApiService.createBulkJobId(mfile.Migration_Object__r.Named_Credential__c,mfile.Migration_Object__r.Object_Api_Name__c, mfile.Migration_Object__r.Operation__c,mfile.Migration_Object__r.Destination_External_Id__c) ;
                if(String.isNotBlank(bulkJobId)){
                    BulkApiService.uploadDataToBulkJob(mfile.Migration_Object__r.Named_Credential__c,bulkJobId, csvStr);
                    BulkApiService.submitBulkJob(mfile.Migration_Object__r.Named_Credential__c,bulkJobId);
                    mfile.Bulk_JobId__c = bulkJobId ;
                    mfile.Job_Status__c = 'Job Submitted' ;
                    update mfile;
                }else{
                    mfile.Job_Status__c = 'Job Failed' ;
                    update mfile;
                }
            }else{
                mfile.Job_Status__c = 'Job Failed' ;
                update mfile;
            }
            System.enqueueJob(new BulkJobQueueable(migrationObjectId), MigrationConstant.QUEUEABLE_DEPLAY);
        }else{
            checkBulkStatus();
        }
    }

    public void checkBulkStatus(){
        List<Migration_File__c> submittedMigrationFiles = [SELECT Id,Bulk_JobId__c,Job_Status__c,Migration_Object__r.Named_Credential__c,Total_Records__c  FROM Migration_File__c WHERE Migration_Object__c=:migrationObjectId AND  Bulk_JobId__c != null AND Job_Status__c IN ('Job Submitted') ORDER BY LASTMODIFIEDDATE ASC LIMIT 5];
        if(!submittedMigrationFiles.isEmpty()){
            List<Attachment> attList = new List<Attachment>();
            for(Migration_File__c mFile : submittedMigrationFiles){
                Map<String, Object> respMap = BulkApiService.getBulkJobInfo(mfile.Migration_Object__r.Named_Credential__c,mfile.Bulk_JobId__c);
                system.debug('respMap - '+respMap);
                if(respMap.containsKey('state')){
                    mFile.Job_End_Time__c = Datetime.now() ;
                    mFile.Failed_Record__c = respMap.containsKey('numberRecordsFailed') ? Integer.valueOf(respMap.get('numberRecordsFailed')) : 0 ;
                    mFile.Successful_Record__c = respMap.containsKey('numberRecordsProcessed') ? Integer.valueOf(respMap.get('numberRecordsProcessed')) : 0 ;
                    mFile.Successful_Record__c = mFile.Successful_Record__c - mFile.Failed_Record__c  ;
                    if(String.valueOf(respMap.get('state')) == 'JobComplete'){
                        if(mFile.Failed_Record__c > 0 && mFile.Successful_Record__c > 0){
                            mFile.Job_Status__c = 'Job Partial Success' ;
                        }else if(mFile.Failed_Record__c == 0){
                            mFile.Job_Status__c ='Job Successful' ;
                        }else{
                            mFile.Job_Status__c ='Job Failed' ;
                        }
                    }else if(String.valueOf(respMap.get('state')) == 'Failed' || String.valueOf(respMap.get('state')) == 'Aborted'){
                        mFile.Job_Status__c = 'Job Failed' ;
                    }
                    if(mFile.Job_Status__c == 'Job Partial Success' || mFile.Job_Status__c == 'Job Failed'){
                        Attachment att = BulkApiService.fetchFailedRecords(mfile.Migration_Object__r.Named_Credential__c,mfile.Bulk_JobId__c,migrationObjectId);
                        if(att!=null){
                            attList.add(att);
                        }
                    }
                }
            }
            update submittedMigrationFiles;
            if(!attList.isEmpty()){
                insert attList;
            }
            System.enqueueJob(new BulkJobQueueable(migrationObjectId), MigrationConstant.QUEUEABLE_DEPLAY);
        }else{
            Migration_Object__c mgObject = [SELECT Id,Failed_Record__c,Sequence__c FROM Migration_Object__c WHERE Id =: migrationObjectId ];
            mgObject.End_Date__c = Datetime.now();
            mgObject.Status__c = mgObject.Failed_Record__c > 0 ? 'Failed' : 'Completed' ;
            update mgObject;
            if(mgObject.Status__c == 'Completed'){
                List<Migration_Object__c> migrationObjectList = [SELECT Id FROM Migration_Object__c WHERE Sequence__c >: mgObject.Sequence__c AND Sequence__c!=NULL AND Status__c ='Inprogress' AND Active__c=true ORDER BY Sequence__c ASC LIMIT 1 ];
                if(!migrationObjectList.isEmpty()){
                    System.enqueueJob(new BulkJobQueueable(migrationObjectList.get(0).Id));
                }
            }
        }
    }

    public void execute(QueueableContext context) {
        submitMigrationBulk();
    }

}