force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Vertical_Major__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Major__c</fullName>
    <description>Assigns a Vertical Major to a PSR - DO NOT UPDATE TO MATCH VERTICALS!!!!  Picklist values can NOT be longer than 30 characters.</description>
    <label>Vertical Major</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Graphic Design/Advertising</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Printer - Commercial/Sheet Fed</fullName>
            </value>
            <value>
                <fullName>Printer - Digital/Wide Format</fullName>
            </value>
            <value>
                <fullName>Printer - Gang Run</fullName>
            </value>
            <value>
                <fullName>Printer - Graphics/Consumables</fullName>
            </value>
            <value>
                <fullName>Printer - In-plant</fullName>
            </value>
            <value>
                <fullName>Printer - Other</fullName>
            </value>
            <value>
                <fullName>Printer - Packaging</fullName>
            </value>
            <value>
                <fullName>Printer - Sheetfed/Web Combo</fullName>
            </value>
            <value>
                <fullName>Printer - Web</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Redistribution - FS</fullName>
            </value>
            <value>
                <fullName>Re-D - Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Vertical_Major_Page__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Major_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vertical Major Page</label>
    <referenceTo>Verticals__c</referenceTo>
    <relationshipLabel>Primary Sales Reps - Major Vertical</relationshipLabel>
    <relationshipName>Primary_Sales_Reps1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Vertical_Minor__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Minor__c</fullName>
    <description>Assigns Minor Vertical to a PSR</description>
    <label>Vertical Minor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Building Service Contractors</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food Processing</fullName>
            </value>
            <value>
                <fullName>Food Service</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Graphic Design/Advertising</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Health Clubs</fullName>
            </value>
            <value>
                <fullName>Hospitality/Lodging</fullName>
            </value>
            <value>
                <fullName>Large Venue</fullName>
            </value>
            <value>
                <fullName>Manufacturing (non food/print)</fullName>
            </value>
            <value>
                <fullName>Printer - Commercial/Sheet Fed</fullName>
            </value>
            <value>
                <fullName>Printer - Digital/Wide Format</fullName>
            </value>
            <value>
                <fullName>Printer - Gang Run</fullName>
            </value>
            <value>
                <fullName>Printer - In-plant</fullName>
            </value>
            <value>
                <fullName>Printer - Packaging</fullName>
            </value>
            <value>
                <fullName>Printer - Sheetfed/Web Combo</fullName>
            </value>
            <value>
                <fullName>Printer - Web</fullName>
            </value>
            <value>
                <fullName>Printer – Other</fullName>
            </value>
            <value>
                <fullName>Property Management</fullName>
            </value>
            <value>
                <fullName>Redistribution - FS</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Vertical_Minor_Page__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Minor_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vertical Minor Page</label>
    <referenceTo>Verticals__c</referenceTo>
    <relationshipLabel>Primary Sales Reps - Minor Vertical</relationshipLabel>
    <relationshipName>Primary_Sales_Reps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verticals__c/Verticals__c.object-meta.xml
<CustomObject>
    <description>Object designed to track account verticals as well as PSR by Major/Minor</description>
    <label>Vertical</label>
    <nameField>
        <label>Vertical Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Verticals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verticals__c/fields/Vertical_Major__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Major__c</fullName>
    <description>Assigns a Vertical Major - DO NOT UPDATE TO MATCH VERTICALS!!!! Picklist values can NOT be longer than 30 characters</description>
    <label>Vertical Major</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Food Processing</fullName>
            </value>
            <value>
                <fullName>FS - Other (General FS)</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Graphic Design/Advertising</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Manufacturing (Non Food/Print)</fullName>
            </value>
            <value>
                <fullName>Niche - FS(Lodging, Lg Venues)</fullName>
            </value>
            <value>
                <fullName>Office(PropMgmt/BSC/HigherEd)</fullName>
            </value>
            <value>
                <fullName>Printer - Commercial/Sheet Fed</fullName>
            </value>
            <value>
                <fullName>Printer - Digital/Wide Format</fullName>
            </value>
            <value>
                <fullName>Printer - Gang Run</fullName>
            </value>
            <value>
                <fullName>Printer - Graphics/Consumables</fullName>
            </value>
            <value>
                <fullName>Printer - In-plant</fullName>
            </value>
            <value>
                <fullName>Printer - Other</fullName>
            </value>
            <value>
                <fullName>Printer - Packaging</fullName>
            </value>
            <value>
                <fullName>Printer - Sheetfed/Web Combo</fullName>
            </value>
            <value>
                <fullName>Printer - Web</fullName>
            </value>
            <value>
                <fullName>Redistribution - FS</fullName>
            </value>
            <value>
                <fullName>Re-D - Office</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>PKG - Other (General PKG)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPSRTrigger.cls
@isTest
private class TestPSRTrigger
{
	static final Integer NUM_OF_PSRs = 4;
	static final String VERTICAL_ONE = 'Education';
	static final String VERTICAL_TWO = 'Food Service';
	static Verticals__c testVertical;

	static void setup()
	{
		testVertical = new Verticals__c( Name = VERTICAL_ONE );
		insert testVertical;
	}

	static testMethod void testPSRVerticalMajor_onInsert_VerticalSetOnHalfPSRs()
	{
		setup();

		List<Primary_Sales_Rep__c> newPSRs = TestingUtils.createPSRs( NUM_OF_PSRs, 'TestName', '10230123', false );
		for( Integer i = 0; i < NUM_OF_PSRs; i+=2 )
		{
			newPSRs[i].Vertical_Major__c = VERTICAL_ONE;
		}

		Test.startTest();

			insert newPSRs;

		Test.stopTest();

		List<Primary_Sales_Rep__c> resultPSRs = [ SELECT Id, Vertical_Major__c, Vertical_Major_Page__c FROM Primary_Sales_Rep__c WHERE Vertical_Major__c != null ];

		System.assertEquals( NUM_OF_PSRs / 2, resultPSRs.size(), 'Only PSRs with Vertical Major specified should be returned' );

		for( Primary_Sales_Rep__c aPSR : resultPSRs )
		{
			System.assertEquals( VERTICAL_ONE, aPSR.Vertical_Major__c, 'Vertical Major on returned PSR object should be equals to the Name of Vertical object' );
			System.assertEquals( testVertical.Id, aPSR.Vertical_Major_Page__c, 'Vertical Lookup on PSR object should be set to matching Vertical' );
		}
	}

	static testMethod void testPSRVerticalMajor_onInsert_VerticalSetAllPSRs_OneVerticalMatching()
	{
		setup();

		Set<String> verticalNames = new Set<String>{ VERTICAL_ONE, VERTICAL_TWO };

		List<Primary_Sales_Rep__c> newPSRs = new List<Primary_Sales_Rep__c>();
		for( Integer i = 0; i < NUM_OF_PSRs; i++ )
		{
			Primary_Sales_Rep__c aPSR = TestingUtils.createPSRs( 1, 'Test PSR'+i, 'TestNW'+i, false )[0];
			Integer residue = Math.mod( i, 2 );
			if( residue == 0 )
			{
				aPSR.Vertical_Major__c = VERTICAL_ONE;
			}
			else
			{
				aPSR.Vertical_Major__c = VERTICAL_TWO;
			}
			newPSRs.add( aPSR );
		}

		Test.startTest();

			insert newPSRs;

		Test.stopTest();

		List<Primary_Sales_Rep__c> resultPSRs = [ SELECT Id, Vertical_Major__c, Vertical_Major_Page__c FROM Primary_Sales_Rep__c ];

		System.assertEquals( NUM_OF_PSRs, resultPSRs.size(), 'All PSRs should be returned' );

		for( Primary_Sales_Rep__c aPSR : resultPSRs )
		{
			System.assert( verticalNames.contains( aPSR.Vertical_Major__c ) );
			if( aPSR.Vertical_Major__c == VERTICAL_ONE )
			{
				System.assertEquals( testVertical.Id, aPSR.Vertical_Major_Page__c, 'Vertical Lookup on PSR object should be set to matching Vertical' );
			}
			else
			{
				System.assertEquals( null, aPSR.Vertical_Major_Page__c, 'Vertical Lookup on PSR object should not be set' );
			}
		}
	}

	static testMethod void testPSRVerticalMajor_onUpdate()
	{
		final String NEW_VERTICAL = 'Education';
		final String OLD_VERTICAL = 'Food Service';

		Verticals__c testVert = new Verticals__c( Name = NEW_VERTICAL );
		insert testVert;

		List<Primary_Sales_Rep__c> testPSRs = new List<Primary_Sales_Rep__c>();
		for( Integer i = 0; i < NUM_OF_PSRs; i++ )
		{
			Primary_Sales_Rep__c aPSR = TestingUtils.createPSRs( 1, 'Test PSR'+i, 'TestNW'+i, false )[0];
			aPSR.Vertical_Major__c = OLD_VERTICAL;
			testPSRs.add( aPSR );
		}
		insert testPSRs;

		for( Integer i = 0; i < NUM_OF_PSRs; i+=2 )
		{
			testPSRs[i].Vertical_Major__c = NEW_VERTICAL;
		}

		Test.startTest();

			update testPSRs;

		Test.stopTest();

		List<Primary_Sales_Rep__c> resultPSRs = [ SELECT Id, Vertical_Major__c, Vertical_Major_Page__c FROM Primary_Sales_Rep__c ];

		System.assertEquals( NUM_OF_PSRs, resultPSRs.size(), 'All PSRs should be returned' );

		for( Primary_Sales_Rep__c aPSR : resultPSRs )
		{
			if( aPSR.Vertical_Major__c == NEW_VERTICAL )
			{
				System.assertEquals( testVert.Id, aPSR.Vertical_Major_Page__c, 'Vertical Lookup on PSR object should be set to matching Vertical' );
			}
			else
			{
				System.assertEquals( OLD_VERTICAL, aPSR.Vertical_Major__c, 'Vertical Name should not be updated to new value' );
				System.assertEquals( null, aPSR.Vertical_Major_Page__c, 'Vertical Lookup on PSR object should not be set' );
			}
		}
	}

	static testMethod void testPSRVerticalMinor_onInsert_VerticalSetOnHalfPSRs()
	{
		setup();

		List<Primary_Sales_Rep__c> newPSRs = TestingUtils.createPSRs( NUM_OF_PSRs, 'TestName', '10230123', false );
		for( Integer i = 0; i < NUM_OF_PSRs; i+=2 )
		{
			newPSRs[i].Vertical_Minor__c = VERTICAL_ONE;
		}

		Test.startTest();

			insert newPSRs;

		Test.stopTest();

		List<Primary_Sales_Rep__c> resultPSRs = [ SELECT Id, Vertical_Minor__c, Vertical_Minor_Page__c FROM Primary_Sales_Rep__c WHERE Vertical_Minor__c != null ];

		System.assertEquals( NUM_OF_PSRs / 2, resultPSRs.size(), 'Only PSRs with Vertical Minor specified should be returned' );

		for( Primary_Sales_Rep__c aPSR : resultPSRs )
		{
			System.assertEquals( VERTICAL_ONE, aPSR.Vertical_Minor__c, 'Vertical Minor on returned PSR object should be equals to the Name of Vertical object' );
			System.assertEquals( testVertical.Id, aPSR.Vertical_Minor_Page__c, 'Vertical Lookup on PSR object should be set to matching Vertical' );
		}
	}

	static testMethod void testPSRVerticalMinor_onInsert_VerticalSetAllPSRs_OneVerticalMatching()
	{
		setup();

		Set<String> verticalNames = new Set<String>{ VERTICAL_ONE, VERTICAL_TWO };

		List<Primary_Sales_Rep__c> newPSRs = new List<Primary_Sales_Rep__c>();
		for( Integer i = 0; i < NUM_OF_PSRs; i++ )
		{
			Primary_Sales_Rep__c aPSR = TestingUtils.createPSRs( 1, 'Test PSR'+i, 'TestNW'+i, false )[0];
			Integer residue = Math.mod( i, 2 );
			if( residue == 0 )
			{
				aPSR.Vertical_Minor__c = VERTICAL_ONE;
			}
			else
			{
				aPSR.Vertical_Minor__c = VERTICAL_TWO;
			}
			newPSRs.add( aPSR );
		}

		Test.startTest();

			insert newPSRs;

		Test.stopTest();

		List<Primary_Sales_Rep__c> resultPSRs = [ SELECT Id, Vertical_Minor__c, Vertical_Minor_Page__c FROM Primary_Sales_Rep__c ];

		System.assertEquals( NUM_OF_PSRs, resultPSRs.size(), 'All PSRs should be returned' );

		for( Primary_Sales_Rep__c aPSR : resultPSRs )
		{
			System.assert( verticalNames.contains( aPSR.Vertical_Minor__c ) );
			if( aPSR.Vertical_Minor__c == VERTICAL_ONE )
			{
				System.assertEquals( testVertical.Id, aPSR.Vertical_Minor_Page__c, 'Vertical Lookup on PSR object should be set to matching Vertical' );
			}
			else
			{
				System.assertEquals( null, aPSR.Vertical_Minor_Page__c, 'Vertical Lookup on PSR object should not be set' );
			}
		}
	}

	static testMethod void testPSRVerticalMinor_onUpdate()
	{
		final String NEW_VERTICAL = 'Education';
		final String OLD_VERTICAL = 'Food Service';

		Verticals__c testVert = new Verticals__c( Name = NEW_VERTICAL );
		insert testVert;

		List<Primary_Sales_Rep__c> testPSRs = new List<Primary_Sales_Rep__c>();
		for( Integer i = 0; i < NUM_OF_PSRs; i++ )
		{
			Primary_Sales_Rep__c aPSR = TestingUtils.createPSRs( 1, 'Test PSR'+i, 'TestNW'+i, false )[0];
			aPSR.Vertical_Minor__c = OLD_VERTICAL;
			testPSRs.add( aPSR );
		}
		insert testPSRs;

		for( Integer i = 0; i < NUM_OF_PSRs; i+=2 )
		{
			testPSRs[i].Vertical_Minor__c = NEW_VERTICAL;
		}

		Test.startTest();

			update testPSRs;

		Test.stopTest();

		List<Primary_Sales_Rep__c> resultPSRs = [ SELECT Id, Vertical_Minor__c, Vertical_Minor_Page__c FROM Primary_Sales_Rep__c ];

		System.assertEquals( NUM_OF_PSRs, resultPSRs.size(), 'All PSRs should be returned' );

		for( Primary_Sales_Rep__c aPSR : resultPSRs )
		{
			if( aPSR.Vertical_Minor__c == NEW_VERTICAL )
			{
				System.assertEquals( testVert.Id, aPSR.Vertical_Minor_Page__c, 'Vertical Lookup on PSR object should be set to matching Vertical' );
			}
			else
			{
				System.assertEquals( OLD_VERTICAL, aPSR.Vertical_Minor__c, 'Vertical Name should not be updated to new value' );
				System.assertEquals( null, aPSR.Vertical_Minor_Page__c, 'Vertical Lookup on PSR object should not be set' );
			}
		}
	}
}