force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reports To</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Primary Sales Reps</relationshipLabel>
    <relationshipName>R00N700000025FT1EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segment_Budget__c/Segment_Budget__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold numbers for the Segment Profitability project</description>
    <label>Segment Budget</label>
    <nameField>
        <displayFormat>SB-{00000}</displayFormat>
        <label>Segment Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Segment_Budget__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Segment_Budget__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Segment Budgets</relationshipLabel>
    <relationshipName>Segment_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Segment_Budget__c/fields/Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reports To</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Segment Budgets (Reports To)</relationshipLabel>
    <relationshipName>Segment_Budgets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Plan__c/Territory_Plan__c.object-meta.xml
<CustomObject>
    <label>Territory Plan</label>
    <nameField>
        <label>Territory Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory_Plan__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
                <default>true</default>
                <label>2016</label>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Plan__c/fields/Primary_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Primary_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Territory Plans</relationshipLabel>
    <relationshipName>R00N700000025EGKEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Plan__c/fields/Segment_Budget__c.field-meta.xml
<CustomField>
    <fullName>Segment_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Budget</label>
    <referenceTo>Segment_Budget__c</referenceTo>
    <relationshipLabel>Territory Plans</relationshipLabel>
    <relationshipName>Territory_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SelectSegmentBudgetController.cls
public with sharing class SelectSegmentBudgetController {

	private Territory_Plan__c tp;
	private Boolean foundRecord;
	
	public SelectSegmentBudgetController(ApexPages.StandardController stdController)
	{	
        tp = [select Id, Fiscal_Quarter__c, Fiscal_Year__c, Primary_Sales_Rep__c, Primary_Sales_Rep__r.Reports_To__c 
				from Territory_Plan__c where Id = :stdController.getId()];
        try
        {
        	// Query for Segment Budgets - need to include
        	// or condition at end to account for those who are their own BMs
	        Segment_Budget__c sb = [select Id from Segment_Budget__c
	        						where Fiscal_Year__c = :tp.Fiscal_Year__c
	        						and Primary_Sales_Rep__c = :tp.Primary_Sales_Rep__c
	        						and (Reports_To__c = :tp.Primary_Sales_Rep__r.Reports_To__c
	        						or Reports_To__c = :tp.Primary_Sales_Rep__c)
	        						order by LastModifiedDate DESC
	        						limit 1];
	        						
			tp.Segment_Budget__c = sb.Id;
			foundRecord = true;
        }
        catch(QueryException qe)
        {
        	foundRecord = false;
        }
        
	}
	
	public PageReference cancel()
	{
		return new PageReference('/' + tp.Id);
	}
	
	public PageReference setSegmentBudget()
	{
		if(!foundRecord)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There were no Segment Budgets found for the selected time period.'));
			return null;
		}
		else
		{
			update tp;
	        return new PageReference('/' + tp.Id);
		}
	}
}