force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Include_in_Reporting_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Reporting_Hierarchy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether a Primary Sales Rep should be included in the reporting hierarchy for Budget Allocations and Direct Report rollup- this is only necessary if they are not attached to a User record and have their User Profile field populated.</description>
    <label>Include in Reporting Hierarchy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reports To</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Primary Sales Reps</relationshipLabel>
    <relationshipName>R00N700000025FT1EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/PrimarySalesRepModelTest.cls
@isTest
public class PrimarySalesRepModelTest {

    
    private static List<Primary_Sales_Rep__c> testReps = new List<Primary_Sales_Rep__c>();
    private static Map<Id, List<Primary_Sales_Rep__c>> testReps2drs = new Map<Id, List<Primary_Sales_Rep__c>>();
    private static List<Primary_Sales_Rep__c> testDirectReports = new List<Primary_Sales_Rep__c>();
    PrimarySalesRepModel obj = new PrimarySalesRepModel();
     primary_sales_rep__c psr = obj.record ;
   
    private static List<Primary_Sales_Rep__c> createTestDirectReports(Primary_Sales_Rep__c reportsTo, Integer batch)
    {
        List<Primary_Sales_Rep__c> tempDrs = new List<Primary_Sales_Rep__c>();
        for(Integer i=0; i<5; i++)
        {
            tempDrs.add(new Primary_Sales_Rep__c(Name='Joe Test2', Network_Id__c= batch + '000' + i, Email__c='user@domain.com', Reports_To__c=reportsTo.Id, Include_in_Reporting_Hierarchy__c=true));
        }
        insert tempDrs;
        return tempDrs;
    }

    
     private static void testSetupData(Integer batchSize)
    {   
        
        testReps.clear();
        testReps2drs.clear();
        
        for(Integer i=0; i<batchSize; i++)
        {
            Primary_Sales_Rep__c testRep = new Primary_Sales_Rep__c(Name='Joe Test', Network_Id__c='1234' + i, Email__c='user@domain.com');
            
            testReps.add(testRep);          
        }
        
        insert testReps;
        for(Integer i=0; i<batchSize; ++i)
        {
            testReps2drs.put(testReps[i].Id, createTestDirectReports(testReps[i], i));
        }
            
    }
    
        public static testmethod void testgetDirectReports_Id()
    {
        testSetupData(1);
        System.assertEquals(testReps2drs.get(testReps[0].Id).size(), PrimarySalesRepModel.getDirectReports(testReps[0]).size());
        primary_sales_rep__c psr = new primary_sales_rep__c();
        PrimarySalesRepModel.getDirectReports( psr);
    }
    
    public static testmethod void testgetDirectReports_List()
    {
        testSetupData(25);
        
        for(Id psrId : testReps2drs.keySet())
        {
            testDirectReports.addAll(testReps2drs.get(psrId));
        }
        System.assertEquals(testDirectReports.size(), PrimarySalesRepModel.getDirectReports(testReps2drs.keySet()).size());
        
    }
}