force-app/main/default/objects/Primary_Sales_Rep__c/Primary_Sales_Rep__c.object-meta.xml
<CustomObject>
    <description>Used as the hub of all records related to a user.</description>
    <label>Primary Sales Rep</label>
    <nameField>
        <label>Primary Sales Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Primary Sales Reps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/deactivated_user__c.field-meta.xml
<CustomField>
    <fullName>deactivated_user__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, this Primary Sales Rep&apos;s license has been deactivated but there IS a user record associated with the Network ID.</inlineHelpText>
    <label>Deactivated User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/FS_GTM_Budget__c.field-meta.xml
<CustomField>
    <fullName>FS_GTM_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - FS CGTM Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/FS_Sales_Budget__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - FS Sales Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Include_in_Reporting_Hierarchy__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Reporting_Hierarchy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether a Primary Sales Rep should be included in the reporting hierarchy for Budget Allocations and Direct Report rollup- this is only necessary if they are not attached to a User record and have their User Profile field populated.</description>
    <label>Include in Reporting Hierarchy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <externalId>true</externalId>
    <label>Network ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Packaging_GTM_Budget__c.field-meta.xml
<CustomField>
    <fullName>Packaging_GTM_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - Packaging CGTM Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Packaging_Sales_Budget__c.field-meta.xml
<CustomField>
    <fullName>Packaging_Sales_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - Packaging Sales Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Paper_GTM_Budget__c.field-meta.xml
<CustomField>
    <fullName>Paper_GTM_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - Paper CGTM Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Paper_Sales_Budget__c.field-meta.xml
<CustomField>
    <fullName>Paper_Sales_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - Paper Sales Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Reports_To__c.field-meta.xml
<CustomField>
    <fullName>Reports_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reports To</label>
    <referenceTo>Primary_Sales_Rep__c</referenceTo>
    <relationshipLabel>Primary Sales Reps</relationshipLabel>
    <relationshipName>R00N700000025FT1EAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/SF_userid__c.field-meta.xml
<CustomField>
    <fullName>SF_userid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N7000000258R6EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Total_GTM_Budget__c.field-meta.xml
<CustomField>
    <fullName>Total_GTM_Budget__c</fullName>
    <formula>FS_GTM_Budget__c + Packaging_GTM_Budget__c + Paper_GTM_Budget__c + Unknown_GTM_Budget__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total CGTM Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Total_Sales_Budget__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales_Budget__c</fullName>
    <formula>FS_Sales_Budget__c + Packaging_Sales_Budget__c + Paper_Sales_Budget__c + Unknown_Sales_Budget__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Sales Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Unknown_GTM_Budget__c.field-meta.xml
<CustomField>
    <fullName>Unknown_GTM_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - Unknown CGTM Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/Unknown_Sales_Budget__c.field-meta.xml
<CustomField>
    <fullName>Unknown_Sales_Budget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>BM - Unknown Sales Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Primary_Sales_Rep__c/fields/user_profile__c.field-meta.xml
<CustomField>
    <fullName>user_profile__c</fullName>
    <formula>SF_userid__r.Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The profile associated with this Primary Sales Rep&apos;s user record.  Shows blank if there is no user associated.</inlineHelpText>
    <label>User: Profile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SegmentBudgetsControllerTest.cls
@isTest
public class SegmentBudgetsControllerTest {


   
/***************************************************************************************************/
/*                 TEST METHODS                                                                    */
/***************************************************************************************************/

    private static User testUser;
    private static User testSalesRepUser;
    private static Primary_Sales_Rep__c testPsr;    
    private static List<Primary_Sales_Rep__c> testDirectReports;
    
    private static Id BM_PROFILE;
    
    public static void testSetupData()
    {
       
        testUser = TestingUtils.createUser('John', 'Sales Manager - lightning', true);
        BM_PROFILE = testUser.ProfileId;
        
        testPsr = TestingUtils.createPSRs(1, 'Jimmy', 'networkid', false)[0];
        testPsr.SF_userid__c = testUser.Id;
        
        System.runAs(TestingUtils.ADMIN_USER){
        	
        	insert testPsr;
        }
        
      /*  testDirectReports = [select Id, Name from Primary_Sales_Rep__c where Reports_To__c = :testPsr.Id 
                            and (user_profile__c like 'Ind and Core Zone Manager%' or user_profile__c like 'Specialist%' or Include_in_Reporting_Hierarchy__c = true)
                            and deactivated_user__c != true];*/
                           
    }
    
    public static testmethod void testConstructor()
    {
        testSetupData();
        
        Test.startTest();                      
        SegmentBudgetsController sbc = new SegmentBudgetsController();
        
        System.assert(!sbc.isTotal);
        System.assert(sbc.isDraft);
        System.assertEquals('Paper', sbc.selectedSegment);
        System.assertEquals('2010', sbc.selectedYear);
        
        Test.stopTest();
    }
    
    public static testmethod void testConstructor_RunAs()
    {
        testSetupData();
        
        System.runAs(testUser)
        {   
            Test.startTest();                          
            SegmentBudgetsController sbc = new SegmentBudgetsController();
            
            System.assert(!sbc.isTotal);
            System.assert(sbc.isDraft);
            System.assertEquals('Paper', sbc.selectedSegment);
            System.assertEquals('2010', sbc.selectedYear);
           
           /*
           	NOTE -- COMMENTING OUT DUE TO REORG -- NEED TO UPDATE BASED ON NEW HIERARCHY 
           
            // Add 1 to testDirectReports, as in the Controller we add the BM to the list of reports as well
            System.assertEquals(testDirectReports.size() + 1, sbc.directReports.size());
            */
            Test.stopTest();
        }
    }
    
    public static testmethod void testConstructorError_RunAs_No_PSR()
    {
        testSetupData();
        
        System.runAs(new User(FirstName='John', LastName='Doe', Email='test@unisourcelink.com', 
                                Username='test@unisourcelink.com', ProfileId=BM_PROFILE,
                                Alias='tuni', Network_Id__c='tuni', TimeZoneSidKey='America/New_York', LocaleSidKey='en_US',
                                EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', Country='USA'))
        {   
            Test.startTest();                          
            SegmentBudgetsController sbc = new SegmentBudgetsController();
            
            System.assertEquals('Error: You do not have a Primary Sales Rep record.', sbc.messageBlock);            
            Test.stopTest();
        }
    }
    
    public static testmethod void testSave()
    {
    	testSetupData();
    	
    	System.runAs(testUser)
        {   
	        Test.startTest();
	                                   
	        SegmentBudgetsController sbc = new SegmentBudgetsController();
	        
	        sbc.saveAll();                  
	        Test.stopTest();
        }
    }
    
    public static testmethod void testSaveAndSendEmail()
    {
    	
        testSetupData();
        
        System.runAs(testUser)
        {    
	        Test.startTest();                          
	        SegmentBudgetsController sbc = new SegmentBudgetsController();
	                    
	        sbc.isDraft = false;
	        
	        System.debug(sbc.isDraft);
	        
	        sbc.saveAll();
	        Test.stopTest();
        }
    }

    public static testmethod void testWrapperClass()
    {
        testSetupData();
        
        System.runAs(testUser)
        {   
            Test.startTest();                          
            SegmentBudgetsController sbc = new SegmentBudgetsController();
            /*
           	NOTE -- COMMENTING OUT DUE TO REORG -- NEED TO UPDATE BASED ON NEW HIERARCHY
            // Add 1 to testDirectReports, as in the Controller we add the BM to the list of reports as well
            System.assertEquals(testDirectReports.size() + 1, sbc.directReports.size());
            */         
            //SegmentBudgetsController.PSRwrapper sbcWrap = new SegmentBudgetsController.PSRwrapper();
            for(String testSegment : new List<String>{'FS', 'Packaging', 'Paper', 'Unknown', 'Total'})
            {
                sbc.selectedSegment = testSegment;
                sbc.findSelectedBudgets();
                
                for(SegmentBudgetsController.PSRWrapper wrapper : sbc.directReports)
                {
                    Double testActiveBudget;
                    Double testGtmActiveBudget;
                    String testActiveBudgetString;
                    String testGtmActiveBudgetString;
                    
                    if(testSegment == 'FS')
                    {
                        testActiveBudget = wrapper.budget.FS_Sales_Budget__c != null ? wrapper.budget.FS_Sales_Budget__c : 0;
                        testGtmActiveBudget = wrapper.budget.FS_GTM_Budget__c != null ? wrapper.budget.FS_GTM_Budget__c : 0;
                    }
                    else if(testSegment == 'Packaging')
                    {
                        testActiveBudget = wrapper.budget.Packaging_Sales_Budget__c != null ? wrapper.budget.Packaging_Sales_Budget__c : 0;
                        testGtmActiveBudget = wrapper.budget.Packaging_GTM_Budget__c != null ? wrapper.budget.Packaging_GTM_Budget__c : 0;
                    }
                    else if(testSegment == 'Paper')
                    {
                        testActiveBudget = wrapper.budget.Paper_Sales_Budget__c != null ? wrapper.budget.Paper_Sales_Budget__c : 0;
                        testGtmActiveBudget = wrapper.budget.Paper_GTM_Budget__c != null ? wrapper.budget.Paper_GTM_Budget__c : 0;
                    }
                    else if(testSegment == 'Unknown')
                    {
                        testActiveBudget = wrapper.budget.Unknown_Sales_Budget__c != null ? wrapper.budget.Unknown_Sales_Budget__c : 0;
                        testGtmActiveBudget = wrapper.budget.Unknown_GTM_Budget__c != null ? wrapper.budget.Unknown_GTM_Budget__c : 0;
                    }
                    else if(testSegment == 'Total')
                    {
                        testActiveBudget = wrapper.budget.Total_Sales_Budget__c != null ? wrapper.budget.Total_Sales_Budget__c : 0;
                        testGtmActiveBudget = wrapper.budget.Total_GTM_Budget__c != null ? wrapper.budget.Total_GTM_Budget__c : 0;
                    }
                    
                    testActiveBudgetString = testActiveBudget.format();
                    testGtmActiveBudgetString = testGtmActiveBudget.format();
                    
                    System.assertEquals(testActiveBudget, wrapper.activeBudgetDecimal);
                    System.assertEquals(testActiveBudgetString, wrapper.activeBudget);
                    System.assertEquals(testGtmActiveBudget, wrapper.activeGTMBudgetDecimal);
                    System.assertEquals(testGtmActiveBudgetString, wrapper.activeGTMBudget);
                }
            }
            
            Test.stopTest();
        }
    }
    
    public static testmethod void testWrapperClass_baseFormattedContent()
    {
        testSetupData();
        System.runAs(testUser)
        {   
            Test.startTest();                          
            SegmentBudgetsController sbc = new SegmentBudgetsController();
            
            for(SegmentBudgetsController.PSRWrapper wrapper : sbc.directReports)
            {
            	System.assertNotEquals(null, wrapper.baseFormattedContent);
            }
            Test.stopTest();
        }
    }
    
    public static testmethod void testWrapperClass_bmFormattedContent()
    {
        testSetupData();
        System.runAs(testUser)
        {   
            Test.startTest();                          
            SegmentBudgetsController sbc = new SegmentBudgetsController();
        	System.assertNotEquals(null, sbc.currentUser.bmFormattedContent);
        	Test.stopTest();
        }
    }
}