force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Costing_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Costing_unit_of_measure__c</fullName>
    <label>Costing UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Price_unit_of_measure__c</fullName>
    <label>Price/Cost UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ViewAdditionalDetailsQuoteContExt.cls
/**
 Objective: Ability to update additional field details on a Quote_Line_Item__c object
 Developer: Hiremath, Naveen - Bluewolf
*/
public with sharing class ViewAdditionalDetailsQuoteContExt {

	public Quote__c quote { get; private set; }

	public QuoteLineItemModel qliModel { get; private set; }

	private String quoteId;
	private String qliIds;

	public Boolean isValidQuote {
        get
        {
            if(isValidQuote == null)
            {
                if(quoteId == null)
                {
                    isValidQuote = false;
                    return isValidQuote;
                }
                else
                {
                    isValidQuote = true;
                    return isValidQuote;
                }
            }
            return isValidQuote;
        }
        set
        {
            isValidQuote = value;
        }
    }

    public void saveQLI() {

    	List<Quote_Line_Item__c> qliList = new List<Quote_Line_Item__c>();
    	Quote_Line_Item__c qli;

    	for(QuoteLineItemModel qliModel : this.qliModel.getSelectedProducts()) {
    		qli = qliModel.getQuoteLineItem();
    		qli.Costing_unit_of_measure__c = qli.Price_unit_of_measure__c;
    		qliList.add(qli);
    	}
    	try {
    		update qliList;
    		ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.CONFIRM, 'Records updated successfully' ) );
    	} catch(DMLException dmle) {
    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There was an error while updating the records.', Consts.EMPTY_STRING));
    	}

    }


    public ViewAdditionalDetailsQuoteContExt(ApexPages.StandardController standardController) {

		this.quote          = (Quote__c)standardController.getRecord();

		this.quoteId        = ApexPages.currentPage().getParameters().get('id');
		this.qliIds         = ApexPages.currentPage().getParameters().get('qliIds');

		if(this.quoteId  == null || this.quoteId == Consts.EMPTY_STRING ||
		   this.qliIds == null || this.qliIds == Consts.EMPTY_STRING) {

		   	this.quoteId = null;
			 return;

		}

    	Set<Id> setOfQliIds = new Set<Id>();
    	for(String qliId :qliIds.split(','))
    	{
    		if( qliId != null && qliId != '' )
    		{
    			setOfQliIds.add(qliId);
    		}
    	}

		QuotesModel quoteModel = new QuotesModel(this.quote);
		this.qliModel = new QuoteLineItemModel(
											quoteModel,
											new Quote_Line_Item__c(),
											QuoteLineItemServices.getQuoteLineItem(quoteId, setOfQliIds));

    }

}