force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Customer Comments (will print on Quote)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Quote Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Basis_Weight__c.field-meta.xml
<CustomField>
    <fullName>Basis_Weight__c</fullName>
    <label>Basis Wgt</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Bid_number_Contract_number__c.field-meta.xml
<CustomField>
    <fullName>Bid_number_Contract_number__c</fullName>
    <label>Bid #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Brightness__c.field-meta.xml
<CustomField>
    <fullName>Brightness__c</fullName>
    <label>Brightness</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Comments_Short__c.field-meta.xml
<CustomField>
    <fullName>Comments_Short__c</fullName>
    <label>Comments</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Core__c.field-meta.xml
<CustomField>
    <fullName>Core__c</fullName>
    <label>Core</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost_Code__c.field-meta.xml
<CustomField>
    <fullName>Cost_Code__c</fullName>
    <label>Cost Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Cost_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Cost_Unit_Factor__c</fullName>
    <label>Cost Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Costing_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Costing_unit_of_measure__c</fullName>
    <label>Costing UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/End_User_Agreement__c.field-meta.xml
<CustomField>
    <fullName>End_User_Agreement__c</fullName>
    <label>End User Agreement #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Extended_Cost__c.field-meta.xml
<CustomField>
    <fullName>Extended_Cost__c</fullName>
    <label>Extd&apos;d Cost</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Extended_Price__c.field-meta.xml
<CustomField>
    <fullName>Extended_Price__c</fullName>
    <label>Ext Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Finish__c.field-meta.xml
<CustomField>
    <fullName>Finish__c</fullName>
    <label>Finish</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Floor_Price__c.field-meta.xml
<CustomField>
    <fullName>Floor_Price__c</fullName>
    <description>Edit 10/2017 to up the length from 4 to 6</description>
    <label>Floor Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Grade_Name_Class__c.field-meta.xml
<CustomField>
    <fullName>Grade_Name_Class__c</fullName>
    <label>Grade Name/Class</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/GTM_CAS__c.field-meta.xml
<CustomField>
    <fullName>GTM_CAS__c</fullName>
    <label>GTM($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/GTM_percent__c.field-meta.xml
<CustomField>
    <fullName>GTM_percent__c</fullName>
    <formula>IF(Price__c != 0,
1 - ( Cost__c / Price__c ),
0
)</formula>
    <label>GTM %</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Item_Origin__c.field-meta.xml
<CustomField>
    <fullName>Item_Origin__c</fullName>
    <label>Item Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Substituted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Item_Seq__c.field-meta.xml
<CustomField>
    <fullName>Item_Seq__c</fullName>
    <label>Item Seq</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Last_Date_of_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Date_of_Change__c</fullName>
    <label>Last Date of Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Locked__c.field-meta.xml
<CustomField>
    <fullName>Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>BW-2012
Identifies locked line items</description>
    <label>Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/mfg_tolerance__c.field-meta.xml
<CustomField>
    <fullName>mfg_tolerance__c</fullName>
    <label>MFG Tol</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Minimum_mfg_quantity__c.field-meta.xml
<CustomField>
    <fullName>Minimum_mfg_quantity__c</fullName>
    <label>Minimum mfg quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Outer_Diameter__c.field-meta.xml
<CustomField>
    <fullName>Outer_Diameter__c</fullName>
    <label>OD</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_Code__c.field-meta.xml
<CustomField>
    <fullName>Price_Code__c</fullName>
    <label>Price Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Price_Unit_Factor__c</fullName>
    <label>Price Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Price_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Price_unit_of_measure__c</fullName>
    <label>Price/Cost UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxOEAU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Projected_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Projected_Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_Unit_Factor__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Unit_Factor__c</fullName>
    <label>Quantity Unit Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quantity_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Quantity_unit_of_measure__c</fullName>
    <label>Qty UOM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Roll_Size__c.field-meta.xml
<CustomField>
    <fullName>Roll_Size__c</fullName>
    <label>Roll Size</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Special_Item__c.field-meta.xml
<CustomField>
    <fullName>Special_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Special_Product__c.field-meta.xml
<CustomField>
    <fullName>Special_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Special Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Start_Price__c.field-meta.xml
<CustomField>
    <fullName>Start_Price__c</fullName>
    <description>Created 12/2017 to capture Start Price as passed over from Zilliant in the GetPrice call on a Quote. To be shown on the QLI table, Additional Details, and Fetch P&amp;A table. Value always comes from Zilliant but will be overwritten in our code to = 0 if the Shipment_Method__c on the Quote is Direct.</description>
    <inlineHelpText>Start Price from Zilliant</inlineHelpText>
    <label>Start Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Stock_Manufactured__c.field-meta.xml
<CustomField>
    <fullName>Stock_Manufactured__c</fullName>
    <label>Stocked/Mfg&apos;d</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manufactured</fullName>
                <default>true</default>
                <label>Manufactured</label>
            </value>
            <value>
                <fullName>Stocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Target_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Price__c</fullName>
    <description>Edit 10/2017 to up the length from 4 to 6</description>
    <label>Target Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Type_Of_Quote__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Quote__c</fullName>
    <label>Type Of Quote</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Specific</fullName>
                <default>true</default>
                <label>Specific</label>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Unisource_Item__c.field-meta.xml
<CustomField>
    <fullName>Unisource_Item__c</fullName>
    <label>Unisource Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.Vendor_Lookup__c</field>
            <operation>equals</operation>
            <valueField>$Source.Vendor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxcEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Item__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Item__c</fullName>
    <label>Vendor Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Name</label>
    <referenceTo>Vendor_Detail__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>R00N700000024LxxEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteLineItemServices.cls
/**
 Objective: Noninstantiable services class that collects all
 			static SOQL service methods operating on Quote_Line_Item__c object
 Developer: Hiremath, Naveen - Bluewolf
*/
public with sharing class QuoteLineItemServices {

	/**
	 Get a list of all the quote line items for a given quoteId
	*/
	public static List<Quote_Line_Item__c> getQuoteLineItems(Id quoteId) {

		return [SELECT Id, Price_Code__c, Cost_Code__c,
        			End_User_Agreement__c, Extended_Price__c,
        			Cost_Unit_Factor__c, Price_Unit_Factor__c,
        			Quantity_Unit_Factor__c, GTM_CAS__c,
        			GTM_percent__c, Bid_number_Contract_number__c,
        			mfg_tolerance__c, Vendor_Name__c, Vendor_Item__c,
        			Vendor_Contact__c, Quantity_unit_of_measure__c,
        			Qty__c, Projected_Delivery_Date__c,
        			Product_Description__c, Product__c,
        			Product_Code__c, Price__c, Start_Price__c, Target_Price__c, Floor_Price__c,
                    Minimum_mfg_quantity__c,
        			Last_Date_of_Change__c, Cost__c, Special_Product__c,
        			Special_Item__c, Price_unit_of_measure__c,
        			Costing_unit_of_measure__c, Product__r.System_ID__c,
        			Product__r.Division_Code__c, Unisource_Item__c,
        			Comments_Short__c, Comments__c,  Vendor_Name__r.Name, Item_Seq__c,
        			Extended_Cost__c, Locked__c, Quote__c,
        			// Web Center fields
        			Type_Of_Quote__c, Item_Origin__c, Roll_Size__c,
					Basis_Weight__c, Outer_Diameter__c, Core__c,
					Color__c, Brightness__c, Brand__c, Finish__c,
					Stock_Manufactured__c, Grade_Name_Class__c,
					Recycled_Content__c, PCW_Content__c,
					Coc_Required__c, Last_Date_To_Order__c,CostCommision__c, CurrencyIsoCode,
					Future_Dev_Cost__c,
                    // Update Pricing Details
                    Pricing_Start_Date__c,
                    List_Down_Percent__c, Cost_Up_Percent__c, Sent_To_Zilliant_Time__c,Quote__r.Account__r.Account_SysDivBillTo__c 
      			FROM Quote_Line_Item__c
        		WHERE Quote__c = :quoteId
        		ORDER BY Item_Seq__c ASC, CreatedDate ASC];

	}

	/**
	 Get the quote line item for the given quoteId and quoteLineItemId
	*/
	public static List<Quote_Line_Item__c> getQuoteLineItem(Id quoteId, Id qliId) {

		return [SELECT Id, Price_Code__c, Cost_Code__c,
        			End_User_Agreement__c, Extended_Price__c,
        			Cost_Unit_Factor__c, Price_Unit_Factor__c,
        			Quantity_Unit_Factor__c, GTM_CAS__c,
        			GTM_percent__c, Bid_number_Contract_number__c,
        			mfg_tolerance__c, Vendor_Name__c, Vendor_Item__c,
        			Vendor_Contact__c, Quantity_unit_of_measure__c,
        			Qty__c, Projected_Delivery_Date__c,
        			Product_Description__c, Product__c,
        			Product_Code__c, Price__c, Start_Price__c, Minimum_mfg_quantity__c,
        			Last_Date_of_Change__c, Cost__c, Special_Product__c,
        			Special_Item__c, Price_unit_of_measure__c,
        			Costing_unit_of_measure__c, Product__r.System_ID__c,
        			Product__r.Division_Code__c, Unisource_Item__c,
        			Comments_Short__c, Comments__c, Vendor_Name__r.Name, Item_Seq__c,
        			Extended_Cost__c, Locked__c, Quote__c,
        			// Web Center fields
        			Type_Of_Quote__c, Item_Origin__c, Roll_Size__c,
					Basis_Weight__c, Outer_Diameter__c, Core__c,
					Color__c, Brightness__c, Brand__c, Finish__c,
					Stock_Manufactured__c, Grade_Name_Class__c,
					Recycled_Content__c, PCW_Content__c,
					Coc_Required__c, Last_Date_To_Order__c,CostCommision__c, CurrencyIsoCode,
					// Additional Details
					Cust_Item_Code__c, Price_Origin__c, Contract_Price_Cd__c, Target_Price__c,
					Floor_Price__c, Future_Dev_Cost__c, Future_Dev_Cost_Starts__c,
					Rebate_Code_Desc__c, Rebate_Starts__c, Rebate_Ends__c,
                    // Update Pricing Details
                    Pricing_Start_Date__c,
                    List_Down_Percent__c, Cost_Up_Percent__c, Sent_To_Zilliant_Time__c, Updated_P_A__c, Quote__r.Account__r.Account_SysDivBillTo__c 
      			FROM Quote_Line_Item__c
        		WHERE Quote__c = :quoteId AND
        		Id = :qliId
        		ORDER BY Item_Seq__c ASC, CreatedDate ASC];

	}

	/**
	 Get the quote line item for the given quoteId and Set of quoteLineItemIds
	*/
	public static List<Quote_Line_Item__c> getQuoteLineItem(Id quoteId, Set<Id> qliIds) {

		System.debug('*** QiD: ' + quoteId + ' QLIiD: ' + qliIds);
		
		return [SELECT Id, Price_Code__c, Cost_Code__c,
        			End_User_Agreement__c, Extended_Price__c,
        			Cost_Unit_Factor__c, Price_Unit_Factor__c,
        			Quantity_Unit_Factor__c, GTM_CAS__c,
        			GTM_percent__c, Bid_number_Contract_number__c,
        			mfg_tolerance__c, Vendor_Name__c, Vendor_Item__c,
        			Vendor_Contact__c, Quantity_unit_of_measure__c,
        			Qty__c, Projected_Delivery_Date__c,
        			Product_Description__c, Product__c,
        			Product_Code__c, Price__c, Start_Price__c, Minimum_mfg_quantity__c,
        			Last_Date_of_Change__c, Cost__c, Special_Product__c,
        			Special_Item__c, Price_unit_of_measure__c,
        			Costing_unit_of_measure__c, Product__r.System_ID__c,
        			Product__r.Division_Code__c, Unisource_Item__c,
        			Comments_Short__c, Comments__c, Vendor_Name__r.Name, Item_Seq__c,
        			Extended_Cost__c, Locked__c, Quote__c, Duty__c, Exchange__c, Brokerage__c,
        			// Web Center fields
        			Type_Of_Quote__c, Item_Origin__c, Roll_Size__c,
					Basis_Weight__c, Outer_Diameter__c, Core__c,
					Color__c, Brightness__c, Brand__c, Finish__c,
					Stock_Manufactured__c, Grade_Name_Class__c,
					Recycled_Content__c, PCW_Content__c,
					Coc_Required__c, Last_Date_To_Order__c,CostCommision__c, CurrencyIsoCode,
					// Additional Details
					Cust_Item_Code__c, Price_Origin__c, Contract_Price_Cd__c, Target_Price__c,
					Floor_Price__c, Future_Dev_Cost__c, Future_Dev_Cost_Starts__c,
					Rebate_Code_Desc__c, Rebate_Starts__c, Rebate_Ends__c,
					// Related Product2
					Product__r.Set__c, Product__r.Subset__c, Product__r.Class__c, Product__r.Brand__c, Product__r.Segment__c,
					Product__r.CWT_Item_Level_Pricing_Allowed__c, Product__r.CWT_Set_Level_Pricing_Allowed__c, Product__r.CWT_Subset_Level_Pricing_Allowed__c,
					//Product__r.List_Down_Percent__c, Product__r.Cost_Up_Percent__c, Pricing_Start_Date__c
					// Update Pricing Details
					Pricing_Start_Date__c,
					List_Down_Percent__c, Cost_Up_Percent__c, Sent_To_Zilliant_Time__c, Quote__r.Account__r.Account_SysDivBillTo__c 
      			FROM Quote_Line_Item__c
        		WHERE Quote__c = :quoteId AND
        		Id IN :qliIds
        		ORDER BY Item_Seq__c ASC, CreatedDate ASC];

	}

	/**
	 Suppress default constructor for noninstantiability
	*/
	private QuoteLineItemServices() { }

}