force-app/main/default/objects/User/fields/Delegation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Delegation_End_Date__c</fullName>
    <description>End Date for temporary override for routing of Contract Line Item Approval records</description>
    <inlineHelpText>End Date for temporary override for routing of Contract Line Item Approval records</inlineHelpText>
    <label>Delegation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Delegation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Delegation_Start_Date__c</fullName>
    <description>Start Date for temporary override for routing of Contract Line Item Approval records</description>
    <inlineHelpText>Start Date for temporary override for routing of Contract Line Item Approval records</inlineHelpText>
    <label>Delegation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Pricing_Delegated_Approver__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Delegated_Approver__c</fullName>
    <description>Temporary override for routing of Contract Line Item Approval records based on Delegation Start and End Date</description>
    <inlineHelpText>Temporary override for routing of Contract Line Item Approval records based on Delegation Start and End Date</inlineHelpText>
    <label>Pricing Delegated Approver</label>
    <relationshipName>PricingDelegatedApprover</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/DelegatedApprovalController.cls
public with sharing class DelegatedApprovalController {

    @AuraEnabled 
    public static user fetchUser(String userId) {
        // query current user information 
        User oUser = [SELECT id, Name, DelegatedApproverId, Pricing_Delegated_Approver__c, Delegation_Start_Date__c, Delegation_End_Date__c
                      FROM User WHERE id =: userId];
        return oUser;
    }
    
    
}