force-app/main/default/objects/User/fields/Inherit_Reporting_Hierarch__c.field-meta.xml
<CustomField>
    <fullName>Inherit_Reporting_Hierarch__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Inherit Reporting Hierarch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Reporting_Hierarchy_Update_Needed__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Hierarchy_Update_Needed__c</fullName>
    <formula>OR (

name_zm_sm__c != Manager.name_zm_sm__c,
name_gsm__c != Manager.name_gsm__c,
name_bdm_rvp__c != Manager.name_bdm_rvp__c,
name_pres__c != Manager.name_pres__c,
name_team_lead__c != Manager.name_team_lead__c,
name_dir__c != Manager.name_dir__c,
name_dmd__c != Manager.name_dmd__c,
name_vp__c != Manager.name_vp__c,

ZM_SM_Email__c != Manager.ZM_SM_Email__c,
GSM_Email__c != Manager.GSM_Email__c,
BDM_RVP_Email__c != Manager.BDM_RVP_Email__c,
Pres_Email__c != Manager.Pres_Email__c,
TL_Email__c != Manager.TL_Email__c,
Dir_Email__c != Manager.Dir_Email__c,
Email_DMD__c != Manager.Email_DMD__c,
Vice_President_Email__c != Manager.Vice_President_Email__c

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporting Hierarchy Update Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UserManagerUpdateBatch.cls
global class UserManagerUpdateBatch implements Database.Batchable<SObject>, Database.Stateful, Schedulable{
	
	ErrorHandling.ErrorLog errorLog;
	
    global UserManagerUpdateBatch()
    {
    	errorLog = new ErrorHandling.ErrorLog();
    }
	
    global database.querylocator start(Database.BatchableContext bc)
    {
    	String subordinatesQuery = 'Select Id, ManagerId,' + String.join(UserService.reportingHierarchyFields, ',') + ' From User ' +
    		'Where Inherit_Reporting_Hierarch__c = true AND Reporting_Hierarchy_Update_Needed__c = true AND isActive = true';
        return Database.getQueryLocator( subordinatesQuery );
    }

    global void execute(Database.BatchableContext bc, List<User> userSubordinatesToUpdate)
    {
    	PrimarySalesRepServices.batchRunning = true;
    	UserService.forceUserUpdate = true;
    	SafeUpdate updateDML = new SafeUpdate();
    	
		updateDML.queue(userSubordinatesToUpdate, errorLog);
		updateDML.doDML();
		
    	UserService.forceUserUpdate = false;
    }
    
    global void execute(SchedulableContext sc)
	{
		UserManagerUpdateBatch batchSheduled = new UserManagerUpdateBatch();
		Database.executeBatch( batchSheduled,50);
	}

    global void finish(Database.BatchableContext bc)
    {
    	if (errorLog.areThereErrors()) 
        {
            errorLog.emailLog(new List<String>{UserInfo.getUserEmail()}, 'Errors encountered while updating manager fields');
        }
    }
    
}