force-app/main/default/objects/Opportunity/recordTypes/Kitting.recordType-meta.xml
<RecordType>
    <fullName>Kitting</fullName>
    <active>true</active>
    <businessProcess>Lightning Sales Process</businessProcess>
    <description>For Kitting Opportunities, available only in Lightning</description>
    <label>Kitting Opportunity - Lightning</label>
</RecordType>

force-app/main/default/objects/OpportunitySpecialistMapping__c/OpportunitySpecialistMapping__c.object-meta.xml
<CustomObject>
    <label>Opportunity Specialist Mapping</label>
    <nameField>
        <label>Opportunity Specialist Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Specialist Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunitySpecialistMapping__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunitySpecialistMapping__c/fields/Role_ID__c.field-meta.xml
<CustomField>
    <fullName>Role_ID__c</fullName>
    <label>Role ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoleNameMapping__c/RoleNameMapping__c.object-meta.xml
<CustomObject>
    <description>Maps role names to Product Categories for specialists</description>
    <label>Role Name Mapping</label>
    <nameField>
        <label>RoleNameMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role Name Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoleNameMapping__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3PL</fullName>
            </value>
            <value>
                <fullName>CAN LINERS</fullName>
            </value>
            <value>
                <fullName>CAN LINERS-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>CARBONLESS</fullName>
            </value>
            <value>
                <fullName>CHEMICALS</fullName>
            </value>
            <value>
                <fullName>CHEMICALS-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>COATED BOARD - ROLLS</fullName>
            </value>
            <value>
                <fullName>COATED BOARD - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED DOMESTIC - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED IMPORT - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED - ROLLS</fullName>
            </value>
            <value>
                <fullName>CORRUGATED</fullName>
            </value>
            <value>
                <fullName>CUSHIONING</fullName>
            </value>
            <value>
                <fullName>ENVELOPES</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT-FACILITY SUPPLIES</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT-FACILITY SUPPLY-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT - PACKAGING</fullName>
            </value>
            <value>
                <fullName>FOOD PACKAGING</fullName>
            </value>
            <value>
                <fullName>FOOD SERVICE</fullName>
            </value>
            <value>
                <fullName>IMAGING - CUT/SHEETS/ROLLS</fullName>
            </value>
            <value>
                <fullName>INVENTORY MGT</fullName>
            </value>
            <value>
                <fullName>KITTING</fullName>
            </value>
            <value>
                <fullName>OTHER PACKAGING</fullName>
            </value>
            <value>
                <fullName>OTHER PAPER</fullName>
            </value>
            <value>
                <fullName>OTHER SUPPLY</fullName>
            </value>
            <value>
                <fullName>PACKAGES</fullName>
            </value>
            <value>
                <fullName>PACKAGING MATERIALS</fullName>
            </value>
            <value>
                <fullName>PARTS</fullName>
            </value>
            <value>
                <fullName>REVERSE LOGISTICS</fullName>
            </value>
            <value>
                <fullName>SANITARY MAINTENANCE</fullName>
            </value>
            <value>
                <fullName>SANITARY MAINTENANCE-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>SHRINK FILM</fullName>
            </value>
            <value>
                <fullName>SPECIALTY FILM</fullName>
            </value>
            <value>
                <fullName>STRETCH FILM</fullName>
            </value>
            <value>
                <fullName>STRETCH FILM-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>TAPES</fullName>
            </value>
            <value>
                <fullName>TAPES-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>TCW</fullName>
            </value>
            <value>
                <fullName>TECHNICAL PLASTICS</fullName>
            </value>
            <value>
                <fullName>UNCOATED BOARD - CUT/SHEETS</fullName>
            </value>
            <value>
                <fullName>UNCOATED BOARD - ROLLS</fullName>
            </value>
            <value>
                <fullName>UNCOATED OFFSET - CUT/SHEETS</fullName>
            </value>
            <value>
                <fullName>UNCOATED OFFSET - ROLLS</fullName>
            </value>
            <value>
                <fullName>UNCOATED OPAQUE - CUT/SHEETS</fullName>
            </value>
            <value>
                <fullName>UNCOATED OPAQUE - ROLLS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoleNameMapping__c/fields/Role_Name__c.field-meta.xml
<CustomField>
    <fullName>Role_Name__c</fullName>
    <label>Role Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/OSM_Override__c.field-meta.xml
<CustomField>
    <fullName>OSM_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OSM Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OsmInfo.cls
/**get Opp specialist mapping info to display*/
public class OsmInfo
{
	public Opportunity opp {get; set;}
	public List<OpportunitySpecialistMapping__c> specialistMapping {get; set;}
	
	
	public List<String> mappingStrings {get; set;}
	
	private Map<Id, UserRole> roleId2Role;
	
	public static final String ADMIN_PREFIX = 'Admin -';
	public static final String BM_PREFIX = 'BM -';
	public static final String SALES_PREFIX = 'Sales Rep';
	
	public static List<RoleNameMapping__c> roleNameMapping = [SELECT Id, Role_Name__c, Product_Category__c FROM RoleNameMapping__c];
	
	public OsmInfo()
	{
		//All roles
		roleId2Role = new Map<Id, UserRole>([SELECT Id, Name, ParentRoleId FROM UserRole]);
		opp = new Opportunity();
	}
	
	public void calcMapping()
	{
		User u = [SELECT Id, Name, UserRoleId, OSM_Override__c FROM User where Id = :opp.OwnerId ];
		
		
		UserRole role = roleId2Role.get(u.UserRoleId);
		UserRole topRole = (u.OSM_Override__c) ? role : getTopRoleInHierarchy(roleId2Role, role);
		
		specialistMapping = [SELECT Role_ID__c, Group_ID__c, Id 
							  FROM OpportunitySpecialistMapping__c
							   WHERE Role_ID__c = :topRole.Id ];
							   
		System.debug(specialistMapping);
		
		Map<String, List<User>> category2Specialists = getCategoryToSpecialistsMapping(specialistMapping, categories);	
		System.debug(category2Specialists);
		
		mappingStrings = new List<String>();
		for(String category : category2Specialists.keySet())
		{
			if(!category2Specialists.get(category).isEmpty())
			{
				for(User user : category2Specialists.get(category))
				{
					mappingStrings.add(category +' : ' +user.Name);
				}
			}
		}
	}
	
	private static UserRole getTopRoleInHierarchy(Map<Id, UserRole> roleId2Role, UserRole startRole)
	{
		//System.debug('CurrentRole:'+role.Name);		
		UserRole currentRole = startRole;
		UserRole topRoleInHierarchy;

		while(topRoleInHierarchy == null)
		{
			if(currentRole.ParentRoleId == null)
				topRoleInHierarchy = currentRole;
			else if(currentRole.Name.startsWith(ADMIN_PREFIX) || 
					(!startRole.Name.startsWith(SALES_PREFIX) && !startRole.Name.startsWith(BM_PREFIX)))
				topRoleInHierarchy = currentRole;
			else
				currentRole = roleId2Role.get(currentRole.ParentRoleId);
		}
		
		return topRoleInHierarchy;
	}
	
	private static Map<String, List<User>> getCategoryToSpecialistsMapping(List<OpportunitySpecialistMapping__c> specialistMapping, Set<String> categories)
	{
		Map<String, List<User>> category2specialists = new Map<String, List<User>>();		
		Set<Id> groupMemberIds = new Set<Id>();
		Set<Id> specialistMappingGroupIds = new Set<Id>();
		
		
		for(OpportunitySpecialistMapping__c sm : specialistMapping)
		{
			specialistMappingGroupIds.add(sm.Group_ID__c);
		}
		
		//Get user Ids from group members
		for(GroupMember gm : [SELECT UserOrGroupId, GroupId
							   FROM GroupMember
							    WHERE GroupId IN :specialistMappingGroupIds])
		{
			if((gm.UserOrGroupId + '').startsWith('005'))
			{
				groupMemberIds.add(gm.UserOrGroupId);
			}
		} 
		
		List<User> users = [SELECT Id, Title, UserRole.Name, IsActive, Name, Email, FirstName, LastName
		 FROM User 
		  WHERE Id IN : groupMemberIds 
		   AND IsActive = true];
		
		for(String category : categories)
		{
			category2specialists.put(category, new List<User>());
			
			for(User u : users)
			{
				if(isSpecialistMatch(u.UserRole.Name, category))
				{
					List<User> specialists = category2specialists.get(category);
					specialists.add(u); 
					category2specialists.put(category, specialists);
				}
			}				
		}
		
		System.debug('cat2specialists:'+category2specialists);		
		return category2specialists;
	}
	
	public static Boolean isSpecialistMatch(String roleName, String productCategory)
	{
		for(RoleNameMapping__c rm : roleNameMapping)
		{
			if(productCategory == rm.Product_Category__c && rm.Role_Name__c == roleName )
				return true;
		}  
		
		return false;
	}
	
			public static Set<String> categories = new Set<String> {'CARBONLESS', 'COATED - ROLLS',
'COATED BOARD - ROLLS',
'COATED BOARD - SHEETS',
'COATED DOMESTIC - SHEETS',
'COATED IMPORT - SHEETS',
'ENVELOPES',
'IMAGING - CUT/SHEETS/ROLLS',
'OTHER PAPER',
'TCW',
'UNCOATED BOARD - CUT/SHEETS',
'UNCOATED BOARD - ROLLS',
'UNCOATED OFFSET - CUT/SHEETS',
'UNCOATED OFFSET - ROLLS',
'UNCOATED OPAQUE - CUT/SHEETS',
'CAN LINERS',
'CAN LINERS-PRIVATE BRAND',
'CHEMICALS',
'CHEMICALS-PRIVATE BRAND',
'EQUIPMENT-FACILITY SUPPLIES',
'EQUIPMENT-FACILITY SUPPLY-PRIVATE BRAND',
'FOOD SERVICE',
'OTHER SUPPLY',
'SANITARY MAINTENANCE',
'SANITARY MAINTENANCE-PRIVATE BRAND',
'TOWEL & TISSUE',
'TOWEL & TISSUE PRIVATE BRAND',
'UNCOATED OPAQUE - ROLLS',
'CORRUGATED',
'CUSHIONING',
'EQUIPMENT - PACKAGING',
'FOOD PACKAGING',
'OTHER PACKAGING',
'PACKAGES',
'PACKAGING MATERIALS',
'PARTS',
'SHRINK FILM',
'SPECIALTY FILM',
'STRETCH FILM',
'STRETCH FILM-PRIVATE BRAND',
'TAPES',
'TAPES-PRIVATE BRAND',
'TECHNICAL PLASTICS',
'3PL',
'KITTING',
'REVERSE LOGISTICS',
'INVENTORY MGT'};
	
}