force-app/main/default/objects/Engineered_Package_Project__c/Engineered_Package_Project__c.object-meta.xml
<CustomObject>
    <description>UES projects synced with corresponding information in @Task.</description>
    <label>Engineered Package Project</label>
    <nameField>
        <label>Engineered Package Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engineered Package Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engineered_Package_Project__c/fields/Billable_Project__c.field-meta.xml
<CustomField>
    <fullName>Billable_Project__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billable Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Engineered_Package_Project__c/fields/Box_com_URL__c.field-meta.xml
<CustomField>
    <fullName>Box_com_URL__c</fullName>
    <label>Box.com URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Engineered_Package_Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Engineered Package Projects</relationshipLabel>
    <relationshipName>Engineered_Package_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engineered_Package_Project__c/fields/Project_Stage__c.field-meta.xml
<CustomField>
    <fullName>Project_Stage__c</fullName>
    <label>Project Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Idea</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Engineered_Package_Project__c/fields/Ship_Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Ship_Tracking_Number__c</fullName>
    <label>Ship Tracking Number</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Engineered_Package_Project__c/fields/UWW_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>UWW_Part_Number__c</fullName>
    <description>Maps to @Task.</description>
    <label>Project #</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <description>Child object to Engineered Packaging Project object. This object was built to house info fed into Salesforce from @Task.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Planned_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Completion_Date__c</fullName>
    <label>Planned Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Primary_Material__c.field-meta.xml
<CustomField>
    <fullName>Primary_Material__c</fullName>
    <label>Primary Material</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fabricated Foam</fullName>
            </value>
            <value>
                <fullName>Molded Foam</fullName>
            </value>
            <value>
                <fullName>Paper Corrugated</fullName>
            </value>
            <value>
                <fullName>Plastic Corrugated</fullName>
            </value>
            <value>
                <fullName>Folding Carton</fullName>
            </value>
            <value>
                <fullName>Bio-Pulp</fullName>
            </value>
            <value>
                <fullName>Bio-Polymer</fullName>
            </value>
            <value>
                <fullName>Wood</fullName>
            </value>
            <value>
                <fullName>Cloth</fullName>
            </value>
            <value>
                <fullName>Hexacomb</fullName>
            </value>
            <value>
                <fullName>Thermoform</fullName>
            </value>
            <value>
                <fullName>Returnable</fullName>
            </value>
            <value>
                <fullName>Injection Molding</fullName>
            </value>
            <value>
                <fullName>Rack Systems</fullName>
            </value>
            <value>
                <fullName>Assembly</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Engineered_Package_Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AtTask.cls
/**
 *  @Author: Naveen Hiremath
 *  @Company: Bluewolf
 *  @Purpose: Represents core logic for AtTask Project integration 
*/


public class AtTask {
    
    public final Id oppId {
        get;
        private set;
    }
    
    public final AtTaskColumnModel columnModel {
        get;
        private set;
    }
    
    public AtTask(Id oppId) {
        this.oppId = oppId;
        
        final List<Engineered_Package_Project__c> oppProjectsAndTasks = this.lookupEngineeredPackageProjectsAndItsTasks();
        
        if(!oppProjectsAndTasks.isEmpty()) {
            this.columnModel = new AtTaskColumnModel(oppProjectsAndTasks);
        }
    }
    /* Sujitha Damidi Backlog#803
    Add 3 new fields to the VF page for Engineered Package Project object 

Billable_Project__c
Box_com_URL__c
Ship_Tracking_Number__c
*/
    
    private List<Engineered_Package_Project__c> lookupEngineeredPackageProjectsAndItsTasks() {      
        return [
            Select
                Id, 
                Name,
                Opportunity__c,
                Project_Stage__c,
                UWW_Part_Number__c,
                Planned_Completion_Date__c,
                Total_Project_Hours__c,
                Billable_Project__c,
                Box_com_URL__c,
                Ship_Tracking_Number__c,
            
                (Select 
                    Name,
                    Primary_Material__c, 
                    Planned_Completion_Date__c, 
                    Comments__c, 
                    Status__c 
                From Project_Tasks__r ORDER BY Planned_Completion_Date__c DESC) 
             From Engineered_Package_Project__c 
             Where Opportunity__c = :this.oppId
             Order By CreatedDate ASC
        ];      
    }
}