force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>The department that the lead represents.</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Engineering/Lean Engineer</fullName>
            </value>
            <value>
                <fullName>Environmental Services (Custodial/EVS/Housekeeping)</fullName>
            </value>
            <value>
                <fullName>Estimating</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Infection Control</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Maintenance/Facility Manager</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations/Logistics/Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Owner/President</fullName>
            </value>
            <value>
                <fullName>Procurement/Purchasing</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Production/Manufacturing</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sustainability</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Employee_Range__c.field-meta.xml
<CustomField>
    <fullName>Employee_Range__c</fullName>
    <label>Employee Range</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - 25</fullName>
            </value>
            <value>
                <fullName>26 - 100</fullName>
            </value>
            <value>
                <fullName>101 - 500</fullName>
            </value>
            <value>
                <fullName>501 +</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <description>BW-2012
Related to the Genesis project for mobile sales reps</description>
    <label>Network ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leadAssignmentRange__c/leadAssignmentRange__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Determines where leads that need to circumvent Sundog Lead Routing must go based on the range of their Employee Range</description>
    <label>Lead Assignment Range Rule</label>
</CustomObject>

force-app/main/default/objects/leadAssignmentRange__c/fields/Assignee_Id__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Id__c</fullName>
    <label>Assignee Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/leadAssignmentRange__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <label>Lower Bound</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/leadAssignmentRange__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <label>Upper Bound</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestLeadAssignmentRange.cls
@isTest
private class TestLeadAssignmentRange {

    static testMethod void assignmentRangeTest() {
    	
    	Id marketingUserProfileId = [ Select Id, Name From Profile WHERE Name = 'Marketing User' ][0].Id;
    	
		User testUser = new User( FirstName='Testttt', LastName='Testtttt', UserName='test11@unisourcelink.com', Email='test11@unisourcelink.com', Alias='tester11',
								LocaleSidKey='en_US', LanguageLocaleKey='en_US', EmailEncodingKey='ISO-8859-1', CommunityNickname='test11', Network_Id__c = 'tester11',
								TimeZoneSidKey='America/New_York', Country = 'USA', profileId = marketingUserProfileId );
    	insert testUser;
    	
    	List<leadAssignmentRange__c> existingAssignmentSettings = leadAssignmentRange__c.getAll().values();
    	delete existingAssignmentSettings;
    	
    	leadAssignmentRange__c testAssignmentRange = new leadAssignmentRange__c( Name = 'Some test range', Lower_Bound__c = 1, Upper_Bound__c = 25, Assignee_Id__c = testUser.Id );
    	insert testAssignmentRange;
    	
		Lead testLead = new Lead( 	Status = '1-Identify', 
									LeadSource = '', 
									LastName = 'Smith', 
									Department__c = 'Marketing', 
									CurrencyIsoCode = 'USD', 
									Company = 'Some Company' );
		
		testLead.Employee_Range__c = '1 - 25';
        
        SundogLeadOverrideConfig leadOverride = new SundogLeadOverrideConfig();
		Boolean assignmentSuccess;
		
        Test.startTest();
        
			assignmentSuccess = leadOverride.assignLead( testLead );
        
        Test.stopTest();
        
        System.assertEquals( testLead.OwnerId, testUser.Id );
        
    }
    
    /*
    
    Currently being addressed in solving the problem of trigger ordering
    
    static testMethod void ensureEloquaAssignment() {
    	
		Lead testLead = new Lead( 	Status = '1-Identify', 
									LeadSource = '', 
									LastName = 'Smith', 
									Department__c = 'Marketing', 
									CurrencyIsoCode = 'USD', 
									Company = 'Some Company' );
		
        SundogLeadOverrideConfig leadOverride = new SundogLeadOverrideConfig();
		Boolean assignmentSuccess;
		
        Test.startTest();
        
			insert testLead;
        
        Test.stopTest();
        
        Lead resolvedLead = [ SELECT sundog_deprm2__Use_Automatic_Lead_Assignment__c FROM Lead WHERE Id = :testLead.Id ];
        
        //Todo: also populate sundog records and check for appropriate assignment
        
        System.assertEquals( true , resolvedLead.sundog_deprm2__Use_Automatic_Lead_Assignment__c );   	
    	
    	update testLead;
    	
        Lead doublyResolvedLead = [ SELECT sundog_deprm2__Use_Automatic_Lead_Assignment__c FROM Lead WHERE Id = :testLead.Id ];

        System.assertEquals( false , doublyResolvedLead.sundog_deprm2__Use_Automatic_Lead_Assignment__c );   	

    }
    */
    
}