force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <inlineHelpText>The department that the lead represents.</inlineHelpText>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Engineering/Lean Engineer</fullName>
            </value>
            <value>
                <fullName>Environmental Services (Custodial/EVS/Housekeeping)</fullName>
            </value>
            <value>
                <fullName>Estimating</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Infection Control</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Maintenance/Facility Manager</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations/Logistics/Shipping</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Owner/President</fullName>
            </value>
            <value>
                <fullName>Procurement/Purchasing</fullName>
            </value>
            <value>
                <fullName>Product Development</fullName>
            </value>
            <value>
                <fullName>Production/Manufacturing</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sustainability</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/USA_Aliases__c/USA_Aliases__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>USA Aliases</label>
</CustomObject>

force-app/main/default/objects/USA_Aliases__c/fields/Is_Primary_Alias__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Alias__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Alias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestCountryOverride.cls
@isTest
private class TestCountryOverride {

	/*
	private static final String EXPECTED_COUNTRY = 'United States';
	private static final Integer TEST_LEAD_COUNT = 3;

    static testMethod void testCountryOverride() {

		//Create some custom settings
		USA_Aliases__c testAlias = new USA_Aliases__c( Name = EXPECTED_COUNTRY, Is_Primary_Alias__c = true);
		USA_Aliases__c testAlias2 = new USA_Aliases__c( Name = 'USA', Is_Primary_Alias__c = false);
		USA_Aliases__c testAlias3 = new USA_Aliases__c( Name = 'US', Is_Primary_Alias__c = false); 
		USA_Aliases__c testAlias4 = new USA_Aliases__c( Name = 'America', Is_Primary_Alias__c = false);
		
		insert new List<USA_Aliases__c>{ testAlias, testAlias2, testAlias3, testAlias4 };
		
		List<Lead> testLeads = new List<Lead>();

		// Ok test seeing as how we cannot insert Custom Settings 
		// to test more robustly.
		for ( Integer i = 0; i < TEST_LEAD_COUNT; i++ ) {
			
			Lead testLead = new Lead( 	Status = '1-Identify', 
										LeadSource = '', 
										LastName = 'Smith', 
										Department__c = 'Marketing', 
										CurrencyIsoCode = 'USD', 
										Company = 'Some Company' );
			
			testLeads.add( testLead );			
			
		}
		
		testLeads[0].State = 'GA';
		testLeads[1].State = 'Colorado';
		testLeads[2].State = 'New York';
		
		 
		Test.startTest();
		
			insert testLeads;
		
		Test.stopTest();
		
		List<Lead> resolvedLeads = [ SELECT Id, Country FROM Lead WHERE Id IN :testLeads ];
		
	    System.assertEquals( TEST_LEAD_COUNT, resolvedLeads.size(), 'The correct number of leads should be returned');
	    
		for ( Lead aLead : resolvedLeads )
			System.assertEquals( EXPECTED_COUNTRY, aLead.Country, 'The correct country should be set for each lead' );
    
    }
    */

}