force-app/main/default/objects/Opportunity/fields/Opportunity_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Date__c</fullName>
    <description>Date Opportunity was closed in Salesforce.</description>
    <label>Opportunity Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <inlineHelpText>Choose whether the opportunity is an ongoing piece of new business, a one-time only purchase (such as equipment), or defending existing business</inlineHelpText>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Type_Picklist__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New Opportunity</fullName>
                <color>#33CC00</color>
                <label>New - Ongoing</label>
            </value>
            <value>
                <fullName>New Opportunity - One Time</fullName>
                <color>#CC66CC</color>
                <label>New - One Time</label>
            </value>
            <value>
                <fullName>Share - Ongoing</fullName>
            </value>
            <value>
                <fullName>Share - One Time</fullName>
            </value>
            <value>
                <fullName>Share &amp; Defend</fullName>
            </value>
            <value>
                <fullName>Defending Existing Business</fullName>
                <color>#3366FF</color>
                <label>Defend</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prod_Category__c.field-meta.xml
<CustomField>
    <fullName>Prod_Category__c</fullName>
    <description>Any changes here should also be made on the following objects - Vendor Detail, Contact, Work Orders and Form Assembly Work Order.  It&apos;s a dependent picklist to Segment.  We have some Dashboards that filter on some values for Specialists, so changes need to be vetted against those dashboards.</description>
    <inlineHelpText>Choose one or more by holding the control button (ctrl, bottom left of your keyboard) down as you select multiple product categories</inlineHelpText>
    <label>Prod Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Opportunity_Segment__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ADHESIVES</fullName>
            </value>
            <value>
                <fullName>AEROSPACE</fullName>
            </value>
            <value>
                <fullName>AMENITIES</fullName>
            </value>
            <value>
                <fullName>AQUEOUS MEDIA</fullName>
            </value>
            <value>
                <fullName>AQUEOUS PRINTERS</fullName>
            </value>
            <value>
                <fullName>AUTODESK - PRODUCT</fullName>
            </value>
            <value>
                <fullName>AUTODESK SUBSCRIPTION - NEW</fullName>
            </value>
            <value>
                <fullName>AUTODESK SUBSCRIPTION - RENEWAL</fullName>
            </value>
            <value>
                <fullName>BAGS</fullName>
            </value>
            <value>
                <fullName>BINDERY</fullName>
            </value>
            <value>
                <fullName>BLANKETS</fullName>
            </value>
            <value>
                <fullName>BOND &amp; WRITING</fullName>
            </value>
            <value>
                <fullName>CAN LINERS</fullName>
            </value>
            <value>
                <fullName>CAN LINERS-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>CANNABIS PACKAGING</fullName>
            </value>
            <value>
                <fullName>CARBONLESS</fullName>
            </value>
            <value>
                <fullName>CHEMICALS</fullName>
            </value>
            <value>
                <fullName>CHEMICALS-PRIVATE BRAND</fullName>
            </value>
            <value>
                <fullName>CHIPBOARD</fullName>
            </value>
            <value>
                <fullName>COATED BOARD - ROLLS</fullName>
            </value>
            <value>
                <fullName>COATED BOARD - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED DOMESTIC - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED IMPORT - SHEETS</fullName>
            </value>
            <value>
                <fullName>COATED - ROLLS</fullName>
            </value>
            <value>
                <fullName>COLD CHAIN</fullName>
            </value>
            <value>
                <fullName>COMPUTER &amp; LAPTOP</fullName>
            </value>
            <value>
                <fullName>CORRUGATED</fullName>
            </value>
            <value>
                <fullName>CUSHIONING</fullName>
            </value>
            <value>
                <fullName>DESIGN</fullName>
            </value>
            <value>
                <fullName>DIGITAL PAPER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VIQ_Batch_Audit__c.field-meta.xml
<CustomField>
    <fullName>VIQ_Batch_Audit__c</fullName>
    <description>Stores the value of the intended owner, Account, and ShipTo based on the username and AccountNumber columns in the CustomerInsight table.</description>
    <inlineHelpText>From Zilliant</inlineHelpText>
    <label>VIQ Batch Audit</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VIQ_Insight_Key__c.field-meta.xml
<CustomField>
    <fullName>VIQ_Insight_Key__c</fullName>
    <description>A unique identifier that must be populated in order to send back to Zilliant for closed loop reporting within their database. Must remain read-only. Corresponds with CustomerInsightKey in the Zilliant database.</description>
    <inlineHelpText>Unique identifier for Zilliant database</inlineHelpText>
    <label>VIQ Insight Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VIQ_Return_Products__c.field-meta.xml
<CustomField>
    <fullName>VIQ_Return_Products__c</fullName>
    <description>Stamps the ProductGroupingKey #s for the corresponding Product Categories specified for this Insight in the CustomerInsight table from Zilliant. This field is not to change. Regardless of if a rep changes the product categories and or segment on the opportunity, these are the productgroupings that win/loss feedback is sent back to Zilliant for.</description>
    <inlineHelpText>Do not edit this field.</inlineHelpText>
    <label>VIQ Return Products</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VIQ_Version_Key__c.field-meta.xml
<CustomField>
    <fullName>VIQ_Version_Key__c</fullName>
    <description>CustomerInsightVersionKey in the Zilliant database. Necessary for sending the OpportunityActivity .csv back to Zilliant</description>
    <inlineHelpText>For Veritiv IQ Integration</inlineHelpText>
    <label>VIQ Version Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <externalId>true</externalId>
    <label>Network Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VeritivIQ_ProductGrouping_Prod_Cat_Maps__c/VeritivIQ_ProductGrouping_Prod_Cat_Maps__c.object-meta.xml
<CustomObject>
    <description>Stores the same mapping of the ProductGrouping table for easy reference in the Veritiv IQ code base when calling the ProductGrouping, ProductGroupingInsights, and building the OpportunityActivity. If any of those values change in Zilliant, these records will need to change.

Edit 6/22/2017 to replace this same functionality that was previously built in Custom Metadata Types. This current method is not the optimal solution and a more dynamic approach would be a target for a phase two approach pending successful testing.</description>
    <label>VeritivIQ ProductGrouping Prod Cat Map</label>
    <nameField>
        <label>VeritivIQ ProductGrouping Prod Cat Map N</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VeritivIQ ProductGrouping Prod Cat Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VeritivIQ_ProductGrouping_Prod_Cat_Maps__c/fields/Opp_Prod_Categories__c.field-meta.xml
<CustomField>
    <fullName>Opp_Prod_Categories__c</fullName>
    <description>Verbatim API values that need to correspond to Opportunity.Prod_Category__c</description>
    <inlineHelpText>Verbatim API values that need to correspond to Opportunity.Prod_Category__c</inlineHelpText>
    <label>Opp Prod Categories</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VeritivIQ_ProductGrouping_Prod_Cat_Maps__c/fields/ProductGroupingDescValue__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupingDescValue__c</fullName>
    <description>ProductGroupingDescValue from the Zilliant ProductGrouping table</description>
    <inlineHelpText>ProductGroupingDescValue from the Zilliant ProductGrouping table</inlineHelpText>
    <label>ProductGroupingDescValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VeritivIQ_ProductGrouping_Prod_Cat_Maps__c/fields/ProductGroupingKey__c.field-meta.xml
<CustomField>
    <fullName>ProductGroupingKey__c</fullName>
    <description>ProductGroupingKey value from the Zilliant ProductGrouping table</description>
    <inlineHelpText>ProductGroupingKey value from the Zilliant ProductGrouping table</inlineHelpText>
    <label>ProductGroupingKey</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VIQ_Last_Successful_Batch_Run_Date__c/VIQ_Last_Successful_Batch_Run_Date__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Captures the last successful batch date for both batches of the VIQ Zilliant integration</description>
    <label>VIQ Last Successful Batch Run Date</label>
</CustomObject>

force-app/main/default/objects/VIQ_Last_Successful_Batch_Run_Date__c/fields/Activities_To_Zilliant__c.field-meta.xml
<CustomField>
    <fullName>Activities_To_Zilliant__c</fullName>
    <description>Date of the last successful batch run when sending activities to zilliant from salesforce</description>
    <inlineHelpText>DO NOT CHANGE.
Date of the last successful batch run when sending activities to zilliant from salesforce</inlineHelpText>
    <label>Activities To Zilliant</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ZilliantSalesMaxBatchIntegrationServices.cls
public with sharing class ZilliantSalesMaxBatchIntegrationServices {
	
	public final static List<String> OPPORTUNITY_ACTIVITY_COLUMNS = new List<String> {
		'customer_insight_key', 'customer_insight_version_key', 'product_grouping_key', 'activity', 'user', 'notes', 'date', 'product_grouping_insight_type'
	};

	public final static Map<String, String> STAGE_NAME_TO_ACTIVITY_MAPPING = new Map<String, String> {
		'8- Closed Won' => 'WON_RESPONSE', '0- Closed Lost' => 'LOST_RESPONSE'
	};

	/* Map to hold Conversion Values for Opportunity Type Field, keyed by SF Opp Type. */
	public static Map<String, String> oppTypeConversionMap_SF_Key = new Map<String, String> {
		'New Opportunity' => 'Cross Sell', 'Defending Existing Business' => 'Lost Sales'
	};

	// Custom Metadata Type used to hold the conversion mapping for the Product Categories picklist.
	/*
	public static Map<String, List<VeritivIQ_ProductGrouping_Prod_Cat_Maps__c>> prodCatMapping_SF_Key
	{
		get
		{
			if(prodCatMapping_SF_Key == NULL)
			{
				prodCatMapping_SF_Key = GroupBy.Strings('Opp_Prod_Categories__c', [SELECT Opp_Prod_Categories__c, ProductGroupingDescValue__c, ProductGroupingKey__c FROM VeritivIQ_ProductGrouping_Prod_Cat_Maps__c]);
			}
			return prodCatMapping_SF_Key;
		}

		set;
	}
	*/

	public ZilliantSalesMaxBatchIntegrationServices() {
	}

	public static String buildQuery_RecentOpportunityActivity()
	{
		String activities = String.join(new List<String>(STAGE_NAME_TO_ACTIVITY_MAPPING.keySet()), '\', \'');
		String activityFilter = '(\'' + activities + '\')';
		VIQ_Last_Successful_Batch_Run_Date__c csLastRun = ZilliantSalesMaxIntegrationServices.csBatchLastRun;
		Integer numOfDaysSinceLastSuccessfulRun = (csLastRun == NULL || csLastRun.Activities_To_Zilliant__c == NULL) 
																		? 7 
																		: csLastRun.Activities_To_Zilliant__c.daysBetween( Date.Today() );
		System.debug('Batch Number Of Days: ' + numOfDaysSinceLastSuccessfulRun);

		String query = 'SELECT' +
					' Id, VIQ_INSIGHT_KEY__C, VIQ_Batch_Audit__c, VIQ_Return_Products__c, VIQ_VERSION_KEY__C, Prod_Category__c, Opportunity_Close_Date__c, StageName, OwnerId, Owner.Network_Id__c, Description, Opportunity_Type__c' +
					' FROM Opportunity' + 
					/* ' WHERE RecordTypeId = \'' + ZilliantSalesMaxIntegrationServices.defaultRT + '\'' + */
					' WHERE StageName IN ' + activityFilter +
					' AND VIQ_Return_Products__c != NULL' + 
					' AND Opportunity_Close_Date__c = LAST_N_DAYS:' + numOfDaysSinceLastSuccessfulRun;

		return query;
	}

	public static String convertOppsToCSV(List<Opportunity> oppsToConvert)
	{
		String convertedOpps = '';
		String oppRow = '';

		for(Opportunity opp : oppsToConvert)
		{

			Integer count = 0;
			List<String> allProdCats = opp.VIQ_Return_Products__c.split(',');
			String selectedProdCat = '';

			do
			{
				selectedProdCat = allProdCats[count];
				oppRow = '';

				oppRow += opp.VIQ_Insight_Key__c != NULL ? (opp.VIQ_Insight_Key__c + ',') : ',';

				oppRow += opp.VIQ_Version_Key__c != NULL ? (opp.VIQ_Version_Key__c + ',') : ',';

				/* Build Product Categories --> Was using Mapping, now using VIQ_Return_Products__c */
				//oppRow += String.isNotBlank(selectedProdCat) && prodCatMapping_SF_Key.containsKey(selectedProdCat) ? (prodCatMapping_SF_Key.get(selectedProdCat)[0].ProductGroupingKey__c + ',') : ' ,';
				oppRow += String.isNotBlank(selectedProdCat) ? selectedProdCat + ',': ',';

				oppRow += opp.StageName != NULL ? (STAGE_NAME_TO_ACTIVITY_MAPPING.get(opp.StageName) + ',') : ',';

				oppRow += opp.Owner.Network_Id__c != NULL ? (opp.Owner.Network_Id__c + ',') : ',';

				oppRow += opp.Description != NULL ? (opp.Description.escapeCsv() + ',') : ',';

				oppRow += opp.Opportunity_Close_Date__c != NULL ? (opp.Opportunity_Close_Date__c.day() + '/' + opp.Opportunity_Close_Date__c.month() + '/' + opp.Opportunity_Close_Date__c.year() + ',') : ',';

				/* TODO : Extra Comma on the End */
				oppRow += opp.Opportunity_Type__c != NULL ? (oppTypeConversionMap_SF_Key.get(opp.Opportunity_Type__c) + ',') : ',';

				convertedOpps += oppRow + '\r\n';

				count++;
			}
			while( count < allProdCats.size() );

		}

		return convertedOpps;
	}

	public static String makeInsertCall(String csvData, String accessToken)
	{
		String bacthJobId = '';

		String csvFile =  String.join( ZilliantSalesMaxBatchIntegrationServices.OPPORTUNITY_ACTIVITY_COLUMNS, ',' );
			   csvFile += '\n';
			   csvFile += csvData;

	    Blob bodyBlob = setupRequestBody(csvFile);

		HttpRequest insertRequest = new HttpRequest();
		insertRequest.setMethod('POST');
		insertRequest.setHeader('Content-Type', 'multipart/form-data');
		insertRequest.setHeader(ZilliantSalesMaxIntegrationServices.AUTHORIZATION_HEADER_KEY, 
		                        ZilliantSalesMaxIntegrationServices.AUTHORIZATION_HEADER_VALUE + accessToken);
		insertRequest.setBodyAsBlob( bodyBlob );
		insertRequest.setEndpoint(ZilliantSalesMaxIntegrationServices.ZILLIANT_BASE_REQUEST_URL + 
		                          '?type=' + ZilliantSalesMaxIntegrationServices.OPPORTUNITY_ACTIVITY_RESOURCE_TYPE + 
		                          '&operation=' + ZilliantSalesMaxIntegrationServices.INSERT_OPERATION_TYPE);
		insertRequest.setTimeout(120000);

		HttpResponse authResponse;

		try
		{
			authResponse = new HTTP().send(insertRequest);
			System.debug(authResponse);
			System.debug( authResponse.getBody());

			if(authResponse.getStatusCode() == ZilliantSalesMaxIntegrationServices.ZIL_RESPONSE_STATUS_OK)
			{
				JSONParser parser = JSON.createParser(authResponse.getBody());
				while(parser.nextToken() != null)
				{
					if(parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == ZilliantSalesMaxIntegrationServices.ZILLIANT_JOB_ID_KEY)
					{
						parser.nextToken();
						bacthJobId = parser.getText();
						break;
					}
				}
			}
			else
			{
				bacthJobId = NULL;
				
			}
		}
		catch(Exception ex)
		{

		}

		return bacthJobId;
	}

	private static Blob setupRequestBody(String csvData)
	{
		// May have to set boundry in header --> boundary=:boundary
		// https://docparser.com/blog/post-file-salesforce-apex-external-http-webservices/

		String boundary = '--------------SFtoZILLIANT--------------';
		String contentDisposition = 'Content-Disposition: form-data;';
		String namePiece = 'name="file";';
		String fileName = 'filename="OpportunityAcitivty_Date.csv"';
		String contentType = 'Content-Type: multipart/form-data';

		String header = boundary + '\r\n' + contentDisposition + namePiece + fileName + contentType + '\r\n'; // added '\r's removed ';' see Tim Smith's comment
		String footer = '\r\n' + boundary;              
		String headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header + '\r\n\r\n'));
		while(headerEncoded.endsWith('='))
		{
		    header+=' ';
		    headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));
		}
		String bodyEncoded = EncodingUtil.base64Encode(Blob.valueOf(csvData));
		String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));

		Blob bodyBlob = null;
		String last4Bytes = bodyEncoded.substring(bodyEncoded.length()-4,bodyEncoded.length());
		if(last4Bytes.endsWith('='))
		{
		    Blob decoded4Bytes = EncodingUtil.base64Decode(last4Bytes);
		    HttpRequest tmp = new HttpRequest();
		    tmp.setBodyAsBlob(decoded4Bytes);
		    String last4BytesFooter = tmp.getBody()+footer;   
		    bodyBlob = EncodingUtil.base64Decode(headerEncoded+bodyEncoded.substring(0,bodyEncoded.length()-4)+EncodingUtil.base64Encode(Blob.valueOf(last4BytesFooter)));
		}
		else
		{
		    bodyBlob = EncodingUtil.base64Decode(headerEncoded + bodyEncoded + footerEncoded);
		}

		return bodyBlob;
	}
}