force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the contact is no longer active.  This will enable the Inactive Reason field for you to give further detail.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Quotes should be attached to a prospect or customer account.  It is not possible to associate a quote with a Unisource account.  If you can&apos;t find the account you need, please create a new prospect.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The account you searched for is not available for quotes either because it does not yet exist or it is a Unisource account.  Please go to the Account tab, click New, and create a Prospect if necessary.</errorMessage>
        <filterItems>
            <field>Account.UWW_Account__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailLookupController.cls
public with sharing class EmailLookupController
{
	public String addressJSON {get; set;}
	public Quote__c quote {get; set;}
	
	static final String UNISOURCE_WORLDWIDE_ACCOUNT_ID = '0017000000NJvZc';
		
	public EmailLookupController()
	{
		String quoteId = ApexPages.currentPage().getParameters().get('id');
		if(quoteId != null)
		{
			quote = [SELECT Id, Account__c FROM Quote__c WHERE Id = :quoteId];
		}
		initPossibleAddresses();
	}
	
	public void initPossibleAddresses()
	{
		addressJSON = '[';

		for(Contact contact : [SELECT Id, Name, Email, AccountId, Account.Name
							 	FROM Contact
							 	WHERE (AccountId = :UNISOURCE_WORLDWIDE_ACCOUNT_ID
							 	 OR AccountId = :quote.Account__c)
							 	 AND email <> null
							 	 AND Inactive__c = false
								 ORDER BY Name LIMIT 9999])
		{
			addressJSON += '{"name" : "' + EncodingUtil.urlEncode(contact.Account.Name +': '+ contact.Name, 'UTF-8') + 
            '", "email" : "' +EncodingUtil.urlEncode(contact.Email, 'UTF-8') + '" },';
		}	
		
		//remove trailing comma
		addressJSON = addressJSON.substring(0, addressJSON.length() - 1);
	
		addressJSON += ']';
	}
	
}