force-app/main/default/objects/Product_Analysis__c/Product_Analysis__c.object-meta.xml
<CustomObject>
    <label>Product Analysis</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Product Analysis Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Analyses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Analysis__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Analyses</relationshipLabel>
    <relationshipName>Product_Analyses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Barrels_of_Oil__c.field-meta.xml
<CustomField>
    <fullName>Barrels_of_Oil__c</fullName>
    <description>Secure Wrap app sustainability benefit metric</description>
    <label>Barrels of Oil</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Bottom_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Current_Bottom_Load_Force__c</fullName>
    <label>Current Bottom Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Estimated_Annual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Current_Estimated_Annual_Cost__c</fullName>
    <label>Current Estimated Annual Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Film_Thickness_ga__c.field-meta.xml
<CustomField>
    <fullName>Current_Film_Thickness_ga__c</fullName>
    <label>Current Film Thickness (ga)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Film_Width_in__c.field-meta.xml
<CustomField>
    <fullName>Current_Film_Width_in__c</fullName>
    <label>Current Film Width (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Item__c.field-meta.xml
<CustomField>
    <fullName>Current_Item__c</fullName>
    <label>Current Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Current_Manufacturer__c</fullName>
    <label>Current Manufacturer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Middle_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Current_Middle_Load_Force__c</fullName>
    <label>Current Middle Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Roll_Length_ft__c.field-meta.xml
<CustomField>
    <fullName>Current_Roll_Length_ft__c</fullName>
    <label>Current Roll Length (ft)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Roll_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Roll_Price__c</fullName>
    <label>Current Roll Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Rotations__c.field-meta.xml
<CustomField>
    <fullName>Current_Rotations__c</fullName>
    <label>Current Rotations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Top_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Current_Top_Load_Force__c</fullName>
    <label>Current Top Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Total_Stretch__c.field-meta.xml
<CustomField>
    <fullName>Current_Total_Stretch__c</fullName>
    <label>Current Total Stretch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Current_Weight_oz__c.field-meta.xml
<CustomField>
    <fullName>Current_Weight_oz__c</fullName>
    <label>Current Weight (oz)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Equipment_Type__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Type__c</fullName>
    <label>Equipment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Film__c.field-meta.xml
<CustomField>
    <fullName>Film__c</fullName>
    <label>Core Usage Decrease</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Homes_Powered__c.field-meta.xml
<CustomField>
    <fullName>Homes_Powered__c</fullName>
    <label>Homes Powered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Manufacturer_Model__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Model__c</fullName>
    <label>Manufacturer/Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Height_in__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Height_in__c</fullName>
    <label>Pallet Height (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Length_in__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Length_in__c</fullName>
    <label>Pallet Length (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Type__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Type__c</fullName>
    <label>Pallet Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Weight_lbs__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Weight_lbs__c</fullName>
    <label>Pallet Weight (lbs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallet_Width_in__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Width_in__c</fullName>
    <label>Pallet Width (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallets__c.field-meta.xml
<CustomField>
    <fullName>Pallets__c</fullName>
    <label>Pallets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Pallets_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>Pallets_Per_Year__c</fullName>
    <label>Pallets Per Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Personal_Vehicle_Emissions__c.field-meta.xml
<CustomField>
    <fullName>Personal_Vehicle_Emissions__c</fullName>
    <description>Secure Wrap app sustainability benefit metric</description>
    <label>Personal Vehicle Emissions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Plastic_Bags_Saved__c.field-meta.xml
<CustomField>
    <fullName>Plastic_Bags_Saved__c</fullName>
    <description>Secure Wrap app sustainability benefit metric</description>
    <label>Plastic Bags Saved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Plastic_Bottles_Saved__c.field-meta.xml
<CustomField>
    <fullName>Plastic_Bottles_Saved__c</fullName>
    <label>Plastic Bottles Saved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Plastic_Straws_Saved__c.field-meta.xml
<CustomField>
    <fullName>Plastic_Straws_Saved__c</fullName>
    <description>Secure Wrap app sustainability benefit metric</description>
    <label>Plastic Straws Saved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Annual_Savings__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Annual_Savings__c</fullName>
    <label>Proposed Annual Savings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Bottom_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Bottom_Load_Force__c</fullName>
    <label>Proposed Bottom Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Estimated_Annual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Estimated_Annual_Cost__c</fullName>
    <label>Proposed Estimated Annual Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Film_Thickness_ga__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Film_Thickness_ga__c</fullName>
    <label>Proposed Film Thickness (ga)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Film_Width_in__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Film_Width_in__c</fullName>
    <label>Proposed Film Width (in)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Item__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Item__c</fullName>
    <label>Proposed Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Middle_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Middle_Load_Force__c</fullName>
    <label>Proposed Middle Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Percent_Savings__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Percent_Savings__c</fullName>
    <label>Proposed Percent Savings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Roll_Length_ft__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Roll_Length_ft__c</fullName>
    <label>Proposed Roll Length (ft)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Roll_Price__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Roll_Price__c</fullName>
    <label>Proposed Roll Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Rotations__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Rotations__c</fullName>
    <label>Proposed Rotations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Top_Load_Force__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Top_Load_Force__c</fullName>
    <label>Proposed Top Load Force</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Total_Stretch__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Total_Stretch__c</fullName>
    <label>Proposed Total Stretch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Proposed_Weight_oz__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Weight_oz__c</fullName>
    <label>Proposed Weight (oz)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Truckloads__c.field-meta.xml
<CustomField>
    <fullName>Truckloads__c</fullName>
    <label>Truckloads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Analysis__c/fields/Waste_Stream_Pounds_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Waste_Stream_Pounds_Reduction__c</fullName>
    <label>Waste Stream Pounds Reduction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PAPDFController.cls
public class PAPDFController {
/*    
    public Product_Analysis__c PARecord { get; set; }
    //public String AccountName { get; set; }
        
    public PAPDFController() {
        String paId = ApexPages.currentPage().getParameters().get('id');
        system.debug('paId '+ paId );
        system.debug('ApexPages-currentPage-getParameters '+ ApexPages.currentPage().getParameters() );
        PARecord = [SELECT Id,
                    account__c, 
                    account__r.Name, 
                    Current_Bottom_Load_Force__c, 
                    Current_Estimated_Annual_Cost__c,
                    Current_Film_Thickness_ga__c, 
                    Current_Film_Width_in__c, 
                    Current_Item__c, 
                    Current_Manufacturer__c,
                    Current_Middle_Load_Force__c, 
                    Current_Roll_Length_ft__c, 
                    Current_Roll_Price__c, 
                    Current_Rotations__c, 
                    Current_Top_Load_Force__c, 
                    Current_Total_Stretch__c,
                    Current_Weight_oz__c,
                    Equipment_Type__c,
                    Manufacturer_Model__c,
                    Pallet_Height_in__c,
                    Pallet_Length_in__c,
                    Pallets_Per_Year__c, 
                    Pallet_Type__c,
                    Pallet_Weight_lbs__c,
                    Pallet_Width_in__c,
                    Proposed_Annual_Savings__c,
                    Proposed_Bottom_Load_Force__c,
                    Proposed_Estimated_Annual_Cost__c,
                    Proposed_Film_Thickness_ga__c,
                    Proposed_Film_Width_in__c,
                    Proposed_Item__c,
                    Proposed_Middle_Load_Force__c,
                    Proposed_Percent_Savings__c,
                    Proposed_Roll_Length_ft__c,
                    Proposed_Roll_Price__c,
                    Proposed_Rotations__c,
                    Proposed_Top_Load_Force__c,
                    Proposed_Total_Stretch__c,
                    Proposed_Weight_oz__c,
                    Serial_Number__c,
                    Waste_Stream_Pounds_Reduction__c,
                    Plastic_Straws_Saved__c,
                    Plastic_Bags_Saved__c,
                    Plastic_Bottles_Saved__c,
                    Personal_Vehicle_Emissions__c,
                    Barrels_of_Oil__c,
                    Homes_Powered__c,
                    Film__c,
                    Pallets__c,
                    Truckloads__c,
                    BarrelInd__c,
                    CarInd__c,
                    CoreInd__c,
                    HomeInd__c,
                    PalletInd__c,
                    PlasticBagInd__c,
                    PlasticBottleInd__c,
                    PlasticStrawInd__c,
                    TruckInd__c
                    FROM Product_Analysis__c
                    WHERE Id = :paId LIMIT 1];
     
        system.debug('The pdf page:'+ PARecord);
    }
 */  
}