force-app/main/default/objects/Vendor_Detail__c/Vendor_Detail__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Detail__c/fields/AIQ_VendorId__c.field-meta.xml
<CustomField>
    <fullName>AIQ_VendorId__c</fullName>
    <externalId>true</externalId>
    <label>Vendor ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AIQ_VendorDetailTriggerHandler.cls
public class AIQ_VendorDetailTriggerHandler extends AIQtr_TriggerHandler {
    private static final String VENDOR_ID_EXTERNAL_FIELD_NAME = Schema.SObjectType.Vendor_Detail__c.fields.AIQ_VendorId__c.getName();

    protected override void beforeInsert() {
        List<Vendor_Detail__c> newVendorDetails = Trigger.new;
        generateVendorId(newVendorDetails);
    }

    protected override void beforeUpdate() {
        List<Vendor_Detail__c> newVendorDetails = Trigger.new;
        generateVendorId(newVendorDetails);
    }

    protected override void afterInsert() {
        /* Next line must be in all after Trirrers!!! */
        syncDownVendor();
    }

    protected override void afterUpdate() {
        /* Next line must be in all after Trirrers!!! */
        syncDownVendor();
    }

    protected override void afterDelete() {
       /* Next line must be in all after Trirrers!!! */
        syncDownVendor();
    }

    private void syncDownVendor() {
        zpf.GenericSynchronizedDomainObject.triggerHandler(VENDOR_ID_EXTERNAL_FIELD_NAME);
    }

    private void generateVendorId(List<Vendor_Detail__c> vendorDetails) {
        AIQtr_TriggerHelper.addId(vendorDetails, VENDOR_ID_EXTERNAL_FIELD_NAME);
    }
}