force-app/main/default/objects/Ship_To__c/Ship_To__c.object-meta.xml
<CustomObject>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ship_To__c/fields/Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ship_To__c/fields/Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Account__c</fullName>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship Tos</relationshipLabel>
    <relationshipName>Ship_Tos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateAccountTeamBatchTest.cls
@isTest
public class UpdateAccountTeamBatchTest {
	public static testMethod void runTest(){
        
        UpdateAccountTeamBatch BC=new UpdateAccountTeamBatch();
        Account a = new Account(name='Test Account Batch');
        insert a;
        
        Account a2 = new Account(name='Test Account Batch 2');
        insert a2;
        
        Ship_To__c shp = new Ship_To__c();
        shp.Bill_To_Account__c = a.Id;
        shp.Name = 'Test Monday';
        shp.Account_Owner__c = UserInfo.getUserId();
        UpdateAccountTeamHelper.runTrigger = false;
        insert shp;
        
        Set<Id> shpIds = New Set<Id>();
        shpIds.add(shp.Id);
        UpdateAccountTeamBatch.run(shpIds);
        
    }
    
    public static testMethod void executeTest(){
        
        UpdateAccountTeamBatch BC=new UpdateAccountTeamBatch();
        Account a = new Account(name='Test Account Batch');
        insert a;
        
        Account a2 = new Account(name='Test Account Batch 2');
        insert a2;
        
        Ship_To__c shp = new Ship_To__c();
        shp.Bill_To_Account__c = a.Id;
        shp.Name = 'Test Monday';
        shp.Account_Owner__c = UserInfo.getUserId();
        UpdateAccountTeamHelper.runTrigger = false;
        insert shp;
        
        Set<Id> shpIds = New Set<Id>();
        shpIds.add(shp.Id);
        
        DataBase.executeBatch(BC,200);
    }
}